
(define (problem taskograph_rearrangement) (:domain taskography_v3)
  (:objects
        agent - agent
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	item16_bottle_smallitem - item
	item17_bottle_smallitem - item
	item18_bottle_smallitem - item
	item19_bottle_smallitem - item
	item1_sports_ball_largeitem - item
	item20_clock_mediumitem - item
	item21_clock_mediumitem - item
	item22_clock_mediumitem - item
	item23_clock_mediumitem - item
	item24_banana_smallitem - item
	item25_banana_smallitem - item
	item31_potted_plant_largeitem - item
	location_Xneg14_Ypos41_place32_room2_floorB - location
	location_Xneg17_Ypos44_place4_room2_floorB - location
	location_Xneg17_Ypos48_place21_room2_floorB - location
	location_Xneg18_Ypos8_place27_room15_floorA - location
	location_Xneg19_Ypos96_place10_room12_floorB - location
	location_Xneg21_Ypos38_place21_room2_floorB - location
	location_Xneg23_Ypos22_place1_room15_floorA - location
	location_Xneg25_Ypos82_place31_room4_floorB - location
	location_Xneg25_Ypos83_place6_room4_floorB - location
	location_Xneg27_Ypos11_place27_room15_floorA - location
	location_Xneg2_Ypos14_place18_room15_floorA - location
	location_Xneg2_Ypos91_place13_room11_floorB - location
	location_Xneg35_Yneg5_place9_room9_floorA - location
	location_Xneg36_Ypos7_place14_room9_floorA - location
	location_Xneg3_Ypos4_place36_room19_floorA - location
	location_Xneg5_Ypos86_place16_room11_floorB - location
	location_Xneg9_Ypos33_place22_room15_floorA - location
	location_Xneg9_Ypos79_place15_room12_floorB - location
	location_Xpos10_Ypos113_place17_room11_floorB - location
	location_Xpos10_Ypos97_place8_room11_floorB - location
	location_Xpos14_Ypos3_place26_room19_floorA - location
	location_Xpos14_Ypos52_place2_room16_floorB - location
	location_Xpos15_Ypos20_place5_room1_floorA - location
	location_Xpos15_Ypos51_place0_room10_floorA - location
	location_Xpos16_Ypos87_place7_room18_floorA - location
	location_Xpos17_Ypos100_place12_room18_floorA - location
	location_Xpos18_Ypos11_place30_room1_floorA - location
	location_Xpos19_Ypos14_place29_room1_floorA - location
	location_Xpos22_Yneg12_place25_room19_floorA - location
	location_Xpos22_Ypos25_place23_room1_floorA - location
	location_Xpos23_Ypos63_place28_room16_floorB - location
	location_Xpos25_Yneg13_place25_room19_floorA - location
	location_Xpos25_Yneg5_place25_room19_floorA - location
	location_Xpos25_Yneg8_place25_room19_floorA - location
	location_Xpos2_Yneg5_place3_room19_floorA - location
	location_Xpos3_Ypos51_place19_room16_floorB - location
	location_Xpos4_Ypos47_place11_room10_floorA - location
	location_Xpos7_Ypos11_place33_room1_floorA - location
	location_Xpos7_Ypos12_place34_room1_floorA - location
	location_Xpos7_Ypos9_place35_room1_floorA - location
	location_Xpos9_Yneg15_place20_room19_floorA - location
	location_Xpos9_Ypos41_place24_room16_floorB - location
	place0_door_room10_empty_room - place
	place10_door_room12_empty_room - place
	place11_item1_sports_ball - place
	place12_item16_bottle - place
	place13_item22_clock - place
	place14_item23_clock - place
	place15_item24_banana - place
	place16_item25_banana - place
	place17_item31_potted_plant - place
	place18_receptacle2_oven - place
	place19_receptacle3_oven - place
	place1_door_room15_kitchen - place
	place20_receptacle4_oven - place
	place21_receptacle5_sink - place
	place22_receptacle6_sink - place
	place23_receptacle7_sink - place
	place24_receptacle8_sink - place
	place25_receptacle9_sink - place
	place26_receptacle10_sink - place
	place27_receptacle11_refrigerator - place
	place28_receptacle12_refrigerator - place
	place29_receptacle13_refrigerator - place
	place2_door_room16_kitchen - place
	place30_receptacle14_refrigerator - place
	place31_receptacle15_refrigerator - place
	place32_receptacle26_toilet - place
	place33_receptacle27_toilet - place
	place34_receptacle28_toilet - place
	place35_receptacle29_toilet - place
	place36_receptacle30_toilet - place
	place3_door_room19_utility_room - place
	place4_door_room2_bathroom - place
	place5_door_room1_bathroom - place
	place6_door_room4_closet - place
	place7_door_room18_staircase - place
	place8_door_room11_empty_room - place
	place9_door_room9_empty_room - place
	receptacle10_sink - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle13_refrigerator - receptacle
	receptacle14_refrigerator - receptacle
	receptacle15_refrigerator - receptacle
	receptacle26_toilet - receptacle
	receptacle27_toilet - receptacle
	receptacle28_toilet - receptacle
	receptacle29_toilet - receptacle
	receptacle2_oven - receptacle
	receptacle30_toilet - receptacle
	receptacle3_oven - receptacle
	receptacle4_oven - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_sink - receptacle
	room10_empty_room - room
	room11_empty_room - room
	room12_empty_room - room
	room15_kitchen - room
	room16_kitchen - room
	room18_staircase - room
	room19_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room4_closet - room
	room9_empty_room - room
  )
  (:init 
	(atlocation agent location_Xneg19_Ypos96_place10_room12_floorB)
	(inanyreceptacle item17_bottle_smallitem)
	(inanyreceptacle item18_bottle_smallitem)
	(inanyreceptacle item19_bottle_smallitem)
	(inanyreceptacle item20_clock_mediumitem)
	(inanyreceptacle item21_clock_mediumitem)
	(inplace agent place10_door_room12_empty_room)
	(inreceptacle item17_bottle_smallitem receptacle9_sink)
	(inreceptacle item18_bottle_smallitem receptacle9_sink)
	(inreceptacle item19_bottle_smallitem receptacle9_sink)
	(inreceptacle item20_clock_mediumitem receptacle5_sink)
	(inreceptacle item21_clock_mediumitem receptacle11_refrigerator)
	(inroom agent room12_empty_room)
	(itematlocation item16_bottle_smallitem location_Xpos17_Ypos100_place12_room18_floorA)
	(itematlocation item17_bottle_smallitem location_Xpos25_Yneg5_place25_room19_floorA)
	(itematlocation item18_bottle_smallitem location_Xpos25_Yneg13_place25_room19_floorA)
	(itematlocation item19_bottle_smallitem location_Xpos25_Yneg8_place25_room19_floorA)
	(itematlocation item1_sports_ball_largeitem location_Xpos4_Ypos47_place11_room10_floorA)
	(itematlocation item20_clock_mediumitem location_Xneg17_Ypos48_place21_room2_floorB)
	(itematlocation item21_clock_mediumitem location_Xneg18_Ypos8_place27_room15_floorA)
	(itematlocation item22_clock_mediumitem location_Xneg2_Ypos91_place13_room11_floorB)
	(itematlocation item23_clock_mediumitem location_Xneg36_Ypos7_place14_room9_floorA)
	(itematlocation item24_banana_smallitem location_Xneg9_Ypos79_place15_room12_floorB)
	(itematlocation item25_banana_smallitem location_Xneg5_Ypos86_place16_room11_floorB)
	(itematlocation item31_potted_plant_largeitem location_Xpos10_Ypos113_place17_room11_floorB)
	(largeitem item1_sports_ball_largeitem)
	(largeitem item31_potted_plant_largeitem)
	(locationinplace location_Xneg14_Ypos41_place32_room2_floorB place32_receptacle26_toilet)
	(locationinplace location_Xneg17_Ypos44_place4_room2_floorB place4_door_room2_bathroom)
	(locationinplace location_Xneg17_Ypos48_place21_room2_floorB place21_receptacle5_sink)
	(locationinplace location_Xneg18_Ypos8_place27_room15_floorA place27_receptacle11_refrigerator)
	(locationinplace location_Xneg19_Ypos96_place10_room12_floorB place10_door_room12_empty_room)
	(locationinplace location_Xneg21_Ypos38_place21_room2_floorB place21_receptacle5_sink)
	(locationinplace location_Xneg23_Ypos22_place1_room15_floorA place1_door_room15_kitchen)
	(locationinplace location_Xneg25_Ypos82_place31_room4_floorB place31_receptacle15_refrigerator)
	(locationinplace location_Xneg25_Ypos83_place6_room4_floorB place6_door_room4_closet)
	(locationinplace location_Xneg27_Ypos11_place27_room15_floorA place27_receptacle11_refrigerator)
	(locationinplace location_Xneg2_Ypos14_place18_room15_floorA place18_receptacle2_oven)
	(locationinplace location_Xneg2_Ypos91_place13_room11_floorB place13_item22_clock)
	(locationinplace location_Xneg35_Yneg5_place9_room9_floorA place9_door_room9_empty_room)
	(locationinplace location_Xneg36_Ypos7_place14_room9_floorA place14_item23_clock)
	(locationinplace location_Xneg3_Ypos4_place36_room19_floorA place36_receptacle30_toilet)
	(locationinplace location_Xneg5_Ypos86_place16_room11_floorB place16_item25_banana)
	(locationinplace location_Xneg9_Ypos33_place22_room15_floorA place22_receptacle6_sink)
	(locationinplace location_Xneg9_Ypos79_place15_room12_floorB place15_item24_banana)
	(locationinplace location_Xpos10_Ypos113_place17_room11_floorB place17_item31_potted_plant)
	(locationinplace location_Xpos10_Ypos97_place8_room11_floorB place8_door_room11_empty_room)
	(locationinplace location_Xpos14_Ypos3_place26_room19_floorA place26_receptacle10_sink)
	(locationinplace location_Xpos14_Ypos52_place2_room16_floorB place2_door_room16_kitchen)
	(locationinplace location_Xpos15_Ypos20_place5_room1_floorA place5_door_room1_bathroom)
	(locationinplace location_Xpos15_Ypos51_place0_room10_floorA place0_door_room10_empty_room)
	(locationinplace location_Xpos16_Ypos87_place7_room18_floorA place7_door_room18_staircase)
	(locationinplace location_Xpos17_Ypos100_place12_room18_floorA place12_item16_bottle)
	(locationinplace location_Xpos18_Ypos11_place30_room1_floorA place30_receptacle14_refrigerator)
	(locationinplace location_Xpos19_Ypos14_place29_room1_floorA place29_receptacle13_refrigerator)
	(locationinplace location_Xpos22_Yneg12_place25_room19_floorA place25_receptacle9_sink)
	(locationinplace location_Xpos22_Ypos25_place23_room1_floorA place23_receptacle7_sink)
	(locationinplace location_Xpos23_Ypos63_place28_room16_floorB place28_receptacle12_refrigerator)
	(locationinplace location_Xpos25_Yneg13_place25_room19_floorA place25_receptacle9_sink)
	(locationinplace location_Xpos25_Yneg5_place25_room19_floorA place25_receptacle9_sink)
	(locationinplace location_Xpos25_Yneg8_place25_room19_floorA place25_receptacle9_sink)
	(locationinplace location_Xpos2_Yneg5_place3_room19_floorA place3_door_room19_utility_room)
	(locationinplace location_Xpos3_Ypos51_place19_room16_floorB place19_receptacle3_oven)
	(locationinplace location_Xpos4_Ypos47_place11_room10_floorA place11_item1_sports_ball)
	(locationinplace location_Xpos7_Ypos11_place33_room1_floorA place33_receptacle27_toilet)
	(locationinplace location_Xpos7_Ypos12_place34_room1_floorA place34_receptacle28_toilet)
	(locationinplace location_Xpos7_Ypos9_place35_room1_floorA place35_receptacle29_toilet)
	(locationinplace location_Xpos9_Yneg15_place20_room19_floorA place20_receptacle4_oven)
	(locationinplace location_Xpos9_Ypos41_place24_room16_floorB place24_receptacle8_sink)
	(mediumitem item20_clock_mediumitem)
	(mediumitem item21_clock_mediumitem)
	(mediumitem item22_clock_mediumitem)
	(mediumitem item23_clock_mediumitem)
	(placeinroom place0_door_room10_empty_room room10_empty_room)
	(placeinroom place10_door_room12_empty_room room12_empty_room)
	(placeinroom place11_item1_sports_ball room10_empty_room)
	(placeinroom place12_item16_bottle room18_staircase)
	(placeinroom place13_item22_clock room11_empty_room)
	(placeinroom place14_item23_clock room9_empty_room)
	(placeinroom place15_item24_banana room12_empty_room)
	(placeinroom place16_item25_banana room11_empty_room)
	(placeinroom place17_item31_potted_plant room11_empty_room)
	(placeinroom place18_receptacle2_oven room15_kitchen)
	(placeinroom place19_receptacle3_oven room16_kitchen)
	(placeinroom place1_door_room15_kitchen room15_kitchen)
	(placeinroom place20_receptacle4_oven room19_utility_room)
	(placeinroom place21_receptacle5_sink room2_bathroom)
	(placeinroom place22_receptacle6_sink room15_kitchen)
	(placeinroom place23_receptacle7_sink room1_bathroom)
	(placeinroom place24_receptacle8_sink room16_kitchen)
	(placeinroom place25_receptacle9_sink room19_utility_room)
	(placeinroom place26_receptacle10_sink room19_utility_room)
	(placeinroom place27_receptacle11_refrigerator room15_kitchen)
	(placeinroom place28_receptacle12_refrigerator room16_kitchen)
	(placeinroom place29_receptacle13_refrigerator room1_bathroom)
	(placeinroom place2_door_room16_kitchen room16_kitchen)
	(placeinroom place30_receptacle14_refrigerator room1_bathroom)
	(placeinroom place31_receptacle15_refrigerator room4_closet)
	(placeinroom place32_receptacle26_toilet room2_bathroom)
	(placeinroom place33_receptacle27_toilet room1_bathroom)
	(placeinroom place34_receptacle28_toilet room1_bathroom)
	(placeinroom place35_receptacle29_toilet room1_bathroom)
	(placeinroom place36_receptacle30_toilet room19_utility_room)
	(placeinroom place3_door_room19_utility_room room19_utility_room)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place5_door_room1_bathroom room1_bathroom)
	(placeinroom place6_door_room4_closet room4_closet)
	(placeinroom place7_door_room18_staircase room18_staircase)
	(placeinroom place8_door_room11_empty_room room11_empty_room)
	(placeinroom place9_door_room9_empty_room room9_empty_room)
	(placelocation location_Xneg14_Ypos41_place32_room2_floorB place32_receptacle26_toilet)
	(placelocation location_Xneg17_Ypos44_place4_room2_floorB place4_door_room2_bathroom)
	(placelocation location_Xneg19_Ypos96_place10_room12_floorB place10_door_room12_empty_room)
	(placelocation location_Xneg21_Ypos38_place21_room2_floorB place21_receptacle5_sink)
	(placelocation location_Xneg23_Ypos22_place1_room15_floorA place1_door_room15_kitchen)
	(placelocation location_Xneg25_Ypos82_place31_room4_floorB place31_receptacle15_refrigerator)
	(placelocation location_Xneg25_Ypos83_place6_room4_floorB place6_door_room4_closet)
	(placelocation location_Xneg27_Ypos11_place27_room15_floorA place27_receptacle11_refrigerator)
	(placelocation location_Xneg2_Ypos14_place18_room15_floorA place18_receptacle2_oven)
	(placelocation location_Xneg2_Ypos91_place13_room11_floorB place13_item22_clock)
	(placelocation location_Xneg35_Yneg5_place9_room9_floorA place9_door_room9_empty_room)
	(placelocation location_Xneg36_Ypos7_place14_room9_floorA place14_item23_clock)
	(placelocation location_Xneg3_Ypos4_place36_room19_floorA place36_receptacle30_toilet)
	(placelocation location_Xneg5_Ypos86_place16_room11_floorB place16_item25_banana)
	(placelocation location_Xneg9_Ypos33_place22_room15_floorA place22_receptacle6_sink)
	(placelocation location_Xneg9_Ypos79_place15_room12_floorB place15_item24_banana)
	(placelocation location_Xpos10_Ypos113_place17_room11_floorB place17_item31_potted_plant)
	(placelocation location_Xpos10_Ypos97_place8_room11_floorB place8_door_room11_empty_room)
	(placelocation location_Xpos14_Ypos3_place26_room19_floorA place26_receptacle10_sink)
	(placelocation location_Xpos14_Ypos52_place2_room16_floorB place2_door_room16_kitchen)
	(placelocation location_Xpos15_Ypos20_place5_room1_floorA place5_door_room1_bathroom)
	(placelocation location_Xpos15_Ypos51_place0_room10_floorA place0_door_room10_empty_room)
	(placelocation location_Xpos16_Ypos87_place7_room18_floorA place7_door_room18_staircase)
	(placelocation location_Xpos17_Ypos100_place12_room18_floorA place12_item16_bottle)
	(placelocation location_Xpos18_Ypos11_place30_room1_floorA place30_receptacle14_refrigerator)
	(placelocation location_Xpos19_Ypos14_place29_room1_floorA place29_receptacle13_refrigerator)
	(placelocation location_Xpos22_Yneg12_place25_room19_floorA place25_receptacle9_sink)
	(placelocation location_Xpos22_Ypos25_place23_room1_floorA place23_receptacle7_sink)
	(placelocation location_Xpos23_Ypos63_place28_room16_floorB place28_receptacle12_refrigerator)
	(placelocation location_Xpos2_Yneg5_place3_room19_floorA place3_door_room19_utility_room)
	(placelocation location_Xpos3_Ypos51_place19_room16_floorB place19_receptacle3_oven)
	(placelocation location_Xpos4_Ypos47_place11_room10_floorA place11_item1_sports_ball)
	(placelocation location_Xpos7_Ypos11_place33_room1_floorA place33_receptacle27_toilet)
	(placelocation location_Xpos7_Ypos12_place34_room1_floorA place34_receptacle28_toilet)
	(placelocation location_Xpos7_Ypos9_place35_room1_floorA place35_receptacle29_toilet)
	(placelocation location_Xpos9_Yneg15_place20_room19_floorA place20_receptacle4_oven)
	(placelocation location_Xpos9_Ypos41_place24_room16_floorB place24_receptacle8_sink)
	(receptacleatlocation receptacle10_sink location_Xpos14_Ypos3_place26_room19_floorA)
	(receptacleatlocation receptacle11_refrigerator location_Xneg27_Ypos11_place27_room15_floorA)
	(receptacleatlocation receptacle12_refrigerator location_Xpos23_Ypos63_place28_room16_floorB)
	(receptacleatlocation receptacle13_refrigerator location_Xpos19_Ypos14_place29_room1_floorA)
	(receptacleatlocation receptacle14_refrigerator location_Xpos18_Ypos11_place30_room1_floorA)
	(receptacleatlocation receptacle15_refrigerator location_Xneg25_Ypos82_place31_room4_floorB)
	(receptacleatlocation receptacle26_toilet location_Xneg14_Ypos41_place32_room2_floorB)
	(receptacleatlocation receptacle27_toilet location_Xpos7_Ypos11_place33_room1_floorA)
	(receptacleatlocation receptacle28_toilet location_Xpos7_Ypos12_place34_room1_floorA)
	(receptacleatlocation receptacle29_toilet location_Xpos7_Ypos9_place35_room1_floorA)
	(receptacleatlocation receptacle2_oven location_Xneg2_Ypos14_place18_room15_floorA)
	(receptacleatlocation receptacle30_toilet location_Xneg3_Ypos4_place36_room19_floorA)
	(receptacleatlocation receptacle3_oven location_Xpos3_Ypos51_place19_room16_floorB)
	(receptacleatlocation receptacle4_oven location_Xpos9_Yneg15_place20_room19_floorA)
	(receptacleatlocation receptacle5_sink location_Xneg21_Ypos38_place21_room2_floorB)
	(receptacleatlocation receptacle6_sink location_Xneg9_Ypos33_place22_room15_floorA)
	(receptacleatlocation receptacle7_sink location_Xpos22_Ypos25_place23_room1_floorA)
	(receptacleatlocation receptacle8_sink location_Xpos9_Ypos41_place24_room16_floorB)
	(receptacleatlocation receptacle9_sink location_Xpos22_Yneg12_place25_room19_floorA)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle13_refrigerator)
	(receptacleopeningtype receptacle14_refrigerator)
	(receptacleopeningtype receptacle15_refrigerator)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle3_oven)
	(receptacleopeningtype receptacle4_oven)
	(roomplace place0_door_room10_empty_room room10_empty_room)
	(roomplace place10_door_room12_empty_room room12_empty_room)
	(roomplace place1_door_room15_kitchen room15_kitchen)
	(roomplace place2_door_room16_kitchen room16_kitchen)
	(roomplace place3_door_room19_utility_room room19_utility_room)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room1_bathroom room1_bathroom)
	(roomplace place6_door_room4_closet room4_closet)
	(roomplace place7_door_room18_staircase room18_staircase)
	(roomplace place8_door_room11_empty_room room11_empty_room)
	(roomplace place9_door_room9_empty_room room9_empty_room)
	(smallitem item16_bottle_smallitem)
	(smallitem item17_bottle_smallitem)
	(smallitem item18_bottle_smallitem)
	(smallitem item19_bottle_smallitem)
	(smallitem item24_banana_smallitem)
	(smallitem item25_banana_smallitem)
  )
  (:goal (and
	(inreceptacle item31_potted_plant_largeitem receptacle7_sink)
	(inreceptacle item22_clock_mediumitem receptacle29_toilet)
	(inreceptacle item20_clock_mediumitem receptacle3_oven)
	(inreceptacle item25_banana_smallitem receptacle13_refrigerator)
	(inreceptacle item19_bottle_smallitem receptacle15_refrigerator)
	(inreceptacle item1_sports_ball_largeitem receptacle13_refrigerator)
	(inreceptacle item23_clock_mediumitem receptacle6_sink)
	(inreceptacle item21_clock_mediumitem receptacle9_sink)
	(inreceptacle item17_bottle_smallitem receptacle2_oven)
	(inreceptacle item18_bottle_smallitem receptacle29_toilet)))
)
