
(define (problem taskograph_rearrangement) (:domain taskography_v3)
  (:objects
        agent - agent
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	item10_cup_smallitem - item
	item11_clock_mediumitem - item
	item12_vase_mediumitem - item
	item13_vase_mediumitem - item
	item14_vase_mediumitem - item
	item15_vase_mediumitem - item
	item16_bowl_smallitem - item
	item17_bowl_smallitem - item
	item18_banana_smallitem - item
	item19_banana_smallitem - item
	item20_apple_smallitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item8_cup_smallitem - item
	item9_cup_smallitem - item
	location_Xneg12_Ypos57_place16_room1_floorA - location
	location_Xneg13_Ypos26_place11_room2_floorA - location
	location_Xneg14_Ypos23_place11_room2_floorA - location
	location_Xneg19_Yneg29_place10_room8_floorA - location
	location_Xneg20_Ypos26_place1_room2_floorA - location
	location_Xneg21_Yneg28_place10_room8_floorA - location
	location_Xneg22_Yneg11_place14_room8_floorA - location
	location_Xneg22_Yneg22_place10_room8_floorA - location
	location_Xneg2_Yneg10_place7_room3_floorA - location
	location_Xneg2_Ypos45_place2_room1_floorA - location
	location_Xneg31_Ypos5_place5_room6_floorA - location
	location_Xneg32_Yneg17_place0_room8_floorA - location
	location_Xneg33_Ypos6_place8_room6_floorA - location
	location_Xneg36_Yneg26_place9_room8_floorA - location
	location_Xneg42_Yneg16_place12_room8_floorA - location
	location_Xneg42_Yneg28_place9_room8_floorA - location
	location_Xneg42_Yneg9_place12_room8_floorA - location
	location_Xneg44_Yneg26_place9_room8_floorA - location
	location_Xneg44_Yneg28_place9_room8_floorA - location
	location_Xneg47_Yneg28_place28_room7_floorA - location
	location_Xneg49_Yneg22_place28_room7_floorA - location
	location_Xneg51_Yneg23_place18_room7_floorA - location
	location_Xneg53_Ypos24_place6_room4_floorA - location
	location_Xneg54_Yneg29_place26_room7_floorA - location
	location_Xneg56_Yneg17_place4_room7_floorA - location
	location_Xneg56_Yneg23_place26_room7_floorA - location
	location_Xneg57_Yneg28_place27_room7_floorA - location
	location_Xneg57_Yneg29_place26_room7_floorA - location
	location_Xneg61_Yneg29_place26_room7_floorA - location
	location_Xneg61_Ypos28_place24_room4_floorA - location
	location_Xneg62_Yneg23_place19_room7_floorA - location
	location_Xneg6_Yneg18_place25_room3_floorA - location
	location_Xneg71_Ypos2_place17_room9_floorA - location
	location_Xneg82_Yneg24_place22_room9_floorA - location
	location_Xneg82_Yneg6_place23_room9_floorA - location
	location_Xneg83_Yneg11_place3_room9_floorA - location
	location_Xneg83_Yneg22_place20_room9_floorA - location
	location_Xneg85_Yneg26_place21_room9_floorA - location
	location_Xneg94_Yneg7_place23_room9_floorA - location
	location_Xneg9_Ypos37_place15_room1_floorA - location
	location_Xpos5_Ypos54_place16_room1_floorA - location
	location_Xpos6_Ypos39_place13_room1_floorA - location
	location_Xpos8_Ypos42_place13_room1_floorA - location
	place0_door_room8_kitchen - place
	place10_receptacle2_oven - place
	place11_receptacle3_sink - place
	place12_receptacle4_sink - place
	place13_receptacle5_sink - place
	place14_receptacle6_refrigerator - place
	place15_receptacle7_refrigerator - place
	place16_receptacle21_toilet - place
	place17_receptacle22_chair - place
	place18_receptacle23_chair - place
	place19_receptacle24_chair - place
	place1_door_room2_bathroom - place
	place20_receptacle25_chair - place
	place21_receptacle26_chair - place
	place22_receptacle27_chair - place
	place23_receptacle29_couch - place
	place24_receptacle34_bed - place
	place25_receptacle35_bed - place
	place26_receptacle36_dining_table - place
	place27_receptacle37_dining_table - place
	place28_receptacle38_dining_table - place
	place2_door_room1_bathroom - place
	place3_door_room9_living_room - place
	place4_door_room7_dining_room - place
	place5_door_room6_corridor - place
	place6_door_room4_bedroom - place
	place7_door_room3_bedroom - place
	place8_item20_apple - place
	place9_receptacle1_microwave - place
	receptacle1_microwave - receptacle
	receptacle21_toilet - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle29_couch - receptacle
	receptacle2_oven - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_dining_table - receptacle
	receptacle37_dining_table - receptacle
	receptacle38_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_sink - receptacle
	receptacle6_refrigerator - receptacle
	receptacle7_refrigerator - receptacle
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room6_corridor - room
	room7_dining_room - room
	room8_kitchen - room
	room9_living_room - room
  )
  (:init 
	(atlocation agent location_Xneg83_Yneg11_place3_room9_floorA)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item11_clock_mediumitem)
	(inanyreceptacle item12_vase_mediumitem)
	(inanyreceptacle item13_vase_mediumitem)
	(inanyreceptacle item14_vase_mediumitem)
	(inanyreceptacle item15_vase_mediumitem)
	(inanyreceptacle item16_bowl_smallitem)
	(inanyreceptacle item17_bowl_smallitem)
	(inanyreceptacle item18_banana_smallitem)
	(inanyreceptacle item19_banana_smallitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item8_cup_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inplace agent place3_door_room9_living_room)
	(inreceptacle item10_cup_smallitem receptacle2_oven)
	(inreceptacle item11_clock_mediumitem receptacle21_toilet)
	(inreceptacle item12_vase_mediumitem receptacle1_microwave)
	(inreceptacle item13_vase_mediumitem receptacle1_microwave)
	(inreceptacle item14_vase_mediumitem receptacle1_microwave)
	(inreceptacle item15_vase_mediumitem receptacle5_sink)
	(inreceptacle item16_bowl_smallitem receptacle29_couch)
	(inreceptacle item17_bowl_smallitem receptacle4_sink)
	(inreceptacle item18_banana_smallitem receptacle36_dining_table)
	(inreceptacle item19_banana_smallitem receptacle38_dining_table)
	(inreceptacle item30_potted_plant_largeitem receptacle3_sink)
	(inreceptacle item31_potted_plant_largeitem receptacle36_dining_table)
	(inreceptacle item32_potted_plant_largeitem receptacle36_dining_table)
	(inreceptacle item33_potted_plant_largeitem receptacle36_dining_table)
	(inreceptacle item8_cup_smallitem receptacle2_oven)
	(inreceptacle item9_cup_smallitem receptacle2_oven)
	(inroom agent room9_living_room)
	(itematlocation item10_cup_smallitem location_Xneg19_Yneg29_place10_room8_floorA)
	(itematlocation item11_clock_mediumitem location_Xneg12_Ypos57_place16_room1_floorA)
	(itematlocation item12_vase_mediumitem location_Xneg44_Yneg26_place9_room8_floorA)
	(itematlocation item13_vase_mediumitem location_Xneg42_Yneg28_place9_room8_floorA)
	(itematlocation item14_vase_mediumitem location_Xneg44_Yneg28_place9_room8_floorA)
	(itematlocation item15_vase_mediumitem location_Xpos8_Ypos42_place13_room1_floorA)
	(itematlocation item16_bowl_smallitem location_Xneg82_Yneg6_place23_room9_floorA)
	(itematlocation item17_bowl_smallitem location_Xneg42_Yneg9_place12_room8_floorA)
	(itematlocation item18_banana_smallitem location_Xneg56_Yneg23_place26_room7_floorA)
	(itematlocation item19_banana_smallitem location_Xneg47_Yneg28_place28_room7_floorA)
	(itematlocation item20_apple_smallitem location_Xneg33_Ypos6_place8_room6_floorA)
	(itematlocation item30_potted_plant_largeitem location_Xneg13_Ypos26_place11_room2_floorA)
	(itematlocation item31_potted_plant_largeitem location_Xneg61_Yneg29_place26_room7_floorA)
	(itematlocation item32_potted_plant_largeitem location_Xneg57_Yneg29_place26_room7_floorA)
	(itematlocation item33_potted_plant_largeitem location_Xneg54_Yneg29_place26_room7_floorA)
	(itematlocation item8_cup_smallitem location_Xneg21_Yneg28_place10_room8_floorA)
	(itematlocation item9_cup_smallitem location_Xneg19_Yneg29_place10_room8_floorA)
	(largeitem item30_potted_plant_largeitem)
	(largeitem item31_potted_plant_largeitem)
	(largeitem item32_potted_plant_largeitem)
	(largeitem item33_potted_plant_largeitem)
	(locationinplace location_Xneg12_Ypos57_place16_room1_floorA place16_receptacle21_toilet)
	(locationinplace location_Xneg13_Ypos26_place11_room2_floorA place11_receptacle3_sink)
	(locationinplace location_Xneg14_Ypos23_place11_room2_floorA place11_receptacle3_sink)
	(locationinplace location_Xneg19_Yneg29_place10_room8_floorA place10_receptacle2_oven)
	(locationinplace location_Xneg20_Ypos26_place1_room2_floorA place1_door_room2_bathroom)
	(locationinplace location_Xneg21_Yneg28_place10_room8_floorA place10_receptacle2_oven)
	(locationinplace location_Xneg22_Yneg11_place14_room8_floorA place14_receptacle6_refrigerator)
	(locationinplace location_Xneg22_Yneg22_place10_room8_floorA place10_receptacle2_oven)
	(locationinplace location_Xneg2_Yneg10_place7_room3_floorA place7_door_room3_bedroom)
	(locationinplace location_Xneg2_Ypos45_place2_room1_floorA place2_door_room1_bathroom)
	(locationinplace location_Xneg31_Ypos5_place5_room6_floorA place5_door_room6_corridor)
	(locationinplace location_Xneg32_Yneg17_place0_room8_floorA place0_door_room8_kitchen)
	(locationinplace location_Xneg33_Ypos6_place8_room6_floorA place8_item20_apple)
	(locationinplace location_Xneg36_Yneg26_place9_room8_floorA place9_receptacle1_microwave)
	(locationinplace location_Xneg42_Yneg16_place12_room8_floorA place12_receptacle4_sink)
	(locationinplace location_Xneg42_Yneg28_place9_room8_floorA place9_receptacle1_microwave)
	(locationinplace location_Xneg42_Yneg9_place12_room8_floorA place12_receptacle4_sink)
	(locationinplace location_Xneg44_Yneg26_place9_room8_floorA place9_receptacle1_microwave)
	(locationinplace location_Xneg44_Yneg28_place9_room8_floorA place9_receptacle1_microwave)
	(locationinplace location_Xneg47_Yneg28_place28_room7_floorA place28_receptacle38_dining_table)
	(locationinplace location_Xneg49_Yneg22_place28_room7_floorA place28_receptacle38_dining_table)
	(locationinplace location_Xneg51_Yneg23_place18_room7_floorA place18_receptacle23_chair)
	(locationinplace location_Xneg53_Ypos24_place6_room4_floorA place6_door_room4_bedroom)
	(locationinplace location_Xneg54_Yneg29_place26_room7_floorA place26_receptacle36_dining_table)
	(locationinplace location_Xneg56_Yneg17_place4_room7_floorA place4_door_room7_dining_room)
	(locationinplace location_Xneg56_Yneg23_place26_room7_floorA place26_receptacle36_dining_table)
	(locationinplace location_Xneg57_Yneg28_place27_room7_floorA place27_receptacle37_dining_table)
	(locationinplace location_Xneg57_Yneg29_place26_room7_floorA place26_receptacle36_dining_table)
	(locationinplace location_Xneg61_Yneg29_place26_room7_floorA place26_receptacle36_dining_table)
	(locationinplace location_Xneg61_Ypos28_place24_room4_floorA place24_receptacle34_bed)
	(locationinplace location_Xneg62_Yneg23_place19_room7_floorA place19_receptacle24_chair)
	(locationinplace location_Xneg6_Yneg18_place25_room3_floorA place25_receptacle35_bed)
	(locationinplace location_Xneg71_Ypos2_place17_room9_floorA place17_receptacle22_chair)
	(locationinplace location_Xneg82_Yneg24_place22_room9_floorA place22_receptacle27_chair)
	(locationinplace location_Xneg82_Yneg6_place23_room9_floorA place23_receptacle29_couch)
	(locationinplace location_Xneg83_Yneg11_place3_room9_floorA place3_door_room9_living_room)
	(locationinplace location_Xneg83_Yneg22_place20_room9_floorA place20_receptacle25_chair)
	(locationinplace location_Xneg85_Yneg26_place21_room9_floorA place21_receptacle26_chair)
	(locationinplace location_Xneg94_Yneg7_place23_room9_floorA place23_receptacle29_couch)
	(locationinplace location_Xneg9_Ypos37_place15_room1_floorA place15_receptacle7_refrigerator)
	(locationinplace location_Xpos5_Ypos54_place16_room1_floorA place16_receptacle21_toilet)
	(locationinplace location_Xpos6_Ypos39_place13_room1_floorA place13_receptacle5_sink)
	(locationinplace location_Xpos8_Ypos42_place13_room1_floorA place13_receptacle5_sink)
	(mediumitem item11_clock_mediumitem)
	(mediumitem item12_vase_mediumitem)
	(mediumitem item13_vase_mediumitem)
	(mediumitem item14_vase_mediumitem)
	(mediumitem item15_vase_mediumitem)
	(placeinroom place0_door_room8_kitchen room8_kitchen)
	(placeinroom place10_receptacle2_oven room8_kitchen)
	(placeinroom place11_receptacle3_sink room2_bathroom)
	(placeinroom place12_receptacle4_sink room8_kitchen)
	(placeinroom place13_receptacle5_sink room1_bathroom)
	(placeinroom place14_receptacle6_refrigerator room8_kitchen)
	(placeinroom place15_receptacle7_refrigerator room1_bathroom)
	(placeinroom place16_receptacle21_toilet room1_bathroom)
	(placeinroom place17_receptacle22_chair room9_living_room)
	(placeinroom place18_receptacle23_chair room7_dining_room)
	(placeinroom place19_receptacle24_chair room7_dining_room)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place20_receptacle25_chair room9_living_room)
	(placeinroom place21_receptacle26_chair room9_living_room)
	(placeinroom place22_receptacle27_chair room9_living_room)
	(placeinroom place23_receptacle29_couch room9_living_room)
	(placeinroom place24_receptacle34_bed room4_bedroom)
	(placeinroom place25_receptacle35_bed room3_bedroom)
	(placeinroom place26_receptacle36_dining_table room7_dining_room)
	(placeinroom place27_receptacle37_dining_table room7_dining_room)
	(placeinroom place28_receptacle38_dining_table room7_dining_room)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place3_door_room9_living_room room9_living_room)
	(placeinroom place4_door_room7_dining_room room7_dining_room)
	(placeinroom place5_door_room6_corridor room6_corridor)
	(placeinroom place6_door_room4_bedroom room4_bedroom)
	(placeinroom place7_door_room3_bedroom room3_bedroom)
	(placeinroom place8_item20_apple room6_corridor)
	(placeinroom place9_receptacle1_microwave room8_kitchen)
	(placelocation location_Xneg14_Ypos23_place11_room2_floorA place11_receptacle3_sink)
	(placelocation location_Xneg20_Ypos26_place1_room2_floorA place1_door_room2_bathroom)
	(placelocation location_Xneg22_Yneg11_place14_room8_floorA place14_receptacle6_refrigerator)
	(placelocation location_Xneg22_Yneg22_place10_room8_floorA place10_receptacle2_oven)
	(placelocation location_Xneg2_Yneg10_place7_room3_floorA place7_door_room3_bedroom)
	(placelocation location_Xneg2_Ypos45_place2_room1_floorA place2_door_room1_bathroom)
	(placelocation location_Xneg31_Ypos5_place5_room6_floorA place5_door_room6_corridor)
	(placelocation location_Xneg32_Yneg17_place0_room8_floorA place0_door_room8_kitchen)
	(placelocation location_Xneg33_Ypos6_place8_room6_floorA place8_item20_apple)
	(placelocation location_Xneg36_Yneg26_place9_room8_floorA place9_receptacle1_microwave)
	(placelocation location_Xneg42_Yneg16_place12_room8_floorA place12_receptacle4_sink)
	(placelocation location_Xneg49_Yneg22_place28_room7_floorA place28_receptacle38_dining_table)
	(placelocation location_Xneg51_Yneg23_place18_room7_floorA place18_receptacle23_chair)
	(placelocation location_Xneg53_Ypos24_place6_room4_floorA place6_door_room4_bedroom)
	(placelocation location_Xneg56_Yneg17_place4_room7_floorA place4_door_room7_dining_room)
	(placelocation location_Xneg56_Yneg23_place26_room7_floorA place26_receptacle36_dining_table)
	(placelocation location_Xneg57_Yneg28_place27_room7_floorA place27_receptacle37_dining_table)
	(placelocation location_Xneg61_Ypos28_place24_room4_floorA place24_receptacle34_bed)
	(placelocation location_Xneg62_Yneg23_place19_room7_floorA place19_receptacle24_chair)
	(placelocation location_Xneg6_Yneg18_place25_room3_floorA place25_receptacle35_bed)
	(placelocation location_Xneg71_Ypos2_place17_room9_floorA place17_receptacle22_chair)
	(placelocation location_Xneg82_Yneg24_place22_room9_floorA place22_receptacle27_chair)
	(placelocation location_Xneg83_Yneg11_place3_room9_floorA place3_door_room9_living_room)
	(placelocation location_Xneg83_Yneg22_place20_room9_floorA place20_receptacle25_chair)
	(placelocation location_Xneg85_Yneg26_place21_room9_floorA place21_receptacle26_chair)
	(placelocation location_Xneg94_Yneg7_place23_room9_floorA place23_receptacle29_couch)
	(placelocation location_Xneg9_Ypos37_place15_room1_floorA place15_receptacle7_refrigerator)
	(placelocation location_Xpos5_Ypos54_place16_room1_floorA place16_receptacle21_toilet)
	(placelocation location_Xpos6_Ypos39_place13_room1_floorA place13_receptacle5_sink)
	(receptacleatlocation receptacle1_microwave location_Xneg36_Yneg26_place9_room8_floorA)
	(receptacleatlocation receptacle21_toilet location_Xpos5_Ypos54_place16_room1_floorA)
	(receptacleatlocation receptacle22_chair location_Xneg71_Ypos2_place17_room9_floorA)
	(receptacleatlocation receptacle23_chair location_Xneg51_Yneg23_place18_room7_floorA)
	(receptacleatlocation receptacle24_chair location_Xneg62_Yneg23_place19_room7_floorA)
	(receptacleatlocation receptacle25_chair location_Xneg83_Yneg22_place20_room9_floorA)
	(receptacleatlocation receptacle26_chair location_Xneg85_Yneg26_place21_room9_floorA)
	(receptacleatlocation receptacle27_chair location_Xneg82_Yneg24_place22_room9_floorA)
	(receptacleatlocation receptacle29_couch location_Xneg94_Yneg7_place23_room9_floorA)
	(receptacleatlocation receptacle2_oven location_Xneg22_Yneg22_place10_room8_floorA)
	(receptacleatlocation receptacle34_bed location_Xneg61_Ypos28_place24_room4_floorA)
	(receptacleatlocation receptacle35_bed location_Xneg6_Yneg18_place25_room3_floorA)
	(receptacleatlocation receptacle36_dining_table location_Xneg56_Yneg23_place26_room7_floorA)
	(receptacleatlocation receptacle37_dining_table location_Xneg57_Yneg28_place27_room7_floorA)
	(receptacleatlocation receptacle38_dining_table location_Xneg49_Yneg22_place28_room7_floorA)
	(receptacleatlocation receptacle3_sink location_Xneg14_Ypos23_place11_room2_floorA)
	(receptacleatlocation receptacle4_sink location_Xneg42_Yneg16_place12_room8_floorA)
	(receptacleatlocation receptacle5_sink location_Xpos6_Ypos39_place13_room1_floorA)
	(receptacleatlocation receptacle6_refrigerator location_Xneg22_Yneg11_place14_room8_floorA)
	(receptacleatlocation receptacle7_refrigerator location_Xneg9_Ypos37_place15_room1_floorA)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle6_refrigerator)
	(receptacleopeningtype receptacle7_refrigerator)
	(roomplace place0_door_room8_kitchen room8_kitchen)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room9_living_room room9_living_room)
	(roomplace place4_door_room7_dining_room room7_dining_room)
	(roomplace place5_door_room6_corridor room6_corridor)
	(roomplace place6_door_room4_bedroom room4_bedroom)
	(roomplace place7_door_room3_bedroom room3_bedroom)
	(smallitem item10_cup_smallitem)
	(smallitem item16_bowl_smallitem)
	(smallitem item17_bowl_smallitem)
	(smallitem item18_banana_smallitem)
	(smallitem item19_banana_smallitem)
	(smallitem item20_apple_smallitem)
	(smallitem item8_cup_smallitem)
	(smallitem item9_cup_smallitem)
  )
  (:goal (and
	(inreceptacle item14_vase_mediumitem receptacle21_toilet)
	(inreceptacle item20_apple_smallitem receptacle25_chair)
	(inreceptacle item16_bowl_smallitem receptacle24_chair)
	(inreceptacle item8_cup_smallitem receptacle29_couch)
	(inreceptacle item18_banana_smallitem receptacle2_oven)
	(inreceptacle item10_cup_smallitem receptacle22_chair)
	(inreceptacle item19_banana_smallitem receptacle5_sink)
	(inreceptacle item17_bowl_smallitem receptacle34_bed)
	(inreceptacle item32_potted_plant_largeitem receptacle7_refrigerator)
	(inreceptacle item31_potted_plant_largeitem receptacle21_toilet)))
)
