
(define (problem taskograph_rearrangement) (:domain taskography_v3)
  (:objects
        agent - agent
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	item18_bottle_smallitem - item
	item19_bottle_smallitem - item
	item20_bottle_smallitem - item
	item21_bottle_smallitem - item
	item22_bottle_smallitem - item
	item23_clock_mediumitem - item
	item24_vase_mediumitem - item
	item25_spoon_smallitem - item
	item26_spoon_smallitem - item
	item27_cup_smallitem - item
	item28_frisbee_mediumitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item37_tv_largeitem - item
	item38_tv_largeitem - item
	item39_tv_largeitem - item
	location_Xneg10_Ypos50_place11_room12_floorA - location
	location_Xneg12_Yneg19_place2_room2_floorA - location
	location_Xneg13_Yneg64_place7_room10_floorA - location
	location_Xneg13_Ypos56_place42_room3_floorB - location
	location_Xneg14_Yneg12_place26_room2_floorA - location
	location_Xneg14_Yneg50_place16_room10_floorA - location
	location_Xneg14_Ypos31_place29_room16_floorB - location
	location_Xneg16_Yneg39_place3_room1_floorA - location
	location_Xneg16_Yneg44_place40_room1_floorA - location
	location_Xneg16_Ypos21_place1_room16_floorB - location
	location_Xneg16_Ypos23_place0_room15_floorA - location
	location_Xneg16_Ypos38_place30_room3_floorB - location
	location_Xneg17_Yneg26_place39_room2_floorA - location
	location_Xneg20_Yneg8_place26_room2_floorA - location
	location_Xneg20_Ypos11_place28_room15_floorA - location
	location_Xneg20_Ypos51_place4_room3_floorB - location
	location_Xneg20_Ypos64_place42_room3_floorB - location
	location_Xneg21_Yneg9_place26_room2_floorA - location
	location_Xneg23_Ypos8_place19_room16_floorB - location
	location_Xneg26_Ypos51_place41_room3_floorB - location
	location_Xneg27_Ypos24_place24_room15_floorA - location
	location_Xneg28_Yneg39_place27_room1_floorA - location
	location_Xneg29_Ypos10_place28_room15_floorA - location
	location_Xneg29_Ypos25_place22_room15_floorA - location
	location_Xneg29_Ypos25_place23_room16_floorB - location
	location_Xneg29_Ypos40_place14_room12_floorA - location
	location_Xneg2_Yneg39_place40_room1_floorA - location
	location_Xneg2_Yneg6_place18_room17_floorA - location
	location_Xneg2_Ypos28_place38_room16_floorB - location
	location_Xneg37_Ypos60_place8_room6_floorA - location
	location_Xneg3_Yneg32_place17_room1_floorA - location
	location_Xneg3_Ypos0_place9_room17_floorA - location
	location_Xneg42_Ypos60_place36_room6_floorA - location
	location_Xneg4_Yneg32_place40_room1_floorA - location
	location_Xneg4_Ypos21_place35_room15_floorA - location
	location_Xneg6_Ypos31_place37_room16_floorB - location
	location_Xneg8_Yneg27_place25_room2_floorA - location
	location_Xpos10_Yneg14_place6_room5_floorA - location
	location_Xpos22_Yneg12_place31_room9_floorA - location
	location_Xpos29_Yneg60_place21_room8_floorA - location
	location_Xpos32_Ypos8_place32_room9_floorA - location
	location_Xpos36_Ypos38_place12_room11_floorA - location
	location_Xpos36_Ypos5_place32_room9_floorA - location
	location_Xpos36_Ypos66_place43_room11_floorA - location
	location_Xpos38_Yneg38_place13_room4_floorA - location
	location_Xpos38_Ypos10_place15_room11_floorA - location
	location_Xpos39_Yneg70_place10_room8_floorA - location
	location_Xpos39_Yneg7_place5_room9_floorA - location
	location_Xpos43_Yneg43_place44_room4_floorA - location
	location_Xpos52_Yneg22_place20_room9_floorA - location
	location_Xpos5_Yneg64_place34_room10_floorA - location
	location_Xpos7_Yneg38_place33_room5_floorA - location
	place0_door_room15_kitchen - place
	place10_door_room8_empty_room - place
	place11_door_room12_empty_room - place
	place12_door_room11_empty_room - place
	place13_door_room4_bedroom - place
	place14_item33_potted_plant - place
	place15_item37_tv - place
	place16_item39_tv - place
	place17_item23_clock - place
	place18_item25_spoon - place
	place19_item26_spoon - place
	place1_door_room16_kitchen - place
	place20_item27_cup - place
	place21_item28_frisbee - place
	place22_receptacle1_microwave - place
	place23_receptacle2_microwave - place
	place24_receptacle3_oven - place
	place25_receptacle4_sink - place
	place26_receptacle5_sink - place
	place27_receptacle6_sink - place
	place28_receptacle7_sink - place
	place29_receptacle8_sink - place
	place2_door_room2_bathroom - place
	place30_receptacle9_sink - place
	place31_receptacle10_refrigerator - place
	place32_receptacle11_refrigerator - place
	place33_receptacle12_refrigerator - place
	place34_receptacle13_refrigerator - place
	place35_receptacle14_refrigerator - place
	place36_receptacle15_refrigerator - place
	place37_receptacle16_refrigerator - place
	place38_receptacle17_refrigerator - place
	place39_receptacle29_toilet - place
	place3_door_room1_bathroom - place
	place40_receptacle30_toilet - place
	place41_receptacle31_toilet - place
	place42_receptacle32_toilet - place
	place43_receptacle35_bed - place
	place44_receptacle36_bed - place
	place4_door_room3_bathroom - place
	place5_door_room9_empty_room - place
	place6_door_room5_corridor - place
	place7_door_room10_empty_room - place
	place8_door_room6_corridor - place
	place9_door_room17_lobby - place
	receptacle10_refrigerator - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle13_refrigerator - receptacle
	receptacle14_refrigerator - receptacle
	receptacle15_refrigerator - receptacle
	receptacle16_refrigerator - receptacle
	receptacle17_refrigerator - receptacle
	receptacle1_microwave - receptacle
	receptacle29_toilet - receptacle
	receptacle2_microwave - receptacle
	receptacle30_toilet - receptacle
	receptacle31_toilet - receptacle
	receptacle32_toilet - receptacle
	receptacle35_bed - receptacle
	receptacle36_bed - receptacle
	receptacle3_oven - receptacle
	receptacle4_sink - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_sink - receptacle
	room10_empty_room - room
	room11_empty_room - room
	room12_empty_room - room
	room15_kitchen - room
	room16_kitchen - room
	room17_lobby - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_corridor - room
	room8_empty_room - room
	room9_empty_room - room
  )
  (:init 
	(atlocation agent location_Xpos39_Yneg7_place5_room9_floorA)
	(inanyreceptacle item18_bottle_smallitem)
	(inanyreceptacle item19_bottle_smallitem)
	(inanyreceptacle item20_bottle_smallitem)
	(inanyreceptacle item21_bottle_smallitem)
	(inanyreceptacle item22_bottle_smallitem)
	(inanyreceptacle item24_vase_mediumitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item38_tv_largeitem)
	(inplace agent place5_door_room9_empty_room)
	(inreceptacle item18_bottle_smallitem receptacle5_sink)
	(inreceptacle item19_bottle_smallitem receptacle5_sink)
	(inreceptacle item20_bottle_smallitem receptacle30_toilet)
	(inreceptacle item21_bottle_smallitem receptacle30_toilet)
	(inreceptacle item22_bottle_smallitem receptacle30_toilet)
	(inreceptacle item24_vase_mediumitem receptacle32_toilet)
	(inreceptacle item34_potted_plant_largeitem receptacle7_sink)
	(inreceptacle item38_tv_largeitem receptacle11_refrigerator)
	(inroom agent room9_empty_room)
	(itematlocation item18_bottle_smallitem location_Xneg20_Yneg8_place26_room2_floorA)
	(itematlocation item19_bottle_smallitem location_Xneg21_Yneg9_place26_room2_floorA)
	(itematlocation item20_bottle_smallitem location_Xneg2_Yneg39_place40_room1_floorA)
	(itematlocation item21_bottle_smallitem location_Xneg4_Yneg32_place40_room1_floorA)
	(itematlocation item22_bottle_smallitem location_Xneg2_Yneg39_place40_room1_floorA)
	(itematlocation item23_clock_mediumitem location_Xneg3_Yneg32_place17_room1_floorA)
	(itematlocation item24_vase_mediumitem location_Xneg13_Ypos56_place42_room3_floorB)
	(itematlocation item25_spoon_smallitem location_Xneg2_Yneg6_place18_room17_floorA)
	(itematlocation item26_spoon_smallitem location_Xneg23_Ypos8_place19_room16_floorB)
	(itematlocation item27_cup_smallitem location_Xpos52_Yneg22_place20_room9_floorA)
	(itematlocation item28_frisbee_mediumitem location_Xpos29_Yneg60_place21_room8_floorA)
	(itematlocation item33_potted_plant_largeitem location_Xneg29_Ypos40_place14_room12_floorA)
	(itematlocation item34_potted_plant_largeitem location_Xneg29_Ypos10_place28_room15_floorA)
	(itematlocation item37_tv_largeitem location_Xpos38_Ypos10_place15_room11_floorA)
	(itematlocation item38_tv_largeitem location_Xpos36_Ypos5_place32_room9_floorA)
	(itematlocation item39_tv_largeitem location_Xneg14_Yneg50_place16_room10_floorA)
	(largeitem item33_potted_plant_largeitem)
	(largeitem item34_potted_plant_largeitem)
	(largeitem item37_tv_largeitem)
	(largeitem item38_tv_largeitem)
	(largeitem item39_tv_largeitem)
	(locationinplace location_Xneg10_Ypos50_place11_room12_floorA place11_door_room12_empty_room)
	(locationinplace location_Xneg12_Yneg19_place2_room2_floorA place2_door_room2_bathroom)
	(locationinplace location_Xneg13_Yneg64_place7_room10_floorA place7_door_room10_empty_room)
	(locationinplace location_Xneg13_Ypos56_place42_room3_floorB place42_receptacle32_toilet)
	(locationinplace location_Xneg14_Yneg12_place26_room2_floorA place26_receptacle5_sink)
	(locationinplace location_Xneg14_Yneg50_place16_room10_floorA place16_item39_tv)
	(locationinplace location_Xneg14_Ypos31_place29_room16_floorB place29_receptacle8_sink)
	(locationinplace location_Xneg16_Yneg39_place3_room1_floorA place3_door_room1_bathroom)
	(locationinplace location_Xneg16_Yneg44_place40_room1_floorA place40_receptacle30_toilet)
	(locationinplace location_Xneg16_Ypos21_place1_room16_floorB place1_door_room16_kitchen)
	(locationinplace location_Xneg16_Ypos23_place0_room15_floorA place0_door_room15_kitchen)
	(locationinplace location_Xneg16_Ypos38_place30_room3_floorB place30_receptacle9_sink)
	(locationinplace location_Xneg17_Yneg26_place39_room2_floorA place39_receptacle29_toilet)
	(locationinplace location_Xneg20_Yneg8_place26_room2_floorA place26_receptacle5_sink)
	(locationinplace location_Xneg20_Ypos11_place28_room15_floorA place28_receptacle7_sink)
	(locationinplace location_Xneg20_Ypos51_place4_room3_floorB place4_door_room3_bathroom)
	(locationinplace location_Xneg20_Ypos64_place42_room3_floorB place42_receptacle32_toilet)
	(locationinplace location_Xneg21_Yneg9_place26_room2_floorA place26_receptacle5_sink)
	(locationinplace location_Xneg23_Ypos8_place19_room16_floorB place19_item26_spoon)
	(locationinplace location_Xneg26_Ypos51_place41_room3_floorB place41_receptacle31_toilet)
	(locationinplace location_Xneg27_Ypos24_place24_room15_floorA place24_receptacle3_oven)
	(locationinplace location_Xneg28_Yneg39_place27_room1_floorA place27_receptacle6_sink)
	(locationinplace location_Xneg29_Ypos10_place28_room15_floorA place28_receptacle7_sink)
	(locationinplace location_Xneg29_Ypos25_place22_room15_floorA place22_receptacle1_microwave)
	(locationinplace location_Xneg29_Ypos25_place23_room16_floorB place23_receptacle2_microwave)
	(locationinplace location_Xneg29_Ypos40_place14_room12_floorA place14_item33_potted_plant)
	(locationinplace location_Xneg2_Yneg39_place40_room1_floorA place40_receptacle30_toilet)
	(locationinplace location_Xneg2_Yneg6_place18_room17_floorA place18_item25_spoon)
	(locationinplace location_Xneg2_Ypos28_place38_room16_floorB place38_receptacle17_refrigerator)
	(locationinplace location_Xneg37_Ypos60_place8_room6_floorA place8_door_room6_corridor)
	(locationinplace location_Xneg3_Yneg32_place17_room1_floorA place17_item23_clock)
	(locationinplace location_Xneg3_Ypos0_place9_room17_floorA place9_door_room17_lobby)
	(locationinplace location_Xneg42_Ypos60_place36_room6_floorA place36_receptacle15_refrigerator)
	(locationinplace location_Xneg4_Yneg32_place40_room1_floorA place40_receptacle30_toilet)
	(locationinplace location_Xneg4_Ypos21_place35_room15_floorA place35_receptacle14_refrigerator)
	(locationinplace location_Xneg6_Ypos31_place37_room16_floorB place37_receptacle16_refrigerator)
	(locationinplace location_Xneg8_Yneg27_place25_room2_floorA place25_receptacle4_sink)
	(locationinplace location_Xpos10_Yneg14_place6_room5_floorA place6_door_room5_corridor)
	(locationinplace location_Xpos22_Yneg12_place31_room9_floorA place31_receptacle10_refrigerator)
	(locationinplace location_Xpos29_Yneg60_place21_room8_floorA place21_item28_frisbee)
	(locationinplace location_Xpos32_Ypos8_place32_room9_floorA place32_receptacle11_refrigerator)
	(locationinplace location_Xpos36_Ypos38_place12_room11_floorA place12_door_room11_empty_room)
	(locationinplace location_Xpos36_Ypos5_place32_room9_floorA place32_receptacle11_refrigerator)
	(locationinplace location_Xpos36_Ypos66_place43_room11_floorA place43_receptacle35_bed)
	(locationinplace location_Xpos38_Yneg38_place13_room4_floorA place13_door_room4_bedroom)
	(locationinplace location_Xpos38_Ypos10_place15_room11_floorA place15_item37_tv)
	(locationinplace location_Xpos39_Yneg70_place10_room8_floorA place10_door_room8_empty_room)
	(locationinplace location_Xpos39_Yneg7_place5_room9_floorA place5_door_room9_empty_room)
	(locationinplace location_Xpos43_Yneg43_place44_room4_floorA place44_receptacle36_bed)
	(locationinplace location_Xpos52_Yneg22_place20_room9_floorA place20_item27_cup)
	(locationinplace location_Xpos5_Yneg64_place34_room10_floorA place34_receptacle13_refrigerator)
	(locationinplace location_Xpos7_Yneg38_place33_room5_floorA place33_receptacle12_refrigerator)
	(mediumitem item23_clock_mediumitem)
	(mediumitem item24_vase_mediumitem)
	(mediumitem item28_frisbee_mediumitem)
	(placeinroom place0_door_room15_kitchen room15_kitchen)
	(placeinroom place10_door_room8_empty_room room8_empty_room)
	(placeinroom place11_door_room12_empty_room room12_empty_room)
	(placeinroom place12_door_room11_empty_room room11_empty_room)
	(placeinroom place13_door_room4_bedroom room4_bedroom)
	(placeinroom place14_item33_potted_plant room12_empty_room)
	(placeinroom place15_item37_tv room11_empty_room)
	(placeinroom place16_item39_tv room10_empty_room)
	(placeinroom place17_item23_clock room1_bathroom)
	(placeinroom place18_item25_spoon room17_lobby)
	(placeinroom place19_item26_spoon room16_kitchen)
	(placeinroom place1_door_room16_kitchen room16_kitchen)
	(placeinroom place20_item27_cup room9_empty_room)
	(placeinroom place21_item28_frisbee room8_empty_room)
	(placeinroom place22_receptacle1_microwave room15_kitchen)
	(placeinroom place23_receptacle2_microwave room16_kitchen)
	(placeinroom place24_receptacle3_oven room15_kitchen)
	(placeinroom place25_receptacle4_sink room2_bathroom)
	(placeinroom place26_receptacle5_sink room2_bathroom)
	(placeinroom place27_receptacle6_sink room1_bathroom)
	(placeinroom place28_receptacle7_sink room15_kitchen)
	(placeinroom place29_receptacle8_sink room16_kitchen)
	(placeinroom place2_door_room2_bathroom room2_bathroom)
	(placeinroom place30_receptacle9_sink room3_bathroom)
	(placeinroom place31_receptacle10_refrigerator room9_empty_room)
	(placeinroom place32_receptacle11_refrigerator room9_empty_room)
	(placeinroom place33_receptacle12_refrigerator room5_corridor)
	(placeinroom place34_receptacle13_refrigerator room10_empty_room)
	(placeinroom place35_receptacle14_refrigerator room15_kitchen)
	(placeinroom place36_receptacle15_refrigerator room6_corridor)
	(placeinroom place37_receptacle16_refrigerator room16_kitchen)
	(placeinroom place38_receptacle17_refrigerator room16_kitchen)
	(placeinroom place39_receptacle29_toilet room2_bathroom)
	(placeinroom place3_door_room1_bathroom room1_bathroom)
	(placeinroom place40_receptacle30_toilet room1_bathroom)
	(placeinroom place41_receptacle31_toilet room3_bathroom)
	(placeinroom place42_receptacle32_toilet room3_bathroom)
	(placeinroom place43_receptacle35_bed room11_empty_room)
	(placeinroom place44_receptacle36_bed room4_bedroom)
	(placeinroom place4_door_room3_bathroom room3_bathroom)
	(placeinroom place5_door_room9_empty_room room9_empty_room)
	(placeinroom place6_door_room5_corridor room5_corridor)
	(placeinroom place7_door_room10_empty_room room10_empty_room)
	(placeinroom place8_door_room6_corridor room6_corridor)
	(placeinroom place9_door_room17_lobby room17_lobby)
	(placelocation location_Xneg10_Ypos50_place11_room12_floorA place11_door_room12_empty_room)
	(placelocation location_Xneg12_Yneg19_place2_room2_floorA place2_door_room2_bathroom)
	(placelocation location_Xneg13_Yneg64_place7_room10_floorA place7_door_room10_empty_room)
	(placelocation location_Xneg14_Yneg12_place26_room2_floorA place26_receptacle5_sink)
	(placelocation location_Xneg14_Yneg50_place16_room10_floorA place16_item39_tv)
	(placelocation location_Xneg14_Ypos31_place29_room16_floorB place29_receptacle8_sink)
	(placelocation location_Xneg16_Yneg39_place3_room1_floorA place3_door_room1_bathroom)
	(placelocation location_Xneg16_Yneg44_place40_room1_floorA place40_receptacle30_toilet)
	(placelocation location_Xneg16_Ypos21_place1_room16_floorB place1_door_room16_kitchen)
	(placelocation location_Xneg16_Ypos23_place0_room15_floorA place0_door_room15_kitchen)
	(placelocation location_Xneg16_Ypos38_place30_room3_floorB place30_receptacle9_sink)
	(placelocation location_Xneg17_Yneg26_place39_room2_floorA place39_receptacle29_toilet)
	(placelocation location_Xneg20_Ypos11_place28_room15_floorA place28_receptacle7_sink)
	(placelocation location_Xneg20_Ypos51_place4_room3_floorB place4_door_room3_bathroom)
	(placelocation location_Xneg20_Ypos64_place42_room3_floorB place42_receptacle32_toilet)
	(placelocation location_Xneg23_Ypos8_place19_room16_floorB place19_item26_spoon)
	(placelocation location_Xneg26_Ypos51_place41_room3_floorB place41_receptacle31_toilet)
	(placelocation location_Xneg27_Ypos24_place24_room15_floorA place24_receptacle3_oven)
	(placelocation location_Xneg28_Yneg39_place27_room1_floorA place27_receptacle6_sink)
	(placelocation location_Xneg29_Ypos25_place22_room15_floorA place22_receptacle1_microwave)
	(placelocation location_Xneg29_Ypos25_place23_room16_floorB place23_receptacle2_microwave)
	(placelocation location_Xneg29_Ypos40_place14_room12_floorA place14_item33_potted_plant)
	(placelocation location_Xneg2_Yneg6_place18_room17_floorA place18_item25_spoon)
	(placelocation location_Xneg2_Ypos28_place38_room16_floorB place38_receptacle17_refrigerator)
	(placelocation location_Xneg37_Ypos60_place8_room6_floorA place8_door_room6_corridor)
	(placelocation location_Xneg3_Yneg32_place17_room1_floorA place17_item23_clock)
	(placelocation location_Xneg3_Ypos0_place9_room17_floorA place9_door_room17_lobby)
	(placelocation location_Xneg42_Ypos60_place36_room6_floorA place36_receptacle15_refrigerator)
	(placelocation location_Xneg4_Ypos21_place35_room15_floorA place35_receptacle14_refrigerator)
	(placelocation location_Xneg6_Ypos31_place37_room16_floorB place37_receptacle16_refrigerator)
	(placelocation location_Xneg8_Yneg27_place25_room2_floorA place25_receptacle4_sink)
	(placelocation location_Xpos10_Yneg14_place6_room5_floorA place6_door_room5_corridor)
	(placelocation location_Xpos22_Yneg12_place31_room9_floorA place31_receptacle10_refrigerator)
	(placelocation location_Xpos29_Yneg60_place21_room8_floorA place21_item28_frisbee)
	(placelocation location_Xpos32_Ypos8_place32_room9_floorA place32_receptacle11_refrigerator)
	(placelocation location_Xpos36_Ypos38_place12_room11_floorA place12_door_room11_empty_room)
	(placelocation location_Xpos36_Ypos66_place43_room11_floorA place43_receptacle35_bed)
	(placelocation location_Xpos38_Yneg38_place13_room4_floorA place13_door_room4_bedroom)
	(placelocation location_Xpos38_Ypos10_place15_room11_floorA place15_item37_tv)
	(placelocation location_Xpos39_Yneg70_place10_room8_floorA place10_door_room8_empty_room)
	(placelocation location_Xpos39_Yneg7_place5_room9_floorA place5_door_room9_empty_room)
	(placelocation location_Xpos43_Yneg43_place44_room4_floorA place44_receptacle36_bed)
	(placelocation location_Xpos52_Yneg22_place20_room9_floorA place20_item27_cup)
	(placelocation location_Xpos5_Yneg64_place34_room10_floorA place34_receptacle13_refrigerator)
	(placelocation location_Xpos7_Yneg38_place33_room5_floorA place33_receptacle12_refrigerator)
	(receptacleatlocation receptacle10_refrigerator location_Xpos22_Yneg12_place31_room9_floorA)
	(receptacleatlocation receptacle11_refrigerator location_Xpos32_Ypos8_place32_room9_floorA)
	(receptacleatlocation receptacle12_refrigerator location_Xpos7_Yneg38_place33_room5_floorA)
	(receptacleatlocation receptacle13_refrigerator location_Xpos5_Yneg64_place34_room10_floorA)
	(receptacleatlocation receptacle14_refrigerator location_Xneg4_Ypos21_place35_room15_floorA)
	(receptacleatlocation receptacle15_refrigerator location_Xneg42_Ypos60_place36_room6_floorA)
	(receptacleatlocation receptacle16_refrigerator location_Xneg6_Ypos31_place37_room16_floorB)
	(receptacleatlocation receptacle17_refrigerator location_Xneg2_Ypos28_place38_room16_floorB)
	(receptacleatlocation receptacle1_microwave location_Xneg29_Ypos25_place22_room15_floorA)
	(receptacleatlocation receptacle29_toilet location_Xneg17_Yneg26_place39_room2_floorA)
	(receptacleatlocation receptacle2_microwave location_Xneg29_Ypos25_place23_room16_floorB)
	(receptacleatlocation receptacle30_toilet location_Xneg16_Yneg44_place40_room1_floorA)
	(receptacleatlocation receptacle31_toilet location_Xneg26_Ypos51_place41_room3_floorB)
	(receptacleatlocation receptacle32_toilet location_Xneg20_Ypos64_place42_room3_floorB)
	(receptacleatlocation receptacle35_bed location_Xpos36_Ypos66_place43_room11_floorA)
	(receptacleatlocation receptacle36_bed location_Xpos43_Yneg43_place44_room4_floorA)
	(receptacleatlocation receptacle3_oven location_Xneg27_Ypos24_place24_room15_floorA)
	(receptacleatlocation receptacle4_sink location_Xneg8_Yneg27_place25_room2_floorA)
	(receptacleatlocation receptacle5_sink location_Xneg14_Yneg12_place26_room2_floorA)
	(receptacleatlocation receptacle6_sink location_Xneg28_Yneg39_place27_room1_floorA)
	(receptacleatlocation receptacle7_sink location_Xneg20_Ypos11_place28_room15_floorA)
	(receptacleatlocation receptacle8_sink location_Xneg14_Ypos31_place29_room16_floorB)
	(receptacleatlocation receptacle9_sink location_Xneg16_Ypos38_place30_room3_floorB)
	(receptacleopeningtype receptacle10_refrigerator)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle13_refrigerator)
	(receptacleopeningtype receptacle14_refrigerator)
	(receptacleopeningtype receptacle15_refrigerator)
	(receptacleopeningtype receptacle16_refrigerator)
	(receptacleopeningtype receptacle17_refrigerator)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_microwave)
	(receptacleopeningtype receptacle3_oven)
	(roomplace place0_door_room15_kitchen room15_kitchen)
	(roomplace place10_door_room8_empty_room room8_empty_room)
	(roomplace place11_door_room12_empty_room room12_empty_room)
	(roomplace place12_door_room11_empty_room room11_empty_room)
	(roomplace place13_door_room4_bedroom room4_bedroom)
	(roomplace place1_door_room16_kitchen room16_kitchen)
	(roomplace place2_door_room2_bathroom room2_bathroom)
	(roomplace place3_door_room1_bathroom room1_bathroom)
	(roomplace place4_door_room3_bathroom room3_bathroom)
	(roomplace place5_door_room9_empty_room room9_empty_room)
	(roomplace place6_door_room5_corridor room5_corridor)
	(roomplace place7_door_room10_empty_room room10_empty_room)
	(roomplace place8_door_room6_corridor room6_corridor)
	(roomplace place9_door_room17_lobby room17_lobby)
	(smallitem item18_bottle_smallitem)
	(smallitem item19_bottle_smallitem)
	(smallitem item20_bottle_smallitem)
	(smallitem item21_bottle_smallitem)
	(smallitem item22_bottle_smallitem)
	(smallitem item25_spoon_smallitem)
	(smallitem item26_spoon_smallitem)
	(smallitem item27_cup_smallitem)
  )
  (:goal (and
	(inreceptacle item22_bottle_smallitem receptacle9_sink)
	(inreceptacle item26_spoon_smallitem receptacle10_refrigerator)
	(inreceptacle item25_spoon_smallitem receptacle29_toilet)
	(inreceptacle item23_clock_mediumitem receptacle11_refrigerator)
	(inreceptacle item38_tv_largeitem receptacle4_sink)
	(inreceptacle item28_frisbee_mediumitem receptacle17_refrigerator)
	(inreceptacle item34_potted_plant_largeitem receptacle8_sink)
	(inreceptacle item33_potted_plant_largeitem receptacle6_sink)
	(inreceptacle item27_cup_smallitem receptacle3_oven)
	(inreceptacle item19_bottle_smallitem receptacle14_refrigerator)))
)
