
(define (problem taskograph_rearrangement) (:domain taskography_v3)
  (:objects
        agent - agent
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	item10_cup_smallitem - item
	item11_cup_smallitem - item
	item12_cup_smallitem - item
	item13_cup_smallitem - item
	item14_bowl_smallitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item46_laptop_mediumitem - item
	item59_book_smallitem - item
	item5_bottle_smallitem - item
	item60_book_smallitem - item
	item61_vase_mediumitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item8_bottle_smallitem - item
	item9_cup_smallitem - item
	location_Xneg10_Yneg11_place15_room13_floorB - location
	location_Xneg10_Ypos26_place37_room14_floorB - location
	location_Xneg12_Ypos16_place47_room14_floorB - location
	location_Xneg12_Ypos26_place39_room14_floorB - location
	location_Xneg12_Ypos3_place6_room13_floorB - location
	location_Xneg16_Yneg10_place17_room13_floorB - location
	location_Xneg20_Ypos34_place42_room14_floorB - location
	location_Xneg21_Ypos23_place4_room14_floorB - location
	location_Xneg25_Ypos9_place8_room6_floorC - location
	location_Xneg29_Ypos14_place47_room14_floorB - location
	location_Xneg30_Ypos14_place47_room14_floorB - location
	location_Xneg30_Ypos21_place42_room14_floorB - location
	location_Xneg31_Ypos29_place42_room14_floorB - location
	location_Xneg36_Ypos16_place22_room15_floorB - location
	location_Xneg36_Ypos22_place21_room15_floorB - location
	location_Xneg3_Yneg10_place14_room13_floorB - location
	location_Xneg41_Yneg10_place24_room6_floorC - location
	location_Xneg44_Ypos21_place28_room6_floorC - location
	location_Xneg45_Yneg10_place13_room15_floorB - location
	location_Xneg50_Ypos11_place5_room15_floorB - location
	location_Xneg54_Ypos5_place25_room15_floorB - location
	location_Xneg55_Ypos20_place25_room15_floorB - location
	location_Xneg60_Yneg10_place16_room15_floorB - location
	location_Xneg67_Ypos31_place23_room15_floorB - location
	location_Xneg9_Yneg15_place33_room13_floorB - location
	location_Xneg9_Yneg16_place18_room13_floorB - location
	location_Xneg9_Yneg4_place19_room13_floorB - location
	location_Xneg9_Yneg9_place32_room13_floorB - location
	location_Xpos10_Yneg7_place48_room8_floorB - location
	location_Xpos15_Ypos24_place12_room1_floorA - location
	location_Xpos20_Yneg10_place38_room18_floorA - location
	location_Xpos22_Yneg8_place43_room3_floorC - location
	location_Xpos22_Ypos26_place0_room1_floorA - location
	location_Xpos23_Yneg6_place9_room18_floorA - location
	location_Xpos23_Ypos24_place1_room2_floorB - location
	location_Xpos24_Ypos10_place2_room3_floorC - location
	location_Xpos27_Ypos24_place36_room3_floorC - location
	location_Xpos27_Ypos26_place34_room1_floorA - location
	location_Xpos28_Ypos15_place46_room3_floorC - location
	location_Xpos28_Ypos19_place40_room1_floorA - location
	location_Xpos28_Ypos25_place35_room2_floorB - location
	location_Xpos28_Ypos2_place45_room3_floorC - location
	location_Xpos29_Yneg13_place43_room3_floorC - location
	location_Xpos29_Ypos16_place41_room2_floorB - location
	location_Xpos30_Ypos16_place40_room1_floorA - location
	location_Xpos30_Ypos20_place40_room1_floorA - location
	location_Xpos30_Ypos22_place40_room1_floorA - location
	location_Xpos30_Ypos5_place44_room3_floorC - location
	location_Xpos30_Ypos9_place44_room3_floorC - location
	location_Xpos31_Ypos14_place41_room2_floorB - location
	location_Xpos31_Ypos19_place41_room2_floorB - location
	location_Xpos31_Ypos2_place44_room3_floorC - location
	location_Xpos3_Yneg7_place10_room8_floorB - location
	location_Xpos49_Ypos26_place27_room5_floorB - location
	location_Xpos51_Ypos15_place7_room5_floorB - location
	location_Xpos51_Ypos16_place3_room4_floorA - location
	location_Xpos51_Ypos27_place26_room4_floorA - location
	location_Xpos56_Ypos1_place30_room4_floorA - location
	location_Xpos56_Ypos2_place31_room4_floorA - location
	location_Xpos57_Ypos0_place30_room4_floorA - location
	location_Xpos57_Ypos2_place31_room4_floorA - location
	location_Xpos57_Ypos7_place31_room4_floorA - location
	location_Xpos58_Ypos5_place31_room4_floorA - location
	location_Xpos58_Ypos6_place31_room4_floorA - location
	location_Xpos59_Ypos3_place31_room4_floorA - location
	location_Xpos60_Ypos9_place29_room4_floorA - location
	location_Xpos63_Ypos1_place20_room5_floorB - location
	location_Xpos64_Ypos1_place11_room4_floorA - location
	place0_door_room1_bathroom - place
	place10_door_room8_closet - place
	place11_receptacle15_chair - place
	place12_receptacle16_chair - place
	place13_receptacle17_chair - place
	place14_receptacle18_chair - place
	place15_receptacle19_chair - place
	place16_receptacle20_chair - place
	place17_receptacle21_chair - place
	place18_receptacle22_chair - place
	place19_receptacle23_chair - place
	place1_door_room2_bathroom - place
	place20_receptacle24_chair - place
	place21_receptacle25_chair - place
	place22_receptacle26_chair - place
	place23_receptacle27_chair - place
	place24_receptacle28_chair - place
	place25_receptacle29_couch - place
	place26_receptacle35_bed - place
	place27_receptacle36_bed - place
	place28_receptacle37_bed - place
	place29_receptacle38_dining_table - place
	place2_door_room3_bathroom - place
	place30_receptacle39_dining_table - place
	place31_receptacle40_dining_table - place
	place32_receptacle41_dining_table - place
	place33_receptacle42_dining_table - place
	place34_receptacle43_toilet - place
	place35_receptacle44_toilet - place
	place36_receptacle45_toilet - place
	place37_receptacle47_microwave - place
	place38_receptacle48_oven - place
	place39_receptacle49_oven - place
	place3_door_room4_bedroom - place
	place40_receptacle50_sink - place
	place41_receptacle51_sink - place
	place42_receptacle52_sink - place
	place43_receptacle53_sink - place
	place44_receptacle54_sink - place
	place45_receptacle55_sink - place
	place46_receptacle56_sink - place
	place47_receptacle57_refrigerator - place
	place48_receptacle58_refrigerator - place
	place4_door_room14_kitchen - place
	place5_door_room15_living_room - place
	place6_door_room13_dining_room - place
	place7_door_room5_bedroom - place
	place8_door_room6_bedroom - place
	place9_door_room18_utility_room - place
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_couch - receptacle
	receptacle35_bed - receptacle
	receptacle36_bed - receptacle
	receptacle37_bed - receptacle
	receptacle38_dining_table - receptacle
	receptacle39_dining_table - receptacle
	receptacle40_dining_table - receptacle
	receptacle41_dining_table - receptacle
	receptacle42_dining_table - receptacle
	receptacle43_toilet - receptacle
	receptacle44_toilet - receptacle
	receptacle45_toilet - receptacle
	receptacle47_microwave - receptacle
	receptacle48_oven - receptacle
	receptacle49_oven - receptacle
	receptacle50_sink - receptacle
	receptacle51_sink - receptacle
	receptacle52_sink - receptacle
	receptacle53_sink - receptacle
	receptacle54_sink - receptacle
	receptacle55_sink - receptacle
	receptacle56_sink - receptacle
	receptacle57_refrigerator - receptacle
	receptacle58_refrigerator - receptacle
	room13_dining_room - room
	room14_kitchen - room
	room15_living_room - room
	room18_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_bedroom - room
	room8_closet - room
  )
  (:init 
	(atlocation agent location_Xneg12_Ypos3_place6_room13_floorB)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item11_cup_smallitem)
	(inanyreceptacle item12_cup_smallitem)
	(inanyreceptacle item13_cup_smallitem)
	(inanyreceptacle item14_bowl_smallitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item46_laptop_mediumitem)
	(inanyreceptacle item59_book_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item60_book_smallitem)
	(inanyreceptacle item61_vase_mediumitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inplace agent place6_door_room13_dining_room)
	(inreceptacle item10_cup_smallitem receptacle40_dining_table)
	(inreceptacle item11_cup_smallitem receptacle40_dining_table)
	(inreceptacle item12_cup_smallitem receptacle40_dining_table)
	(inreceptacle item13_cup_smallitem receptacle39_dining_table)
	(inreceptacle item14_bowl_smallitem receptacle52_sink)
	(inreceptacle item30_potted_plant_largeitem receptacle50_sink)
	(inreceptacle item31_potted_plant_largeitem receptacle57_refrigerator)
	(inreceptacle item32_potted_plant_largeitem receptacle29_couch)
	(inreceptacle item33_potted_plant_largeitem receptacle53_sink)
	(inreceptacle item34_potted_plant_largeitem receptacle54_sink)
	(inreceptacle item46_laptop_mediumitem receptacle40_dining_table)
	(inreceptacle item59_book_smallitem receptacle40_dining_table)
	(inreceptacle item5_bottle_smallitem receptacle50_sink)
	(inreceptacle item60_book_smallitem receptacle52_sink)
	(inreceptacle item61_vase_mediumitem receptacle57_refrigerator)
	(inreceptacle item6_bottle_smallitem receptacle51_sink)
	(inreceptacle item7_bottle_smallitem receptacle51_sink)
	(inreceptacle item8_bottle_smallitem receptacle54_sink)
	(inreceptacle item9_cup_smallitem receptacle50_sink)
	(inroom agent room13_dining_room)
	(itematlocation item10_cup_smallitem location_Xpos58_Ypos6_place31_room4_floorA)
	(itematlocation item11_cup_smallitem location_Xpos57_Ypos2_place31_room4_floorA)
	(itematlocation item12_cup_smallitem location_Xpos59_Ypos3_place31_room4_floorA)
	(itematlocation item13_cup_smallitem location_Xpos57_Ypos0_place30_room4_floorA)
	(itematlocation item14_bowl_smallitem location_Xneg30_Ypos21_place42_room14_floorB)
	(itematlocation item30_potted_plant_largeitem location_Xpos30_Ypos16_place40_room1_floorA)
	(itematlocation item31_potted_plant_largeitem location_Xneg30_Ypos14_place47_room14_floorB)
	(itematlocation item32_potted_plant_largeitem location_Xneg55_Ypos20_place25_room15_floorB)
	(itematlocation item33_potted_plant_largeitem location_Xpos29_Yneg13_place43_room3_floorC)
	(itematlocation item34_potted_plant_largeitem location_Xpos30_Ypos9_place44_room3_floorC)
	(itematlocation item46_laptop_mediumitem location_Xpos57_Ypos7_place31_room4_floorA)
	(itematlocation item59_book_smallitem location_Xpos56_Ypos2_place31_room4_floorA)
	(itematlocation item5_bottle_smallitem location_Xpos30_Ypos20_place40_room1_floorA)
	(itematlocation item60_book_smallitem location_Xneg31_Ypos29_place42_room14_floorB)
	(itematlocation item61_vase_mediumitem location_Xneg29_Ypos14_place47_room14_floorB)
	(itematlocation item6_bottle_smallitem location_Xpos31_Ypos19_place41_room2_floorB)
	(itematlocation item7_bottle_smallitem location_Xpos31_Ypos14_place41_room2_floorB)
	(itematlocation item8_bottle_smallitem location_Xpos30_Ypos5_place44_room3_floorC)
	(itematlocation item9_cup_smallitem location_Xpos30_Ypos22_place40_room1_floorA)
	(largeitem item30_potted_plant_largeitem)
	(largeitem item31_potted_plant_largeitem)
	(largeitem item32_potted_plant_largeitem)
	(largeitem item33_potted_plant_largeitem)
	(largeitem item34_potted_plant_largeitem)
	(locationinplace location_Xneg10_Yneg11_place15_room13_floorB place15_receptacle19_chair)
	(locationinplace location_Xneg10_Ypos26_place37_room14_floorB place37_receptacle47_microwave)
	(locationinplace location_Xneg12_Ypos16_place47_room14_floorB place47_receptacle57_refrigerator)
	(locationinplace location_Xneg12_Ypos26_place39_room14_floorB place39_receptacle49_oven)
	(locationinplace location_Xneg12_Ypos3_place6_room13_floorB place6_door_room13_dining_room)
	(locationinplace location_Xneg16_Yneg10_place17_room13_floorB place17_receptacle21_chair)
	(locationinplace location_Xneg20_Ypos34_place42_room14_floorB place42_receptacle52_sink)
	(locationinplace location_Xneg21_Ypos23_place4_room14_floorB place4_door_room14_kitchen)
	(locationinplace location_Xneg25_Ypos9_place8_room6_floorC place8_door_room6_bedroom)
	(locationinplace location_Xneg29_Ypos14_place47_room14_floorB place47_receptacle57_refrigerator)
	(locationinplace location_Xneg30_Ypos14_place47_room14_floorB place47_receptacle57_refrigerator)
	(locationinplace location_Xneg30_Ypos21_place42_room14_floorB place42_receptacle52_sink)
	(locationinplace location_Xneg31_Ypos29_place42_room14_floorB place42_receptacle52_sink)
	(locationinplace location_Xneg36_Ypos16_place22_room15_floorB place22_receptacle26_chair)
	(locationinplace location_Xneg36_Ypos22_place21_room15_floorB place21_receptacle25_chair)
	(locationinplace location_Xneg3_Yneg10_place14_room13_floorB place14_receptacle18_chair)
	(locationinplace location_Xneg41_Yneg10_place24_room6_floorC place24_receptacle28_chair)
	(locationinplace location_Xneg44_Ypos21_place28_room6_floorC place28_receptacle37_bed)
	(locationinplace location_Xneg45_Yneg10_place13_room15_floorB place13_receptacle17_chair)
	(locationinplace location_Xneg50_Ypos11_place5_room15_floorB place5_door_room15_living_room)
	(locationinplace location_Xneg54_Ypos5_place25_room15_floorB place25_receptacle29_couch)
	(locationinplace location_Xneg55_Ypos20_place25_room15_floorB place25_receptacle29_couch)
	(locationinplace location_Xneg60_Yneg10_place16_room15_floorB place16_receptacle20_chair)
	(locationinplace location_Xneg67_Ypos31_place23_room15_floorB place23_receptacle27_chair)
	(locationinplace location_Xneg9_Yneg15_place33_room13_floorB place33_receptacle42_dining_table)
	(locationinplace location_Xneg9_Yneg16_place18_room13_floorB place18_receptacle22_chair)
	(locationinplace location_Xneg9_Yneg4_place19_room13_floorB place19_receptacle23_chair)
	(locationinplace location_Xneg9_Yneg9_place32_room13_floorB place32_receptacle41_dining_table)
	(locationinplace location_Xpos10_Yneg7_place48_room8_floorB place48_receptacle58_refrigerator)
	(locationinplace location_Xpos15_Ypos24_place12_room1_floorA place12_receptacle16_chair)
	(locationinplace location_Xpos20_Yneg10_place38_room18_floorA place38_receptacle48_oven)
	(locationinplace location_Xpos22_Yneg8_place43_room3_floorC place43_receptacle53_sink)
	(locationinplace location_Xpos22_Ypos26_place0_room1_floorA place0_door_room1_bathroom)
	(locationinplace location_Xpos23_Yneg6_place9_room18_floorA place9_door_room18_utility_room)
	(locationinplace location_Xpos23_Ypos24_place1_room2_floorB place1_door_room2_bathroom)
	(locationinplace location_Xpos24_Ypos10_place2_room3_floorC place2_door_room3_bathroom)
	(locationinplace location_Xpos27_Ypos24_place36_room3_floorC place36_receptacle45_toilet)
	(locationinplace location_Xpos27_Ypos26_place34_room1_floorA place34_receptacle43_toilet)
	(locationinplace location_Xpos28_Ypos15_place46_room3_floorC place46_receptacle56_sink)
	(locationinplace location_Xpos28_Ypos19_place40_room1_floorA place40_receptacle50_sink)
	(locationinplace location_Xpos28_Ypos25_place35_room2_floorB place35_receptacle44_toilet)
	(locationinplace location_Xpos28_Ypos2_place45_room3_floorC place45_receptacle55_sink)
	(locationinplace location_Xpos29_Yneg13_place43_room3_floorC place43_receptacle53_sink)
	(locationinplace location_Xpos29_Ypos16_place41_room2_floorB place41_receptacle51_sink)
	(locationinplace location_Xpos30_Ypos16_place40_room1_floorA place40_receptacle50_sink)
	(locationinplace location_Xpos30_Ypos20_place40_room1_floorA place40_receptacle50_sink)
	(locationinplace location_Xpos30_Ypos22_place40_room1_floorA place40_receptacle50_sink)
	(locationinplace location_Xpos30_Ypos5_place44_room3_floorC place44_receptacle54_sink)
	(locationinplace location_Xpos30_Ypos9_place44_room3_floorC place44_receptacle54_sink)
	(locationinplace location_Xpos31_Ypos14_place41_room2_floorB place41_receptacle51_sink)
	(locationinplace location_Xpos31_Ypos19_place41_room2_floorB place41_receptacle51_sink)
	(locationinplace location_Xpos31_Ypos2_place44_room3_floorC place44_receptacle54_sink)
	(locationinplace location_Xpos3_Yneg7_place10_room8_floorB place10_door_room8_closet)
	(locationinplace location_Xpos49_Ypos26_place27_room5_floorB place27_receptacle36_bed)
	(locationinplace location_Xpos51_Ypos15_place7_room5_floorB place7_door_room5_bedroom)
	(locationinplace location_Xpos51_Ypos16_place3_room4_floorA place3_door_room4_bedroom)
	(locationinplace location_Xpos51_Ypos27_place26_room4_floorA place26_receptacle35_bed)
	(locationinplace location_Xpos56_Ypos1_place30_room4_floorA place30_receptacle39_dining_table)
	(locationinplace location_Xpos56_Ypos2_place31_room4_floorA place31_receptacle40_dining_table)
	(locationinplace location_Xpos57_Ypos0_place30_room4_floorA place30_receptacle39_dining_table)
	(locationinplace location_Xpos57_Ypos2_place31_room4_floorA place31_receptacle40_dining_table)
	(locationinplace location_Xpos57_Ypos7_place31_room4_floorA place31_receptacle40_dining_table)
	(locationinplace location_Xpos58_Ypos5_place31_room4_floorA place31_receptacle40_dining_table)
	(locationinplace location_Xpos58_Ypos6_place31_room4_floorA place31_receptacle40_dining_table)
	(locationinplace location_Xpos59_Ypos3_place31_room4_floorA place31_receptacle40_dining_table)
	(locationinplace location_Xpos60_Ypos9_place29_room4_floorA place29_receptacle38_dining_table)
	(locationinplace location_Xpos63_Ypos1_place20_room5_floorB place20_receptacle24_chair)
	(locationinplace location_Xpos64_Ypos1_place11_room4_floorA place11_receptacle15_chair)
	(mediumitem item46_laptop_mediumitem)
	(mediumitem item61_vase_mediumitem)
	(placeinroom place0_door_room1_bathroom room1_bathroom)
	(placeinroom place10_door_room8_closet room8_closet)
	(placeinroom place11_receptacle15_chair room4_bedroom)
	(placeinroom place12_receptacle16_chair room1_bathroom)
	(placeinroom place13_receptacle17_chair room15_living_room)
	(placeinroom place14_receptacle18_chair room13_dining_room)
	(placeinroom place15_receptacle19_chair room13_dining_room)
	(placeinroom place16_receptacle20_chair room15_living_room)
	(placeinroom place17_receptacle21_chair room13_dining_room)
	(placeinroom place18_receptacle22_chair room13_dining_room)
	(placeinroom place19_receptacle23_chair room13_dining_room)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place20_receptacle24_chair room5_bedroom)
	(placeinroom place21_receptacle25_chair room15_living_room)
	(placeinroom place22_receptacle26_chair room15_living_room)
	(placeinroom place23_receptacle27_chair room15_living_room)
	(placeinroom place24_receptacle28_chair room6_bedroom)
	(placeinroom place25_receptacle29_couch room15_living_room)
	(placeinroom place26_receptacle35_bed room4_bedroom)
	(placeinroom place27_receptacle36_bed room5_bedroom)
	(placeinroom place28_receptacle37_bed room6_bedroom)
	(placeinroom place29_receptacle38_dining_table room4_bedroom)
	(placeinroom place2_door_room3_bathroom room3_bathroom)
	(placeinroom place30_receptacle39_dining_table room4_bedroom)
	(placeinroom place31_receptacle40_dining_table room4_bedroom)
	(placeinroom place32_receptacle41_dining_table room13_dining_room)
	(placeinroom place33_receptacle42_dining_table room13_dining_room)
	(placeinroom place34_receptacle43_toilet room1_bathroom)
	(placeinroom place35_receptacle44_toilet room2_bathroom)
	(placeinroom place36_receptacle45_toilet room3_bathroom)
	(placeinroom place37_receptacle47_microwave room14_kitchen)
	(placeinroom place38_receptacle48_oven room18_utility_room)
	(placeinroom place39_receptacle49_oven room14_kitchen)
	(placeinroom place3_door_room4_bedroom room4_bedroom)
	(placeinroom place40_receptacle50_sink room1_bathroom)
	(placeinroom place41_receptacle51_sink room2_bathroom)
	(placeinroom place42_receptacle52_sink room14_kitchen)
	(placeinroom place43_receptacle53_sink room3_bathroom)
	(placeinroom place44_receptacle54_sink room3_bathroom)
	(placeinroom place45_receptacle55_sink room3_bathroom)
	(placeinroom place46_receptacle56_sink room3_bathroom)
	(placeinroom place47_receptacle57_refrigerator room14_kitchen)
	(placeinroom place48_receptacle58_refrigerator room8_closet)
	(placeinroom place4_door_room14_kitchen room14_kitchen)
	(placeinroom place5_door_room15_living_room room15_living_room)
	(placeinroom place6_door_room13_dining_room room13_dining_room)
	(placeinroom place7_door_room5_bedroom room5_bedroom)
	(placeinroom place8_door_room6_bedroom room6_bedroom)
	(placeinroom place9_door_room18_utility_room room18_utility_room)
	(placelocation location_Xneg10_Yneg11_place15_room13_floorB place15_receptacle19_chair)
	(placelocation location_Xneg10_Ypos26_place37_room14_floorB place37_receptacle47_microwave)
	(placelocation location_Xneg12_Ypos16_place47_room14_floorB place47_receptacle57_refrigerator)
	(placelocation location_Xneg12_Ypos26_place39_room14_floorB place39_receptacle49_oven)
	(placelocation location_Xneg12_Ypos3_place6_room13_floorB place6_door_room13_dining_room)
	(placelocation location_Xneg16_Yneg10_place17_room13_floorB place17_receptacle21_chair)
	(placelocation location_Xneg20_Ypos34_place42_room14_floorB place42_receptacle52_sink)
	(placelocation location_Xneg21_Ypos23_place4_room14_floorB place4_door_room14_kitchen)
	(placelocation location_Xneg25_Ypos9_place8_room6_floorC place8_door_room6_bedroom)
	(placelocation location_Xneg36_Ypos16_place22_room15_floorB place22_receptacle26_chair)
	(placelocation location_Xneg36_Ypos22_place21_room15_floorB place21_receptacle25_chair)
	(placelocation location_Xneg3_Yneg10_place14_room13_floorB place14_receptacle18_chair)
	(placelocation location_Xneg41_Yneg10_place24_room6_floorC place24_receptacle28_chair)
	(placelocation location_Xneg44_Ypos21_place28_room6_floorC place28_receptacle37_bed)
	(placelocation location_Xneg45_Yneg10_place13_room15_floorB place13_receptacle17_chair)
	(placelocation location_Xneg50_Ypos11_place5_room15_floorB place5_door_room15_living_room)
	(placelocation location_Xneg54_Ypos5_place25_room15_floorB place25_receptacle29_couch)
	(placelocation location_Xneg60_Yneg10_place16_room15_floorB place16_receptacle20_chair)
	(placelocation location_Xneg67_Ypos31_place23_room15_floorB place23_receptacle27_chair)
	(placelocation location_Xneg9_Yneg15_place33_room13_floorB place33_receptacle42_dining_table)
	(placelocation location_Xneg9_Yneg16_place18_room13_floorB place18_receptacle22_chair)
	(placelocation location_Xneg9_Yneg4_place19_room13_floorB place19_receptacle23_chair)
	(placelocation location_Xneg9_Yneg9_place32_room13_floorB place32_receptacle41_dining_table)
	(placelocation location_Xpos10_Yneg7_place48_room8_floorB place48_receptacle58_refrigerator)
	(placelocation location_Xpos15_Ypos24_place12_room1_floorA place12_receptacle16_chair)
	(placelocation location_Xpos20_Yneg10_place38_room18_floorA place38_receptacle48_oven)
	(placelocation location_Xpos22_Yneg8_place43_room3_floorC place43_receptacle53_sink)
	(placelocation location_Xpos22_Ypos26_place0_room1_floorA place0_door_room1_bathroom)
	(placelocation location_Xpos23_Yneg6_place9_room18_floorA place9_door_room18_utility_room)
	(placelocation location_Xpos23_Ypos24_place1_room2_floorB place1_door_room2_bathroom)
	(placelocation location_Xpos24_Ypos10_place2_room3_floorC place2_door_room3_bathroom)
	(placelocation location_Xpos27_Ypos24_place36_room3_floorC place36_receptacle45_toilet)
	(placelocation location_Xpos27_Ypos26_place34_room1_floorA place34_receptacle43_toilet)
	(placelocation location_Xpos28_Ypos15_place46_room3_floorC place46_receptacle56_sink)
	(placelocation location_Xpos28_Ypos19_place40_room1_floorA place40_receptacle50_sink)
	(placelocation location_Xpos28_Ypos25_place35_room2_floorB place35_receptacle44_toilet)
	(placelocation location_Xpos28_Ypos2_place45_room3_floorC place45_receptacle55_sink)
	(placelocation location_Xpos29_Ypos16_place41_room2_floorB place41_receptacle51_sink)
	(placelocation location_Xpos31_Ypos2_place44_room3_floorC place44_receptacle54_sink)
	(placelocation location_Xpos3_Yneg7_place10_room8_floorB place10_door_room8_closet)
	(placelocation location_Xpos49_Ypos26_place27_room5_floorB place27_receptacle36_bed)
	(placelocation location_Xpos51_Ypos15_place7_room5_floorB place7_door_room5_bedroom)
	(placelocation location_Xpos51_Ypos16_place3_room4_floorA place3_door_room4_bedroom)
	(placelocation location_Xpos51_Ypos27_place26_room4_floorA place26_receptacle35_bed)
	(placelocation location_Xpos56_Ypos1_place30_room4_floorA place30_receptacle39_dining_table)
	(placelocation location_Xpos58_Ypos5_place31_room4_floorA place31_receptacle40_dining_table)
	(placelocation location_Xpos60_Ypos9_place29_room4_floorA place29_receptacle38_dining_table)
	(placelocation location_Xpos63_Ypos1_place20_room5_floorB place20_receptacle24_chair)
	(placelocation location_Xpos64_Ypos1_place11_room4_floorA place11_receptacle15_chair)
	(receptacleatlocation receptacle15_chair location_Xpos64_Ypos1_place11_room4_floorA)
	(receptacleatlocation receptacle16_chair location_Xpos15_Ypos24_place12_room1_floorA)
	(receptacleatlocation receptacle17_chair location_Xneg45_Yneg10_place13_room15_floorB)
	(receptacleatlocation receptacle18_chair location_Xneg3_Yneg10_place14_room13_floorB)
	(receptacleatlocation receptacle19_chair location_Xneg10_Yneg11_place15_room13_floorB)
	(receptacleatlocation receptacle20_chair location_Xneg60_Yneg10_place16_room15_floorB)
	(receptacleatlocation receptacle21_chair location_Xneg16_Yneg10_place17_room13_floorB)
	(receptacleatlocation receptacle22_chair location_Xneg9_Yneg16_place18_room13_floorB)
	(receptacleatlocation receptacle23_chair location_Xneg9_Yneg4_place19_room13_floorB)
	(receptacleatlocation receptacle24_chair location_Xpos63_Ypos1_place20_room5_floorB)
	(receptacleatlocation receptacle25_chair location_Xneg36_Ypos22_place21_room15_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg36_Ypos16_place22_room15_floorB)
	(receptacleatlocation receptacle27_chair location_Xneg67_Ypos31_place23_room15_floorB)
	(receptacleatlocation receptacle28_chair location_Xneg41_Yneg10_place24_room6_floorC)
	(receptacleatlocation receptacle29_couch location_Xneg54_Ypos5_place25_room15_floorB)
	(receptacleatlocation receptacle35_bed location_Xpos51_Ypos27_place26_room4_floorA)
	(receptacleatlocation receptacle36_bed location_Xpos49_Ypos26_place27_room5_floorB)
	(receptacleatlocation receptacle37_bed location_Xneg44_Ypos21_place28_room6_floorC)
	(receptacleatlocation receptacle38_dining_table location_Xpos60_Ypos9_place29_room4_floorA)
	(receptacleatlocation receptacle39_dining_table location_Xpos56_Ypos1_place30_room4_floorA)
	(receptacleatlocation receptacle40_dining_table location_Xpos58_Ypos5_place31_room4_floorA)
	(receptacleatlocation receptacle41_dining_table location_Xneg9_Yneg9_place32_room13_floorB)
	(receptacleatlocation receptacle42_dining_table location_Xneg9_Yneg15_place33_room13_floorB)
	(receptacleatlocation receptacle43_toilet location_Xpos27_Ypos26_place34_room1_floorA)
	(receptacleatlocation receptacle44_toilet location_Xpos28_Ypos25_place35_room2_floorB)
	(receptacleatlocation receptacle45_toilet location_Xpos27_Ypos24_place36_room3_floorC)
	(receptacleatlocation receptacle47_microwave location_Xneg10_Ypos26_place37_room14_floorB)
	(receptacleatlocation receptacle48_oven location_Xpos20_Yneg10_place38_room18_floorA)
	(receptacleatlocation receptacle49_oven location_Xneg12_Ypos26_place39_room14_floorB)
	(receptacleatlocation receptacle50_sink location_Xpos28_Ypos19_place40_room1_floorA)
	(receptacleatlocation receptacle51_sink location_Xpos29_Ypos16_place41_room2_floorB)
	(receptacleatlocation receptacle52_sink location_Xneg20_Ypos34_place42_room14_floorB)
	(receptacleatlocation receptacle53_sink location_Xpos22_Yneg8_place43_room3_floorC)
	(receptacleatlocation receptacle54_sink location_Xpos31_Ypos2_place44_room3_floorC)
	(receptacleatlocation receptacle55_sink location_Xpos28_Ypos2_place45_room3_floorC)
	(receptacleatlocation receptacle56_sink location_Xpos28_Ypos15_place46_room3_floorC)
	(receptacleatlocation receptacle57_refrigerator location_Xneg12_Ypos16_place47_room14_floorB)
	(receptacleatlocation receptacle58_refrigerator location_Xpos10_Yneg7_place48_room8_floorB)
	(receptacleopeningtype receptacle47_microwave)
	(receptacleopeningtype receptacle48_oven)
	(receptacleopeningtype receptacle49_oven)
	(receptacleopeningtype receptacle57_refrigerator)
	(receptacleopeningtype receptacle58_refrigerator)
	(roomplace place0_door_room1_bathroom room1_bathroom)
	(roomplace place10_door_room8_closet room8_closet)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room3_bathroom room3_bathroom)
	(roomplace place3_door_room4_bedroom room4_bedroom)
	(roomplace place4_door_room14_kitchen room14_kitchen)
	(roomplace place5_door_room15_living_room room15_living_room)
	(roomplace place6_door_room13_dining_room room13_dining_room)
	(roomplace place7_door_room5_bedroom room5_bedroom)
	(roomplace place8_door_room6_bedroom room6_bedroom)
	(roomplace place9_door_room18_utility_room room18_utility_room)
	(smallitem item10_cup_smallitem)
	(smallitem item11_cup_smallitem)
	(smallitem item12_cup_smallitem)
	(smallitem item13_cup_smallitem)
	(smallitem item14_bowl_smallitem)
	(smallitem item59_book_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item60_book_smallitem)
	(smallitem item6_bottle_smallitem)
	(smallitem item7_bottle_smallitem)
	(smallitem item8_bottle_smallitem)
	(smallitem item9_cup_smallitem)
  )
  (:goal (and
	(inreceptacle item31_potted_plant_largeitem receptacle15_chair)
	(inreceptacle item33_potted_plant_largeitem receptacle44_toilet)
	(inreceptacle item13_cup_smallitem receptacle47_microwave)
	(inreceptacle item5_bottle_smallitem receptacle28_chair)
	(inreceptacle item8_bottle_smallitem receptacle58_refrigerator)
	(inreceptacle item12_cup_smallitem receptacle48_oven)
	(inreceptacle item10_cup_smallitem receptacle47_microwave)
	(inreceptacle item34_potted_plant_largeitem receptacle40_dining_table)
	(inreceptacle item6_bottle_smallitem receptacle22_chair)
	(inreceptacle item32_potted_plant_largeitem receptacle16_chair)))
)
