
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_bowl_smallitem - item
	item1_umbrella_largeitem - item
	item2_umbrella_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item3_umbrella_largeitem - item
	item48_tv_largeitem - item
	item4_tie_smallitem - item
	item58_book_smallitem - item
	item59_book_smallitem - item
	item5_suitcase_largeitem - item
	item60_book_smallitem - item
	item61_book_smallitem - item
	item62_clock_mediumitem - item
	item63_clock_mediumitem - item
	item64_clock_mediumitem - item
	item65_clock_mediumitem - item
	item66_clock_mediumitem - item
	item67_clock_mediumitem - item
	item68_clock_mediumitem - item
	item69_clock_mediumitem - item
	item6_kite_largeitem - item
	item70_clock_mediumitem - item
	item71_clock_mediumitem - item
	item72_clock_mediumitem - item
	item73_vase_mediumitem - item
	item74_vase_mediumitem - item
	item75_vase_mediumitem - item
	item76_vase_mediumitem - item
	item77_vase_mediumitem - item
	item78_vase_mediumitem - item
	item79_vase_mediumitem - item
	item7_baseball_bat_largeitem - item
	item80_vase_mediumitem - item
	item8_knife_smallitem - item
	item9_bowl_smallitem - item
	location_Xneg101_Ypos21_place22_room6_floorB - location
	location_Xneg103_Ypos10_place35_room11_floorA - location
	location_Xneg105_Ypos8_place46_room11_floorA - location
	location_Xneg106_Ypos16_place22_room6_floorB - location
	location_Xneg106_Ypos8_place34_room11_floorA - location
	location_Xneg107_Ypos22_place22_room6_floorB - location
	location_Xneg107_Ypos6_place36_room11_floorA - location
	location_Xneg109_Yneg35_place32_room14_floorA - location
	location_Xneg110_Yneg43_place39_room14_floorA - location
	location_Xneg112_Yneg27_place32_room14_floorA - location
	location_Xneg113_Yneg23_place40_room14_floorA - location
	location_Xneg117_Yneg12_place40_room14_floorA - location
	location_Xneg117_Yneg19_place40_room14_floorA - location
	location_Xneg118_Yneg16_place40_room14_floorA - location
	location_Xneg118_Yneg18_place40_room14_floorA - location
	location_Xneg11_Ypos25_place38_room13_floorA - location
	location_Xneg12_Yneg8_place37_room13_floorA - location
	location_Xneg12_Ypos2_place24_room13_floorA - location
	location_Xneg21_Ypos17_place41_room4_floorB - location
	location_Xneg22_Ypos14_place21_room2_floorB - location
	location_Xneg27_Ypos15_place28_room13_floorA - location
	location_Xneg31_Ypos9_place29_room13_floorA - location
	location_Xneg32_Ypos10_place31_room13_floorA - location
	location_Xneg32_Ypos11_place31_room13_floorA - location
	location_Xneg33_Ypos15_place48_room2_floorB - location
	location_Xneg33_Ypos4_place55_room2_floorB - location
	location_Xneg34_Yneg2_place55_room2_floorB - location
	location_Xneg36_Ypos14_place48_room2_floorB - location
	location_Xneg36_Ypos15_place48_room2_floorB - location
	location_Xneg38_Ypos10_place14_room5_floorB - location
	location_Xneg41_Ypos30_place17_room5_floorB - location
	location_Xneg47_Ypos19_place26_room10_floorA - location
	location_Xneg48_Ypos1_place15_room5_floorB - location
	location_Xneg49_Yneg41_place18_room16_floorA - location
	location_Xneg4_Ypos11_place38_room13_floorA - location
	location_Xneg52_Yneg41_place19_room16_floorA - location
	location_Xneg52_Ypos15_place23_room10_floorA - location
	location_Xneg54_Ypos16_place30_room10_floorA - location
	location_Xneg55_Ypos19_place25_room10_floorA - location
	location_Xneg57_Yneg26_place45_room7_floorB - location
	location_Xneg57_Ypos17_place27_room10_floorA - location
	location_Xneg57_Ypos17_place42_room5_floorB - location
	location_Xneg58_Yneg24_place51_room1_floorA - location
	location_Xneg59_Yneg26_place45_room7_floorB - location
	location_Xneg59_Yneg27_place45_room7_floorB - location
	location_Xneg59_Yneg35_place53_room17_floorA - location
	location_Xneg5_Ypos15_place38_room13_floorA - location
	location_Xneg60_Yneg32_place45_room7_floorB - location
	location_Xneg63_Ypos15_place27_room10_floorA - location
	location_Xneg64_Ypos0_place16_room10_floorA - location
	location_Xneg67_Yneg25_place57_room1_floorA - location
	location_Xneg69_Yneg36_place45_room7_floorB - location
	location_Xneg69_Ypos6_place60_room12_floorA - location
	location_Xneg70_Ypos14_place52_room12_floorA - location
	location_Xneg71_Yneg22_place59_room14_floorA - location
	location_Xneg71_Ypos15_place54_room12_floorA - location
	location_Xneg72_Yneg23_place59_room14_floorA - location
	location_Xneg72_Yneg26_place59_room14_floorA - location
	location_Xneg72_Yneg27_place59_room14_floorA - location
	location_Xneg72_Ypos1_place60_room12_floorA - location
	location_Xneg72_Ypos26_place20_room6_floorB - location
	location_Xneg73_Yneg20_place59_room14_floorA - location
	location_Xneg74_Yneg23_place59_room14_floorA - location
	location_Xneg75_Yneg17_place43_room3_floorB - location
	location_Xneg77_Yneg39_place50_room3_floorB - location
	location_Xneg79_Yneg38_place49_room3_floorB - location
	location_Xneg86_Ypos24_place58_room12_floorA - location
	location_Xneg89_Ypos2_place47_room12_floorA - location
	location_Xneg89_Ypos3_place47_room12_floorA - location
	location_Xneg8_Ypos17_place41_room4_floorB - location
	location_Xneg92_Ypos4_place33_room12_floorA - location
	location_Xneg94_Yneg14_place56_room3_floorB - location
	location_Xneg94_Yneg23_place56_room3_floorB - location
	location_Xneg95_Yneg38_place39_room14_floorA - location
	location_Xneg95_Ypos7_place44_room6_floorB - location
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_couch - receptacle
	receptacle28_couch - receptacle
	receptacle29_couch - receptacle
	receptacle33_couch - receptacle
	receptacle37_bed - receptacle
	receptacle38_bed - receptacle
	receptacle39_bed - receptacle
	receptacle40_bed - receptacle
	receptacle41_bed - receptacle
	receptacle42_dining_table - receptacle
	receptacle43_dining_table - receptacle
	receptacle44_toilet - receptacle
	receptacle45_toilet - receptacle
	receptacle46_toilet - receptacle
	receptacle47_toilet - receptacle
	receptacle49_microwave - receptacle
	receptacle50_microwave - receptacle
	receptacle51_oven - receptacle
	receptacle52_sink - receptacle
	receptacle53_sink - receptacle
	receptacle54_sink - receptacle
	receptacle55_sink - receptacle
	receptacle56_refrigerator - receptacle
	receptacle57_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg59_Yneg27_place45_room7_floorB)
	(inanyreceptacle item10_bowl_smallitem)
	(inanyreceptacle item1_umbrella_largeitem)
	(inanyreceptacle item2_umbrella_largeitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item36_potted_plant_largeitem)
	(inanyreceptacle item3_umbrella_largeitem)
	(inanyreceptacle item48_tv_largeitem)
	(inanyreceptacle item4_tie_smallitem)
	(inanyreceptacle item58_book_smallitem)
	(inanyreceptacle item59_book_smallitem)
	(inanyreceptacle item60_book_smallitem)
	(inanyreceptacle item61_book_smallitem)
	(inanyreceptacle item62_clock_mediumitem)
	(inanyreceptacle item63_clock_mediumitem)
	(inanyreceptacle item65_clock_mediumitem)
	(inanyreceptacle item66_clock_mediumitem)
	(inanyreceptacle item67_clock_mediumitem)
	(inanyreceptacle item69_clock_mediumitem)
	(inanyreceptacle item6_kite_largeitem)
	(inanyreceptacle item70_clock_mediumitem)
	(inanyreceptacle item71_clock_mediumitem)
	(inanyreceptacle item72_clock_mediumitem)
	(inanyreceptacle item73_vase_mediumitem)
	(inanyreceptacle item76_vase_mediumitem)
	(inanyreceptacle item77_vase_mediumitem)
	(inanyreceptacle item78_vase_mediumitem)
	(inanyreceptacle item79_vase_mediumitem)
	(inanyreceptacle item80_vase_mediumitem)
	(inanyreceptacle item8_knife_smallitem)
	(inanyreceptacle item9_bowl_smallitem)
	(inreceptacle item10_bowl_smallitem receptacle43_dining_table)
	(inreceptacle item1_umbrella_largeitem receptacle41_bed)
	(inreceptacle item2_umbrella_largeitem receptacle41_bed)
	(inreceptacle item35_potted_plant_largeitem receptacle22_chair)
	(inreceptacle item36_potted_plant_largeitem receptacle29_couch)
	(inreceptacle item3_umbrella_largeitem receptacle41_bed)
	(inreceptacle item48_tv_largeitem receptacle33_couch)
	(inreceptacle item4_tie_smallitem receptacle41_bed)
	(inreceptacle item58_book_smallitem receptacle28_couch)
	(inreceptacle item59_book_smallitem receptacle28_couch)
	(inreceptacle item60_book_smallitem receptacle28_couch)
	(inreceptacle item61_book_smallitem receptacle21_chair)
	(inreceptacle item62_clock_mediumitem receptacle37_bed)
	(inreceptacle item63_clock_mediumitem receptacle52_sink)
	(inreceptacle item65_clock_mediumitem receptacle12_chair)
	(inreceptacle item66_clock_mediumitem receptacle12_chair)
	(inreceptacle item67_clock_mediumitem receptacle53_sink)
	(inreceptacle item69_clock_mediumitem receptacle56_refrigerator)
	(inreceptacle item6_kite_largeitem receptacle28_couch)
	(inreceptacle item70_clock_mediumitem receptacle56_refrigerator)
	(inreceptacle item71_clock_mediumitem receptacle56_refrigerator)
	(inreceptacle item72_clock_mediumitem receptacle56_refrigerator)
	(inreceptacle item73_vase_mediumitem receptacle44_toilet)
	(inreceptacle item76_vase_mediumitem receptacle17_chair)
	(inreceptacle item77_vase_mediumitem receptacle33_couch)
	(inreceptacle item78_vase_mediumitem receptacle33_couch)
	(inreceptacle item79_vase_mediumitem receptacle33_couch)
	(inreceptacle item80_vase_mediumitem receptacle56_refrigerator)
	(inreceptacle item8_knife_smallitem receptacle57_refrigerator)
	(inreceptacle item9_bowl_smallitem receptacle44_toilet)
	(itematlocation item10_bowl_smallitem location_Xneg89_Ypos2_place47_room12_floorA)
	(itematlocation item1_umbrella_largeitem location_Xneg57_Yneg26_place45_room7_floorB)
	(itematlocation item2_umbrella_largeitem location_Xneg59_Yneg27_place45_room7_floorB)
	(itematlocation item34_potted_plant_largeitem location_Xneg48_Ypos1_place15_room5_floorB)
	(itematlocation item35_potted_plant_largeitem location_Xneg109_Yneg35_place32_room14_floorA)
	(itematlocation item36_potted_plant_largeitem location_Xneg110_Yneg43_place39_room14_floorA)
	(itematlocation item3_umbrella_largeitem location_Xneg59_Yneg26_place45_room7_floorB)
	(itematlocation item48_tv_largeitem location_Xneg117_Yneg12_place40_room14_floorA)
	(itematlocation item4_tie_smallitem location_Xneg60_Yneg32_place45_room7_floorB)
	(itematlocation item58_book_smallitem location_Xneg11_Ypos25_place38_room13_floorA)
	(itematlocation item59_book_smallitem location_Xneg11_Ypos25_place38_room13_floorA)
	(itematlocation item5_suitcase_largeitem location_Xneg41_Ypos30_place17_room5_floorB)
	(itematlocation item60_book_smallitem location_Xneg11_Ypos25_place38_room13_floorA)
	(itematlocation item61_book_smallitem location_Xneg32_Ypos11_place31_room13_floorA)
	(itematlocation item62_clock_mediumitem location_Xneg21_Ypos17_place41_room4_floorB)
	(itematlocation item63_clock_mediumitem location_Xneg34_Yneg2_place55_room2_floorB)
	(itematlocation item64_clock_mediumitem location_Xneg38_Ypos10_place14_room5_floorB)
	(itematlocation item65_clock_mediumitem location_Xneg107_Ypos22_place22_room6_floorB)
	(itematlocation item66_clock_mediumitem location_Xneg106_Ypos16_place22_room6_floorB)
	(itematlocation item67_clock_mediumitem location_Xneg94_Yneg14_place56_room3_floorB)
	(itematlocation item68_clock_mediumitem location_Xneg64_Ypos0_place16_room10_floorA)
	(itematlocation item69_clock_mediumitem location_Xneg72_Yneg23_place59_room14_floorA)
	(itematlocation item6_kite_largeitem location_Xneg4_Ypos11_place38_room13_floorA)
	(itematlocation item70_clock_mediumitem location_Xneg71_Yneg22_place59_room14_floorA)
	(itematlocation item71_clock_mediumitem location_Xneg72_Yneg27_place59_room14_floorA)
	(itematlocation item72_clock_mediumitem location_Xneg72_Yneg26_place59_room14_floorA)
	(itematlocation item73_vase_mediumitem location_Xneg36_Ypos14_place48_room2_floorB)
	(itematlocation item74_vase_mediumitem location_Xneg52_Yneg41_place19_room16_floorA)
	(itematlocation item75_vase_mediumitem location_Xneg72_Ypos26_place20_room6_floorB)
	(itematlocation item76_vase_mediumitem location_Xneg63_Ypos15_place27_room10_floorA)
	(itematlocation item77_vase_mediumitem location_Xneg118_Yneg16_place40_room14_floorA)
	(itematlocation item78_vase_mediumitem location_Xneg117_Yneg19_place40_room14_floorA)
	(itematlocation item79_vase_mediumitem location_Xneg118_Yneg18_place40_room14_floorA)
	(itematlocation item7_baseball_bat_largeitem location_Xneg49_Yneg41_place18_room16_floorA)
	(itematlocation item80_vase_mediumitem location_Xneg73_Yneg20_place59_room14_floorA)
	(itematlocation item8_knife_smallitem location_Xneg69_Ypos6_place60_room12_floorA)
	(itematlocation item9_bowl_smallitem location_Xneg36_Ypos15_place48_room2_floorB)
	(receptacleatlocation receptacle11_chair location_Xneg22_Ypos14_place21_room2_floorB)
	(receptacleatlocation receptacle12_chair location_Xneg101_Ypos21_place22_room6_floorB)
	(receptacleatlocation receptacle13_chair location_Xneg52_Ypos15_place23_room10_floorA)
	(receptacleatlocation receptacle14_chair location_Xneg12_Ypos2_place24_room13_floorA)
	(receptacleatlocation receptacle15_chair location_Xneg55_Ypos19_place25_room10_floorA)
	(receptacleatlocation receptacle16_chair location_Xneg47_Ypos19_place26_room10_floorA)
	(receptacleatlocation receptacle17_chair location_Xneg57_Ypos17_place27_room10_floorA)
	(receptacleatlocation receptacle18_chair location_Xneg27_Ypos15_place28_room13_floorA)
	(receptacleatlocation receptacle19_chair location_Xneg31_Ypos9_place29_room13_floorA)
	(receptacleatlocation receptacle20_chair location_Xneg54_Ypos16_place30_room10_floorA)
	(receptacleatlocation receptacle21_chair location_Xneg32_Ypos10_place31_room13_floorA)
	(receptacleatlocation receptacle22_chair location_Xneg112_Yneg27_place32_room14_floorA)
	(receptacleatlocation receptacle23_chair location_Xneg92_Ypos4_place33_room12_floorA)
	(receptacleatlocation receptacle24_chair location_Xneg106_Ypos8_place34_room11_floorA)
	(receptacleatlocation receptacle25_chair location_Xneg103_Ypos10_place35_room11_floorA)
	(receptacleatlocation receptacle26_chair location_Xneg107_Ypos6_place36_room11_floorA)
	(receptacleatlocation receptacle27_couch location_Xneg12_Yneg8_place37_room13_floorA)
	(receptacleatlocation receptacle28_couch location_Xneg5_Ypos15_place38_room13_floorA)
	(receptacleatlocation receptacle29_couch location_Xneg95_Yneg38_place39_room14_floorA)
	(receptacleatlocation receptacle33_couch location_Xneg113_Yneg23_place40_room14_floorA)
	(receptacleatlocation receptacle37_bed location_Xneg8_Ypos17_place41_room4_floorB)
	(receptacleatlocation receptacle38_bed location_Xneg57_Ypos17_place42_room5_floorB)
	(receptacleatlocation receptacle39_bed location_Xneg75_Yneg17_place43_room3_floorB)
	(receptacleatlocation receptacle40_bed location_Xneg95_Ypos7_place44_room6_floorB)
	(receptacleatlocation receptacle41_bed location_Xneg69_Yneg36_place45_room7_floorB)
	(receptacleatlocation receptacle42_dining_table location_Xneg105_Ypos8_place46_room11_floorA)
	(receptacleatlocation receptacle43_dining_table location_Xneg89_Ypos3_place47_room12_floorA)
	(receptacleatlocation receptacle44_toilet location_Xneg33_Ypos15_place48_room2_floorB)
	(receptacleatlocation receptacle45_toilet location_Xneg79_Yneg38_place49_room3_floorB)
	(receptacleatlocation receptacle46_toilet location_Xneg77_Yneg39_place50_room3_floorB)
	(receptacleatlocation receptacle47_toilet location_Xneg58_Yneg24_place51_room1_floorA)
	(receptacleatlocation receptacle49_microwave location_Xneg70_Ypos14_place52_room12_floorA)
	(receptacleatlocation receptacle50_microwave location_Xneg59_Yneg35_place53_room17_floorA)
	(receptacleatlocation receptacle51_oven location_Xneg71_Ypos15_place54_room12_floorA)
	(receptacleatlocation receptacle52_sink location_Xneg33_Ypos4_place55_room2_floorB)
	(receptacleatlocation receptacle53_sink location_Xneg94_Yneg23_place56_room3_floorB)
	(receptacleatlocation receptacle54_sink location_Xneg67_Yneg25_place57_room1_floorA)
	(receptacleatlocation receptacle55_sink location_Xneg86_Ypos24_place58_room12_floorA)
	(receptacleatlocation receptacle56_refrigerator location_Xneg74_Yneg23_place59_room14_floorA)
	(receptacleatlocation receptacle57_refrigerator location_Xneg72_Ypos1_place60_room12_floorA)
	(receptacleopeningtype receptacle49_microwave)
	(receptacleopeningtype receptacle50_microwave)
	(receptacleopeningtype receptacle51_oven)
	(receptacleopeningtype receptacle56_refrigerator)
	(receptacleopeningtype receptacle57_refrigerator)
  )
  (:goal (and
	(inreceptacle item64_clock_mediumitem receptacle27_couch)
	(inreceptacle item73_vase_mediumitem receptacle12_chair)
	(inreceptacle item75_vase_mediumitem receptacle51_oven)
	(inreceptacle item74_vase_mediumitem receptacle17_chair)
	(inreceptacle item6_kite_largeitem receptacle16_chair)
	(inreceptacle item4_tie_smallitem receptacle38_bed)
	(inreceptacle item61_book_smallitem receptacle39_bed)
	(inreceptacle item71_clock_mediumitem receptacle17_chair)
	(inreceptacle item36_potted_plant_largeitem receptacle47_toilet)
	(inreceptacle item69_clock_mediumitem receptacle13_chair)))
)
