
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_bottle_smallitem - item
	item11_cup_smallitem - item
	item12_cup_smallitem - item
	item13_cup_smallitem - item
	item14_cup_smallitem - item
	item15_cup_smallitem - item
	item16_spoon_smallitem - item
	item17_bowl_smallitem - item
	item18_bowl_smallitem - item
	item5_baseball_bat_largeitem - item
	item66_book_smallitem - item
	item68_book_smallitem - item
	item69_book_smallitem - item
	item6_baseball_bat_largeitem - item
	item70_book_smallitem - item
	item71_clock_mediumitem - item
	item72_clock_mediumitem - item
	item73_vase_mediumitem - item
	item74_vase_mediumitem - item
	item75_vase_mediumitem - item
	item76_vase_mediumitem - item
	item7_bottle_smallitem - item
	item8_bottle_smallitem - item
	item9_bottle_smallitem - item
	location_Xneg5_Yneg21_place22_room10_floorA - location
	location_Xpos0_Yneg71_place35_room6_floorB - location
	location_Xpos11_Ypos4_place23_room10_floorA - location
	location_Xpos12_Yneg12_place22_room10_floorA - location
	location_Xpos12_Ypos43_place29_room14_floorA - location
	location_Xpos13_Ypos44_place30_room14_floorA - location
	location_Xpos14_Yneg41_place49_room13_floorA - location
	location_Xpos14_Yneg59_place47_room13_floorA - location
	location_Xpos14_Yneg7_place16_room10_floorA - location
	location_Xpos15_Yneg32_place26_room6_floorB - location
	location_Xpos15_Yneg4_place37_room10_floorA - location
	location_Xpos15_Ypos24_place32_room7_floorC - location
	location_Xpos15_Ypos7_place33_room5_floorB - location
	location_Xpos17_Yneg5_place17_room10_floorA - location
	location_Xpos18_Yneg38_place18_room13_floorA - location
	location_Xpos18_Yneg70_place34_room6_floorB - location
	location_Xpos18_Ypos3_place20_room10_floorA - location
	location_Xpos18_Ypos60_place25_room12_floorB - location
	location_Xpos22_Yneg44_place56_room13_floorA - location
	location_Xpos23_Yneg59_place47_room13_floorA - location
	location_Xpos24_Ypos33_place28_room14_floorA - location
	location_Xpos24_Ypos37_place32_room7_floorC - location
	location_Xpos24_Ypos45_place30_room14_floorA - location
	location_Xpos27_Yneg68_place52_room2_floorB - location
	location_Xpos27_Yneg70_place52_room2_floorB - location
	location_Xpos29_Yneg73_place52_room2_floorB - location
	location_Xpos2_Ypos39_place29_room14_floorA - location
	location_Xpos2_Ypos49_place15_room12_floorB - location
	location_Xpos32_Yneg56_place48_room13_floorA - location
	location_Xpos37_Yneg40_place55_room13_floorA - location
	location_Xpos38_Yneg2_place38_room8_floorB - location
	location_Xpos38_Ypos1_place21_room10_floorA - location
	location_Xpos39_Yneg10_place19_room10_floorA - location
	location_Xpos39_Yneg2_place38_room8_floorB - location
	location_Xpos39_Ypos10_place19_room10_floorA - location
	location_Xpos39_Ypos1_place19_room10_floorA - location
	location_Xpos3_Yneg21_place31_room7_floorC - location
	location_Xpos40_Yneg38_place57_room19_floorB - location
	location_Xpos41_Yneg59_place40_room16_floorA - location
	location_Xpos42_Yneg36_place57_room19_floorB - location
	location_Xpos43_Ypos38_place36_room11_floorA - location
	location_Xpos43_Ypos61_place51_room3_floorB - location
	location_Xpos44_Yneg60_place40_room16_floorA - location
	location_Xpos45_Yneg36_place57_room19_floorB - location
	location_Xpos45_Ypos35_place36_room11_floorA - location
	location_Xpos47_Yneg52_place59_room19_floorB - location
	location_Xpos47_Yneg61_place46_room2_floorB - location
	location_Xpos48_Yneg59_place39_room16_floorA - location
	location_Xpos48_Yneg61_place45_room2_floorB - location
	location_Xpos48_Ypos38_place36_room11_floorA - location
	location_Xpos48_Ypos61_place42_room4_floorC - location
	location_Xpos49_Yneg45_place58_room16_floorA - location
	location_Xpos49_Ypos47_place53_room4_floorC - location
	location_Xpos49_Ypos52_place41_room1_floorA - location
	location_Xpos49_Ypos55_place43_room3_floorB - location
	location_Xpos4_Yneg32_place27_room6_floorB - location
	location_Xpos4_Ypos49_place25_room12_floorB - location
	location_Xpos50_Ypos45_place54_room1_floorA - location
	location_Xpos50_Ypos46_place50_room3_floorB - location
	location_Xpos51_Yneg61_place44_room2_floorB - location
	location_Xpos52_Ypos43_place50_room3_floorB - location
	location_Xpos52_Ypos43_place54_room1_floorA - location
	location_Xpos52_Ypos48_place50_room3_floorB - location
	location_Xpos52_Ypos51_place53_room4_floorC - location
	location_Xpos6_Yneg60_place47_room13_floorA - location
	location_Xpos7_Yneg77_place35_room6_floorB - location
	location_Xpos7_Yneg80_place35_room6_floorB - location
	location_Xpos8_Yneg36_place24_room13_floorA - location
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle30_chair - receptacle
	receptacle32_couch - receptacle
	receptacle33_couch - receptacle
	receptacle34_couch - receptacle
	receptacle35_couch - receptacle
	receptacle36_bed - receptacle
	receptacle37_bed - receptacle
	receptacle38_bed - receptacle
	receptacle39_bed - receptacle
	receptacle40_bed - receptacle
	receptacle41_dining_table - receptacle
	receptacle42_dining_table - receptacle
	receptacle45_dining_table - receptacle
	receptacle46_dining_table - receptacle
	receptacle47_toilet - receptacle
	receptacle48_toilet - receptacle
	receptacle49_toilet - receptacle
	receptacle50_toilet - receptacle
	receptacle51_toilet - receptacle
	receptacle52_toilet - receptacle
	receptacle53_oven - receptacle
	receptacle54_oven - receptacle
	receptacle55_sink - receptacle
	receptacle56_sink - receptacle
	receptacle57_sink - receptacle
	receptacle58_sink - receptacle
	receptacle59_sink - receptacle
	receptacle60_sink - receptacle
	receptacle61_refrigerator - receptacle
	receptacle62_refrigerator - receptacle
	receptacle63_refrigerator - receptacle
	receptacle64_refrigerator - receptacle
	receptacle65_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xpos43_Ypos38_place36_room11_floorA)
	(inanyreceptacle item10_bottle_smallitem)
	(inanyreceptacle item11_cup_smallitem)
	(inanyreceptacle item12_cup_smallitem)
	(inanyreceptacle item13_cup_smallitem)
	(inanyreceptacle item14_cup_smallitem)
	(inanyreceptacle item15_cup_smallitem)
	(inanyreceptacle item16_spoon_smallitem)
	(inanyreceptacle item17_bowl_smallitem)
	(inanyreceptacle item18_bowl_smallitem)
	(inanyreceptacle item5_baseball_bat_largeitem)
	(inanyreceptacle item66_book_smallitem)
	(inanyreceptacle item68_book_smallitem)
	(inanyreceptacle item69_book_smallitem)
	(inanyreceptacle item6_baseball_bat_largeitem)
	(inanyreceptacle item70_book_smallitem)
	(inanyreceptacle item71_clock_mediumitem)
	(inanyreceptacle item72_clock_mediumitem)
	(inanyreceptacle item74_vase_mediumitem)
	(inanyreceptacle item75_vase_mediumitem)
	(inanyreceptacle item76_vase_mediumitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item9_bottle_smallitem)
	(inreceptacle item10_bottle_smallitem receptacle59_sink)
	(inreceptacle item11_cup_smallitem receptacle22_chair)
	(inreceptacle item12_cup_smallitem receptacle42_dining_table)
	(inreceptacle item13_cup_smallitem receptacle22_chair)
	(inreceptacle item14_cup_smallitem receptacle56_sink)
	(inreceptacle item15_cup_smallitem receptacle46_dining_table)
	(inreceptacle item16_spoon_smallitem receptacle53_oven)
	(inreceptacle item17_bowl_smallitem receptacle25_chair)
	(inreceptacle item18_bowl_smallitem receptacle58_sink)
	(inreceptacle item5_baseball_bat_largeitem receptacle40_bed)
	(inreceptacle item66_book_smallitem receptacle28_chair)
	(inreceptacle item68_book_smallitem receptacle53_oven)
	(inreceptacle item69_book_smallitem receptacle39_bed)
	(inreceptacle item6_baseball_bat_largeitem receptacle40_bed)
	(inreceptacle item70_book_smallitem receptacle39_bed)
	(inreceptacle item71_clock_mediumitem receptacle63_refrigerator)
	(inreceptacle item72_clock_mediumitem receptacle63_refrigerator)
	(inreceptacle item74_vase_mediumitem receptacle36_bed)
	(inreceptacle item75_vase_mediumitem receptacle33_couch)
	(inreceptacle item76_vase_mediumitem receptacle58_sink)
	(inreceptacle item7_bottle_smallitem receptacle34_couch)
	(inreceptacle item8_bottle_smallitem receptacle56_sink)
	(inreceptacle item9_bottle_smallitem receptacle60_sink)
	(itematlocation item10_bottle_smallitem location_Xpos52_Ypos51_place53_room4_floorC)
	(itematlocation item11_cup_smallitem location_Xpos39_Ypos10_place19_room10_floorA)
	(itematlocation item12_cup_smallitem location_Xpos39_Yneg2_place38_room8_floorB)
	(itematlocation item13_cup_smallitem location_Xpos39_Yneg10_place19_room10_floorA)
	(itematlocation item14_cup_smallitem location_Xpos52_Ypos48_place50_room3_floorB)
	(itematlocation item15_cup_smallitem location_Xpos44_Yneg60_place40_room16_floorA)
	(itematlocation item16_spoon_smallitem location_Xpos6_Yneg60_place47_room13_floorA)
	(itematlocation item17_bowl_smallitem location_Xneg5_Yneg21_place22_room10_floorA)
	(itematlocation item18_bowl_smallitem location_Xpos27_Yneg70_place52_room2_floorB)
	(itematlocation item5_baseball_bat_largeitem location_Xpos48_Ypos38_place36_room11_floorA)
	(itematlocation item66_book_smallitem location_Xpos4_Ypos49_place25_room12_floorB)
	(itematlocation item68_book_smallitem location_Xpos23_Yneg59_place47_room13_floorA)
	(itematlocation item69_book_smallitem location_Xpos7_Yneg80_place35_room6_floorB)
	(itematlocation item6_baseball_bat_largeitem location_Xpos43_Ypos38_place36_room11_floorA)
	(itematlocation item70_book_smallitem location_Xpos7_Yneg77_place35_room6_floorB)
	(itematlocation item71_clock_mediumitem location_Xpos45_Yneg36_place57_room19_floorB)
	(itematlocation item72_clock_mediumitem location_Xpos42_Yneg36_place57_room19_floorB)
	(itematlocation item73_vase_mediumitem location_Xpos2_Ypos49_place15_room12_floorB)
	(itematlocation item74_vase_mediumitem location_Xpos24_Ypos37_place32_room7_floorC)
	(itematlocation item75_vase_mediumitem location_Xpos12_Ypos43_place29_room14_floorA)
	(itematlocation item76_vase_mediumitem location_Xpos27_Yneg68_place52_room2_floorB)
	(itematlocation item7_bottle_smallitem location_Xpos13_Ypos44_place30_room14_floorA)
	(itematlocation item8_bottle_smallitem location_Xpos52_Ypos43_place50_room3_floorB)
	(itematlocation item9_bottle_smallitem location_Xpos52_Ypos43_place54_room1_floorA)
	(receptacleatlocation receptacle19_chair location_Xpos14_Yneg7_place16_room10_floorA)
	(receptacleatlocation receptacle20_chair location_Xpos17_Yneg5_place17_room10_floorA)
	(receptacleatlocation receptacle21_chair location_Xpos18_Yneg38_place18_room13_floorA)
	(receptacleatlocation receptacle22_chair location_Xpos39_Ypos1_place19_room10_floorA)
	(receptacleatlocation receptacle23_chair location_Xpos18_Ypos3_place20_room10_floorA)
	(receptacleatlocation receptacle24_chair location_Xpos38_Ypos1_place21_room10_floorA)
	(receptacleatlocation receptacle25_chair location_Xpos12_Yneg12_place22_room10_floorA)
	(receptacleatlocation receptacle26_chair location_Xpos11_Ypos4_place23_room10_floorA)
	(receptacleatlocation receptacle27_chair location_Xpos8_Yneg36_place24_room13_floorA)
	(receptacleatlocation receptacle28_chair location_Xpos18_Ypos60_place25_room12_floorB)
	(receptacleatlocation receptacle29_chair location_Xpos15_Yneg32_place26_room6_floorB)
	(receptacleatlocation receptacle30_chair location_Xpos4_Yneg32_place27_room6_floorB)
	(receptacleatlocation receptacle32_couch location_Xpos24_Ypos33_place28_room14_floorA)
	(receptacleatlocation receptacle33_couch location_Xpos2_Ypos39_place29_room14_floorA)
	(receptacleatlocation receptacle34_couch location_Xpos24_Ypos45_place30_room14_floorA)
	(receptacleatlocation receptacle35_couch location_Xpos3_Yneg21_place31_room7_floorC)
	(receptacleatlocation receptacle36_bed location_Xpos15_Ypos24_place32_room7_floorC)
	(receptacleatlocation receptacle37_bed location_Xpos15_Ypos7_place33_room5_floorB)
	(receptacleatlocation receptacle38_bed location_Xpos18_Yneg70_place34_room6_floorB)
	(receptacleatlocation receptacle39_bed location_Xpos0_Yneg71_place35_room6_floorB)
	(receptacleatlocation receptacle40_bed location_Xpos45_Ypos35_place36_room11_floorA)
	(receptacleatlocation receptacle41_dining_table location_Xpos15_Yneg4_place37_room10_floorA)
	(receptacleatlocation receptacle42_dining_table location_Xpos38_Yneg2_place38_room8_floorB)
	(receptacleatlocation receptacle45_dining_table location_Xpos48_Yneg59_place39_room16_floorA)
	(receptacleatlocation receptacle46_dining_table location_Xpos41_Yneg59_place40_room16_floorA)
	(receptacleatlocation receptacle47_toilet location_Xpos49_Ypos52_place41_room1_floorA)
	(receptacleatlocation receptacle48_toilet location_Xpos48_Ypos61_place42_room4_floorC)
	(receptacleatlocation receptacle49_toilet location_Xpos49_Ypos55_place43_room3_floorB)
	(receptacleatlocation receptacle50_toilet location_Xpos51_Yneg61_place44_room2_floorB)
	(receptacleatlocation receptacle51_toilet location_Xpos48_Yneg61_place45_room2_floorB)
	(receptacleatlocation receptacle52_toilet location_Xpos47_Yneg61_place46_room2_floorB)
	(receptacleatlocation receptacle53_oven location_Xpos14_Yneg59_place47_room13_floorA)
	(receptacleatlocation receptacle54_oven location_Xpos32_Yneg56_place48_room13_floorA)
	(receptacleatlocation receptacle55_sink location_Xpos14_Yneg41_place49_room13_floorA)
	(receptacleatlocation receptacle56_sink location_Xpos50_Ypos46_place50_room3_floorB)
	(receptacleatlocation receptacle57_sink location_Xpos43_Ypos61_place51_room3_floorB)
	(receptacleatlocation receptacle58_sink location_Xpos29_Yneg73_place52_room2_floorB)
	(receptacleatlocation receptacle59_sink location_Xpos49_Ypos47_place53_room4_floorC)
	(receptacleatlocation receptacle60_sink location_Xpos50_Ypos45_place54_room1_floorA)
	(receptacleatlocation receptacle61_refrigerator location_Xpos37_Yneg40_place55_room13_floorA)
	(receptacleatlocation receptacle62_refrigerator location_Xpos22_Yneg44_place56_room13_floorA)
	(receptacleatlocation receptacle63_refrigerator location_Xpos40_Yneg38_place57_room19_floorB)
	(receptacleatlocation receptacle64_refrigerator location_Xpos49_Yneg45_place58_room16_floorA)
	(receptacleatlocation receptacle65_refrigerator location_Xpos47_Yneg52_place59_room19_floorB)
	(receptacleopeningtype receptacle53_oven)
	(receptacleopeningtype receptacle54_oven)
	(receptacleopeningtype receptacle61_refrigerator)
	(receptacleopeningtype receptacle62_refrigerator)
	(receptacleopeningtype receptacle63_refrigerator)
	(receptacleopeningtype receptacle64_refrigerator)
	(receptacleopeningtype receptacle65_refrigerator)
  )
  (:goal (and
	(inreceptacle item18_bowl_smallitem receptacle33_couch)
	(inreceptacle item17_bowl_smallitem receptacle47_toilet)
	(inreceptacle item75_vase_mediumitem receptacle47_toilet)
	(inreceptacle item71_clock_mediumitem receptacle27_chair)
	(inreceptacle item68_book_smallitem receptacle37_bed)
	(inreceptacle item76_vase_mediumitem receptacle64_refrigerator)
	(inreceptacle item15_cup_smallitem receptacle63_refrigerator)
	(inreceptacle item9_bottle_smallitem receptacle57_sink)
	(inreceptacle item5_baseball_bat_largeitem receptacle56_sink)
	(inreceptacle item8_bottle_smallitem receptacle21_chair)))
)
