
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item13_clock_mediumitem - item
	item14_vase_mediumitem - item
	item15_vase_mediumitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item19_vase_mediumitem - item
	item20_vase_mediumitem - item
	item21_vase_mediumitem - item
	item22_vase_mediumitem - item
	item23_vase_mediumitem - item
	item24_cup_smallitem - item
	item2_surfboard_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item50_potted_plant_largeitem - item
	location_Xneg17_Ypos37_place52_room22_floorA - location
	location_Xneg19_Ypos54_place48_room6_floorB - location
	location_Xneg22_Yneg20_place50_room18_floorA - location
	location_Xneg22_Yneg37_place28_room3_floorB - location
	location_Xneg28_Yneg37_place50_room18_floorA - location
	location_Xneg2_Ypos61_place22_room22_floorA - location
	location_Xneg2_Ypos61_place24_room6_floorB - location
	location_Xneg5_Yneg49_place46_room18_floorA - location
	location_Xneg5_Ypos61_place21_room22_floorA - location
	location_Xneg6_Ypos62_place19_room6_floorB - location
	location_Xpos10_Yneg27_place20_room3_floorB - location
	location_Xpos112_Ypos37_place18_room17_floorB - location
	location_Xpos116_Yneg19_place29_room5_floorB - location
	location_Xpos119_Yneg27_place33_room19_floorA - location
	location_Xpos119_Yneg42_place25_room19_floorA - location
	location_Xpos119_Yneg56_place25_room19_floorA - location
	location_Xpos120_Yneg28_place39_room5_floorB - location
	location_Xpos120_Ypos53_place43_room21_floorA - location
	location_Xpos121_Yneg57_place25_room19_floorA - location
	location_Xpos15_Yneg55_place38_room3_floorB - location
	location_Xpos162_Yneg26_place49_room23_floorB - location
	location_Xpos186_Ypos1_place41_room14_floorB - location
	location_Xpos186_Ypos2_place41_room14_floorB - location
	location_Xpos18_Yneg23_place17_room18_floorA - location
	location_Xpos1_Yneg44_place46_room18_floorA - location
	location_Xpos20_Ypos11_place47_room10_floorA - location
	location_Xpos24_Ypos45_place34_room16_floorB - location
	location_Xpos30_Yneg34_place32_room1_floorA - location
	location_Xpos35_Yneg45_place36_room1_floorA - location
	location_Xpos42_Ypos37_place58_room13_floorA - location
	location_Xpos43_Ypos37_place58_room13_floorA - location
	location_Xpos43_Ypos38_place42_room13_floorA - location
	location_Xpos43_Ypos38_place58_room13_floorA - location
	location_Xpos44_Yneg41_place26_room1_floorA - location
	location_Xpos44_Ypos64_place56_room13_floorA - location
	location_Xpos53_Yneg7_place27_room2_floorA - location
	location_Xpos54_Yneg18_place37_room2_floorA - location
	location_Xpos58_Yneg28_place35_room24_floorA - location
	location_Xpos5_Ypos37_place55_room6_floorB - location
	location_Xpos71_Yneg57_place23_room19_floorA - location
	location_Xpos72_Ypos54_place45_room21_floorA - location
	location_Xpos76_Ypos55_place30_room4_floorB - location
	location_Xpos80_Ypos46_place40_room4_floorB - location
	location_Xpos8_Ypos37_place53_room22_floorA - location
	location_Xpos92_Ypos21_place51_room21_floorA - location
	location_Xpos93_Yneg23_place44_room19_floorA - location
	location_Xpos94_Yneg23_place57_room19_floorA - location
	location_Xpos94_Yneg26_place57_room19_floorA - location
	location_Xpos94_Yneg57_place31_room19_floorA - location
	location_Xpos95_Yneg32_place57_room19_floorA - location
	location_Xpos96_Yneg33_place57_room19_floorA - location
	location_Xpos97_Ypos35_place51_room21_floorA - location
	location_Xpos9_Ypos30_place53_room22_floorA - location
	location_Xpos9_Ypos44_place54_room22_floorA - location
	receptacle10_refrigerator - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle1_oven - receptacle
	receptacle25_toilet - receptacle
	receptacle26_toilet - receptacle
	receptacle27_toilet - receptacle
	receptacle28_toilet - receptacle
	receptacle29_toilet - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_couch - receptacle
	receptacle39_couch - receptacle
	receptacle3_sink - receptacle
	receptacle40_couch - receptacle
	receptacle41_couch - receptacle
	receptacle42_couch - receptacle
	receptacle43_couch - receptacle
	receptacle4_sink - receptacle
	receptacle51_bed - receptacle
	receptacle52_bed - receptacle
	receptacle53_dining_table - receptacle
	receptacle54_dining_table - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xpos92_Ypos21_place51_room21_floorA)
	(inanyreceptacle item14_vase_mediumitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item17_vase_mediumitem)
	(inanyreceptacle item18_vase_mediumitem)
	(inanyreceptacle item19_vase_mediumitem)
	(inanyreceptacle item22_vase_mediumitem)
	(inanyreceptacle item23_vase_mediumitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item47_potted_plant_largeitem)
	(inanyreceptacle item49_potted_plant_largeitem)
	(inreceptacle item14_vase_mediumitem receptacle30_chair)
	(inreceptacle item16_vase_mediumitem receptacle54_dining_table)
	(inreceptacle item17_vase_mediumitem receptacle53_dining_table)
	(inreceptacle item18_vase_mediumitem receptacle40_couch)
	(inreceptacle item19_vase_mediumitem receptacle42_couch)
	(inreceptacle item22_vase_mediumitem receptacle1_oven)
	(inreceptacle item23_vase_mediumitem receptacle1_oven)
	(inreceptacle item44_potted_plant_largeitem receptacle39_couch)
	(inreceptacle item45_potted_plant_largeitem receptacle35_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item47_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item49_potted_plant_largeitem receptacle54_dining_table)
	(itematlocation item13_clock_mediumitem location_Xpos112_Ypos37_place18_room17_floorB)
	(itematlocation item14_vase_mediumitem location_Xpos186_Ypos1_place41_room14_floorB)
	(itematlocation item15_vase_mediumitem location_Xneg6_Ypos62_place19_room6_floorB)
	(itematlocation item16_vase_mediumitem location_Xpos43_Ypos37_place58_room13_floorA)
	(itematlocation item17_vase_mediumitem location_Xpos95_Yneg32_place57_room19_floorA)
	(itematlocation item18_vase_mediumitem location_Xpos97_Ypos35_place51_room21_floorA)
	(itematlocation item19_vase_mediumitem location_Xpos8_Ypos37_place53_room22_floorA)
	(itematlocation item20_vase_mediumitem location_Xneg2_Ypos61_place22_room22_floorA)
	(itematlocation item21_vase_mediumitem location_Xpos71_Yneg57_place23_room19_floorA)
	(itematlocation item22_vase_mediumitem location_Xpos119_Yneg56_place25_room19_floorA)
	(itematlocation item23_vase_mediumitem location_Xpos121_Yneg57_place25_room19_floorA)
	(itematlocation item24_cup_smallitem location_Xneg2_Ypos61_place24_room6_floorB)
	(itematlocation item2_surfboard_largeitem location_Xpos18_Yneg23_place17_room18_floorA)
	(itematlocation item44_potted_plant_largeitem location_Xneg22_Yneg20_place50_room18_floorA)
	(itematlocation item45_potted_plant_largeitem location_Xpos1_Yneg44_place46_room18_floorA)
	(itematlocation item46_potted_plant_largeitem location_Xpos94_Yneg26_place57_room19_floorA)
	(itematlocation item47_potted_plant_largeitem location_Xpos96_Yneg33_place57_room19_floorA)
	(itematlocation item48_potted_plant_largeitem location_Xpos10_Yneg27_place20_room3_floorB)
	(itematlocation item49_potted_plant_largeitem location_Xpos43_Ypos38_place58_room13_floorA)
	(itematlocation item50_potted_plant_largeitem location_Xneg5_Ypos61_place21_room22_floorA)
	(receptacleatlocation receptacle10_refrigerator location_Xpos119_Yneg27_place33_room19_floorA)
	(receptacleatlocation receptacle11_refrigerator location_Xpos24_Ypos45_place34_room16_floorB)
	(receptacleatlocation receptacle12_refrigerator location_Xpos58_Yneg28_place35_room24_floorA)
	(receptacleatlocation receptacle1_oven location_Xpos119_Yneg42_place25_room19_floorA)
	(receptacleatlocation receptacle25_toilet location_Xpos35_Yneg45_place36_room1_floorA)
	(receptacleatlocation receptacle26_toilet location_Xpos54_Yneg18_place37_room2_floorA)
	(receptacleatlocation receptacle27_toilet location_Xpos15_Yneg55_place38_room3_floorB)
	(receptacleatlocation receptacle28_toilet location_Xpos120_Yneg28_place39_room5_floorB)
	(receptacleatlocation receptacle29_toilet location_Xpos80_Ypos46_place40_room4_floorB)
	(receptacleatlocation receptacle30_chair location_Xpos186_Ypos2_place41_room14_floorB)
	(receptacleatlocation receptacle31_chair location_Xpos43_Ypos38_place42_room13_floorA)
	(receptacleatlocation receptacle32_chair location_Xpos120_Ypos53_place43_room21_floorA)
	(receptacleatlocation receptacle33_chair location_Xpos93_Yneg23_place44_room19_floorA)
	(receptacleatlocation receptacle34_chair location_Xpos72_Ypos54_place45_room21_floorA)
	(receptacleatlocation receptacle35_chair location_Xneg5_Yneg49_place46_room18_floorA)
	(receptacleatlocation receptacle36_chair location_Xpos20_Ypos11_place47_room10_floorA)
	(receptacleatlocation receptacle37_chair location_Xneg19_Ypos54_place48_room6_floorB)
	(receptacleatlocation receptacle38_couch location_Xpos162_Yneg26_place49_room23_floorB)
	(receptacleatlocation receptacle39_couch location_Xneg28_Yneg37_place50_room18_floorA)
	(receptacleatlocation receptacle3_sink location_Xpos44_Yneg41_place26_room1_floorA)
	(receptacleatlocation receptacle40_couch location_Xpos92_Ypos21_place51_room21_floorA)
	(receptacleatlocation receptacle41_couch location_Xneg17_Ypos37_place52_room22_floorA)
	(receptacleatlocation receptacle42_couch location_Xpos9_Ypos30_place53_room22_floorA)
	(receptacleatlocation receptacle43_couch location_Xpos9_Ypos44_place54_room22_floorA)
	(receptacleatlocation receptacle4_sink location_Xpos53_Yneg7_place27_room2_floorA)
	(receptacleatlocation receptacle51_bed location_Xpos5_Ypos37_place55_room6_floorB)
	(receptacleatlocation receptacle52_bed location_Xpos44_Ypos64_place56_room13_floorA)
	(receptacleatlocation receptacle53_dining_table location_Xpos94_Yneg23_place57_room19_floorA)
	(receptacleatlocation receptacle54_dining_table location_Xpos42_Ypos37_place58_room13_floorA)
	(receptacleatlocation receptacle5_sink location_Xneg22_Yneg37_place28_room3_floorB)
	(receptacleatlocation receptacle6_sink location_Xpos116_Yneg19_place29_room5_floorB)
	(receptacleatlocation receptacle7_sink location_Xpos76_Ypos55_place30_room4_floorB)
	(receptacleatlocation receptacle8_sink location_Xpos94_Yneg57_place31_room19_floorA)
	(receptacleatlocation receptacle9_refrigerator location_Xpos30_Yneg34_place32_room1_floorA)
	(receptacleopeningtype receptacle10_refrigerator)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle9_refrigerator)
  )
  (:goal (and
	(inreceptacle item47_potted_plant_largeitem receptacle11_refrigerator)
	(inreceptacle item18_vase_mediumitem receptacle11_refrigerator)
	(inreceptacle item49_potted_plant_largeitem receptacle32_chair)
	(inreceptacle item17_vase_mediumitem receptacle5_sink)
	(inreceptacle item16_vase_mediumitem receptacle26_toilet)
	(inreceptacle item24_cup_smallitem receptacle27_toilet)
	(inreceptacle item44_potted_plant_largeitem receptacle25_toilet)
	(inreceptacle item21_vase_mediumitem receptacle38_couch)
	(inreceptacle item22_vase_mediumitem receptacle30_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle28_toilet)))
)
