
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item102_tv_largeitem - item
	item103_tv_largeitem - item
	item104_tv_largeitem - item
	item10_bottle_smallitem - item
	item117_book_smallitem - item
	item118_book_smallitem - item
	item119_book_smallitem - item
	item11_bottle_smallitem - item
	item120_book_smallitem - item
	item121_book_smallitem - item
	item122_book_smallitem - item
	item123_book_smallitem - item
	item124_book_smallitem - item
	item125_book_smallitem - item
	item126_book_smallitem - item
	item127_book_smallitem - item
	item128_book_smallitem - item
	item129_clock_mediumitem - item
	item12_wine_glass_smallitem - item
	item130_clock_mediumitem - item
	item131_vase_mediumitem - item
	item132_vase_mediumitem - item
	item133_vase_mediumitem - item
	item134_vase_mediumitem - item
	item135_teddy_bear_mediumitem - item
	item136_teddy_bear_mediumitem - item
	item13_wine_glass_smallitem - item
	item14_wine_glass_smallitem - item
	item15_wine_glass_smallitem - item
	item16_wine_glass_smallitem - item
	item17_cup_smallitem - item
	item18_bowl_smallitem - item
	item19_bowl_smallitem - item
	item1_handbag_largeitem - item
	item20_bowl_smallitem - item
	item21_bowl_smallitem - item
	item22_apple_smallitem - item
	item23_apple_smallitem - item
	item24_cake_mediumitem - item
	item25_cake_mediumitem - item
	item26_cake_mediumitem - item
	item27_cake_mediumitem - item
	item2_tie_smallitem - item
	item3_tie_smallitem - item
	item4_tie_smallitem - item
	item52_potted_plant_largeitem - item
	item53_potted_plant_largeitem - item
	item54_potted_plant_largeitem - item
	item55_potted_plant_largeitem - item
	item56_potted_plant_largeitem - item
	item57_potted_plant_largeitem - item
	item58_potted_plant_largeitem - item
	item59_potted_plant_largeitem - item
	item5_tie_smallitem - item
	item60_potted_plant_largeitem - item
	item61_potted_plant_largeitem - item
	item62_potted_plant_largeitem - item
	item63_potted_plant_largeitem - item
	item64_potted_plant_largeitem - item
	item65_potted_plant_largeitem - item
	item66_potted_plant_largeitem - item
	item67_potted_plant_largeitem - item
	item68_potted_plant_largeitem - item
	item69_potted_plant_largeitem - item
	item6_tie_smallitem - item
	item70_potted_plant_largeitem - item
	item71_potted_plant_largeitem - item
	item72_potted_plant_largeitem - item
	item73_potted_plant_largeitem - item
	item74_potted_plant_largeitem - item
	item75_potted_plant_largeitem - item
	item76_potted_plant_largeitem - item
	item77_potted_plant_largeitem - item
	item78_potted_plant_largeitem - item
	item79_potted_plant_largeitem - item
	item7_tie_smallitem - item
	item80_potted_plant_largeitem - item
	item81_potted_plant_largeitem - item
	item82_potted_plant_largeitem - item
	item83_potted_plant_largeitem - item
	item84_potted_plant_largeitem - item
	item85_potted_plant_largeitem - item
	item86_potted_plant_largeitem - item
	item87_potted_plant_largeitem - item
	item88_potted_plant_largeitem - item
	item89_potted_plant_largeitem - item
	item8_tie_smallitem - item
	item90_potted_plant_largeitem - item
	item9_bottle_smallitem - item
	location_Xneg10_Yneg66_place47_room16_floorA - location
	location_Xneg12_Yneg37_place50_room10_floorA - location
	location_Xneg12_Yneg68_place76_room15_floorA - location
	location_Xneg13_Ypos22_place89_room6_floorB - location
	location_Xneg13_Ypos24_place89_room6_floorB - location
	location_Xneg15_Yneg85_place94_room3_floorB - location
	location_Xneg16_Yneg115_place99_room3_floorB - location
	location_Xneg16_Yneg35_place37_room10_floorA - location
	location_Xneg16_Yneg36_place51_room10_floorA - location
	location_Xneg16_Yneg39_place24_room21_floorA - location
	location_Xneg16_Yneg39_place52_room21_floorA - location
	location_Xneg17_Yneg120_place99_room3_floorB - location
	location_Xneg17_Yneg67_place76_room15_floorA - location
	location_Xneg17_Ypos24_place59_room18_floorA - location
	location_Xneg18_Yneg67_place76_room15_floorA - location
	location_Xneg18_Yneg85_place94_room3_floorB - location
	location_Xneg18_Ypos24_place57_room18_floorA - location
	location_Xneg19_Yneg4_place79_room18_floorA - location
	location_Xneg19_Yneg66_place76_room15_floorA - location
	location_Xneg19_Yneg68_place76_room15_floorA - location
	location_Xneg19_Ypos24_place58_room18_floorA - location
	location_Xneg19_Ypos5_place101_room2_floorB - location
	location_Xneg20_Yneg32_place77_room11_floorB - location
	location_Xneg21_Yneg35_place31_room10_floorA - location
	location_Xneg21_Yneg37_place49_room10_floorA - location
	location_Xneg21_Yneg80_place95_room17_floorA - location
	location_Xneg21_Ypos8_place101_room2_floorB - location
	location_Xneg22_Ypos19_place92_room2_floorB - location
	location_Xneg23_Yneg84_place95_room17_floorA - location
	location_Xneg25_Ypos4_place80_room18_floorA - location
	location_Xneg25_Ypos5_place80_room18_floorA - location
	location_Xneg26_Yneg35_place48_room10_floorA - location
	location_Xneg26_Yneg74_place95_room17_floorA - location
	location_Xneg27_Ypos22_place80_room18_floorA - location
	location_Xneg31_Ypos26_place74_room2_floorB - location
	location_Xneg38_Yneg66_place73_room17_floorA - location
	location_Xneg3_Yneg68_place30_room16_floorA - location
	location_Xneg3_Yneg68_place35_room16_floorA - location
	location_Xneg41_Yneg76_place73_room17_floorA - location
	location_Xneg41_Yneg96_place96_room17_floorA - location
	location_Xneg41_Ypos24_place22_room18_floorA - location
	location_Xneg42_Yneg80_place87_room8_floorB - location
	location_Xneg44_Yneg36_place40_room4_floorB - location
	location_Xneg44_Yneg78_place73_room17_floorA - location
	location_Xneg45_Yneg124_place85_room5_floorB - location
	location_Xneg45_Ypos24_place53_room18_floorA - location
	location_Xneg45_Ypos25_place86_room7_floorB - location
	location_Xneg46_Ypos24_place86_room7_floorB - location
	location_Xneg46_Ypos25_place86_room7_floorB - location
	location_Xneg47_Yneg79_place87_room8_floorB - location
	location_Xneg49_Ypos24_place56_room18_floorA - location
	location_Xneg51_Yneg95_place96_room17_floorA - location
	location_Xneg54_Yneg70_place105_room22_floorB - location
	location_Xneg55_Yneg97_place54_room5_floorB - location
	location_Xneg57_Ypos15_place86_room7_floorB - location
	location_Xneg57_Ypos4_place86_room7_floorB - location
	location_Xneg58_Yneg58_place97_room22_floorB - location
	location_Xneg58_Ypos5_place86_room7_floorB - location
	location_Xneg59_Yneg69_place105_room22_floorB - location
	location_Xneg59_Yneg82_place87_room8_floorB - location
	location_Xneg59_Ypos4_place86_room7_floorB - location
	location_Xneg59_Ypos5_place86_room7_floorB - location
	location_Xneg5_Ypos15_place89_room6_floorB - location
	location_Xneg62_Yneg37_place67_room13_floorA - location
	location_Xneg63_Yneg118_place81_room5_floorB - location
	location_Xneg63_Yneg29_place68_room13_floorA - location
	location_Xneg63_Yneg56_place106_room17_floorA - location
	location_Xneg64_Yneg90_place23_room8_floorB - location
	location_Xneg65_Yneg28_place84_room4_floorB - location
	location_Xneg65_Yneg63_place97_room22_floorB - location
	location_Xneg65_Yneg76_place102_room17_floorA - location
	location_Xneg66_Yneg69_place102_room17_floorA - location
	location_Xneg66_Yneg84_place102_room17_floorA - location
	location_Xneg67_Yneg34_place71_room13_floorA - location
	location_Xneg68_Yneg33_place69_room13_floorA - location
	location_Xneg68_Yneg64_place97_room22_floorB - location
	location_Xneg71_Yneg29_place69_room13_floorA - location
	location_Xneg71_Yneg37_place70_room13_floorA - location
	location_Xneg77_Yneg50_place70_room13_floorA - location
	location_Xneg7_Yneg129_place98_room3_floorB - location
	location_Xneg8_Yneg67_place46_room16_floorA - location
	location_Xneg9_Ypos22_place55_room18_floorA - location
	location_Xpos0_Ypos15_place93_room1_floorA - location
	location_Xpos0_Ypos19_place93_room1_floorA - location
	location_Xpos10_Yneg103_place27_room9_floorB - location
	location_Xpos10_Yneg93_place39_room9_floorB - location
	location_Xpos11_Yneg40_place44_room12_floorA - location
	location_Xpos12_Yneg107_place26_room9_floorB - location
	location_Xpos12_Ypos22_place93_room1_floorA - location
	location_Xpos12_Ypos7_place104_room1_floorA - location
	location_Xpos13_Yneg40_place43_room12_floorA - location
	location_Xpos13_Ypos8_place103_room1_floorA - location
	location_Xpos14_Ypos10_place104_room1_floorA - location
	location_Xpos15_Yneg32_place45_room19_floorA - location
	location_Xpos18_Yneg37_place42_room12_floorA - location
	location_Xpos18_Ypos7_place61_room14_floorA - location
	location_Xpos19_Yneg41_place64_room12_floorA - location
	location_Xpos19_Yneg47_place82_room20_floorB - location
	location_Xpos19_Ypos4_place91_room14_floorA - location
	location_Xpos1_Yneg106_place72_room3_floorB - location
	location_Xpos1_Yneg123_place98_room3_floorB - location
	location_Xpos1_Ypos12_place104_room1_floorA - location
	location_Xpos21_Yneg84_place78_room20_floorB - location
	location_Xpos22_Ypos17_place61_room14_floorA - location
	location_Xpos25_Yneg115_place29_room3_floorB - location
	location_Xpos26_Yneg95_place25_room9_floorB - location
	location_Xpos28_Yneg55_place64_room12_floorA - location
	location_Xpos28_Ypos6_place91_room14_floorA - location
	location_Xpos29_Ypos12_place62_room14_floorA - location
	location_Xpos2_Ypos20_place93_room1_floorA - location
	location_Xpos30_Yneg40_place82_room20_floorB - location
	location_Xpos30_Ypos2_place60_room14_floorA - location
	location_Xpos31_Yneg38_place83_room20_floorB - location
	location_Xpos31_Yneg53_place90_room12_floorA - location
	location_Xpos32_Yneg42_place83_room20_floorB - location
	location_Xpos33_Yneg85_place78_room20_floorB - location
	location_Xpos34_Yneg49_place63_room12_floorA - location
	location_Xpos34_Yneg53_place90_room12_floorA - location
	location_Xpos37_Yneg53_place90_room12_floorA - location
	location_Xpos37_Yneg57_place66_room12_floorA - location
	location_Xpos3_Yneg68_place34_room16_floorA - location
	location_Xpos43_Yneg47_place83_room20_floorB - location
	location_Xpos43_Yneg53_place65_room12_floorA - location
	location_Xpos4_Yneg99_place100_room3_floorB - location
	location_Xpos50_Ypos14_place41_room14_floorA - location
	location_Xpos51_Yneg66_place65_room12_floorA - location
	location_Xpos51_Yneg7_place75_room14_floorA - location
	location_Xpos56_Yneg63_place32_room20_floorB - location
	location_Xpos5_Yneg93_place100_room3_floorB - location
	location_Xpos5_Ypos19_place88_room6_floorB - location
	location_Xpos7_Yneg68_place33_room16_floorA - location
	location_Xpos7_Yneg68_place36_room16_floorA - location
	location_Xpos9_Yneg103_place28_room9_floorB - location
	location_Xpos9_Yneg104_place38_room9_floorB - location
	receptacle100_toilet - receptacle
	receptacle101_toilet - receptacle
	receptacle105_oven - receptacle
	receptacle106_oven - receptacle
	receptacle107_sink - receptacle
	receptacle108_sink - receptacle
	receptacle109_sink - receptacle
	receptacle110_sink - receptacle
	receptacle111_sink - receptacle
	receptacle112_sink - receptacle
	receptacle113_sink - receptacle
	receptacle114_sink - receptacle
	receptacle115_refrigerator - receptacle
	receptacle116_refrigerator - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_chair - receptacle
	receptacle39_chair - receptacle
	receptacle40_chair - receptacle
	receptacle41_chair - receptacle
	receptacle42_chair - receptacle
	receptacle43_chair - receptacle
	receptacle44_chair - receptacle
	receptacle45_chair - receptacle
	receptacle46_chair - receptacle
	receptacle47_couch - receptacle
	receptacle48_couch - receptacle
	receptacle49_couch - receptacle
	receptacle50_couch - receptacle
	receptacle51_couch - receptacle
	receptacle91_bed - receptacle
	receptacle92_bed - receptacle
	receptacle93_bed - receptacle
	receptacle94_bed - receptacle
	receptacle95_bed - receptacle
	receptacle96_bed - receptacle
	receptacle97_dining_table - receptacle
	receptacle98_dining_table - receptacle
	receptacle99_toilet - receptacle
  )
  (:init 
	(atlocation agent location_Xneg59_Yneg69_place105_room22_floorB)
	(inanyreceptacle item103_tv_largeitem)
	(inanyreceptacle item104_tv_largeitem)
	(inanyreceptacle item10_bottle_smallitem)
	(inanyreceptacle item117_book_smallitem)
	(inanyreceptacle item118_book_smallitem)
	(inanyreceptacle item119_book_smallitem)
	(inanyreceptacle item11_bottle_smallitem)
	(inanyreceptacle item124_book_smallitem)
	(inanyreceptacle item125_book_smallitem)
	(inanyreceptacle item126_book_smallitem)
	(inanyreceptacle item127_book_smallitem)
	(inanyreceptacle item129_clock_mediumitem)
	(inanyreceptacle item12_wine_glass_smallitem)
	(inanyreceptacle item131_vase_mediumitem)
	(inanyreceptacle item132_vase_mediumitem)
	(inanyreceptacle item135_teddy_bear_mediumitem)
	(inanyreceptacle item136_teddy_bear_mediumitem)
	(inanyreceptacle item16_wine_glass_smallitem)
	(inanyreceptacle item17_cup_smallitem)
	(inanyreceptacle item18_bowl_smallitem)
	(inanyreceptacle item1_handbag_largeitem)
	(inanyreceptacle item21_bowl_smallitem)
	(inanyreceptacle item22_apple_smallitem)
	(inanyreceptacle item23_apple_smallitem)
	(inanyreceptacle item24_cake_mediumitem)
	(inanyreceptacle item27_cake_mediumitem)
	(inanyreceptacle item3_tie_smallitem)
	(inanyreceptacle item52_potted_plant_largeitem)
	(inanyreceptacle item55_potted_plant_largeitem)
	(inanyreceptacle item56_potted_plant_largeitem)
	(inanyreceptacle item61_potted_plant_largeitem)
	(inanyreceptacle item64_potted_plant_largeitem)
	(inanyreceptacle item70_potted_plant_largeitem)
	(inanyreceptacle item71_potted_plant_largeitem)
	(inanyreceptacle item72_potted_plant_largeitem)
	(inanyreceptacle item73_potted_plant_largeitem)
	(inanyreceptacle item74_potted_plant_largeitem)
	(inanyreceptacle item75_potted_plant_largeitem)
	(inanyreceptacle item76_potted_plant_largeitem)
	(inanyreceptacle item78_potted_plant_largeitem)
	(inanyreceptacle item80_potted_plant_largeitem)
	(inanyreceptacle item81_potted_plant_largeitem)
	(inanyreceptacle item82_potted_plant_largeitem)
	(inanyreceptacle item83_potted_plant_largeitem)
	(inanyreceptacle item84_potted_plant_largeitem)
	(inanyreceptacle item85_potted_plant_largeitem)
	(inanyreceptacle item86_potted_plant_largeitem)
	(inanyreceptacle item87_potted_plant_largeitem)
	(inanyreceptacle item88_potted_plant_largeitem)
	(inanyreceptacle item89_potted_plant_largeitem)
	(inanyreceptacle item90_potted_plant_largeitem)
	(inreceptacle item103_tv_largeitem receptacle46_chair)
	(inreceptacle item104_tv_largeitem receptacle48_couch)
	(inreceptacle item10_bottle_smallitem receptacle111_sink)
	(inreceptacle item117_book_smallitem receptacle93_bed)
	(inreceptacle item118_book_smallitem receptacle93_bed)
	(inreceptacle item119_book_smallitem receptacle93_bed)
	(inreceptacle item11_bottle_smallitem receptacle114_sink)
	(inreceptacle item124_book_smallitem receptacle29_chair)
	(inreceptacle item125_book_smallitem receptacle105_oven)
	(inreceptacle item126_book_smallitem receptacle44_chair)
	(inreceptacle item127_book_smallitem receptacle44_chair)
	(inreceptacle item129_clock_mediumitem receptacle115_refrigerator)
	(inreceptacle item12_wine_glass_smallitem receptacle97_dining_table)
	(inreceptacle item131_vase_mediumitem receptacle107_sink)
	(inreceptacle item132_vase_mediumitem receptacle93_bed)
	(inreceptacle item135_teddy_bear_mediumitem receptacle96_bed)
	(inreceptacle item136_teddy_bear_mediumitem receptacle96_bed)
	(inreceptacle item16_wine_glass_smallitem receptacle97_dining_table)
	(inreceptacle item17_cup_smallitem receptacle44_chair)
	(inreceptacle item18_bowl_smallitem receptacle109_sink)
	(inreceptacle item1_handbag_largeitem receptacle94_bed)
	(inreceptacle item21_bowl_smallitem receptacle44_chair)
	(inreceptacle item22_apple_smallitem receptacle41_chair)
	(inreceptacle item23_apple_smallitem receptacle41_chair)
	(inreceptacle item24_cake_mediumitem receptacle93_bed)
	(inreceptacle item27_cake_mediumitem receptacle101_toilet)
	(inreceptacle item3_tie_smallitem receptacle94_bed)
	(inreceptacle item52_potted_plant_largeitem receptacle107_sink)
	(inreceptacle item55_potted_plant_largeitem receptacle33_chair)
	(inreceptacle item56_potted_plant_largeitem receptacle32_chair)
	(inreceptacle item61_potted_plant_largeitem receptacle97_dining_table)
	(inreceptacle item64_potted_plant_largeitem receptacle98_dining_table)
	(inreceptacle item70_potted_plant_largeitem receptacle38_chair)
	(inreceptacle item71_potted_plant_largeitem receptacle108_sink)
	(inreceptacle item72_potted_plant_largeitem receptacle110_sink)
	(inreceptacle item73_potted_plant_largeitem receptacle93_bed)
	(inreceptacle item74_potted_plant_largeitem receptacle93_bed)
	(inreceptacle item75_potted_plant_largeitem receptacle48_couch)
	(inreceptacle item76_potted_plant_largeitem receptacle48_couch)
	(inreceptacle item78_potted_plant_largeitem receptacle105_oven)
	(inreceptacle item80_potted_plant_largeitem receptacle112_sink)
	(inreceptacle item81_potted_plant_largeitem receptacle112_sink)
	(inreceptacle item82_potted_plant_largeitem receptacle100_toilet)
	(inreceptacle item83_potted_plant_largeitem receptacle100_toilet)
	(inreceptacle item84_potted_plant_largeitem receptacle100_toilet)
	(inreceptacle item85_potted_plant_largeitem receptacle114_sink)
	(inreceptacle item86_potted_plant_largeitem receptacle106_oven)
	(inreceptacle item87_potted_plant_largeitem receptacle51_couch)
	(inreceptacle item88_potted_plant_largeitem receptacle51_couch)
	(inreceptacle item89_potted_plant_largeitem receptacle50_couch)
	(inreceptacle item90_potted_plant_largeitem receptacle37_chair)
	(itematlocation item102_tv_largeitem location_Xneg9_Ypos22_place55_room18_floorA)
	(itematlocation item103_tv_largeitem location_Xpos33_Yneg85_place78_room20_floorB)
	(itematlocation item104_tv_largeitem location_Xneg27_Ypos22_place80_room18_floorA)
	(itematlocation item10_bottle_smallitem location_Xneg19_Ypos5_place101_room2_floorB)
	(itematlocation item117_book_smallitem location_Xneg59_Ypos5_place86_room7_floorB)
	(itematlocation item118_book_smallitem location_Xneg58_Ypos5_place86_room7_floorB)
	(itematlocation item119_book_smallitem location_Xneg57_Ypos4_place86_room7_floorB)
	(itematlocation item11_bottle_smallitem location_Xpos14_Ypos10_place104_room1_floorA)
	(itematlocation item120_book_smallitem location_Xneg49_Ypos24_place56_room18_floorA)
	(itematlocation item121_book_smallitem location_Xneg18_Ypos24_place57_room18_floorA)
	(itematlocation item122_book_smallitem location_Xneg19_Ypos24_place58_room18_floorA)
	(itematlocation item123_book_smallitem location_Xneg17_Ypos24_place59_room18_floorA)
	(itematlocation item124_book_smallitem location_Xpos18_Ypos7_place61_room14_floorA)
	(itematlocation item125_book_smallitem location_Xneg21_Yneg80_place95_room17_floorA)
	(itematlocation item126_book_smallitem location_Xneg18_Yneg67_place76_room15_floorA)
	(itematlocation item127_book_smallitem location_Xneg17_Yneg67_place76_room15_floorA)
	(itematlocation item128_book_smallitem location_Xneg41_Ypos24_place22_room18_floorA)
	(itematlocation item129_clock_mediumitem location_Xneg59_Yneg69_place105_room22_floorB)
	(itematlocation item12_wine_glass_smallitem location_Xpos37_Yneg53_place90_room12_floorA)
	(itematlocation item130_clock_mediumitem location_Xneg16_Yneg39_place24_room21_floorA)
	(itematlocation item131_vase_mediumitem location_Xneg58_Yneg58_place97_room22_floorB)
	(itematlocation item132_vase_mediumitem location_Xneg45_Ypos25_place86_room7_floorB)
	(itematlocation item133_vase_mediumitem location_Xneg21_Yneg35_place31_room10_floorA)
	(itematlocation item134_vase_mediumitem location_Xpos56_Yneg63_place32_room20_floorB)
	(itematlocation item135_teddy_bear_mediumitem location_Xneg13_Ypos24_place89_room6_floorB)
	(itematlocation item136_teddy_bear_mediumitem location_Xneg13_Ypos22_place89_room6_floorB)
	(itematlocation item13_wine_glass_smallitem location_Xpos7_Yneg68_place33_room16_floorA)
	(itematlocation item14_wine_glass_smallitem location_Xpos3_Yneg68_place34_room16_floorA)
	(itematlocation item15_wine_glass_smallitem location_Xneg3_Yneg68_place35_room16_floorA)
	(itematlocation item16_wine_glass_smallitem location_Xpos31_Yneg53_place90_room12_floorA)
	(itematlocation item17_cup_smallitem location_Xneg12_Yneg68_place76_room15_floorA)
	(itematlocation item18_bowl_smallitem location_Xneg17_Yneg120_place99_room3_floorB)
	(itematlocation item19_bowl_smallitem location_Xpos7_Yneg68_place36_room16_floorA)
	(itematlocation item1_handbag_largeitem location_Xneg42_Yneg80_place87_room8_floorB)
	(itematlocation item20_bowl_smallitem location_Xneg16_Yneg35_place37_room10_floorA)
	(itematlocation item21_bowl_smallitem location_Xneg19_Yneg68_place76_room15_floorA)
	(itematlocation item22_apple_smallitem location_Xneg44_Yneg78_place73_room17_floorA)
	(itematlocation item23_apple_smallitem location_Xneg41_Yneg76_place73_room17_floorA)
	(itematlocation item24_cake_mediumitem location_Xneg59_Ypos4_place86_room7_floorB)
	(itematlocation item25_cake_mediumitem location_Xpos9_Yneg104_place38_room9_floorB)
	(itematlocation item26_cake_mediumitem location_Xpos10_Yneg93_place39_room9_floorB)
	(itematlocation item27_cake_mediumitem location_Xneg18_Yneg85_place94_room3_floorB)
	(itematlocation item2_tie_smallitem location_Xneg64_Yneg90_place23_room8_floorB)
	(itematlocation item3_tie_smallitem location_Xneg59_Yneg82_place87_room8_floorB)
	(itematlocation item4_tie_smallitem location_Xpos26_Yneg95_place25_room9_floorB)
	(itematlocation item52_potted_plant_largeitem location_Xneg68_Yneg64_place97_room22_floorB)
	(itematlocation item53_potted_plant_largeitem location_Xneg44_Yneg36_place40_room4_floorB)
	(itematlocation item54_potted_plant_largeitem location_Xpos50_Ypos14_place41_room14_floorA)
	(itematlocation item55_potted_plant_largeitem location_Xpos51_Yneg66_place65_room12_floorA)
	(itematlocation item56_potted_plant_largeitem location_Xpos19_Yneg41_place64_room12_floorA)
	(itematlocation item57_potted_plant_largeitem location_Xpos18_Yneg37_place42_room12_floorA)
	(itematlocation item58_potted_plant_largeitem location_Xpos13_Yneg40_place43_room12_floorA)
	(itematlocation item59_potted_plant_largeitem location_Xpos11_Yneg40_place44_room12_floorA)
	(itematlocation item5_tie_smallitem location_Xpos12_Yneg107_place26_room9_floorB)
	(itematlocation item60_potted_plant_largeitem location_Xpos15_Yneg32_place45_room19_floorA)
	(itematlocation item61_potted_plant_largeitem location_Xpos34_Yneg53_place90_room12_floorA)
	(itematlocation item62_potted_plant_largeitem location_Xneg8_Yneg67_place46_room16_floorA)
	(itematlocation item63_potted_plant_largeitem location_Xneg10_Yneg66_place47_room16_floorA)
	(itematlocation item64_potted_plant_largeitem location_Xpos19_Ypos4_place91_room14_floorA)
	(itematlocation item65_potted_plant_largeitem location_Xneg26_Yneg35_place48_room10_floorA)
	(itematlocation item66_potted_plant_largeitem location_Xneg21_Yneg37_place49_room10_floorA)
	(itematlocation item67_potted_plant_largeitem location_Xneg12_Yneg37_place50_room10_floorA)
	(itematlocation item68_potted_plant_largeitem location_Xneg16_Yneg36_place51_room10_floorA)
	(itematlocation item69_potted_plant_largeitem location_Xneg16_Yneg39_place52_room21_floorA)
	(itematlocation item6_tie_smallitem location_Xpos10_Yneg103_place27_room9_floorB)
	(itematlocation item70_potted_plant_largeitem location_Xneg77_Yneg50_place70_room13_floorA)
	(itematlocation item71_potted_plant_largeitem location_Xpos1_Yneg123_place98_room3_floorB)
	(itematlocation item72_potted_plant_largeitem location_Xpos5_Yneg93_place100_room3_floorB)
	(itematlocation item73_potted_plant_largeitem location_Xneg46_Ypos25_place86_room7_floorB)
	(itematlocation item74_potted_plant_largeitem location_Xneg46_Ypos24_place86_room7_floorB)
	(itematlocation item75_potted_plant_largeitem location_Xneg25_Ypos4_place80_room18_floorA)
	(itematlocation item76_potted_plant_largeitem location_Xneg25_Ypos5_place80_room18_floorA)
	(itematlocation item77_potted_plant_largeitem location_Xneg45_Ypos24_place53_room18_floorA)
	(itematlocation item78_potted_plant_largeitem location_Xneg23_Yneg84_place95_room17_floorA)
	(itematlocation item79_potted_plant_largeitem location_Xneg55_Yneg97_place54_room5_floorB)
	(itematlocation item7_tie_smallitem location_Xpos9_Yneg103_place28_room9_floorB)
	(itematlocation item80_potted_plant_largeitem location_Xneg66_Yneg84_place102_room17_floorA)
	(itematlocation item81_potted_plant_largeitem location_Xneg66_Yneg69_place102_room17_floorA)
	(itematlocation item82_potted_plant_largeitem location_Xpos2_Ypos20_place93_room1_floorA)
	(itematlocation item83_potted_plant_largeitem location_Xpos0_Ypos15_place93_room1_floorA)
	(itematlocation item84_potted_plant_largeitem location_Xpos0_Ypos19_place93_room1_floorA)
	(itematlocation item85_potted_plant_largeitem location_Xpos1_Ypos12_place104_room1_floorA)
	(itematlocation item86_potted_plant_largeitem location_Xneg41_Yneg96_place96_room17_floorA)
	(itematlocation item87_potted_plant_largeitem location_Xpos31_Yneg38_place83_room20_floorB)
	(itematlocation item88_potted_plant_largeitem location_Xpos32_Yneg42_place83_room20_floorB)
	(itematlocation item89_potted_plant_largeitem location_Xpos30_Yneg40_place82_room20_floorB)
	(itematlocation item8_tie_smallitem location_Xpos25_Yneg115_place29_room3_floorB)
	(itematlocation item90_potted_plant_largeitem location_Xneg68_Yneg33_place69_room13_floorA)
	(itematlocation item9_bottle_smallitem location_Xneg3_Yneg68_place30_room16_floorA)
	(receptacleatlocation receptacle100_toilet location_Xpos12_Ypos22_place93_room1_floorA)
	(receptacleatlocation receptacle101_toilet location_Xneg15_Yneg85_place94_room3_floorB)
	(receptacleatlocation receptacle105_oven location_Xneg26_Yneg74_place95_room17_floorA)
	(receptacleatlocation receptacle106_oven location_Xneg51_Yneg95_place96_room17_floorA)
	(receptacleatlocation receptacle107_sink location_Xneg65_Yneg63_place97_room22_floorB)
	(receptacleatlocation receptacle108_sink location_Xneg7_Yneg129_place98_room3_floorB)
	(receptacleatlocation receptacle109_sink location_Xneg16_Yneg115_place99_room3_floorB)
	(receptacleatlocation receptacle110_sink location_Xpos4_Yneg99_place100_room3_floorB)
	(receptacleatlocation receptacle111_sink location_Xneg21_Ypos8_place101_room2_floorB)
	(receptacleatlocation receptacle112_sink location_Xneg65_Yneg76_place102_room17_floorA)
	(receptacleatlocation receptacle113_sink location_Xpos13_Ypos8_place103_room1_floorA)
	(receptacleatlocation receptacle114_sink location_Xpos12_Ypos7_place104_room1_floorA)
	(receptacleatlocation receptacle115_refrigerator location_Xneg54_Yneg70_place105_room22_floorB)
	(receptacleatlocation receptacle116_refrigerator location_Xneg63_Yneg56_place106_room17_floorA)
	(receptacleatlocation receptacle28_chair location_Xpos30_Ypos2_place60_room14_floorA)
	(receptacleatlocation receptacle29_chair location_Xpos22_Ypos17_place61_room14_floorA)
	(receptacleatlocation receptacle30_chair location_Xpos29_Ypos12_place62_room14_floorA)
	(receptacleatlocation receptacle31_chair location_Xpos34_Yneg49_place63_room12_floorA)
	(receptacleatlocation receptacle32_chair location_Xpos28_Yneg55_place64_room12_floorA)
	(receptacleatlocation receptacle33_chair location_Xpos43_Yneg53_place65_room12_floorA)
	(receptacleatlocation receptacle34_chair location_Xpos37_Yneg57_place66_room12_floorA)
	(receptacleatlocation receptacle35_chair location_Xneg62_Yneg37_place67_room13_floorA)
	(receptacleatlocation receptacle36_chair location_Xneg63_Yneg29_place68_room13_floorA)
	(receptacleatlocation receptacle37_chair location_Xneg71_Yneg29_place69_room13_floorA)
	(receptacleatlocation receptacle38_chair location_Xneg71_Yneg37_place70_room13_floorA)
	(receptacleatlocation receptacle39_chair location_Xneg67_Yneg34_place71_room13_floorA)
	(receptacleatlocation receptacle40_chair location_Xpos1_Yneg106_place72_room3_floorB)
	(receptacleatlocation receptacle41_chair location_Xneg38_Yneg66_place73_room17_floorA)
	(receptacleatlocation receptacle42_chair location_Xneg31_Ypos26_place74_room2_floorB)
	(receptacleatlocation receptacle43_chair location_Xpos51_Yneg7_place75_room14_floorA)
	(receptacleatlocation receptacle44_chair location_Xneg19_Yneg66_place76_room15_floorA)
	(receptacleatlocation receptacle45_chair location_Xneg20_Yneg32_place77_room11_floorB)
	(receptacleatlocation receptacle46_chair location_Xpos21_Yneg84_place78_room20_floorB)
	(receptacleatlocation receptacle47_couch location_Xneg19_Yneg4_place79_room18_floorA)
	(receptacleatlocation receptacle48_couch location_Xneg25_Ypos4_place80_room18_floorA)
	(receptacleatlocation receptacle49_couch location_Xneg63_Yneg118_place81_room5_floorB)
	(receptacleatlocation receptacle50_couch location_Xpos19_Yneg47_place82_room20_floorB)
	(receptacleatlocation receptacle51_couch location_Xpos43_Yneg47_place83_room20_floorB)
	(receptacleatlocation receptacle91_bed location_Xneg65_Yneg28_place84_room4_floorB)
	(receptacleatlocation receptacle92_bed location_Xneg45_Yneg124_place85_room5_floorB)
	(receptacleatlocation receptacle93_bed location_Xneg57_Ypos15_place86_room7_floorB)
	(receptacleatlocation receptacle94_bed location_Xneg47_Yneg79_place87_room8_floorB)
	(receptacleatlocation receptacle95_bed location_Xpos5_Ypos19_place88_room6_floorB)
	(receptacleatlocation receptacle96_bed location_Xneg5_Ypos15_place89_room6_floorB)
	(receptacleatlocation receptacle97_dining_table location_Xpos34_Yneg53_place90_room12_floorA)
	(receptacleatlocation receptacle98_dining_table location_Xpos28_Ypos6_place91_room14_floorA)
	(receptacleatlocation receptacle99_toilet location_Xneg22_Ypos19_place92_room2_floorB)
	(receptacleopeningtype receptacle105_oven)
	(receptacleopeningtype receptacle106_oven)
	(receptacleopeningtype receptacle115_refrigerator)
	(receptacleopeningtype receptacle116_refrigerator)
  )
  (:goal (and
	(inreceptacle item23_apple_smallitem receptacle92_bed)
	(inreceptacle item76_potted_plant_largeitem receptacle94_bed)
	(inreceptacle item26_cake_mediumitem receptacle30_chair)
	(inreceptacle item62_potted_plant_largeitem receptacle33_chair)
	(inreceptacle item129_clock_mediumitem receptacle51_couch)
	(inreceptacle item89_potted_plant_largeitem receptacle101_toilet)
	(inreceptacle item4_tie_smallitem receptacle40_chair)
	(inreceptacle item9_bottle_smallitem receptacle99_toilet)
	(inreceptacle item84_potted_plant_largeitem receptacle41_chair)
	(inreceptacle item71_potted_plant_largeitem receptacle51_couch)))
)
