
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_book_smallitem - item
	item11_book_smallitem - item
	item12_book_smallitem - item
	item13_bottle_smallitem - item
	item14_bottle_smallitem - item
	item15_bottle_smallitem - item
	item16_vase_mediumitem - item
	item17_bowl_smallitem - item
	item18_bowl_smallitem - item
	item19_bowl_smallitem - item
	item20_toothbrush_smallitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item8_book_smallitem - item
	item9_book_smallitem - item
	location_Xneg17_Yneg79_place19_room1_floorA - location
	location_Xneg18_Yneg70_place20_room2_floorA - location
	location_Xneg18_Yneg70_place21_room2_floorA - location
	location_Xneg1_Yneg30_place29_room3_floorA - location
	location_Xneg20_Yneg31_place29_room3_floorA - location
	location_Xneg22_Yneg91_place19_room1_floorA - location
	location_Xneg24_Yneg54_place9_room3_floorA - location
	location_Xneg25_Yneg55_place10_room3_floorA - location
	location_Xneg25_Yneg55_place11_room3_floorA - location
	location_Xneg26_Yneg66_place17_room2_floorA - location
	location_Xneg6_Yneg71_place15_room2_floorA - location
	location_Xneg6_Yneg78_place16_room1_floorA - location
	location_Xneg7_Yneg73_place15_room2_floorA - location
	location_Xneg9_Yneg76_place16_room1_floorA - location
	location_Xpos0_Yneg75_place15_room2_floorA - location
	location_Xpos20_Yneg55_place18_room10_floorA - location
	location_Xpos30_Yneg97_place7_room4_floorA - location
	location_Xpos32_Yneg33_place24_room10_floorA - location
	location_Xpos34_Yneg97_place30_room4_floorA - location
	location_Xpos38_Yneg58_place13_room10_floorA - location
	location_Xpos39_Yneg1_place27_room11_floorA - location
	location_Xpos39_Yneg41_place14_room10_floorA - location
	location_Xpos39_Yneg59_place12_room10_floorA - location
	location_Xpos39_Yneg6_place25_room11_floorA - location
	location_Xpos40_Ypos10_place28_room11_floorA - location
	location_Xpos41_Ypos10_place27_room11_floorA - location
	location_Xpos41_Ypos11_place28_room11_floorA - location
	location_Xpos44_Yneg18_place25_room11_floorA - location
	location_Xpos46_Yneg35_place26_room10_floorA - location
	location_Xpos46_Yneg61_place13_room10_floorA - location
	location_Xpos48_Yneg83_place30_room4_floorA - location
	location_Xpos51_Yneg60_place12_room10_floorA - location
	location_Xpos56_Yneg2_place8_room11_floorA - location
	location_Xpos7_Yneg12_place23_room9_floorA - location
	location_Xpos7_Yneg24_place22_room9_floorA - location
	location_Xpos8_Yneg18_place31_room9_floorA - location
	location_Xpos8_Yneg18_place32_room9_floorA - location
	receptacle1_microwave - receptacle
	receptacle21_toilet - receptacle
	receptacle22_toilet - receptacle
	receptacle23_toilet - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_couch - receptacle
	receptacle2_oven - receptacle
	receptacle30_couch - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_dining_table - receptacle
	receptacle37_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xpos44_Yneg18_place25_room11_floorA)
	(inanyreceptacle item10_book_smallitem)
	(inanyreceptacle item11_book_smallitem)
	(inanyreceptacle item14_bottle_smallitem)
	(inanyreceptacle item15_bottle_smallitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item20_toothbrush_smallitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item8_book_smallitem)
	(inanyreceptacle item9_book_smallitem)
	(inreceptacle item10_book_smallitem receptacle30_couch)
	(inreceptacle item11_book_smallitem receptacle35_bed)
	(inreceptacle item14_bottle_smallitem receptacle5_sink)
	(inreceptacle item15_bottle_smallitem receptacle4_sink)
	(inreceptacle item16_vase_mediumitem receptacle4_sink)
	(inreceptacle item20_toothbrush_smallitem receptacle21_toilet)
	(inreceptacle item31_potted_plant_largeitem receptacle1_microwave)
	(inreceptacle item32_potted_plant_largeitem receptacle34_bed)
	(inreceptacle item33_potted_plant_largeitem receptacle29_couch)
	(inreceptacle item8_book_smallitem receptacle2_oven)
	(inreceptacle item9_book_smallitem receptacle27_chair)
	(itematlocation item10_book_smallitem location_Xpos40_Ypos10_place28_room11_floorA)
	(itematlocation item11_book_smallitem location_Xpos34_Yneg97_place30_room4_floorA)
	(itematlocation item12_book_smallitem location_Xpos30_Yneg97_place7_room4_floorA)
	(itematlocation item13_bottle_smallitem location_Xpos56_Yneg2_place8_room11_floorA)
	(itematlocation item14_bottle_smallitem location_Xneg9_Yneg76_place16_room1_floorA)
	(itematlocation item15_bottle_smallitem location_Xneg7_Yneg73_place15_room2_floorA)
	(itematlocation item16_vase_mediumitem location_Xpos0_Yneg75_place15_room2_floorA)
	(itematlocation item17_bowl_smallitem location_Xneg24_Yneg54_place9_room3_floorA)
	(itematlocation item18_bowl_smallitem location_Xneg25_Yneg55_place10_room3_floorA)
	(itematlocation item19_bowl_smallitem location_Xneg25_Yneg55_place11_room3_floorA)
	(itematlocation item20_toothbrush_smallitem location_Xneg22_Yneg91_place19_room1_floorA)
	(itematlocation item31_potted_plant_largeitem location_Xpos51_Yneg60_place12_room10_floorA)
	(itematlocation item32_potted_plant_largeitem location_Xneg1_Yneg30_place29_room3_floorA)
	(itematlocation item33_potted_plant_largeitem location_Xpos39_Yneg1_place27_room11_floorA)
	(itematlocation item8_book_smallitem location_Xpos46_Yneg61_place13_room10_floorA)
	(itematlocation item9_book_smallitem location_Xpos39_Yneg6_place25_room11_floorA)
	(receptacleatlocation receptacle1_microwave location_Xpos39_Yneg59_place12_room10_floorA)
	(receptacleatlocation receptacle21_toilet location_Xneg17_Yneg79_place19_room1_floorA)
	(receptacleatlocation receptacle22_toilet location_Xneg18_Yneg70_place20_room2_floorA)
	(receptacleatlocation receptacle23_toilet location_Xneg18_Yneg70_place21_room2_floorA)
	(receptacleatlocation receptacle24_chair location_Xpos7_Yneg24_place22_room9_floorA)
	(receptacleatlocation receptacle25_chair location_Xpos7_Yneg12_place23_room9_floorA)
	(receptacleatlocation receptacle26_chair location_Xpos32_Yneg33_place24_room10_floorA)
	(receptacleatlocation receptacle27_chair location_Xpos44_Yneg18_place25_room11_floorA)
	(receptacleatlocation receptacle28_chair location_Xpos46_Yneg35_place26_room10_floorA)
	(receptacleatlocation receptacle29_couch location_Xpos41_Ypos10_place27_room11_floorA)
	(receptacleatlocation receptacle2_oven location_Xpos38_Yneg58_place13_room10_floorA)
	(receptacleatlocation receptacle30_couch location_Xpos41_Ypos11_place28_room11_floorA)
	(receptacleatlocation receptacle34_bed location_Xneg20_Yneg31_place29_room3_floorA)
	(receptacleatlocation receptacle35_bed location_Xpos48_Yneg83_place30_room4_floorA)
	(receptacleatlocation receptacle36_dining_table location_Xpos8_Yneg18_place31_room9_floorA)
	(receptacleatlocation receptacle37_dining_table location_Xpos8_Yneg18_place32_room9_floorA)
	(receptacleatlocation receptacle3_sink location_Xpos39_Yneg41_place14_room10_floorA)
	(receptacleatlocation receptacle4_sink location_Xneg6_Yneg71_place15_room2_floorA)
	(receptacleatlocation receptacle5_sink location_Xneg6_Yneg78_place16_room1_floorA)
	(receptacleatlocation receptacle6_sink location_Xneg26_Yneg66_place17_room2_floorA)
	(receptacleatlocation receptacle7_refrigerator location_Xpos20_Yneg55_place18_room10_floorA)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle7_refrigerator)
  )
  (:goal (and
	(inreceptacle item14_bottle_smallitem receptacle23_toilet)
	(inreceptacle item8_book_smallitem receptacle6_sink)
	(inreceptacle item15_bottle_smallitem receptacle34_bed)
	(inreceptacle item31_potted_plant_largeitem receptacle25_chair)
	(inreceptacle item32_potted_plant_largeitem receptacle37_dining_table)
	(inreceptacle item11_book_smallitem receptacle6_sink)
	(inreceptacle item16_vase_mediumitem receptacle21_toilet)
	(inreceptacle item10_book_smallitem receptacle37_dining_table)
	(inreceptacle item20_toothbrush_smallitem receptacle29_couch)
	(inreceptacle item12_book_smallitem receptacle1_microwave)))
)
