
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_cup_smallitem - item
	item11_cup_smallitem - item
	item12_cup_smallitem - item
	item13_cup_smallitem - item
	item14_bowl_smallitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item46_laptop_mediumitem - item
	item59_book_smallitem - item
	item5_bottle_smallitem - item
	item60_book_smallitem - item
	item61_vase_mediumitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item8_bottle_smallitem - item
	item9_cup_smallitem - item
	location_Xneg10_Yneg11_place15_room13_floorB - location
	location_Xneg10_Ypos26_place37_room14_floorB - location
	location_Xneg12_Ypos16_place47_room14_floorB - location
	location_Xneg12_Ypos26_place39_room14_floorB - location
	location_Xneg16_Yneg10_place17_room13_floorB - location
	location_Xneg20_Ypos34_place42_room14_floorB - location
	location_Xneg29_Ypos14_place47_room14_floorB - location
	location_Xneg30_Ypos14_place47_room14_floorB - location
	location_Xneg30_Ypos21_place42_room14_floorB - location
	location_Xneg31_Ypos29_place42_room14_floorB - location
	location_Xneg36_Ypos16_place22_room15_floorB - location
	location_Xneg36_Ypos22_place21_room15_floorB - location
	location_Xneg3_Yneg10_place14_room13_floorB - location
	location_Xneg41_Yneg10_place24_room6_floorC - location
	location_Xneg44_Ypos21_place28_room6_floorC - location
	location_Xneg45_Yneg10_place13_room15_floorB - location
	location_Xneg54_Ypos5_place25_room15_floorB - location
	location_Xneg55_Ypos20_place25_room15_floorB - location
	location_Xneg60_Yneg10_place16_room15_floorB - location
	location_Xneg67_Ypos31_place23_room15_floorB - location
	location_Xneg9_Yneg15_place33_room13_floorB - location
	location_Xneg9_Yneg16_place18_room13_floorB - location
	location_Xneg9_Yneg4_place19_room13_floorB - location
	location_Xneg9_Yneg9_place32_room13_floorB - location
	location_Xpos10_Yneg7_place48_room8_floorB - location
	location_Xpos15_Ypos24_place12_room1_floorA - location
	location_Xpos20_Yneg10_place38_room18_floorA - location
	location_Xpos22_Yneg8_place43_room3_floorC - location
	location_Xpos27_Ypos24_place36_room3_floorC - location
	location_Xpos27_Ypos26_place34_room1_floorA - location
	location_Xpos28_Ypos15_place46_room3_floorC - location
	location_Xpos28_Ypos19_place40_room1_floorA - location
	location_Xpos28_Ypos25_place35_room2_floorB - location
	location_Xpos28_Ypos2_place45_room3_floorC - location
	location_Xpos29_Yneg13_place43_room3_floorC - location
	location_Xpos29_Ypos16_place41_room2_floorB - location
	location_Xpos30_Ypos16_place40_room1_floorA - location
	location_Xpos30_Ypos20_place40_room1_floorA - location
	location_Xpos30_Ypos22_place40_room1_floorA - location
	location_Xpos30_Ypos5_place44_room3_floorC - location
	location_Xpos30_Ypos9_place44_room3_floorC - location
	location_Xpos31_Ypos14_place41_room2_floorB - location
	location_Xpos31_Ypos19_place41_room2_floorB - location
	location_Xpos31_Ypos2_place44_room3_floorC - location
	location_Xpos49_Ypos26_place27_room5_floorB - location
	location_Xpos51_Ypos27_place26_room4_floorA - location
	location_Xpos56_Ypos1_place30_room4_floorA - location
	location_Xpos56_Ypos2_place31_room4_floorA - location
	location_Xpos57_Ypos0_place30_room4_floorA - location
	location_Xpos57_Ypos2_place31_room4_floorA - location
	location_Xpos57_Ypos7_place31_room4_floorA - location
	location_Xpos58_Ypos5_place31_room4_floorA - location
	location_Xpos58_Ypos6_place31_room4_floorA - location
	location_Xpos59_Ypos3_place31_room4_floorA - location
	location_Xpos60_Ypos9_place29_room4_floorA - location
	location_Xpos63_Ypos1_place20_room5_floorB - location
	location_Xpos64_Ypos1_place11_room4_floorA - location
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_couch - receptacle
	receptacle35_bed - receptacle
	receptacle36_bed - receptacle
	receptacle37_bed - receptacle
	receptacle38_dining_table - receptacle
	receptacle39_dining_table - receptacle
	receptacle40_dining_table - receptacle
	receptacle41_dining_table - receptacle
	receptacle42_dining_table - receptacle
	receptacle43_toilet - receptacle
	receptacle44_toilet - receptacle
	receptacle45_toilet - receptacle
	receptacle47_microwave - receptacle
	receptacle48_oven - receptacle
	receptacle49_oven - receptacle
	receptacle50_sink - receptacle
	receptacle51_sink - receptacle
	receptacle52_sink - receptacle
	receptacle53_sink - receptacle
	receptacle54_sink - receptacle
	receptacle55_sink - receptacle
	receptacle56_sink - receptacle
	receptacle57_refrigerator - receptacle
	receptacle58_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg30_Ypos14_place47_room14_floorB)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item11_cup_smallitem)
	(inanyreceptacle item12_cup_smallitem)
	(inanyreceptacle item13_cup_smallitem)
	(inanyreceptacle item14_bowl_smallitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item46_laptop_mediumitem)
	(inanyreceptacle item59_book_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item60_book_smallitem)
	(inanyreceptacle item61_vase_mediumitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inreceptacle item10_cup_smallitem receptacle40_dining_table)
	(inreceptacle item11_cup_smallitem receptacle40_dining_table)
	(inreceptacle item12_cup_smallitem receptacle40_dining_table)
	(inreceptacle item13_cup_smallitem receptacle39_dining_table)
	(inreceptacle item14_bowl_smallitem receptacle52_sink)
	(inreceptacle item30_potted_plant_largeitem receptacle50_sink)
	(inreceptacle item31_potted_plant_largeitem receptacle57_refrigerator)
	(inreceptacle item32_potted_plant_largeitem receptacle29_couch)
	(inreceptacle item33_potted_plant_largeitem receptacle53_sink)
	(inreceptacle item34_potted_plant_largeitem receptacle54_sink)
	(inreceptacle item46_laptop_mediumitem receptacle40_dining_table)
	(inreceptacle item59_book_smallitem receptacle40_dining_table)
	(inreceptacle item5_bottle_smallitem receptacle50_sink)
	(inreceptacle item60_book_smallitem receptacle52_sink)
	(inreceptacle item61_vase_mediumitem receptacle57_refrigerator)
	(inreceptacle item6_bottle_smallitem receptacle51_sink)
	(inreceptacle item7_bottle_smallitem receptacle51_sink)
	(inreceptacle item8_bottle_smallitem receptacle54_sink)
	(inreceptacle item9_cup_smallitem receptacle50_sink)
	(itematlocation item10_cup_smallitem location_Xpos58_Ypos6_place31_room4_floorA)
	(itematlocation item11_cup_smallitem location_Xpos57_Ypos2_place31_room4_floorA)
	(itematlocation item12_cup_smallitem location_Xpos59_Ypos3_place31_room4_floorA)
	(itematlocation item13_cup_smallitem location_Xpos57_Ypos0_place30_room4_floorA)
	(itematlocation item14_bowl_smallitem location_Xneg30_Ypos21_place42_room14_floorB)
	(itematlocation item30_potted_plant_largeitem location_Xpos30_Ypos16_place40_room1_floorA)
	(itematlocation item31_potted_plant_largeitem location_Xneg30_Ypos14_place47_room14_floorB)
	(itematlocation item32_potted_plant_largeitem location_Xneg55_Ypos20_place25_room15_floorB)
	(itematlocation item33_potted_plant_largeitem location_Xpos29_Yneg13_place43_room3_floorC)
	(itematlocation item34_potted_plant_largeitem location_Xpos30_Ypos9_place44_room3_floorC)
	(itematlocation item46_laptop_mediumitem location_Xpos57_Ypos7_place31_room4_floorA)
	(itematlocation item59_book_smallitem location_Xpos56_Ypos2_place31_room4_floorA)
	(itematlocation item5_bottle_smallitem location_Xpos30_Ypos20_place40_room1_floorA)
	(itematlocation item60_book_smallitem location_Xneg31_Ypos29_place42_room14_floorB)
	(itematlocation item61_vase_mediumitem location_Xneg29_Ypos14_place47_room14_floorB)
	(itematlocation item6_bottle_smallitem location_Xpos31_Ypos19_place41_room2_floorB)
	(itematlocation item7_bottle_smallitem location_Xpos31_Ypos14_place41_room2_floorB)
	(itematlocation item8_bottle_smallitem location_Xpos30_Ypos5_place44_room3_floorC)
	(itematlocation item9_cup_smallitem location_Xpos30_Ypos22_place40_room1_floorA)
	(receptacleatlocation receptacle15_chair location_Xpos64_Ypos1_place11_room4_floorA)
	(receptacleatlocation receptacle16_chair location_Xpos15_Ypos24_place12_room1_floorA)
	(receptacleatlocation receptacle17_chair location_Xneg45_Yneg10_place13_room15_floorB)
	(receptacleatlocation receptacle18_chair location_Xneg3_Yneg10_place14_room13_floorB)
	(receptacleatlocation receptacle19_chair location_Xneg10_Yneg11_place15_room13_floorB)
	(receptacleatlocation receptacle20_chair location_Xneg60_Yneg10_place16_room15_floorB)
	(receptacleatlocation receptacle21_chair location_Xneg16_Yneg10_place17_room13_floorB)
	(receptacleatlocation receptacle22_chair location_Xneg9_Yneg16_place18_room13_floorB)
	(receptacleatlocation receptacle23_chair location_Xneg9_Yneg4_place19_room13_floorB)
	(receptacleatlocation receptacle24_chair location_Xpos63_Ypos1_place20_room5_floorB)
	(receptacleatlocation receptacle25_chair location_Xneg36_Ypos22_place21_room15_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg36_Ypos16_place22_room15_floorB)
	(receptacleatlocation receptacle27_chair location_Xneg67_Ypos31_place23_room15_floorB)
	(receptacleatlocation receptacle28_chair location_Xneg41_Yneg10_place24_room6_floorC)
	(receptacleatlocation receptacle29_couch location_Xneg54_Ypos5_place25_room15_floorB)
	(receptacleatlocation receptacle35_bed location_Xpos51_Ypos27_place26_room4_floorA)
	(receptacleatlocation receptacle36_bed location_Xpos49_Ypos26_place27_room5_floorB)
	(receptacleatlocation receptacle37_bed location_Xneg44_Ypos21_place28_room6_floorC)
	(receptacleatlocation receptacle38_dining_table location_Xpos60_Ypos9_place29_room4_floorA)
	(receptacleatlocation receptacle39_dining_table location_Xpos56_Ypos1_place30_room4_floorA)
	(receptacleatlocation receptacle40_dining_table location_Xpos58_Ypos5_place31_room4_floorA)
	(receptacleatlocation receptacle41_dining_table location_Xneg9_Yneg9_place32_room13_floorB)
	(receptacleatlocation receptacle42_dining_table location_Xneg9_Yneg15_place33_room13_floorB)
	(receptacleatlocation receptacle43_toilet location_Xpos27_Ypos26_place34_room1_floorA)
	(receptacleatlocation receptacle44_toilet location_Xpos28_Ypos25_place35_room2_floorB)
	(receptacleatlocation receptacle45_toilet location_Xpos27_Ypos24_place36_room3_floorC)
	(receptacleatlocation receptacle47_microwave location_Xneg10_Ypos26_place37_room14_floorB)
	(receptacleatlocation receptacle48_oven location_Xpos20_Yneg10_place38_room18_floorA)
	(receptacleatlocation receptacle49_oven location_Xneg12_Ypos26_place39_room14_floorB)
	(receptacleatlocation receptacle50_sink location_Xpos28_Ypos19_place40_room1_floorA)
	(receptacleatlocation receptacle51_sink location_Xpos29_Ypos16_place41_room2_floorB)
	(receptacleatlocation receptacle52_sink location_Xneg20_Ypos34_place42_room14_floorB)
	(receptacleatlocation receptacle53_sink location_Xpos22_Yneg8_place43_room3_floorC)
	(receptacleatlocation receptacle54_sink location_Xpos31_Ypos2_place44_room3_floorC)
	(receptacleatlocation receptacle55_sink location_Xpos28_Ypos2_place45_room3_floorC)
	(receptacleatlocation receptacle56_sink location_Xpos28_Ypos15_place46_room3_floorC)
	(receptacleatlocation receptacle57_refrigerator location_Xneg12_Ypos16_place47_room14_floorB)
	(receptacleatlocation receptacle58_refrigerator location_Xpos10_Yneg7_place48_room8_floorB)
	(receptacleopeningtype receptacle47_microwave)
	(receptacleopeningtype receptacle48_oven)
	(receptacleopeningtype receptacle49_oven)
	(receptacleopeningtype receptacle57_refrigerator)
	(receptacleopeningtype receptacle58_refrigerator)
  )
  (:goal (and
	(inreceptacle item33_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item60_book_smallitem receptacle50_sink)
	(inreceptacle item12_cup_smallitem receptacle26_chair)
	(inreceptacle item8_bottle_smallitem receptacle58_refrigerator)
	(inreceptacle item6_bottle_smallitem receptacle58_refrigerator)
	(inreceptacle item61_vase_mediumitem receptacle38_dining_table)
	(inreceptacle item10_cup_smallitem receptacle54_sink)
	(inreceptacle item11_cup_smallitem receptacle55_sink)
	(inreceptacle item13_cup_smallitem receptacle51_sink)
	(inreceptacle item9_cup_smallitem receptacle21_chair)))
)
