
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_bottle_smallitem - item
	item11_book_smallitem - item
	item12_book_smallitem - item
	item13_book_smallitem - item
	item14_book_smallitem - item
	item15_vase_mediumitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item19_vase_mediumitem - item
	item20_bowl_smallitem - item
	item21_bowl_smallitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item9_bottle_smallitem - item
	location_Xneg1_Ypos9_place35_room4_floorC - location
	location_Xneg2_Yneg9_place16_room11_floorB - location
	location_Xneg2_Ypos13_place26_room2_floorB - location
	location_Xneg3_Yneg9_place15_room11_floorB - location
	location_Xneg4_Yneg14_place16_room11_floorB - location
	location_Xneg4_Ypos2_place16_room11_floorB - location
	location_Xpos13_Yneg26_place18_room11_floorB - location
	location_Xpos17_Yneg25_place43_room4_floorC - location
	location_Xpos20_Yneg22_place18_room11_floorB - location
	location_Xpos24_Yneg17_place19_room3_floorC - location
	location_Xpos24_Yneg24_place25_room3_floorC - location
	location_Xpos32_Yneg17_place27_room9_floorB - location
	location_Xpos33_Yneg14_place44_room9_floorB - location
	location_Xpos33_Yneg8_place28_room9_floorB - location
	location_Xpos34_Yneg13_place29_room9_floorB - location
	location_Xpos35_Yneg11_place45_room9_floorB - location
	location_Xpos35_Yneg14_place29_room9_floorB - location
	location_Xpos36_Yneg15_place31_room9_floorB - location
	location_Xpos40_Yneg14_place30_room9_floorB - location
	location_Xpos41_Ypos0_place23_room1_floorA - location
	location_Xpos41_Ypos0_place24_room1_floorA - location
	location_Xpos48_Ypos11_place13_room12_floorB - location
	location_Xpos49_Yneg11_place17_room1_floorA - location
	location_Xpos52_Yneg25_place42_room5_floorC - location
	location_Xpos52_Yneg5_place36_room10_floorA - location
	location_Xpos52_Ypos12_place12_room12_floorB - location
	location_Xpos53_Yneg10_place39_room12_floorB - location
	location_Xpos57_Yneg23_place39_room12_floorB - location
	location_Xpos58_Ypos1_place36_room10_floorA - location
	location_Xpos61_Yneg1_place37_room10_floorA - location
	location_Xpos64_Yneg15_place42_room5_floorC - location
	location_Xpos69_Yneg17_place46_room10_floorA - location
	location_Xpos69_Ypos0_place40_room12_floorB - location
	location_Xpos6_Yneg17_place43_room4_floorC - location
	location_Xpos6_Ypos10_place20_room2_floorB - location
	location_Xpos71_Yneg18_place46_room10_floorA - location
	location_Xpos71_Yneg23_place38_room10_floorA - location
	location_Xpos71_Yneg2_place32_room12_floorB - location
	location_Xpos72_Yneg11_place41_room12_floorB - location
	location_Xpos72_Ypos9_place33_room5_floorC - location
	location_Xpos75_Yneg22_place41_room12_floorB - location
	location_Xpos75_Yneg24_place41_room12_floorB - location
	location_Xpos75_Yneg26_place10_room12_floorB - location
	location_Xpos75_Yneg26_place11_room12_floorB - location
	location_Xpos75_Ypos12_place34_room5_floorC - location
	location_Xpos76_Yneg26_place9_room12_floorB - location
	location_Xpos76_Yneg27_place14_room12_floorB - location
	location_Xpos7_Ypos6_place22_room11_floorB - location
	location_Xpos8_Yneg24_place18_room11_floorB - location
	location_Xpos8_Ypos12_place20_room2_floorB - location
	location_Xpos9_Ypos4_place21_room11_floorB - location
	receptacle1_microwave - receptacle
	receptacle22_toilet - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_toilet - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_couch - receptacle
	receptacle39_couch - receptacle
	receptacle3_sink - receptacle
	receptacle40_couch - receptacle
	receptacle47_bed - receptacle
	receptacle48_bed - receptacle
	receptacle49_dining_table - receptacle
	receptacle4_sink - receptacle
	receptacle50_dining_table - receptacle
	receptacle51_dining_table - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_refrigerator - receptacle
	receptacle8_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg2_Yneg9_place16_room11_floorB)
	(inanyreceptacle item10_bottle_smallitem)
	(inanyreceptacle item11_book_smallitem)
	(inanyreceptacle item12_book_smallitem)
	(inanyreceptacle item13_book_smallitem)
	(inanyreceptacle item15_vase_mediumitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item18_vase_mediumitem)
	(inanyreceptacle item19_vase_mediumitem)
	(inanyreceptacle item20_bowl_smallitem)
	(inanyreceptacle item21_bowl_smallitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item9_bottle_smallitem)
	(inreceptacle item10_bottle_smallitem receptacle4_sink)
	(inreceptacle item11_book_smallitem receptacle38_couch)
	(inreceptacle item12_book_smallitem receptacle35_chair)
	(inreceptacle item13_book_smallitem receptacle51_dining_table)
	(inreceptacle item15_vase_mediumitem receptacle40_couch)
	(inreceptacle item16_vase_mediumitem receptacle40_couch)
	(inreceptacle item18_vase_mediumitem receptacle47_bed)
	(inreceptacle item19_vase_mediumitem receptacle28_chair)
	(inreceptacle item20_bowl_smallitem receptacle4_sink)
	(inreceptacle item21_bowl_smallitem receptacle48_bed)
	(inreceptacle item44_potted_plant_largeitem receptacle2_oven)
	(inreceptacle item46_potted_plant_largeitem receptacle6_sink)
	(inreceptacle item9_bottle_smallitem receptacle2_oven)
	(itematlocation item10_bottle_smallitem location_Xpos20_Yneg22_place18_room11_floorB)
	(itematlocation item11_book_smallitem location_Xpos53_Yneg10_place39_room12_floorB)
	(itematlocation item12_book_smallitem location_Xpos52_Yneg5_place36_room10_floorA)
	(itematlocation item13_book_smallitem location_Xpos71_Yneg18_place46_room10_floorA)
	(itematlocation item14_book_smallitem location_Xpos48_Ypos11_place13_room12_floorB)
	(itematlocation item15_vase_mediumitem location_Xpos75_Yneg24_place41_room12_floorB)
	(itematlocation item16_vase_mediumitem location_Xpos75_Yneg22_place41_room12_floorB)
	(itematlocation item17_vase_mediumitem location_Xpos76_Yneg27_place14_room12_floorB)
	(itematlocation item18_vase_mediumitem location_Xpos52_Yneg25_place42_room5_floorC)
	(itematlocation item19_vase_mediumitem location_Xpos35_Yneg14_place29_room9_floorB)
	(itematlocation item20_bowl_smallitem location_Xpos13_Yneg26_place18_room11_floorB)
	(itematlocation item21_bowl_smallitem location_Xpos17_Yneg25_place43_room4_floorC)
	(itematlocation item41_potted_plant_largeitem location_Xpos76_Yneg26_place9_room12_floorB)
	(itematlocation item42_potted_plant_largeitem location_Xpos75_Yneg26_place10_room12_floorB)
	(itematlocation item43_potted_plant_largeitem location_Xpos75_Yneg26_place11_room12_floorB)
	(itematlocation item44_potted_plant_largeitem location_Xneg4_Ypos2_place16_room11_floorB)
	(itematlocation item45_potted_plant_largeitem location_Xpos52_Ypos12_place12_room12_floorB)
	(itematlocation item46_potted_plant_largeitem location_Xpos6_Ypos10_place20_room2_floorB)
	(itematlocation item9_bottle_smallitem location_Xneg4_Yneg14_place16_room11_floorB)
	(receptacleatlocation receptacle1_microwave location_Xneg3_Yneg9_place15_room11_floorB)
	(receptacleatlocation receptacle22_toilet location_Xpos41_Ypos0_place23_room1_floorA)
	(receptacleatlocation receptacle23_toilet location_Xpos41_Ypos0_place24_room1_floorA)
	(receptacleatlocation receptacle24_toilet location_Xpos24_Yneg24_place25_room3_floorC)
	(receptacleatlocation receptacle25_toilet location_Xneg2_Ypos13_place26_room2_floorB)
	(receptacleatlocation receptacle26_chair location_Xpos32_Yneg17_place27_room9_floorB)
	(receptacleatlocation receptacle27_chair location_Xpos33_Yneg8_place28_room9_floorB)
	(receptacleatlocation receptacle28_chair location_Xpos34_Yneg13_place29_room9_floorB)
	(receptacleatlocation receptacle29_chair location_Xpos40_Yneg14_place30_room9_floorB)
	(receptacleatlocation receptacle2_oven location_Xneg2_Yneg9_place16_room11_floorB)
	(receptacleatlocation receptacle30_chair location_Xpos36_Yneg15_place31_room9_floorB)
	(receptacleatlocation receptacle31_chair location_Xpos71_Yneg2_place32_room12_floorB)
	(receptacleatlocation receptacle32_chair location_Xpos72_Ypos9_place33_room5_floorC)
	(receptacleatlocation receptacle33_chair location_Xpos75_Ypos12_place34_room5_floorC)
	(receptacleatlocation receptacle34_chair location_Xneg1_Ypos9_place35_room4_floorC)
	(receptacleatlocation receptacle35_chair location_Xpos58_Ypos1_place36_room10_floorA)
	(receptacleatlocation receptacle36_chair location_Xpos61_Yneg1_place37_room10_floorA)
	(receptacleatlocation receptacle37_chair location_Xpos71_Yneg23_place38_room10_floorA)
	(receptacleatlocation receptacle38_couch location_Xpos57_Yneg23_place39_room12_floorB)
	(receptacleatlocation receptacle39_couch location_Xpos69_Ypos0_place40_room12_floorB)
	(receptacleatlocation receptacle3_sink location_Xpos49_Yneg11_place17_room1_floorA)
	(receptacleatlocation receptacle40_couch location_Xpos72_Yneg11_place41_room12_floorB)
	(receptacleatlocation receptacle47_bed location_Xpos64_Yneg15_place42_room5_floorC)
	(receptacleatlocation receptacle48_bed location_Xpos6_Yneg17_place43_room4_floorC)
	(receptacleatlocation receptacle49_dining_table location_Xpos33_Yneg14_place44_room9_floorB)
	(receptacleatlocation receptacle4_sink location_Xpos8_Yneg24_place18_room11_floorB)
	(receptacleatlocation receptacle50_dining_table location_Xpos35_Yneg11_place45_room9_floorB)
	(receptacleatlocation receptacle51_dining_table location_Xpos69_Yneg17_place46_room10_floorA)
	(receptacleatlocation receptacle5_sink location_Xpos24_Yneg17_place19_room3_floorC)
	(receptacleatlocation receptacle6_sink location_Xpos8_Ypos12_place20_room2_floorB)
	(receptacleatlocation receptacle7_refrigerator location_Xpos9_Ypos4_place21_room11_floorB)
	(receptacleatlocation receptacle8_refrigerator location_Xpos7_Ypos6_place22_room11_floorB)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle7_refrigerator)
	(receptacleopeningtype receptacle8_refrigerator)
  )
  (:goal (and
	(inreceptacle item41_potted_plant_largeitem receptacle32_chair)
	(inreceptacle item21_bowl_smallitem receptacle30_chair)
	(inreceptacle item10_bottle_smallitem receptacle26_chair)
	(inreceptacle item13_book_smallitem receptacle50_dining_table)
	(inreceptacle item20_bowl_smallitem receptacle36_chair)
	(inreceptacle item45_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item16_vase_mediumitem receptacle51_dining_table)
	(inreceptacle item18_vase_mediumitem receptacle40_couch)
	(inreceptacle item42_potted_plant_largeitem receptacle25_toilet)
	(inreceptacle item12_book_smallitem receptacle7_refrigerator)))
)
