
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_cup_smallitem - item
	item11_bowl_smallitem - item
	item12_bowl_smallitem - item
	item29_potted_plant_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item3_baseball_bat_largeitem - item
	item47_tv_largeitem - item
	item48_tv_largeitem - item
	item4_baseball_bat_largeitem - item
	item57_book_smallitem - item
	item58_book_smallitem - item
	item59_book_smallitem - item
	item5_bottle_smallitem - item
	item60_book_smallitem - item
	item61_book_smallitem - item
	item62_book_smallitem - item
	item63_book_smallitem - item
	item64_book_smallitem - item
	item65_book_smallitem - item
	item66_clock_mediumitem - item
	item67_vase_mediumitem - item
	item68_vase_mediumitem - item
	item69_vase_mediumitem - item
	item6_bottle_smallitem - item
	item70_vase_mediumitem - item
	item71_vase_mediumitem - item
	item72_vase_mediumitem - item
	item73_vase_mediumitem - item
	item74_vase_mediumitem - item
	item7_bottle_smallitem - item
	item8_bottle_smallitem - item
	item9_wine_glass_smallitem - item
	location_Xneg101_Ypos29_place43_room21_floorD - location
	location_Xneg103_Yneg7_place18_room8_floorB - location
	location_Xneg104_Yneg1_place26_room8_floorB - location
	location_Xneg104_Yneg7_place17_room8_floorB - location
	location_Xneg105_Yneg9_place27_room8_floorB - location
	location_Xneg105_Yneg9_place32_room8_floorB - location
	location_Xneg11_Ypos59_place53_room5_floorC - location
	location_Xneg13_Ypos66_place49_room18_floorD - location
	location_Xneg17_Yneg2_place20_room10_floorA - location
	location_Xneg17_Ypos60_place51_room18_floorD - location
	location_Xneg1_Yneg14_place54_room9_floorB - location
	location_Xneg24_Ypos0_place24_room10_floorA - location
	location_Xneg25_Ypos40_place30_room18_floorD - location
	location_Xneg28_Ypos33_place31_room20_floorB - location
	location_Xneg29_Ypos33_place22_room20_floorB - location
	location_Xneg31_Yneg22_place61_room2_floorC - location
	location_Xneg32_Ypos3_place68_room15_floorB - location
	location_Xneg32_Ypos70_place45_room5_floorC - location
	location_Xneg37_Yneg8_place61_room2_floorC - location
	location_Xneg3_Ypos48_place46_room25_floorB - location
	location_Xneg40_Ypos46_place52_room17_floorC - location
	location_Xneg40_Ypos47_place52_room17_floorC - location
	location_Xneg42_Ypos2_place62_room15_floorB - location
	location_Xneg43_Yneg20_place67_room15_floorB - location
	location_Xneg48_Yneg17_place66_room10_floorA - location
	location_Xneg48_Ypos5_place62_room15_floorB - location
	location_Xneg4_Ypos6_place63_room1_floorB - location
	location_Xneg4_Ypos7_place29_room13_floorC - location
	location_Xneg53_Yneg22_place67_room15_floorB - location
	location_Xneg54_Ypos50_place52_room17_floorC - location
	location_Xneg56_Yneg21_place67_room15_floorB - location
	location_Xneg5_Ypos14_place34_room25_floorB - location
	location_Xneg5_Ypos17_place65_room3_floorC - location
	location_Xneg61_Ypos2_place69_room15_floorB - location
	location_Xneg62_Yneg18_place33_room10_floorA - location
	location_Xneg63_Yneg20_place67_room15_floorB - location
	location_Xneg64_Yneg14_place25_room4_floorC - location
	location_Xneg69_Ypos54_place21_room16_floorB - location
	location_Xneg77_Ypos1_place28_room21_floorD - location
	location_Xneg78_Ypos0_place23_room21_floorD - location
	location_Xneg7_Ypos18_place64_room3_floorC - location
	location_Xneg83_Yneg12_place56_room8_floorB - location
	location_Xneg83_Yneg4_place36_room8_floorB - location
	location_Xneg83_Yneg5_place55_room8_floorB - location
	location_Xneg83_Yneg6_place55_room8_floorB - location
	location_Xneg84_Yneg11_place35_room8_floorB - location
	location_Xneg84_Ypos1_place42_room21_floorD - location
	location_Xneg84_Ypos21_place47_room16_floorB - location
	location_Xneg84_Ypos23_place38_room16_floorB - location
	location_Xneg84_Ypos39_place37_room16_floorB - location
	location_Xneg85_Yneg10_place50_room4_floorC - location
	location_Xneg85_Ypos49_place37_room16_floorB - location
	location_Xneg88_Ypos10_place41_room4_floorC - location
	location_Xneg88_Ypos8_place41_room4_floorC - location
	location_Xneg90_Ypos23_place57_room21_floorD - location
	location_Xneg91_Ypos28_place44_room21_floorD - location
	location_Xneg93_Ypos20_place57_room21_floorD - location
	location_Xneg93_Ypos7_place41_room4_floorC - location
	location_Xneg94_Ypos15_place42_room21_floorD - location
	location_Xneg97_Ypos28_place58_room21_floorD - location
	location_Xneg97_Ypos35_place48_room16_floorB - location
	location_Xneg99_Ypos29_place43_room21_floorD - location
	location_Xpos10_Ypos16_place60_room3_floorC - location
	location_Xpos10_Ypos27_place60_room3_floorC - location
	location_Xpos11_Yneg3_place54_room9_floorB - location
	location_Xpos1_Yneg13_place54_room9_floorB - location
	location_Xpos1_Ypos35_place46_room25_floorB - location
	location_Xpos3_Ypos5_place19_room10_floorA - location
	location_Xpos4_Ypos20_place40_room19_floorD - location
	location_Xpos5_Ypos10_place39_room19_floorD - location
	location_Xpos6_Ypos19_place34_room25_floorB - location
	location_Xpos8_Ypos11_place60_room3_floorC - location
	location_Xpos8_Ypos6_place59_room1_floorB - location
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_bench - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_couch - receptacle
	receptacle26_couch - receptacle
	receptacle27_couch - receptacle
	receptacle28_couch - receptacle
	receptacle35_bed - receptacle
	receptacle36_bed - receptacle
	receptacle37_bed - receptacle
	receptacle38_bed - receptacle
	receptacle39_dining_table - receptacle
	receptacle40_dining_table - receptacle
	receptacle41_dining_table - receptacle
	receptacle42_dining_table - receptacle
	receptacle43_dining_table - receptacle
	receptacle44_toilet - receptacle
	receptacle45_toilet - receptacle
	receptacle46_toilet - receptacle
	receptacle49_oven - receptacle
	receptacle50_sink - receptacle
	receptacle51_sink - receptacle
	receptacle52_sink - receptacle
	receptacle53_sink - receptacle
	receptacle54_sink - receptacle
	receptacle55_refrigerator - receptacle
	receptacle56_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg48_Ypos5_place62_room15_floorB)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item11_bowl_smallitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item47_tv_largeitem)
	(inanyreceptacle item58_book_smallitem)
	(inanyreceptacle item59_book_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item60_book_smallitem)
	(inanyreceptacle item61_book_smallitem)
	(inanyreceptacle item62_book_smallitem)
	(inanyreceptacle item63_book_smallitem)
	(inanyreceptacle item64_book_smallitem)
	(inanyreceptacle item68_vase_mediumitem)
	(inanyreceptacle item69_vase_mediumitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item70_vase_mediumitem)
	(inanyreceptacle item72_vase_mediumitem)
	(inanyreceptacle item73_vase_mediumitem)
	(inreceptacle item10_cup_smallitem receptacle25_couch)
	(inreceptacle item11_bowl_smallitem receptacle45_toilet)
	(inreceptacle item30_potted_plant_largeitem receptacle39_dining_table)
	(inreceptacle item32_potted_plant_largeitem receptacle54_sink)
	(inreceptacle item34_potted_plant_largeitem receptacle46_toilet)
	(inreceptacle item47_tv_largeitem receptacle13_chair)
	(inreceptacle item58_book_smallitem receptacle37_bed)
	(inreceptacle item59_book_smallitem receptacle20_chair)
	(inreceptacle item5_bottle_smallitem receptacle49_oven)
	(inreceptacle item60_book_smallitem receptacle22_chair)
	(inreceptacle item61_book_smallitem receptacle42_dining_table)
	(inreceptacle item62_book_smallitem receptacle21_chair)
	(inreceptacle item63_book_smallitem receptacle16_chair)
	(inreceptacle item64_book_smallitem receptacle54_sink)
	(inreceptacle item68_vase_mediumitem receptacle39_dining_table)
	(inreceptacle item69_vase_mediumitem receptacle20_chair)
	(inreceptacle item6_bottle_smallitem receptacle54_sink)
	(inreceptacle item70_vase_mediumitem receptacle40_dining_table)
	(inreceptacle item72_vase_mediumitem receptacle37_bed)
	(inreceptacle item73_vase_mediumitem receptacle45_toilet)
	(itematlocation item10_cup_smallitem location_Xpos1_Ypos35_place46_room25_floorB)
	(itematlocation item11_bowl_smallitem location_Xpos10_Ypos16_place60_room3_floorC)
	(itematlocation item12_bowl_smallitem location_Xneg77_Ypos1_place28_room21_floorD)
	(itematlocation item29_potted_plant_largeitem location_Xneg28_Ypos33_place31_room20_floorB)
	(itematlocation item30_potted_plant_largeitem location_Xpos11_Yneg3_place54_room9_floorB)
	(itematlocation item31_potted_plant_largeitem location_Xneg105_Yneg9_place32_room8_floorB)
	(itematlocation item32_potted_plant_largeitem location_Xneg53_Yneg22_place67_room15_floorB)
	(itematlocation item33_potted_plant_largeitem location_Xneg104_Yneg7_place17_room8_floorB)
	(itematlocation item34_potted_plant_largeitem location_Xneg31_Yneg22_place61_room2_floorC)
	(itematlocation item3_baseball_bat_largeitem location_Xpos3_Ypos5_place19_room10_floorA)
	(itematlocation item47_tv_largeitem location_Xneg5_Ypos14_place34_room25_floorB)
	(itematlocation item48_tv_largeitem location_Xneg4_Ypos7_place29_room13_floorC)
	(itematlocation item4_baseball_bat_largeitem location_Xneg17_Yneg2_place20_room10_floorA)
	(itematlocation item57_book_smallitem location_Xneg25_Ypos40_place30_room18_floorD)
	(itematlocation item58_book_smallitem location_Xneg40_Ypos46_place52_room17_floorC)
	(itematlocation item59_book_smallitem location_Xneg88_Ypos8_place41_room4_floorC)
	(itematlocation item5_bottle_smallitem location_Xneg48_Ypos5_place62_room15_floorB)
	(itematlocation item60_book_smallitem location_Xneg101_Ypos29_place43_room21_floorD)
	(itematlocation item61_book_smallitem location_Xneg90_Ypos23_place57_room21_floorD)
	(itematlocation item62_book_smallitem location_Xneg84_Ypos1_place42_room21_floorD)
	(itematlocation item63_book_smallitem location_Xneg84_Ypos39_place37_room16_floorB)
	(itematlocation item64_book_smallitem location_Xneg63_Yneg20_place67_room15_floorB)
	(itematlocation item65_book_smallitem location_Xneg103_Yneg7_place18_room8_floorB)
	(itematlocation item66_clock_mediumitem location_Xneg69_Ypos54_place21_room16_floorB)
	(itematlocation item67_vase_mediumitem location_Xneg29_Ypos33_place22_room20_floorB)
	(itematlocation item68_vase_mediumitem location_Xneg1_Yneg14_place54_room9_floorB)
	(itematlocation item69_vase_mediumitem location_Xneg88_Ypos10_place41_room4_floorC)
	(itematlocation item6_bottle_smallitem location_Xneg56_Yneg21_place67_room15_floorB)
	(itematlocation item70_vase_mediumitem location_Xneg83_Yneg5_place55_room8_floorB)
	(itematlocation item71_vase_mediumitem location_Xneg104_Yneg1_place26_room8_floorB)
	(itematlocation item72_vase_mediumitem location_Xneg40_Ypos47_place52_room17_floorC)
	(itematlocation item73_vase_mediumitem location_Xpos10_Ypos27_place60_room3_floorC)
	(itematlocation item74_vase_mediumitem location_Xneg105_Yneg9_place27_room8_floorB)
	(itematlocation item7_bottle_smallitem location_Xneg78_Ypos0_place23_room21_floorD)
	(itematlocation item8_bottle_smallitem location_Xneg24_Ypos0_place24_room10_floorA)
	(itematlocation item9_wine_glass_smallitem location_Xneg64_Yneg14_place25_room4_floorC)
	(receptacleatlocation receptacle13_chair location_Xpos6_Ypos19_place34_room25_floorB)
	(receptacleatlocation receptacle14_chair location_Xneg84_Yneg11_place35_room8_floorB)
	(receptacleatlocation receptacle15_chair location_Xneg83_Yneg4_place36_room8_floorB)
	(receptacleatlocation receptacle16_chair location_Xneg85_Ypos49_place37_room16_floorB)
	(receptacleatlocation receptacle17_chair location_Xneg84_Ypos23_place38_room16_floorB)
	(receptacleatlocation receptacle18_chair location_Xpos5_Ypos10_place39_room19_floorD)
	(receptacleatlocation receptacle19_chair location_Xpos4_Ypos20_place40_room19_floorD)
	(receptacleatlocation receptacle1_bench location_Xneg62_Yneg18_place33_room10_floorA)
	(receptacleatlocation receptacle20_chair location_Xneg93_Ypos7_place41_room4_floorC)
	(receptacleatlocation receptacle21_chair location_Xneg94_Ypos15_place42_room21_floorD)
	(receptacleatlocation receptacle22_chair location_Xneg99_Ypos29_place43_room21_floorD)
	(receptacleatlocation receptacle23_chair location_Xneg91_Ypos28_place44_room21_floorD)
	(receptacleatlocation receptacle24_chair location_Xneg32_Ypos70_place45_room5_floorC)
	(receptacleatlocation receptacle25_couch location_Xneg3_Ypos48_place46_room25_floorB)
	(receptacleatlocation receptacle26_couch location_Xneg84_Ypos21_place47_room16_floorB)
	(receptacleatlocation receptacle27_couch location_Xneg97_Ypos35_place48_room16_floorB)
	(receptacleatlocation receptacle28_couch location_Xneg13_Ypos66_place49_room18_floorD)
	(receptacleatlocation receptacle35_bed location_Xneg85_Yneg10_place50_room4_floorC)
	(receptacleatlocation receptacle36_bed location_Xneg17_Ypos60_place51_room18_floorD)
	(receptacleatlocation receptacle37_bed location_Xneg54_Ypos50_place52_room17_floorC)
	(receptacleatlocation receptacle38_bed location_Xneg11_Ypos59_place53_room5_floorC)
	(receptacleatlocation receptacle39_dining_table location_Xpos1_Yneg13_place54_room9_floorB)
	(receptacleatlocation receptacle40_dining_table location_Xneg83_Yneg6_place55_room8_floorB)
	(receptacleatlocation receptacle41_dining_table location_Xneg83_Yneg12_place56_room8_floorB)
	(receptacleatlocation receptacle42_dining_table location_Xneg93_Ypos20_place57_room21_floorD)
	(receptacleatlocation receptacle43_dining_table location_Xneg97_Ypos28_place58_room21_floorD)
	(receptacleatlocation receptacle44_toilet location_Xpos8_Ypos6_place59_room1_floorB)
	(receptacleatlocation receptacle45_toilet location_Xpos8_Ypos11_place60_room3_floorC)
	(receptacleatlocation receptacle46_toilet location_Xneg37_Yneg8_place61_room2_floorC)
	(receptacleatlocation receptacle49_oven location_Xneg42_Ypos2_place62_room15_floorB)
	(receptacleatlocation receptacle50_sink location_Xneg4_Ypos6_place63_room1_floorB)
	(receptacleatlocation receptacle51_sink location_Xneg7_Ypos18_place64_room3_floorC)
	(receptacleatlocation receptacle52_sink location_Xneg5_Ypos17_place65_room3_floorC)
	(receptacleatlocation receptacle53_sink location_Xneg48_Yneg17_place66_room10_floorA)
	(receptacleatlocation receptacle54_sink location_Xneg43_Yneg20_place67_room15_floorB)
	(receptacleatlocation receptacle55_refrigerator location_Xneg32_Ypos3_place68_room15_floorB)
	(receptacleatlocation receptacle56_refrigerator location_Xneg61_Ypos2_place69_room15_floorB)
	(receptacleopeningtype receptacle49_oven)
	(receptacleopeningtype receptacle55_refrigerator)
	(receptacleopeningtype receptacle56_refrigerator)
  )
  (:goal (and
	(inreceptacle item62_book_smallitem receptacle37_bed)
	(inreceptacle item5_bottle_smallitem receptacle46_toilet)
	(inreceptacle item66_clock_mediumitem receptacle39_dining_table)
	(inreceptacle item4_baseball_bat_largeitem receptacle13_chair)
	(inreceptacle item71_vase_mediumitem receptacle55_refrigerator)
	(inreceptacle item74_vase_mediumitem receptacle42_dining_table)
	(inreceptacle item70_vase_mediumitem receptacle18_chair)
	(inreceptacle item68_vase_mediumitem receptacle44_toilet)
	(inreceptacle item32_potted_plant_largeitem receptacle35_bed)
	(inreceptacle item58_book_smallitem receptacle14_chair)))
)
