
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item100_teddy_bear_mediumitem - item
	item24_potted_plant_largeitem - item
	item25_potted_plant_largeitem - item
	item26_potted_plant_largeitem - item
	item27_potted_plant_largeitem - item
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item2_handbag_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_handbag_largeitem - item
	item40_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item4_bowl_smallitem - item
	item58_tv_largeitem - item
	item59_tv_largeitem - item
	item60_keyboard_largeitem - item
	item71_book_smallitem - item
	item72_book_smallitem - item
	item73_book_smallitem - item
	item74_book_smallitem - item
	item75_book_smallitem - item
	item76_book_smallitem - item
	item77_book_smallitem - item
	item78_book_smallitem - item
	item79_book_smallitem - item
	item80_book_smallitem - item
	item81_book_smallitem - item
	item82_book_smallitem - item
	item83_book_smallitem - item
	item84_book_smallitem - item
	item85_book_smallitem - item
	item86_book_smallitem - item
	item87_book_smallitem - item
	item88_book_smallitem - item
	item89_vase_mediumitem - item
	item90_vase_mediumitem - item
	item91_vase_mediumitem - item
	item92_vase_mediumitem - item
	item93_vase_mediumitem - item
	item94_vase_mediumitem - item
	item95_vase_mediumitem - item
	item96_vase_mediumitem - item
	item97_vase_mediumitem - item
	item98_vase_mediumitem - item
	item99_vase_mediumitem - item
	location_Xneg103_Yneg33_place23_room26_floorB - location
	location_Xneg104_Yneg34_place51_room4_floorB - location
	location_Xneg109_Ypos10_place63_room8_floorC - location
	location_Xneg11_Ypos15_place47_room20_floorB - location
	location_Xneg123_Yneg21_place59_room26_floorB - location
	location_Xneg125_Yneg32_place73_room4_floorB - location
	location_Xneg125_Ypos17_place64_room8_floorC - location
	location_Xneg13_Yneg16_place67_room6_floorC - location
	location_Xneg21_Yneg37_place54_room5_floorA - location
	location_Xneg22_Yneg17_place42_room13_floorB - location
	location_Xneg22_Yneg27_place85_room6_floorC - location
	location_Xneg23_Yneg23_place40_room13_floorB - location
	location_Xneg23_Ypos13_place81_room3_floorB - location
	location_Xneg25_Yneg33_place54_room5_floorA - location
	location_Xneg25_Ypos19_place74_room1_floorA - location
	location_Xneg25_Ypos21_place75_room3_floorB - location
	location_Xneg2_Yneg33_place68_room13_floorB - location
	location_Xneg2_Ypos7_place47_room20_floorB - location
	location_Xneg34_Ypos21_place80_room1_floorA - location
	location_Xneg39_Yneg29_place76_room2_floorB - location
	location_Xneg3_Ypos5_place47_room20_floorB - location
	location_Xneg41_Ypos24_place27_room3_floorB - location
	location_Xneg41_Ypos4_place35_room14_floorB - location
	location_Xneg41_Ypos4_place41_room14_floorB - location
	location_Xneg42_Ypos4_place36_room14_floorB - location
	location_Xneg42_Ypos4_place37_room14_floorB - location
	location_Xneg43_Yneg25_place79_room25_floorA - location
	location_Xneg43_Ypos13_place44_room15_floorB - location
	location_Xneg44_Yneg33_place22_room7_floorC - location
	location_Xneg44_Yneg34_place21_room7_floorC - location
	location_Xneg46_Yneg32_place83_room25_floorA - location
	location_Xneg46_Ypos4_place33_room14_floorB - location
	location_Xneg46_Ypos4_place38_room14_floorB - location
	location_Xneg46_Ypos4_place39_room14_floorB - location
	location_Xneg47_Ypos13_place69_room15_floorB - location
	location_Xneg47_Ypos14_place69_room15_floorB - location
	location_Xneg47_Ypos4_place32_room14_floorB - location
	location_Xneg47_Ypos4_place34_room14_floorB - location
	location_Xneg48_Ypos4_place31_room14_floorB - location
	location_Xneg52_Ypos19_place49_room15_floorB - location
	location_Xneg53_Ypos13_place46_room15_floorB - location
	location_Xneg54_Ypos18_place72_room16_floorA - location
	location_Xneg56_Yneg31_place43_room25_floorA - location
	location_Xneg56_Ypos15_place50_room16_floorA - location
	location_Xneg56_Ypos21_place72_room16_floorA - location
	location_Xneg57_Yneg15_place43_room25_floorA - location
	location_Xneg57_Ypos18_place50_room16_floorA - location
	location_Xneg59_Yneg25_place84_room17_floorB - location
	location_Xneg60_Yneg24_place43_room25_floorA - location
	location_Xneg61_Ypos17_place50_room16_floorA - location
	location_Xneg68_Yneg30_place65_room7_floorC - location
	location_Xneg6_Ypos22_place58_room21_floorC - location
	location_Xneg70_Ypos22_place49_room15_floorB - location
	location_Xneg71_Yneg34_place78_room17_floorB - location
	location_Xneg72_Yneg33_place77_room17_floorB - location
	location_Xneg73_Ypos14_place20_room11_floorB - location
	location_Xneg73_Ypos14_place28_room11_floorB - location
	location_Xneg74_Ypos14_place29_room11_floorB - location
	location_Xneg75_Yneg15_place52_room7_floorC - location
	location_Xneg75_Yneg15_place53_room7_floorC - location
	location_Xneg76_Yneg8_place26_room14_floorB - location
	location_Xneg76_Yneg9_place25_room14_floorB - location
	location_Xneg77_Yneg24_place52_room7_floorC - location
	location_Xneg77_Ypos14_place30_room11_floorB - location
	location_Xneg79_Yneg4_place45_room17_floorB - location
	location_Xneg81_Yneg11_place86_room18_floorA - location
	location_Xneg81_Yneg29_place77_room17_floorB - location
	location_Xneg82_Yneg12_place70_room17_floorB - location
	location_Xneg86_Yneg13_place70_room17_floorB - location
	location_Xneg86_Yneg26_place62_room18_floorA - location
	location_Xneg89_Yneg5_place48_room17_floorB - location
	location_Xneg92_Yneg35_place82_room4_floorB - location
	location_Xneg93_Yneg16_place82_room4_floorB - location
	location_Xneg93_Yneg36_place82_room4_floorB - location
	location_Xneg93_Yneg8_place71_room26_floorB - location
	location_Xneg94_Yneg34_place82_room4_floorB - location
	location_Xneg95_Yneg23_place82_room4_floorB - location
	location_Xneg96_Yneg10_place71_room26_floorB - location
	location_Xneg96_Yneg11_place71_room26_floorB - location
	location_Xneg96_Yneg24_place71_room26_floorB - location
	location_Xneg96_Yneg33_place24_room26_floorB - location
	location_Xpos10_Ypos21_place57_room21_floorC - location
	location_Xpos11_Ypos21_place56_room21_floorC - location
	location_Xpos11_Ypos6_place61_room20_floorB - location
	location_Xpos12_Yneg21_place55_room6_floorC - location
	location_Xpos12_Yneg5_place61_room20_floorB - location
	location_Xpos12_Yneg7_place61_room20_floorB - location
	location_Xpos12_Ypos6_place57_room21_floorC - location
	location_Xpos15_Yneg5_place61_room20_floorB - location
	location_Xpos3_Yneg23_place66_room5_floorA - location
	location_Xpos5_Ypos18_place60_room19_floorA - location
	location_Xpos6_Yneg35_place55_room6_floorC - location
	location_Xpos6_Yneg37_place55_room6_floorC - location
	location_Xpos9_Yneg34_place55_room6_floorC - location
	location_Xpos9_Ypos5_place57_room21_floorC - location
	receptacle10_chair - receptacle
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_bench - receptacle
	receptacle20_couch - receptacle
	receptacle21_couch - receptacle
	receptacle22_couch - receptacle
	receptacle23_couch - receptacle
	receptacle44_bed - receptacle
	receptacle45_bed - receptacle
	receptacle46_bed - receptacle
	receptacle47_bed - receptacle
	receptacle48_bed - receptacle
	receptacle49_bed - receptacle
	receptacle50_dining_table - receptacle
	receptacle51_dining_table - receptacle
	receptacle52_dining_table - receptacle
	receptacle53_dining_table - receptacle
	receptacle54_toilet - receptacle
	receptacle55_toilet - receptacle
	receptacle56_toilet - receptacle
	receptacle57_toilet - receptacle
	receptacle5_chair - receptacle
	receptacle61_oven - receptacle
	receptacle62_oven - receptacle
	receptacle63_oven - receptacle
	receptacle64_sink - receptacle
	receptacle65_sink - receptacle
	receptacle66_sink - receptacle
	receptacle67_refrigerator - receptacle
	receptacle68_refrigerator - receptacle
	receptacle69_refrigerator - receptacle
	receptacle6_chair - receptacle
	receptacle70_refrigerator - receptacle
	receptacle7_chair - receptacle
	receptacle8_chair - receptacle
	receptacle9_chair - receptacle
  )
  (:init 
	(atlocation agent location_Xneg2_Ypos7_place47_room20_floorB)
	(inanyreceptacle item100_teddy_bear_mediumitem)
	(inanyreceptacle item25_potted_plant_largeitem)
	(inanyreceptacle item26_potted_plant_largeitem)
	(inanyreceptacle item27_potted_plant_largeitem)
	(inanyreceptacle item28_potted_plant_largeitem)
	(inanyreceptacle item29_potted_plant_largeitem)
	(inanyreceptacle item2_handbag_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item3_handbag_largeitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item43_potted_plant_largeitem)
	(inanyreceptacle item4_bowl_smallitem)
	(inanyreceptacle item58_tv_largeitem)
	(inanyreceptacle item59_tv_largeitem)
	(inanyreceptacle item60_keyboard_largeitem)
	(inanyreceptacle item83_book_smallitem)
	(inanyreceptacle item84_book_smallitem)
	(inanyreceptacle item85_book_smallitem)
	(inanyreceptacle item86_book_smallitem)
	(inanyreceptacle item89_vase_mediumitem)
	(inanyreceptacle item90_vase_mediumitem)
	(inanyreceptacle item91_vase_mediumitem)
	(inanyreceptacle item92_vase_mediumitem)
	(inanyreceptacle item93_vase_mediumitem)
	(inanyreceptacle item95_vase_mediumitem)
	(inanyreceptacle item96_vase_mediumitem)
	(inanyreceptacle item97_vase_mediumitem)
	(inanyreceptacle item98_vase_mediumitem)
	(inanyreceptacle item99_vase_mediumitem)
	(inreceptacle item100_teddy_bear_mediumitem receptacle18_chair)
	(inreceptacle item25_potted_plant_largeitem receptacle50_dining_table)
	(inreceptacle item26_potted_plant_largeitem receptacle11_chair)
	(inreceptacle item27_potted_plant_largeitem receptacle66_sink)
	(inreceptacle item28_potted_plant_largeitem receptacle66_sink)
	(inreceptacle item29_potted_plant_largeitem receptacle66_sink)
	(inreceptacle item2_handbag_largeitem receptacle1_bench)
	(inreceptacle item32_potted_plant_largeitem receptacle16_chair)
	(inreceptacle item33_potted_plant_largeitem receptacle22_couch)
	(inreceptacle item34_potted_plant_largeitem receptacle8_chair)
	(inreceptacle item35_potted_plant_largeitem receptacle22_couch)
	(inreceptacle item3_handbag_largeitem receptacle1_bench)
	(inreceptacle item42_potted_plant_largeitem receptacle15_chair)
	(inreceptacle item43_potted_plant_largeitem receptacle61_oven)
	(inreceptacle item4_bowl_smallitem receptacle18_chair)
	(inreceptacle item58_tv_largeitem receptacle53_dining_table)
	(inreceptacle item59_tv_largeitem receptacle52_dining_table)
	(inreceptacle item60_keyboard_largeitem receptacle11_chair)
	(inreceptacle item83_book_smallitem receptacle16_chair)
	(inreceptacle item84_book_smallitem receptacle13_chair)
	(inreceptacle item85_book_smallitem receptacle52_dining_table)
	(inreceptacle item86_book_smallitem receptacle52_dining_table)
	(inreceptacle item89_vase_mediumitem receptacle66_sink)
	(inreceptacle item90_vase_mediumitem receptacle66_sink)
	(inreceptacle item91_vase_mediumitem receptacle66_sink)
	(inreceptacle item92_vase_mediumitem receptacle10_chair)
	(inreceptacle item93_vase_mediumitem receptacle22_couch)
	(inreceptacle item95_vase_mediumitem receptacle8_chair)
	(inreceptacle item96_vase_mediumitem receptacle16_chair)
	(inreceptacle item97_vase_mediumitem receptacle15_chair)
	(inreceptacle item98_vase_mediumitem receptacle51_dining_table)
	(inreceptacle item99_vase_mediumitem receptacle61_oven)
	(itematlocation item100_teddy_bear_mediumitem location_Xpos12_Ypos6_place57_room21_floorC)
	(itematlocation item24_potted_plant_largeitem location_Xneg73_Ypos14_place20_room11_floorB)
	(itematlocation item25_potted_plant_largeitem location_Xneg47_Ypos14_place69_room15_floorB)
	(itematlocation item26_potted_plant_largeitem location_Xneg61_Ypos17_place50_room16_floorA)
	(itematlocation item27_potted_plant_largeitem location_Xneg94_Yneg34_place82_room4_floorB)
	(itematlocation item28_potted_plant_largeitem location_Xneg92_Yneg35_place82_room4_floorB)
	(itematlocation item29_potted_plant_largeitem location_Xneg93_Yneg16_place82_room4_floorB)
	(itematlocation item2_handbag_largeitem location_Xneg57_Yneg15_place43_room25_floorA)
	(itematlocation item30_potted_plant_largeitem location_Xneg44_Yneg34_place21_room7_floorC)
	(itematlocation item31_potted_plant_largeitem location_Xneg44_Yneg33_place22_room7_floorC)
	(itematlocation item32_potted_plant_largeitem location_Xpos6_Yneg37_place55_room6_floorC)
	(itematlocation item33_potted_plant_largeitem location_Xpos12_Yneg5_place61_room20_floorB)
	(itematlocation item34_potted_plant_largeitem location_Xneg3_Ypos5_place47_room20_floorB)
	(itematlocation item35_potted_plant_largeitem location_Xpos15_Yneg5_place61_room20_floorB)
	(itematlocation item36_potted_plant_largeitem location_Xneg103_Yneg33_place23_room26_floorB)
	(itematlocation item37_potted_plant_largeitem location_Xneg96_Yneg33_place24_room26_floorB)
	(itematlocation item38_potted_plant_largeitem location_Xneg76_Yneg9_place25_room14_floorB)
	(itematlocation item39_potted_plant_largeitem location_Xneg76_Yneg8_place26_room14_floorB)
	(itematlocation item3_handbag_largeitem location_Xneg60_Yneg24_place43_room25_floorA)
	(itematlocation item40_potted_plant_largeitem location_Xneg41_Ypos24_place27_room3_floorB)
	(itematlocation item42_potted_plant_largeitem location_Xneg21_Yneg37_place54_room5_floorA)
	(itematlocation item43_potted_plant_largeitem location_Xneg81_Yneg29_place77_room17_floorB)
	(itematlocation item4_bowl_smallitem location_Xpos9_Ypos5_place57_room21_floorC)
	(itematlocation item58_tv_largeitem location_Xneg56_Ypos21_place72_room16_floorA)
	(itematlocation item59_tv_largeitem location_Xneg96_Yneg24_place71_room26_floorB)
	(itematlocation item60_keyboard_largeitem location_Xneg57_Ypos18_place50_room16_floorA)
	(itematlocation item71_book_smallitem location_Xneg73_Ypos14_place28_room11_floorB)
	(itematlocation item72_book_smallitem location_Xneg74_Ypos14_place29_room11_floorB)
	(itematlocation item73_book_smallitem location_Xneg77_Ypos14_place30_room11_floorB)
	(itematlocation item74_book_smallitem location_Xneg48_Ypos4_place31_room14_floorB)
	(itematlocation item75_book_smallitem location_Xneg47_Ypos4_place32_room14_floorB)
	(itematlocation item76_book_smallitem location_Xneg46_Ypos4_place33_room14_floorB)
	(itematlocation item77_book_smallitem location_Xneg47_Ypos4_place34_room14_floorB)
	(itematlocation item78_book_smallitem location_Xneg41_Ypos4_place35_room14_floorB)
	(itematlocation item79_book_smallitem location_Xneg42_Ypos4_place36_room14_floorB)
	(itematlocation item80_book_smallitem location_Xneg42_Ypos4_place37_room14_floorB)
	(itematlocation item81_book_smallitem location_Xneg46_Ypos4_place38_room14_floorB)
	(itematlocation item82_book_smallitem location_Xneg46_Ypos4_place39_room14_floorB)
	(itematlocation item83_book_smallitem location_Xpos12_Yneg21_place55_room6_floorC)
	(itematlocation item84_book_smallitem location_Xneg77_Yneg24_place52_room7_floorC)
	(itematlocation item85_book_smallitem location_Xneg96_Yneg10_place71_room26_floorB)
	(itematlocation item86_book_smallitem location_Xneg96_Yneg11_place71_room26_floorB)
	(itematlocation item87_book_smallitem location_Xneg23_Yneg23_place40_room13_floorB)
	(itematlocation item88_book_smallitem location_Xneg41_Ypos4_place41_room14_floorB)
	(itematlocation item89_vase_mediumitem location_Xneg94_Yneg34_place82_room4_floorB)
	(itematlocation item90_vase_mediumitem location_Xneg93_Yneg36_place82_room4_floorB)
	(itematlocation item91_vase_mediumitem location_Xneg92_Yneg35_place82_room4_floorB)
	(itematlocation item92_vase_mediumitem location_Xneg70_Ypos22_place49_room15_floorB)
	(itematlocation item93_vase_mediumitem location_Xpos12_Yneg7_place61_room20_floorB)
	(itematlocation item94_vase_mediumitem location_Xneg22_Yneg17_place42_room13_floorB)
	(itematlocation item95_vase_mediumitem location_Xneg2_Ypos7_place47_room20_floorB)
	(itematlocation item96_vase_mediumitem location_Xpos6_Yneg35_place55_room6_floorC)
	(itematlocation item97_vase_mediumitem location_Xneg21_Yneg37_place54_room5_floorA)
	(itematlocation item98_vase_mediumitem location_Xneg86_Yneg13_place70_room17_floorB)
	(itematlocation item99_vase_mediumitem location_Xneg81_Yneg29_place77_room17_floorB)
	(receptacleatlocation receptacle10_chair location_Xneg52_Ypos19_place49_room15_floorB)
	(receptacleatlocation receptacle11_chair location_Xneg56_Ypos15_place50_room16_floorA)
	(receptacleatlocation receptacle12_chair location_Xneg104_Yneg34_place51_room4_floorB)
	(receptacleatlocation receptacle13_chair location_Xneg75_Yneg15_place52_room7_floorC)
	(receptacleatlocation receptacle14_chair location_Xneg75_Yneg15_place53_room7_floorC)
	(receptacleatlocation receptacle15_chair location_Xneg25_Yneg33_place54_room5_floorA)
	(receptacleatlocation receptacle16_chair location_Xpos9_Yneg34_place55_room6_floorC)
	(receptacleatlocation receptacle17_chair location_Xpos11_Ypos21_place56_room21_floorC)
	(receptacleatlocation receptacle18_chair location_Xpos10_Ypos21_place57_room21_floorC)
	(receptacleatlocation receptacle19_chair location_Xneg6_Ypos22_place58_room21_floorC)
	(receptacleatlocation receptacle1_bench location_Xneg56_Yneg31_place43_room25_floorA)
	(receptacleatlocation receptacle20_couch location_Xneg123_Yneg21_place59_room26_floorB)
	(receptacleatlocation receptacle21_couch location_Xpos5_Ypos18_place60_room19_floorA)
	(receptacleatlocation receptacle22_couch location_Xpos11_Ypos6_place61_room20_floorB)
	(receptacleatlocation receptacle23_couch location_Xneg86_Yneg26_place62_room18_floorA)
	(receptacleatlocation receptacle44_bed location_Xneg109_Ypos10_place63_room8_floorC)
	(receptacleatlocation receptacle45_bed location_Xneg125_Ypos17_place64_room8_floorC)
	(receptacleatlocation receptacle46_bed location_Xneg68_Yneg30_place65_room7_floorC)
	(receptacleatlocation receptacle47_bed location_Xpos3_Yneg23_place66_room5_floorA)
	(receptacleatlocation receptacle48_bed location_Xneg13_Yneg16_place67_room6_floorC)
	(receptacleatlocation receptacle49_bed location_Xneg2_Yneg33_place68_room13_floorB)
	(receptacleatlocation receptacle50_dining_table location_Xneg47_Ypos13_place69_room15_floorB)
	(receptacleatlocation receptacle51_dining_table location_Xneg82_Yneg12_place70_room17_floorB)
	(receptacleatlocation receptacle52_dining_table location_Xneg93_Yneg8_place71_room26_floorB)
	(receptacleatlocation receptacle53_dining_table location_Xneg54_Ypos18_place72_room16_floorA)
	(receptacleatlocation receptacle54_toilet location_Xneg125_Yneg32_place73_room4_floorB)
	(receptacleatlocation receptacle55_toilet location_Xneg25_Ypos19_place74_room1_floorA)
	(receptacleatlocation receptacle56_toilet location_Xneg25_Ypos21_place75_room3_floorB)
	(receptacleatlocation receptacle57_toilet location_Xneg39_Yneg29_place76_room2_floorB)
	(receptacleatlocation receptacle5_chair location_Xneg43_Ypos13_place44_room15_floorB)
	(receptacleatlocation receptacle61_oven location_Xneg72_Yneg33_place77_room17_floorB)
	(receptacleatlocation receptacle62_oven location_Xneg71_Yneg34_place78_room17_floorB)
	(receptacleatlocation receptacle63_oven location_Xneg43_Yneg25_place79_room25_floorA)
	(receptacleatlocation receptacle64_sink location_Xneg34_Ypos21_place80_room1_floorA)
	(receptacleatlocation receptacle65_sink location_Xneg23_Ypos13_place81_room3_floorB)
	(receptacleatlocation receptacle66_sink location_Xneg95_Yneg23_place82_room4_floorB)
	(receptacleatlocation receptacle67_refrigerator location_Xneg46_Yneg32_place83_room25_floorA)
	(receptacleatlocation receptacle68_refrigerator location_Xneg59_Yneg25_place84_room17_floorB)
	(receptacleatlocation receptacle69_refrigerator location_Xneg22_Yneg27_place85_room6_floorC)
	(receptacleatlocation receptacle6_chair location_Xneg79_Yneg4_place45_room17_floorB)
	(receptacleatlocation receptacle70_refrigerator location_Xneg81_Yneg11_place86_room18_floorA)
	(receptacleatlocation receptacle7_chair location_Xneg53_Ypos13_place46_room15_floorB)
	(receptacleatlocation receptacle8_chair location_Xneg11_Ypos15_place47_room20_floorB)
	(receptacleatlocation receptacle9_chair location_Xneg89_Yneg5_place48_room17_floorB)
	(receptacleopeningtype receptacle61_oven)
	(receptacleopeningtype receptacle62_oven)
	(receptacleopeningtype receptacle63_oven)
	(receptacleopeningtype receptacle67_refrigerator)
	(receptacleopeningtype receptacle68_refrigerator)
	(receptacleopeningtype receptacle69_refrigerator)
	(receptacleopeningtype receptacle70_refrigerator)
  )
  (:goal (and
	(inreceptacle item58_tv_largeitem receptacle65_sink)
	(inreceptacle item27_potted_plant_largeitem receptacle18_chair)
	(inreceptacle item82_book_smallitem receptacle56_toilet)
	(inreceptacle item59_tv_largeitem receptacle19_chair)
	(inreceptacle item89_vase_mediumitem receptacle20_couch)
	(inreceptacle item43_potted_plant_largeitem receptacle5_chair)
	(inreceptacle item79_book_smallitem receptacle56_toilet)
	(inreceptacle item91_vase_mediumitem receptacle14_chair)
	(inreceptacle item42_potted_plant_largeitem receptacle44_bed)
	(inreceptacle item93_vase_mediumitem receptacle57_toilet)))
)
