
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_bowl_smallitem - item
	item11_bowl_smallitem - item
	item1_bottle_smallitem - item
	item22_potted_plant_largeitem - item
	item23_potted_plant_largeitem - item
	item24_potted_plant_largeitem - item
	item25_potted_plant_largeitem - item
	item2_bottle_smallitem - item
	item32_tv_largeitem - item
	item33_laptop_mediumitem - item
	item3_bottle_smallitem - item
	item4_bottle_smallitem - item
	item50_book_smallitem - item
	item51_clock_mediumitem - item
	item52_vase_mediumitem - item
	item53_vase_mediumitem - item
	item5_cup_smallitem - item
	item6_knife_smallitem - item
	item7_bowl_smallitem - item
	item8_bowl_smallitem - item
	item9_bowl_smallitem - item
	location_Xneg14_Yneg6_place23_room10_floorB - location
	location_Xneg16_Ypos5_place24_room10_floorB - location
	location_Xneg19_Ypos13_place16_room11_floorA - location
	location_Xneg20_Yneg3_place25_room10_floorB - location
	location_Xneg21_Ypos11_place15_room11_floorA - location
	location_Xneg24_Ypos10_place43_room2_floorC - location
	location_Xneg26_Yneg30_place20_room14_floorB - location
	location_Xneg28_Yneg19_place40_room2_floorC - location
	location_Xneg28_Yneg4_place21_room13_floorB - location
	location_Xneg28_Yneg6_place41_room2_floorC - location
	location_Xneg28_Ypos10_place21_room13_floorB - location
	location_Xneg28_Ypos3_place33_room2_floorC - location
	location_Xneg2_Yneg6_place26_room14_floorB - location
	location_Xneg2_Yneg7_place27_room14_floorB - location
	location_Xneg30_Ypos12_place42_room2_floorC - location
	location_Xneg32_Yneg25_place11_room15_floorA - location
	location_Xneg32_Ypos13_place36_room13_floorB - location
	location_Xneg33_Yneg19_place44_room11_floorA - location
	location_Xneg33_Yneg7_place21_room13_floorB - location
	location_Xneg33_Yneg8_place21_room13_floorB - location
	location_Xneg33_Ypos11_place36_room13_floorB - location
	location_Xneg34_Yneg9_place21_room13_floorB - location
	location_Xneg38_Yneg20_place45_room11_floorA - location
	location_Xneg40_Yneg39_place32_room3_floorC - location
	location_Xneg41_Yneg45_place30_room15_floorA - location
	location_Xneg45_Ypos10_place36_room13_floorB - location
	location_Xneg45_Ypos11_place34_room13_floorB - location
	location_Xneg46_Ypos13_place29_room5_floorC - location
	location_Xneg47_Ypos1_place29_room5_floorC - location
	location_Xneg49_Yneg33_place38_room1_floorB - location
	location_Xneg53_Yneg2_place35_room13_floorB - location
	location_Xneg55_Yneg24_place48_room13_floorB - location
	location_Xneg55_Yneg40_place32_room3_floorC - location
	location_Xneg56_Yneg17_place49_room5_floorC - location
	location_Xneg56_Yneg30_place39_room3_floorC - location
	location_Xneg56_Yneg34_place31_room1_floorB - location
	location_Xneg57_Yneg11_place37_room13_floorB - location
	location_Xneg58_Yneg15_place37_room13_floorB - location
	location_Xneg58_Yneg28_place39_room3_floorC - location
	location_Xneg58_Ypos6_place35_room13_floorB - location
	location_Xneg6_Yneg30_place22_room14_floorB - location
	location_Xpos10_Yneg19_place13_room12_floorA - location
	location_Xpos10_Ypos10_place26_room14_floorB - location
	location_Xpos11_Yneg42_place18_room12_floorA - location
	location_Xpos13_Yneg21_place19_room14_floorB - location
	location_Xpos15_Ypos10_place14_room14_floorB - location
	location_Xpos16_Yneg1_place46_room11_floorA - location
	location_Xpos16_Ypos11_place17_room14_floorB - location
	location_Xpos18_Ypos3_place47_room11_floorA - location
	location_Xpos2_Yneg41_place18_room12_floorA - location
	location_Xpos2_Ypos3_place28_room4_floorC - location
	location_Xpos6_Yneg14_place46_room11_floorA - location
	location_Xpos8_Yneg19_place12_room12_floorA - location
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_couch - receptacle
	receptacle21_couch - receptacle
	receptacle26_bed - receptacle
	receptacle27_bed - receptacle
	receptacle28_toilet - receptacle
	receptacle29_toilet - receptacle
	receptacle30_toilet - receptacle
	receptacle31_toilet - receptacle
	receptacle34_microwave - receptacle
	receptacle35_oven - receptacle
	receptacle36_oven - receptacle
	receptacle37_sink - receptacle
	receptacle38_sink - receptacle
	receptacle39_sink - receptacle
	receptacle40_sink - receptacle
	receptacle41_sink - receptacle
	receptacle42_sink - receptacle
	receptacle43_sink - receptacle
	receptacle44_refrigerator - receptacle
	receptacle45_refrigerator - receptacle
	receptacle46_refrigerator - receptacle
	receptacle47_refrigerator - receptacle
	receptacle48_refrigerator - receptacle
	receptacle49_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg56_Yneg34_place31_room1_floorB)
	(inanyreceptacle item10_bowl_smallitem)
	(inanyreceptacle item11_bowl_smallitem)
	(inanyreceptacle item1_bottle_smallitem)
	(inanyreceptacle item25_potted_plant_largeitem)
	(inanyreceptacle item2_bottle_smallitem)
	(inanyreceptacle item32_tv_largeitem)
	(inanyreceptacle item33_laptop_mediumitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inanyreceptacle item51_clock_mediumitem)
	(inanyreceptacle item5_cup_smallitem)
	(inanyreceptacle item7_bowl_smallitem)
	(inanyreceptacle item8_bowl_smallitem)
	(inanyreceptacle item9_bowl_smallitem)
	(inreceptacle item10_bowl_smallitem receptacle36_oven)
	(inreceptacle item11_bowl_smallitem receptacle15_chair)
	(inreceptacle item1_bottle_smallitem receptacle46_refrigerator)
	(inreceptacle item25_potted_plant_largeitem receptacle15_chair)
	(inreceptacle item2_bottle_smallitem receptacle12_chair)
	(inreceptacle item32_tv_largeitem receptacle20_couch)
	(inreceptacle item33_laptop_mediumitem receptacle30_toilet)
	(inreceptacle item3_bottle_smallitem receptacle15_chair)
	(inreceptacle item4_bottle_smallitem receptacle15_chair)
	(inreceptacle item51_clock_mediumitem receptacle27_bed)
	(inreceptacle item5_cup_smallitem receptacle39_sink)
	(inreceptacle item7_bowl_smallitem receptacle37_sink)
	(inreceptacle item8_bowl_smallitem receptacle35_oven)
	(inreceptacle item9_bowl_smallitem receptacle36_oven)
	(itematlocation item10_bowl_smallitem location_Xneg32_Ypos13_place36_room13_floorB)
	(itematlocation item11_bowl_smallitem location_Xneg34_Yneg9_place21_room13_floorB)
	(itematlocation item1_bottle_smallitem location_Xpos6_Yneg14_place46_room11_floorA)
	(itematlocation item22_potted_plant_largeitem location_Xneg21_Ypos11_place15_room11_floorA)
	(itematlocation item23_potted_plant_largeitem location_Xneg19_Ypos13_place16_room11_floorA)
	(itematlocation item24_potted_plant_largeitem location_Xpos16_Ypos11_place17_room14_floorB)
	(itematlocation item25_potted_plant_largeitem location_Xneg28_Ypos10_place21_room13_floorB)
	(itematlocation item2_bottle_smallitem location_Xpos11_Yneg42_place18_room12_floorA)
	(itematlocation item32_tv_largeitem location_Xpos10_Ypos10_place26_room14_floorB)
	(itematlocation item33_laptop_mediumitem location_Xneg40_Yneg39_place32_room3_floorC)
	(itematlocation item3_bottle_smallitem location_Xneg33_Yneg8_place21_room13_floorB)
	(itematlocation item4_bottle_smallitem location_Xneg33_Yneg7_place21_room13_floorB)
	(itematlocation item50_book_smallitem location_Xpos8_Yneg19_place12_room12_floorA)
	(itematlocation item51_clock_mediumitem location_Xneg46_Ypos13_place29_room5_floorC)
	(itematlocation item52_vase_mediumitem location_Xpos10_Yneg19_place13_room12_floorA)
	(itematlocation item53_vase_mediumitem location_Xpos15_Ypos10_place14_room14_floorB)
	(itematlocation item5_cup_smallitem location_Xneg58_Yneg28_place39_room3_floorC)
	(itematlocation item6_knife_smallitem location_Xneg32_Yneg25_place11_room15_floorA)
	(itematlocation item7_bowl_smallitem location_Xneg58_Yneg15_place37_room13_floorB)
	(itematlocation item8_bowl_smallitem location_Xneg58_Ypos6_place35_room13_floorB)
	(itematlocation item9_bowl_smallitem location_Xneg33_Ypos11_place36_room13_floorB)
	(receptacleatlocation receptacle12_chair location_Xpos2_Yneg41_place18_room12_floorA)
	(receptacleatlocation receptacle13_chair location_Xpos13_Yneg21_place19_room14_floorB)
	(receptacleatlocation receptacle14_chair location_Xneg26_Yneg30_place20_room14_floorB)
	(receptacleatlocation receptacle15_chair location_Xneg28_Yneg4_place21_room13_floorB)
	(receptacleatlocation receptacle16_chair location_Xneg6_Yneg30_place22_room14_floorB)
	(receptacleatlocation receptacle17_chair location_Xneg14_Yneg6_place23_room10_floorB)
	(receptacleatlocation receptacle18_chair location_Xneg16_Ypos5_place24_room10_floorB)
	(receptacleatlocation receptacle19_chair location_Xneg20_Yneg3_place25_room10_floorB)
	(receptacleatlocation receptacle20_couch location_Xneg2_Yneg6_place26_room14_floorB)
	(receptacleatlocation receptacle21_couch location_Xneg2_Yneg7_place27_room14_floorB)
	(receptacleatlocation receptacle26_bed location_Xpos2_Ypos3_place28_room4_floorC)
	(receptacleatlocation receptacle27_bed location_Xneg47_Ypos1_place29_room5_floorC)
	(receptacleatlocation receptacle28_toilet location_Xneg41_Yneg45_place30_room15_floorA)
	(receptacleatlocation receptacle29_toilet location_Xneg56_Yneg34_place31_room1_floorB)
	(receptacleatlocation receptacle30_toilet location_Xneg55_Yneg40_place32_room3_floorC)
	(receptacleatlocation receptacle31_toilet location_Xneg28_Ypos3_place33_room2_floorC)
	(receptacleatlocation receptacle34_microwave location_Xneg45_Ypos11_place34_room13_floorB)
	(receptacleatlocation receptacle35_oven location_Xneg53_Yneg2_place35_room13_floorB)
	(receptacleatlocation receptacle36_oven location_Xneg45_Ypos10_place36_room13_floorB)
	(receptacleatlocation receptacle37_sink location_Xneg57_Yneg11_place37_room13_floorB)
	(receptacleatlocation receptacle38_sink location_Xneg49_Yneg33_place38_room1_floorB)
	(receptacleatlocation receptacle39_sink location_Xneg56_Yneg30_place39_room3_floorC)
	(receptacleatlocation receptacle40_sink location_Xneg28_Yneg19_place40_room2_floorC)
	(receptacleatlocation receptacle41_sink location_Xneg28_Yneg6_place41_room2_floorC)
	(receptacleatlocation receptacle42_sink location_Xneg30_Ypos12_place42_room2_floorC)
	(receptacleatlocation receptacle43_sink location_Xneg24_Ypos10_place43_room2_floorC)
	(receptacleatlocation receptacle44_refrigerator location_Xneg33_Yneg19_place44_room11_floorA)
	(receptacleatlocation receptacle45_refrigerator location_Xneg38_Yneg20_place45_room11_floorA)
	(receptacleatlocation receptacle46_refrigerator location_Xpos16_Yneg1_place46_room11_floorA)
	(receptacleatlocation receptacle47_refrigerator location_Xpos18_Ypos3_place47_room11_floorA)
	(receptacleatlocation receptacle48_refrigerator location_Xneg55_Yneg24_place48_room13_floorB)
	(receptacleatlocation receptacle49_refrigerator location_Xneg56_Yneg17_place49_room5_floorC)
	(receptacleopeningtype receptacle34_microwave)
	(receptacleopeningtype receptacle35_oven)
	(receptacleopeningtype receptacle36_oven)
	(receptacleopeningtype receptacle44_refrigerator)
	(receptacleopeningtype receptacle45_refrigerator)
	(receptacleopeningtype receptacle46_refrigerator)
	(receptacleopeningtype receptacle47_refrigerator)
	(receptacleopeningtype receptacle48_refrigerator)
	(receptacleopeningtype receptacle49_refrigerator)
  )
  (:goal (and
	(inreceptacle item11_bowl_smallitem receptacle16_chair)
	(inreceptacle item5_cup_smallitem receptacle45_refrigerator)
	(inreceptacle item50_book_smallitem receptacle35_oven)
	(inreceptacle item24_potted_plant_largeitem receptacle47_refrigerator)
	(inreceptacle item25_potted_plant_largeitem receptacle39_sink)
	(inreceptacle item3_bottle_smallitem receptacle44_refrigerator)
	(inreceptacle item53_vase_mediumitem receptacle36_oven)
	(inreceptacle item32_tv_largeitem receptacle35_oven)
	(inreceptacle item8_bowl_smallitem receptacle12_chair)
	(inreceptacle item51_clock_mediumitem receptacle20_couch)))
)
