
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item23_potted_plant_largeitem - item
	item24_potted_plant_largeitem - item
	item25_potted_plant_largeitem - item
	item26_potted_plant_largeitem - item
	item27_potted_plant_largeitem - item
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item2_frisbee_mediumitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item44_tv_largeitem - item
	item45_tv_largeitem - item
	item46_tv_largeitem - item
	item4_bottle_smallitem - item
	item54_book_smallitem - item
	item55_book_smallitem - item
	item56_clock_mediumitem - item
	item57_clock_mediumitem - item
	item58_clock_mediumitem - item
	item59_vase_mediumitem - item
	item5_bottle_smallitem - item
	item60_vase_mediumitem - item
	item6_bottle_smallitem - item
	item7_bowl_smallitem - item
	location_Xneg11_Ypos22_place21_room11_floorB - location
	location_Xneg12_Ypos38_place39_room2_floorC - location
	location_Xneg12_Ypos43_place29_room12_floorB - location
	location_Xneg14_Ypos8_place35_room4_floorC - location
	location_Xneg15_Yneg5_place42_room11_floorB - location
	location_Xneg17_Ypos72_place41_room3_floorC - location
	location_Xneg18_Ypos26_place11_room4_floorC - location
	location_Xneg18_Ypos58_place47_room9_floorA - location
	location_Xneg19_Ypos35_place43_room2_floorC - location
	location_Xneg21_Ypos50_place17_room3_floorC - location
	location_Xneg23_Yneg4_place42_room11_floorB - location
	location_Xneg3_Ypos16_place45_room11_floorB - location
	location_Xneg3_Ypos23_place26_room11_floorB - location
	location_Xneg3_Ypos52_place23_room12_floorB - location
	location_Xneg3_Ypos68_place41_room3_floorC - location
	location_Xneg5_Ypos52_place29_room12_floorB - location
	location_Xneg5_Ypos66_place33_room12_floorB - location
	location_Xneg6_Ypos40_place44_room2_floorC - location
	location_Xneg8_Ypos52_place29_room12_floorB - location
	location_Xneg9_Yneg1_place42_room11_floorB - location
	location_Xneg9_Yneg2_place42_room11_floorB - location
	location_Xpos0_Yneg5_place42_room11_floorB - location
	location_Xpos0_Ypos21_place25_room11_floorB - location
	location_Xpos11_Ypos0_place48_room11_floorB - location
	location_Xpos11_Ypos62_place32_room10_floorA - location
	location_Xpos13_Ypos59_place32_room10_floorA - location
	location_Xpos13_Ypos60_place32_room10_floorA - location
	location_Xpos14_Yneg1_place40_room1_floorA - location
	location_Xpos14_Yneg6_place40_room1_floorA - location
	location_Xpos18_Ypos25_place14_room6_floorA - location
	location_Xpos19_Ypos57_place28_room8_floorB - location
	location_Xpos21_Ypos49_place20_room8_floorB - location
	location_Xpos21_Ypos51_place19_room8_floorB - location
	location_Xpos23_Ypos51_place36_room8_floorB - location
	location_Xpos26_Ypos52_place27_room8_floorB - location
	location_Xpos28_Ypos52_place22_room8_floorB - location
	location_Xpos28_Ypos52_place30_room10_floorA - location
	location_Xpos28_Ypos60_place34_room5_floorC - location
	location_Xpos2_Yneg3_place12_room9_floorA - location
	location_Xpos2_Yneg6_place48_room11_floorB - location
	location_Xpos30_Ypos50_place31_room10_floorA - location
	location_Xpos35_Ypos50_place37_room10_floorA - location
	location_Xpos35_Ypos67_place22_room8_floorB - location
	location_Xpos36_Ypos49_place34_room5_floorC - location
	location_Xpos36_Ypos52_place22_room8_floorB - location
	location_Xpos36_Ypos54_place38_room10_floorA - location
	location_Xpos36_Ypos66_place34_room5_floorC - location
	location_Xpos36_Ypos69_place16_room8_floorB - location
	location_Xpos37_Ypos47_place37_room10_floorA - location
	location_Xpos37_Ypos48_place22_room8_floorB - location
	location_Xpos37_Ypos51_place22_room8_floorB - location
	location_Xpos38_Ypos69_place22_room8_floorB - location
	location_Xpos3_Ypos42_place23_room12_floorB - location
	location_Xpos4_Ypos23_place24_room11_floorB - location
	location_Xpos5_Ypos14_place35_room4_floorC - location
	location_Xpos5_Ypos18_place13_room4_floorC - location
	location_Xpos5_Ypos64_place18_room5_floorC - location
	location_Xpos5_Ypos9_place46_room1_floorA - location
	location_Xpos7_Ypos51_place15_room9_floorA - location
	location_Xpos8_Ypos12_place46_room1_floorA - location
	receptacle10_chair - receptacle
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_bench - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_couch - receptacle
	receptacle36_bed - receptacle
	receptacle37_bed - receptacle
	receptacle38_dining_table - receptacle
	receptacle39_dining_table - receptacle
	receptacle40_dining_table - receptacle
	receptacle41_toilet - receptacle
	receptacle42_toilet - receptacle
	receptacle43_toilet - receptacle
	receptacle47_oven - receptacle
	receptacle48_sink - receptacle
	receptacle49_sink - receptacle
	receptacle50_sink - receptacle
	receptacle51_sink - receptacle
	receptacle52_refrigerator - receptacle
	receptacle53_refrigerator - receptacle
	receptacle8_chair - receptacle
	receptacle9_chair - receptacle
  )
  (:init 
	(atlocation agent location_Xneg18_Ypos26_place11_room4_floorC)
	(inanyreceptacle item23_potted_plant_largeitem)
	(inanyreceptacle item24_potted_plant_largeitem)
	(inanyreceptacle item25_potted_plant_largeitem)
	(inanyreceptacle item26_potted_plant_largeitem)
	(inanyreceptacle item28_potted_plant_largeitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item44_tv_largeitem)
	(inanyreceptacle item45_tv_largeitem)
	(inanyreceptacle item54_book_smallitem)
	(inanyreceptacle item55_book_smallitem)
	(inanyreceptacle item58_clock_mediumitem)
	(inanyreceptacle item59_vase_mediumitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item60_vase_mediumitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bowl_smallitem)
	(inreceptacle item23_potted_plant_largeitem receptacle11_chair)
	(inreceptacle item24_potted_plant_largeitem receptacle11_chair)
	(inreceptacle item25_potted_plant_largeitem receptacle11_chair)
	(inreceptacle item26_potted_plant_largeitem receptacle11_chair)
	(inreceptacle item28_potted_plant_largeitem receptacle11_chair)
	(inreceptacle item30_potted_plant_largeitem receptacle18_chair)
	(inreceptacle item31_potted_plant_largeitem receptacle43_toilet)
	(inreceptacle item32_potted_plant_largeitem receptacle42_toilet)
	(inreceptacle item33_potted_plant_largeitem receptacle47_oven)
	(inreceptacle item34_potted_plant_largeitem receptacle21_chair)
	(inreceptacle item35_potted_plant_largeitem receptacle21_chair)
	(inreceptacle item3_bottle_smallitem receptacle51_sink)
	(inreceptacle item44_tv_largeitem receptacle47_oven)
	(inreceptacle item45_tv_largeitem receptacle37_bed)
	(inreceptacle item54_book_smallitem receptacle12_chair)
	(inreceptacle item55_book_smallitem receptacle18_chair)
	(inreceptacle item58_clock_mediumitem receptacle39_dining_table)
	(inreceptacle item59_vase_mediumitem receptacle36_bed)
	(inreceptacle item5_bottle_smallitem receptacle47_oven)
	(inreceptacle item60_vase_mediumitem receptacle36_bed)
	(inreceptacle item6_bottle_smallitem receptacle53_refrigerator)
	(inreceptacle item7_bowl_smallitem receptacle47_oven)
	(itematlocation item23_potted_plant_largeitem location_Xpos36_Ypos52_place22_room8_floorB)
	(itematlocation item24_potted_plant_largeitem location_Xpos37_Ypos48_place22_room8_floorB)
	(itematlocation item25_potted_plant_largeitem location_Xpos35_Ypos67_place22_room8_floorB)
	(itematlocation item26_potted_plant_largeitem location_Xpos38_Ypos69_place22_room8_floorB)
	(itematlocation item27_potted_plant_largeitem location_Xpos36_Ypos69_place16_room8_floorB)
	(itematlocation item28_potted_plant_largeitem location_Xpos37_Ypos51_place22_room8_floorB)
	(itematlocation item29_potted_plant_largeitem location_Xneg21_Ypos50_place17_room3_floorC)
	(itematlocation item2_frisbee_mediumitem location_Xneg18_Ypos26_place11_room4_floorC)
	(itematlocation item30_potted_plant_largeitem location_Xneg5_Ypos52_place29_room12_floorB)
	(itematlocation item31_potted_plant_largeitem location_Xneg17_Ypos72_place41_room3_floorC)
	(itematlocation item32_potted_plant_largeitem location_Xpos14_Yneg6_place40_room1_floorA)
	(itematlocation item33_potted_plant_largeitem location_Xneg23_Yneg4_place42_room11_floorB)
	(itematlocation item34_potted_plant_largeitem location_Xpos13_Ypos60_place32_room10_floorA)
	(itematlocation item35_potted_plant_largeitem location_Xpos11_Ypos62_place32_room10_floorA)
	(itematlocation item3_bottle_smallitem location_Xpos5_Ypos9_place46_room1_floorA)
	(itematlocation item44_tv_largeitem location_Xneg9_Yneg1_place42_room11_floorB)
	(itematlocation item45_tv_largeitem location_Xpos5_Ypos14_place35_room4_floorC)
	(itematlocation item46_tv_largeitem location_Xpos5_Ypos18_place13_room4_floorC)
	(itematlocation item4_bottle_smallitem location_Xpos2_Yneg3_place12_room9_floorA)
	(itematlocation item54_book_smallitem location_Xneg3_Ypos52_place23_room12_floorB)
	(itematlocation item55_book_smallitem location_Xneg8_Ypos52_place29_room12_floorB)
	(itematlocation item56_clock_mediumitem location_Xpos18_Ypos25_place14_room6_floorA)
	(itematlocation item57_clock_mediumitem location_Xpos7_Ypos51_place15_room9_floorA)
	(itematlocation item58_clock_mediumitem location_Xpos37_Ypos47_place37_room10_floorA)
	(itematlocation item59_vase_mediumitem location_Xpos36_Ypos49_place34_room5_floorC)
	(itematlocation item5_bottle_smallitem location_Xpos0_Yneg5_place42_room11_floorB)
	(itematlocation item60_vase_mediumitem location_Xpos36_Ypos66_place34_room5_floorC)
	(itematlocation item6_bottle_smallitem location_Xpos2_Yneg6_place48_room11_floorB)
	(itematlocation item7_bowl_smallitem location_Xneg15_Yneg5_place42_room11_floorB)
	(receptacleatlocation receptacle10_chair location_Xneg11_Ypos22_place21_room11_floorB)
	(receptacleatlocation receptacle11_chair location_Xpos28_Ypos52_place22_room8_floorB)
	(receptacleatlocation receptacle12_chair location_Xpos3_Ypos42_place23_room12_floorB)
	(receptacleatlocation receptacle13_chair location_Xpos4_Ypos23_place24_room11_floorB)
	(receptacleatlocation receptacle14_chair location_Xpos0_Ypos21_place25_room11_floorB)
	(receptacleatlocation receptacle15_chair location_Xneg3_Ypos23_place26_room11_floorB)
	(receptacleatlocation receptacle16_chair location_Xpos26_Ypos52_place27_room8_floorB)
	(receptacleatlocation receptacle17_chair location_Xpos19_Ypos57_place28_room8_floorB)
	(receptacleatlocation receptacle18_chair location_Xneg12_Ypos43_place29_room12_floorB)
	(receptacleatlocation receptacle19_chair location_Xpos28_Ypos52_place30_room10_floorA)
	(receptacleatlocation receptacle1_bench location_Xpos5_Ypos64_place18_room5_floorC)
	(receptacleatlocation receptacle20_chair location_Xpos30_Ypos50_place31_room10_floorA)
	(receptacleatlocation receptacle21_chair location_Xpos13_Ypos59_place32_room10_floorA)
	(receptacleatlocation receptacle22_couch location_Xneg5_Ypos66_place33_room12_floorB)
	(receptacleatlocation receptacle36_bed location_Xpos28_Ypos60_place34_room5_floorC)
	(receptacleatlocation receptacle37_bed location_Xneg14_Ypos8_place35_room4_floorC)
	(receptacleatlocation receptacle38_dining_table location_Xpos23_Ypos51_place36_room8_floorB)
	(receptacleatlocation receptacle39_dining_table location_Xpos35_Ypos50_place37_room10_floorA)
	(receptacleatlocation receptacle40_dining_table location_Xpos36_Ypos54_place38_room10_floorA)
	(receptacleatlocation receptacle41_toilet location_Xneg12_Ypos38_place39_room2_floorC)
	(receptacleatlocation receptacle42_toilet location_Xpos14_Yneg1_place40_room1_floorA)
	(receptacleatlocation receptacle43_toilet location_Xneg3_Ypos68_place41_room3_floorC)
	(receptacleatlocation receptacle47_oven location_Xneg9_Yneg2_place42_room11_floorB)
	(receptacleatlocation receptacle48_sink location_Xneg19_Ypos35_place43_room2_floorC)
	(receptacleatlocation receptacle49_sink location_Xneg6_Ypos40_place44_room2_floorC)
	(receptacleatlocation receptacle50_sink location_Xneg3_Ypos16_place45_room11_floorB)
	(receptacleatlocation receptacle51_sink location_Xpos8_Ypos12_place46_room1_floorA)
	(receptacleatlocation receptacle52_refrigerator location_Xneg18_Ypos58_place47_room9_floorA)
	(receptacleatlocation receptacle53_refrigerator location_Xpos11_Ypos0_place48_room11_floorB)
	(receptacleatlocation receptacle8_chair location_Xpos21_Ypos51_place19_room8_floorB)
	(receptacleatlocation receptacle9_chair location_Xpos21_Ypos49_place20_room8_floorB)
	(receptacleopeningtype receptacle47_oven)
	(receptacleopeningtype receptacle52_refrigerator)
	(receptacleopeningtype receptacle53_refrigerator)
  )
  (:goal (and
	(inreceptacle item31_potted_plant_largeitem receptacle41_toilet)
	(inreceptacle item59_vase_mediumitem receptacle48_sink)
	(inreceptacle item44_tv_largeitem receptacle9_chair)
	(inreceptacle item46_tv_largeitem receptacle11_chair)
	(inreceptacle item28_potted_plant_largeitem receptacle41_toilet)
	(inreceptacle item57_clock_mediumitem receptacle13_chair)
	(inreceptacle item5_bottle_smallitem receptacle37_bed)
	(inreceptacle item55_book_smallitem receptacle8_chair)
	(inreceptacle item26_potted_plant_largeitem receptacle40_dining_table)
	(inreceptacle item54_book_smallitem receptacle47_oven)))
)
