
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_bowl_smallitem - item
	item11_banana_smallitem - item
	item12_banana_smallitem - item
	item13_cake_mediumitem - item
	item14_cake_mediumitem - item
	item1_umbrella_largeitem - item
	item2_umbrella_largeitem - item
	item3_kite_largeitem - item
	item40_tv_largeitem - item
	item41_tv_largeitem - item
	item4_surfboard_largeitem - item
	item54_book_smallitem - item
	item55_book_smallitem - item
	item56_clock_mediumitem - item
	item57_vase_mediumitem - item
	item58_vase_mediumitem - item
	item59_vase_mediumitem - item
	item5_bottle_smallitem - item
	item60_vase_mediumitem - item
	item61_vase_mediumitem - item
	item62_vase_mediumitem - item
	item63_vase_mediumitem - item
	item64_vase_mediumitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item8_bottle_smallitem - item
	item9_bowl_smallitem - item
	location_Xneg10_Yneg23_place34_room18_floorB - location
	location_Xneg13_Yneg40_place42_room4_floorC - location
	location_Xneg14_Yneg26_place41_room4_floorC - location
	location_Xneg15_Ypos17_place31_room18_floorB - location
	location_Xneg16_Ypos19_place30_room18_floorB - location
	location_Xneg20_Ypos12_place56_room13_floorA - location
	location_Xneg21_Yneg7_place55_room13_floorA - location
	location_Xneg29_Yneg65_place38_room11_floorB - location
	location_Xneg33_Yneg80_place23_room11_floorB - location
	location_Xneg34_Yneg24_place32_room20_floorB - location
	location_Xneg34_Yneg79_place44_room11_floorB - location
	location_Xneg35_Yneg78_place44_room11_floorB - location
	location_Xneg35_Yneg79_place44_room11_floorB - location
	location_Xneg38_Yneg79_place22_room11_floorB - location
	location_Xneg40_Yneg73_place53_room2_floorC - location
	location_Xneg42_Yneg76_place53_room2_floorC - location
	location_Xneg43_Yneg84_place54_room2_floorC - location
	location_Xneg46_Yneg50_place52_room1_floorB - location
	location_Xneg48_Yneg38_place28_room12_floorB - location
	location_Xneg49_Yneg38_place20_room12_floorB - location
	location_Xneg49_Yneg39_place19_room12_floorB - location
	location_Xneg4_Yneg36_place34_room18_floorB - location
	location_Xneg4_Yneg4_place39_room15_floorC - location
	location_Xneg4_Yneg9_place36_room18_floorB - location
	location_Xneg50_Yneg28_place21_room14_floorA - location
	location_Xneg50_Yneg78_place48_room16_floorB - location
	location_Xneg51_Yneg49_place45_room1_floorB - location
	location_Xneg52_Yneg72_place48_room16_floorB - location
	location_Xneg54_Yneg13_place15_room14_floorA - location
	location_Xneg54_Yneg21_place25_room12_floorB - location
	location_Xneg55_Yneg49_place33_room3_floorC - location
	location_Xneg56_Yneg13_place27_room12_floorB - location
	location_Xneg57_Yneg20_place43_room3_floorC - location
	location_Xneg58_Yneg10_place16_room14_floorA - location
	location_Xneg58_Yneg86_place46_room2_floorC - location
	location_Xneg59_Yneg52_place33_room3_floorC - location
	location_Xneg60_Yneg25_place28_room12_floorB - location
	location_Xneg60_Yneg29_place43_room3_floorC - location
	location_Xneg62_Yneg18_place29_room12_floorB - location
	location_Xneg65_Yneg15_place26_room12_floorB - location
	location_Xneg65_Yneg20_place24_room12_floorB - location
	location_Xneg65_Yneg87_place57_room14_floorA - location
	location_Xneg67_Yneg57_place58_room16_floorB - location
	location_Xneg69_Yneg57_place47_room21_floorA - location
	location_Xneg70_Yneg48_place51_room17_floorB - location
	location_Xneg70_Yneg62_place47_room21_floorA - location
	location_Xneg70_Yneg72_place50_room16_floorB - location
	location_Xneg70_Yneg74_place47_room21_floorA - location
	location_Xneg70_Yneg79_place50_room16_floorB - location
	location_Xneg72_Yneg80_place50_room16_floorB - location
	location_Xneg73_Yneg43_place51_room17_floorB - location
	location_Xneg73_Yneg82_place50_room16_floorB - location
	location_Xneg74_Yneg29_place24_room12_floorB - location
	location_Xpos11_Ypos2_place17_room13_floorA - location
	location_Xpos13_Yneg14_place18_room6_floorC - location
	location_Xpos13_Yneg24_place49_room18_floorB - location
	location_Xpos13_Yneg36_place49_room18_floorB - location
	location_Xpos13_Yneg37_place49_room18_floorB - location
	location_Xpos13_Ypos11_place35_room18_floorB - location
	location_Xpos3_Yneg59_place40_room18_floorB - location
	location_Xpos3_Ypos14_place35_room18_floorB - location
	location_Xpos5_Yneg57_place37_room18_floorB - location
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_couch - receptacle
	receptacle28_couch - receptacle
	receptacle29_couch - receptacle
	receptacle30_couch - receptacle
	receptacle31_couch - receptacle
	receptacle32_couch - receptacle
	receptacle33_bed - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_bed - receptacle
	receptacle37_dining_table - receptacle
	receptacle38_toilet - receptacle
	receptacle39_toilet - receptacle
	receptacle42_oven - receptacle
	receptacle43_oven - receptacle
	receptacle44_oven - receptacle
	receptacle45_sink - receptacle
	receptacle46_sink - receptacle
	receptacle47_sink - receptacle
	receptacle48_sink - receptacle
	receptacle49_sink - receptacle
	receptacle50_refrigerator - receptacle
	receptacle51_refrigerator - receptacle
	receptacle52_refrigerator - receptacle
	receptacle53_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg34_Yneg24_place32_room20_floorB)
	(inanyreceptacle item10_bowl_smallitem)
	(inanyreceptacle item13_cake_mediumitem)
	(inanyreceptacle item14_cake_mediumitem)
	(inanyreceptacle item40_tv_largeitem)
	(inanyreceptacle item41_tv_largeitem)
	(inanyreceptacle item54_book_smallitem)
	(inanyreceptacle item55_book_smallitem)
	(inanyreceptacle item57_vase_mediumitem)
	(inanyreceptacle item58_vase_mediumitem)
	(inanyreceptacle item59_vase_mediumitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item60_vase_mediumitem)
	(inanyreceptacle item61_vase_mediumitem)
	(inanyreceptacle item62_vase_mediumitem)
	(inanyreceptacle item63_vase_mediumitem)
	(inanyreceptacle item64_vase_mediumitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item9_bowl_smallitem)
	(inreceptacle item10_bowl_smallitem receptacle44_oven)
	(inreceptacle item13_cake_mediumitem receptacle44_oven)
	(inreceptacle item14_cake_mediumitem receptacle44_oven)
	(inreceptacle item40_tv_largeitem receptacle17_chair)
	(inreceptacle item41_tv_largeitem receptacle28_couch)
	(inreceptacle item54_book_smallitem receptacle27_couch)
	(inreceptacle item55_book_smallitem receptacle36_bed)
	(inreceptacle item57_vase_mediumitem receptacle45_sink)
	(inreceptacle item58_vase_mediumitem receptacle37_dining_table)
	(inreceptacle item59_vase_mediumitem receptacle37_dining_table)
	(inreceptacle item5_bottle_smallitem receptacle42_oven)
	(inreceptacle item60_vase_mediumitem receptacle43_oven)
	(inreceptacle item61_vase_mediumitem receptacle45_sink)
	(inreceptacle item62_vase_mediumitem receptacle45_sink)
	(inreceptacle item63_vase_mediumitem receptacle46_sink)
	(inreceptacle item64_vase_mediumitem receptacle26_chair)
	(inreceptacle item6_bottle_smallitem receptacle42_oven)
	(inreceptacle item7_bottle_smallitem receptacle37_dining_table)
	(inreceptacle item8_bottle_smallitem receptacle48_sink)
	(inreceptacle item9_bowl_smallitem receptacle21_chair)
	(itematlocation item10_bowl_smallitem location_Xpos13_Yneg37_place49_room18_floorB)
	(itematlocation item11_banana_smallitem location_Xneg49_Yneg39_place19_room12_floorB)
	(itematlocation item12_banana_smallitem location_Xneg49_Yneg38_place20_room12_floorB)
	(itematlocation item13_cake_mediumitem location_Xpos13_Yneg37_place49_room18_floorB)
	(itematlocation item14_cake_mediumitem location_Xpos13_Yneg36_place49_room18_floorB)
	(itematlocation item1_umbrella_largeitem location_Xneg54_Yneg13_place15_room14_floorA)
	(itematlocation item2_umbrella_largeitem location_Xneg58_Yneg10_place16_room14_floorA)
	(itematlocation item3_kite_largeitem location_Xpos11_Ypos2_place17_room13_floorA)
	(itematlocation item40_tv_largeitem location_Xneg74_Yneg29_place24_room12_floorB)
	(itematlocation item41_tv_largeitem location_Xpos13_Ypos11_place35_room18_floorB)
	(itematlocation item4_surfboard_largeitem location_Xpos13_Yneg14_place18_room6_floorC)
	(itematlocation item54_book_smallitem location_Xneg10_Yneg23_place34_room18_floorB)
	(itematlocation item55_book_smallitem location_Xneg60_Yneg29_place43_room3_floorC)
	(itematlocation item56_clock_mediumitem location_Xneg50_Yneg28_place21_room14_floorA)
	(itematlocation item57_vase_mediumitem location_Xneg72_Yneg80_place50_room16_floorB)
	(itematlocation item58_vase_mediumitem location_Xneg35_Yneg79_place44_room11_floorB)
	(itematlocation item59_vase_mediumitem location_Xneg34_Yneg79_place44_room11_floorB)
	(itematlocation item5_bottle_smallitem location_Xneg70_Yneg62_place47_room21_floorA)
	(itematlocation item60_vase_mediumitem location_Xneg50_Yneg78_place48_room16_floorB)
	(itematlocation item61_vase_mediumitem location_Xneg70_Yneg79_place50_room16_floorB)
	(itematlocation item62_vase_mediumitem location_Xneg73_Yneg82_place50_room16_floorB)
	(itematlocation item63_vase_mediumitem location_Xneg73_Yneg43_place51_room17_floorB)
	(itematlocation item64_vase_mediumitem location_Xneg59_Yneg52_place33_room3_floorC)
	(itematlocation item6_bottle_smallitem location_Xneg70_Yneg74_place47_room21_floorA)
	(itematlocation item7_bottle_smallitem location_Xneg35_Yneg78_place44_room11_floorB)
	(itematlocation item8_bottle_smallitem location_Xneg40_Yneg73_place53_room2_floorC)
	(itematlocation item9_bowl_smallitem location_Xneg48_Yneg38_place28_room12_floorB)
	(receptacleatlocation receptacle15_chair location_Xneg38_Yneg79_place22_room11_floorB)
	(receptacleatlocation receptacle16_chair location_Xneg33_Yneg80_place23_room11_floorB)
	(receptacleatlocation receptacle17_chair location_Xneg65_Yneg20_place24_room12_floorB)
	(receptacleatlocation receptacle18_chair location_Xneg54_Yneg21_place25_room12_floorB)
	(receptacleatlocation receptacle19_chair location_Xneg65_Yneg15_place26_room12_floorB)
	(receptacleatlocation receptacle20_chair location_Xneg56_Yneg13_place27_room12_floorB)
	(receptacleatlocation receptacle21_chair location_Xneg60_Yneg25_place28_room12_floorB)
	(receptacleatlocation receptacle22_chair location_Xneg62_Yneg18_place29_room12_floorB)
	(receptacleatlocation receptacle23_chair location_Xneg16_Ypos19_place30_room18_floorB)
	(receptacleatlocation receptacle24_chair location_Xneg15_Ypos17_place31_room18_floorB)
	(receptacleatlocation receptacle25_chair location_Xneg34_Yneg24_place32_room20_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg55_Yneg49_place33_room3_floorC)
	(receptacleatlocation receptacle27_couch location_Xneg4_Yneg36_place34_room18_floorB)
	(receptacleatlocation receptacle28_couch location_Xpos3_Ypos14_place35_room18_floorB)
	(receptacleatlocation receptacle29_couch location_Xneg4_Yneg9_place36_room18_floorB)
	(receptacleatlocation receptacle30_couch location_Xpos5_Yneg57_place37_room18_floorB)
	(receptacleatlocation receptacle31_couch location_Xneg29_Yneg65_place38_room11_floorB)
	(receptacleatlocation receptacle32_couch location_Xneg4_Yneg4_place39_room15_floorC)
	(receptacleatlocation receptacle33_bed location_Xpos3_Yneg59_place40_room18_floorB)
	(receptacleatlocation receptacle34_bed location_Xneg14_Yneg26_place41_room4_floorC)
	(receptacleatlocation receptacle35_bed location_Xneg13_Yneg40_place42_room4_floorC)
	(receptacleatlocation receptacle36_bed location_Xneg57_Yneg20_place43_room3_floorC)
	(receptacleatlocation receptacle37_dining_table location_Xneg35_Yneg79_place44_room11_floorB)
	(receptacleatlocation receptacle38_toilet location_Xneg51_Yneg49_place45_room1_floorB)
	(receptacleatlocation receptacle39_toilet location_Xneg58_Yneg86_place46_room2_floorC)
	(receptacleatlocation receptacle42_oven location_Xneg69_Yneg57_place47_room21_floorA)
	(receptacleatlocation receptacle43_oven location_Xneg52_Yneg72_place48_room16_floorB)
	(receptacleatlocation receptacle44_oven location_Xpos13_Yneg24_place49_room18_floorB)
	(receptacleatlocation receptacle45_sink location_Xneg70_Yneg72_place50_room16_floorB)
	(receptacleatlocation receptacle46_sink location_Xneg70_Yneg48_place51_room17_floorB)
	(receptacleatlocation receptacle47_sink location_Xneg46_Yneg50_place52_room1_floorB)
	(receptacleatlocation receptacle48_sink location_Xneg42_Yneg76_place53_room2_floorC)
	(receptacleatlocation receptacle49_sink location_Xneg43_Yneg84_place54_room2_floorC)
	(receptacleatlocation receptacle50_refrigerator location_Xneg21_Yneg7_place55_room13_floorA)
	(receptacleatlocation receptacle51_refrigerator location_Xneg20_Ypos12_place56_room13_floorA)
	(receptacleatlocation receptacle52_refrigerator location_Xneg65_Yneg87_place57_room14_floorA)
	(receptacleatlocation receptacle53_refrigerator location_Xneg67_Yneg57_place58_room16_floorB)
	(receptacleopeningtype receptacle42_oven)
	(receptacleopeningtype receptacle43_oven)
	(receptacleopeningtype receptacle44_oven)
	(receptacleopeningtype receptacle50_refrigerator)
	(receptacleopeningtype receptacle51_refrigerator)
	(receptacleopeningtype receptacle52_refrigerator)
	(receptacleopeningtype receptacle53_refrigerator)
  )
  (:goal (and
	(inreceptacle item60_vase_mediumitem receptacle32_couch)
	(inreceptacle item2_umbrella_largeitem receptacle19_chair)
	(inreceptacle item11_banana_smallitem receptacle46_sink)
	(inreceptacle item5_bottle_smallitem receptacle25_chair)
	(inreceptacle item62_vase_mediumitem receptacle21_chair)
	(inreceptacle item59_vase_mediumitem receptacle49_sink)
	(inreceptacle item9_bowl_smallitem receptacle31_couch)
	(inreceptacle item41_tv_largeitem receptacle52_refrigerator)
	(inreceptacle item57_vase_mediumitem receptacle42_oven)
	(inreceptacle item64_vase_mediumitem receptacle45_sink)))
)
