
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item100_book_smallitem - item
	item101_book_smallitem - item
	item102_book_smallitem - item
	item103_book_smallitem - item
	item104_book_smallitem - item
	item105_book_smallitem - item
	item106_clock_mediumitem - item
	item107_clock_mediumitem - item
	item108_clock_mediumitem - item
	item109_clock_mediumitem - item
	item10_cup_smallitem - item
	item110_vase_mediumitem - item
	item111_vase_mediumitem - item
	item112_vase_mediumitem - item
	item113_vase_mediumitem - item
	item114_vase_mediumitem - item
	item11_spoon_smallitem - item
	item12_bowl_smallitem - item
	item13_apple_smallitem - item
	item14_orange_smallitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item50_potted_plant_largeitem - item
	item51_potted_plant_largeitem - item
	item52_potted_plant_largeitem - item
	item53_potted_plant_largeitem - item
	item54_potted_plant_largeitem - item
	item55_potted_plant_largeitem - item
	item56_potted_plant_largeitem - item
	item57_potted_plant_largeitem - item
	item58_potted_plant_largeitem - item
	item59_potted_plant_largeitem - item
	item60_potted_plant_largeitem - item
	item63_potted_plant_largeitem - item
	item64_potted_plant_largeitem - item
	item6_handbag_largeitem - item
	item76_tv_largeitem - item
	item77_tv_largeitem - item
	item78_tv_largeitem - item
	item79_remote_smallitem - item
	item7_bottle_smallitem - item
	item80_remote_smallitem - item
	item8_cup_smallitem - item
	item90_book_smallitem - item
	item91_book_smallitem - item
	item92_book_smallitem - item
	item93_book_smallitem - item
	item94_book_smallitem - item
	item95_book_smallitem - item
	item96_book_smallitem - item
	item97_book_smallitem - item
	item98_book_smallitem - item
	item99_book_smallitem - item
	item9_cup_smallitem - item
	location_Xneg107_Yneg108_place27_room18_floorB - location
	location_Xneg12_Yneg101_place45_room24_floorA - location
	location_Xneg13_Ypos7_place57_room5_floorB - location
	location_Xneg14_Ypos0_place56_room5_floorB - location
	location_Xneg19_Yneg127_place20_room12_floorB - location
	location_Xneg19_Yneg127_place36_room12_floorB - location
	location_Xneg1_Yneg48_place33_room16_floorB - location
	location_Xneg1_Yneg59_place88_room17_floorA - location
	location_Xneg26_Yneg59_place85_room1_floorA - location
	location_Xneg27_Yneg63_place79_room2_floorB - location
	location_Xneg28_Yneg14_place72_room5_floorB - location
	location_Xneg28_Yneg5_place71_room4_floorA - location
	location_Xneg2_Yneg19_place67_room19_floorA - location
	location_Xneg2_Yneg84_place78_room10_floorB - location
	location_Xneg33_Yneg58_place80_room1_floorA - location
	location_Xneg33_Yneg84_place43_room24_floorA - location
	location_Xneg36_Yneg44_place84_room2_floorB - location
	location_Xneg37_Yneg59_place79_room2_floorB - location
	location_Xneg37_Yneg80_place65_room20_floorB - location
	location_Xneg37_Ypos9_place28_room5_floorB - location
	location_Xneg38_Yneg24_place72_room5_floorB - location
	location_Xneg38_Yneg69_place65_room20_floorB - location
	location_Xneg39_Yneg123_place48_room21_floorB - location
	location_Xneg39_Yneg81_place65_room20_floorB - location
	location_Xneg3_Yneg50_place62_room17_floorA - location
	location_Xneg3_Ypos8_place63_room6_floorB - location
	location_Xneg41_Yneg82_place65_room20_floorB - location
	location_Xneg42_Yneg56_place79_room2_floorB - location
	location_Xneg44_Yneg59_place65_room20_floorB - location
	location_Xneg44_Yneg70_place64_room24_floorA - location
	location_Xneg44_Yneg84_place76_room24_floorA - location
	location_Xneg45_Yneg166_place40_room21_floorB - location
	location_Xneg45_Yneg85_place76_room24_floorA - location
	location_Xneg47_Yneg144_place69_room21_floorB - location
	location_Xneg48_Yneg143_place69_room21_floorB - location
	location_Xneg49_Yneg168_place39_room21_floorB - location
	location_Xneg4_Ypos6_place63_room6_floorB - location
	location_Xneg51_Yneg145_place69_room21_floorB - location
	location_Xneg53_Yneg92_place55_room20_floorB - location
	location_Xneg54_Yneg144_place47_room21_floorB - location
	location_Xneg56_Yneg92_place66_room20_floorB - location
	location_Xneg58_Yneg79_place44_room24_floorA - location
	location_Xneg65_Yneg69_place44_room24_floorA - location
	location_Xneg67_Yneg107_place90_room24_floorA - location
	location_Xneg68_Yneg107_place24_room20_floorB - location
	location_Xneg68_Yneg132_place70_room21_floorB - location
	location_Xneg69_Yneg67_place26_room20_floorB - location
	location_Xneg6_Yneg73_place42_room16_floorB - location
	location_Xneg70_Yneg91_place66_room20_floorB - location
	location_Xneg71_Yneg68_place34_room20_floorB - location
	location_Xneg71_Yneg74_place35_room20_floorB - location
	location_Xneg71_Yneg90_place22_room20_floorB - location
	location_Xneg71_Yneg90_place66_room20_floorB - location
	location_Xneg72_Yneg74_place38_room20_floorB - location
	location_Xneg72_Yneg91_place21_room20_floorB - location
	location_Xneg73_Yneg87_place23_room20_floorB - location
	location_Xneg77_Yneg146_place70_room21_floorB - location
	location_Xneg77_Yneg147_place70_room21_floorB - location
	location_Xneg78_Yneg142_place70_room21_floorB - location
	location_Xneg78_Yneg146_place70_room21_floorB - location
	location_Xneg7_Yneg3_place56_room5_floorB - location
	location_Xneg7_Yneg68_place42_room16_floorB - location
	location_Xneg7_Yneg71_place42_room16_floorB - location
	location_Xneg81_Yneg125_place83_room18_floorB - location
	location_Xneg82_Yneg121_place83_room18_floorB - location
	location_Xneg82_Yneg133_place87_room18_floorB - location
	location_Xneg82_Yneg90_place58_room15_floorB - location
	location_Xneg83_Yneg89_place58_room15_floorB - location
	location_Xneg8_Yneg97_place45_room24_floorA - location
	location_Xneg8_Ypos6_place57_room5_floorB - location
	location_Xneg90_Yneg162_place52_room14_floorB - location
	location_Xneg92_Yneg155_place53_room14_floorB - location
	location_Xneg93_Yneg151_place49_room14_floorB - location
	location_Xneg93_Yneg159_place54_room14_floorB - location
	location_Xneg93_Yneg160_place54_room14_floorB - location
	location_Xneg93_Yneg169_place50_room14_floorB - location
	location_Xneg97_Yneg159_place51_room14_floorB - location
	location_Xneg97_Yneg93_place58_room15_floorB - location
	location_Xneg99_Yneg90_place77_room15_floorB - location
	location_Xneg9_Yneg133_place89_room7_floorB - location
	location_Xpos11_Yneg70_place59_room16_floorB - location
	location_Xpos11_Yneg99_place31_room23_floorA - location
	location_Xpos12_Yneg100_place29_room23_floorA - location
	location_Xpos12_Yneg78_place41_room16_floorB - location
	location_Xpos12_Ypos7_place63_room6_floorB - location
	location_Xpos15_Yneg100_place30_room23_floorA - location
	location_Xpos16_Yneg129_place73_room7_floorB - location
	location_Xpos17_Yneg13_place74_room6_floorB - location
	location_Xpos17_Yneg7_place68_room19_floorA - location
	location_Xpos18_Yneg75_place86_room17_floorA - location
	location_Xpos19_Ypos4_place68_room19_floorA - location
	location_Xpos20_Yneg105_place25_room7_floorB - location
	location_Xpos21_Yneg55_place60_room13_floorA - location
	location_Xpos21_Yneg57_place46_room16_floorB - location
	location_Xpos21_Yneg59_place75_room13_floorA - location
	location_Xpos21_Yneg62_place61_room13_floorA - location
	location_Xpos23_Yneg76_place86_room17_floorA - location
	location_Xpos24_Yneg85_place81_room3_floorB - location
	location_Xpos25_Yneg118_place73_room7_floorB - location
	location_Xpos25_Yneg74_place86_room17_floorA - location
	location_Xpos27_Yneg119_place73_room7_floorB - location
	location_Xpos27_Yneg22_place74_room6_floorB - location
	location_Xpos5_Yneg48_place32_room16_floorB - location
	location_Xpos5_Yneg74_place82_room17_floorA - location
	location_Xpos8_Yneg107_place37_room7_floorB - location
	location_Xpos8_Yneg18_place67_room19_floorA - location
	location_Xpos8_Yneg77_place42_room16_floorB - location
	location_Xpos9_Yneg21_place67_room19_floorA - location
	location_Xpos9_Yneg77_place41_room16_floorB - location
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_bench - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_bench - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_couch - receptacle
	receptacle37_couch - receptacle
	receptacle38_couch - receptacle
	receptacle39_couch - receptacle
	receptacle3_bench - receptacle
	receptacle40_couch - receptacle
	receptacle41_couch - receptacle
	receptacle42_couch - receptacle
	receptacle4_bench - receptacle
	receptacle65_bed - receptacle
	receptacle66_bed - receptacle
	receptacle67_bed - receptacle
	receptacle68_bed - receptacle
	receptacle69_dining_table - receptacle
	receptacle70_dining_table - receptacle
	receptacle71_dining_table - receptacle
	receptacle72_dining_table - receptacle
	receptacle73_toilet - receptacle
	receptacle74_toilet - receptacle
	receptacle75_toilet - receptacle
	receptacle81_oven - receptacle
	receptacle82_oven - receptacle
	receptacle83_sink - receptacle
	receptacle84_sink - receptacle
	receptacle85_sink - receptacle
	receptacle86_refrigerator - receptacle
	receptacle87_refrigerator - receptacle
	receptacle88_refrigerator - receptacle
	receptacle89_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xpos21_Yneg62_place61_room13_floorA)
	(inanyreceptacle item102_book_smallitem)
	(inanyreceptacle item103_book_smallitem)
	(inanyreceptacle item104_book_smallitem)
	(inanyreceptacle item106_clock_mediumitem)
	(inanyreceptacle item107_clock_mediumitem)
	(inanyreceptacle item108_clock_mediumitem)
	(inanyreceptacle item109_clock_mediumitem)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item112_vase_mediumitem)
	(inanyreceptacle item113_vase_mediumitem)
	(inanyreceptacle item11_spoon_smallitem)
	(inanyreceptacle item12_bowl_smallitem)
	(inanyreceptacle item13_apple_smallitem)
	(inanyreceptacle item14_orange_smallitem)
	(inanyreceptacle item43_potted_plant_largeitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item51_potted_plant_largeitem)
	(inanyreceptacle item52_potted_plant_largeitem)
	(inanyreceptacle item53_potted_plant_largeitem)
	(inanyreceptacle item54_potted_plant_largeitem)
	(inanyreceptacle item55_potted_plant_largeitem)
	(inanyreceptacle item56_potted_plant_largeitem)
	(inanyreceptacle item58_potted_plant_largeitem)
	(inanyreceptacle item59_potted_plant_largeitem)
	(inanyreceptacle item60_potted_plant_largeitem)
	(inanyreceptacle item6_handbag_largeitem)
	(inanyreceptacle item77_tv_largeitem)
	(inanyreceptacle item79_remote_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item80_remote_smallitem)
	(inanyreceptacle item8_cup_smallitem)
	(inanyreceptacle item93_book_smallitem)
	(inanyreceptacle item94_book_smallitem)
	(inanyreceptacle item95_book_smallitem)
	(inanyreceptacle item97_book_smallitem)
	(inanyreceptacle item98_book_smallitem)
	(inanyreceptacle item99_book_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inreceptacle item102_book_smallitem receptacle42_couch)
	(inreceptacle item103_book_smallitem receptacle42_couch)
	(inreceptacle item104_book_smallitem receptacle42_couch)
	(inreceptacle item106_clock_mediumitem receptacle66_bed)
	(inreceptacle item107_clock_mediumitem receptacle68_bed)
	(inreceptacle item108_clock_mediumitem receptacle67_bed)
	(inreceptacle item109_clock_mediumitem receptacle67_bed)
	(inreceptacle item10_cup_smallitem receptacle28_chair)
	(inreceptacle item112_vase_mediumitem receptacle37_couch)
	(inreceptacle item113_vase_mediumitem receptacle42_couch)
	(inreceptacle item11_spoon_smallitem receptacle82_oven)
	(inreceptacle item12_bowl_smallitem receptacle30_chair)
	(inreceptacle item13_apple_smallitem receptacle69_dining_table)
	(inreceptacle item14_orange_smallitem receptacle71_dining_table)
	(inreceptacle item43_potted_plant_largeitem receptacle37_couch)
	(inreceptacle item44_potted_plant_largeitem receptacle26_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item48_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item51_potted_plant_largeitem receptacle29_chair)
	(inreceptacle item52_potted_plant_largeitem receptacle40_couch)
	(inreceptacle item53_potted_plant_largeitem receptacle39_couch)
	(inreceptacle item54_potted_plant_largeitem receptacle41_couch)
	(inreceptacle item55_potted_plant_largeitem receptacle16_chair)
	(inreceptacle item56_potted_plant_largeitem receptacle3_bench)
	(inreceptacle item58_potted_plant_largeitem receptacle30_chair)
	(inreceptacle item59_potted_plant_largeitem receptacle37_couch)
	(inreceptacle item60_potted_plant_largeitem receptacle73_toilet)
	(inreceptacle item6_handbag_largeitem receptacle17_chair)
	(inreceptacle item77_tv_largeitem receptacle4_bench)
	(inreceptacle item79_remote_smallitem receptacle4_bench)
	(inreceptacle item7_bottle_smallitem receptacle73_toilet)
	(inreceptacle item80_remote_smallitem receptacle4_bench)
	(inreceptacle item8_cup_smallitem receptacle85_sink)
	(inreceptacle item93_book_smallitem receptacle37_couch)
	(inreceptacle item94_book_smallitem receptacle39_couch)
	(inreceptacle item95_book_smallitem receptacle41_couch)
	(inreceptacle item97_book_smallitem receptacle35_chair)
	(inreceptacle item98_book_smallitem receptacle35_chair)
	(inreceptacle item99_book_smallitem receptacle70_dining_table)
	(inreceptacle item9_cup_smallitem receptacle85_sink)
	(itematlocation item100_book_smallitem location_Xneg1_Yneg48_place33_room16_floorB)
	(itematlocation item101_book_smallitem location_Xneg71_Yneg68_place34_room20_floorB)
	(itematlocation item102_book_smallitem location_Xneg78_Yneg146_place70_room21_floorB)
	(itematlocation item103_book_smallitem location_Xneg77_Yneg146_place70_room21_floorB)
	(itematlocation item104_book_smallitem location_Xneg78_Yneg142_place70_room21_floorB)
	(itematlocation item105_book_smallitem location_Xneg71_Yneg74_place35_room20_floorB)
	(itematlocation item106_clock_mediumitem location_Xneg38_Yneg24_place72_room5_floorB)
	(itematlocation item107_clock_mediumitem location_Xpos27_Yneg22_place74_room6_floorB)
	(itematlocation item108_clock_mediumitem location_Xpos27_Yneg119_place73_room7_floorB)
	(itematlocation item109_clock_mediumitem location_Xpos25_Yneg118_place73_room7_floorB)
	(itematlocation item10_cup_smallitem location_Xneg7_Yneg3_place56_room5_floorB)
	(itematlocation item110_vase_mediumitem location_Xneg19_Yneg127_place36_room12_floorB)
	(itematlocation item111_vase_mediumitem location_Xpos8_Yneg107_place37_room7_floorB)
	(itematlocation item112_vase_mediumitem location_Xneg41_Yneg82_place65_room20_floorB)
	(itematlocation item113_vase_mediumitem location_Xneg77_Yneg147_place70_room21_floorB)
	(itematlocation item114_vase_mediumitem location_Xneg72_Yneg74_place38_room20_floorB)
	(itematlocation item11_spoon_smallitem location_Xneg81_Yneg125_place83_room18_floorB)
	(itematlocation item12_bowl_smallitem location_Xneg82_Yneg90_place58_room15_floorB)
	(itematlocation item13_apple_smallitem location_Xpos21_Yneg59_place75_room13_floorA)
	(itematlocation item14_orange_smallitem location_Xneg99_Yneg90_place77_room15_floorB)
	(itematlocation item43_potted_plant_largeitem location_Xneg39_Yneg81_place65_room20_floorB)
	(itematlocation item44_potted_plant_largeitem location_Xneg93_Yneg160_place54_room14_floorB)
	(itematlocation item45_potted_plant_largeitem location_Xneg19_Yneg127_place20_room12_floorB)
	(itematlocation item46_potted_plant_largeitem location_Xneg71_Yneg90_place66_room20_floorB)
	(itematlocation item47_potted_plant_largeitem location_Xneg72_Yneg91_place21_room20_floorB)
	(itematlocation item48_potted_plant_largeitem location_Xneg70_Yneg91_place66_room20_floorB)
	(itematlocation item49_potted_plant_largeitem location_Xneg71_Yneg90_place22_room20_floorB)
	(itematlocation item50_potted_plant_largeitem location_Xneg73_Yneg87_place23_room20_floorB)
	(itematlocation item51_potted_plant_largeitem location_Xneg8_Ypos6_place57_room5_floorB)
	(itematlocation item52_potted_plant_largeitem location_Xpos19_Ypos4_place68_room19_floorA)
	(itematlocation item53_potted_plant_largeitem location_Xpos8_Yneg18_place67_room19_floorA)
	(itematlocation item54_potted_plant_largeitem location_Xneg47_Yneg144_place69_room21_floorB)
	(itematlocation item55_potted_plant_largeitem location_Xneg65_Yneg69_place44_room24_floorA)
	(itematlocation item56_potted_plant_largeitem location_Xpos12_Yneg78_place41_room16_floorB)
	(itematlocation item57_potted_plant_largeitem location_Xneg68_Yneg107_place24_room20_floorB)
	(itematlocation item58_potted_plant_largeitem location_Xneg83_Yneg89_place58_room15_floorB)
	(itematlocation item59_potted_plant_largeitem location_Xneg44_Yneg59_place65_room20_floorB)
	(itematlocation item60_potted_plant_largeitem location_Xneg42_Yneg56_place79_room2_floorB)
	(itematlocation item63_potted_plant_largeitem location_Xpos20_Yneg105_place25_room7_floorB)
	(itematlocation item64_potted_plant_largeitem location_Xneg69_Yneg67_place26_room20_floorB)
	(itematlocation item6_handbag_largeitem location_Xneg8_Yneg97_place45_room24_floorA)
	(itematlocation item76_tv_largeitem location_Xneg107_Yneg108_place27_room18_floorB)
	(itematlocation item77_tv_largeitem location_Xneg7_Yneg71_place42_room16_floorB)
	(itematlocation item78_tv_largeitem location_Xneg37_Ypos9_place28_room5_floorB)
	(itematlocation item79_remote_smallitem location_Xneg6_Yneg73_place42_room16_floorB)
	(itematlocation item7_bottle_smallitem location_Xneg27_Yneg63_place79_room2_floorB)
	(itematlocation item80_remote_smallitem location_Xneg7_Yneg68_place42_room16_floorB)
	(itematlocation item8_cup_smallitem location_Xpos25_Yneg74_place86_room17_floorA)
	(itematlocation item90_book_smallitem location_Xpos12_Yneg100_place29_room23_floorA)
	(itematlocation item91_book_smallitem location_Xpos15_Yneg100_place30_room23_floorA)
	(itematlocation item92_book_smallitem location_Xpos11_Yneg99_place31_room23_floorA)
	(itematlocation item93_book_smallitem location_Xneg37_Yneg80_place65_room20_floorB)
	(itematlocation item94_book_smallitem location_Xpos9_Yneg21_place67_room19_floorA)
	(itematlocation item95_book_smallitem location_Xneg48_Yneg143_place69_room21_floorB)
	(itematlocation item96_book_smallitem location_Xpos5_Yneg48_place32_room16_floorB)
	(itematlocation item97_book_smallitem location_Xneg3_Ypos8_place63_room6_floorB)
	(itematlocation item98_book_smallitem location_Xneg4_Ypos6_place63_room6_floorB)
	(itematlocation item99_book_smallitem location_Xneg45_Yneg85_place76_room24_floorA)
	(itematlocation item9_cup_smallitem location_Xpos23_Yneg76_place86_room17_floorA)
	(receptacleatlocation receptacle15_chair location_Xneg33_Yneg84_place43_room24_floorA)
	(receptacleatlocation receptacle16_chair location_Xneg58_Yneg79_place44_room24_floorA)
	(receptacleatlocation receptacle17_chair location_Xneg12_Yneg101_place45_room24_floorA)
	(receptacleatlocation receptacle18_chair location_Xpos21_Yneg57_place46_room16_floorB)
	(receptacleatlocation receptacle19_chair location_Xneg54_Yneg144_place47_room21_floorB)
	(receptacleatlocation receptacle1_bench location_Xneg49_Yneg168_place39_room21_floorB)
	(receptacleatlocation receptacle20_chair location_Xneg39_Yneg123_place48_room21_floorB)
	(receptacleatlocation receptacle21_chair location_Xneg93_Yneg151_place49_room14_floorB)
	(receptacleatlocation receptacle22_chair location_Xneg93_Yneg169_place50_room14_floorB)
	(receptacleatlocation receptacle23_chair location_Xneg97_Yneg159_place51_room14_floorB)
	(receptacleatlocation receptacle24_chair location_Xneg90_Yneg162_place52_room14_floorB)
	(receptacleatlocation receptacle25_chair location_Xneg92_Yneg155_place53_room14_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg93_Yneg159_place54_room14_floorB)
	(receptacleatlocation receptacle27_chair location_Xneg53_Yneg92_place55_room20_floorB)
	(receptacleatlocation receptacle28_chair location_Xneg14_Ypos0_place56_room5_floorB)
	(receptacleatlocation receptacle29_chair location_Xneg13_Ypos7_place57_room5_floorB)
	(receptacleatlocation receptacle2_bench location_Xneg45_Yneg166_place40_room21_floorB)
	(receptacleatlocation receptacle30_chair location_Xneg97_Yneg93_place58_room15_floorB)
	(receptacleatlocation receptacle31_chair location_Xpos11_Yneg70_place59_room16_floorB)
	(receptacleatlocation receptacle32_chair location_Xpos21_Yneg55_place60_room13_floorA)
	(receptacleatlocation receptacle33_chair location_Xpos21_Yneg62_place61_room13_floorA)
	(receptacleatlocation receptacle34_chair location_Xneg3_Yneg50_place62_room17_floorA)
	(receptacleatlocation receptacle35_chair location_Xpos12_Ypos7_place63_room6_floorB)
	(receptacleatlocation receptacle36_couch location_Xneg44_Yneg70_place64_room24_floorA)
	(receptacleatlocation receptacle37_couch location_Xneg38_Yneg69_place65_room20_floorB)
	(receptacleatlocation receptacle38_couch location_Xneg56_Yneg92_place66_room20_floorB)
	(receptacleatlocation receptacle39_couch location_Xneg2_Yneg19_place67_room19_floorA)
	(receptacleatlocation receptacle3_bench location_Xpos9_Yneg77_place41_room16_floorB)
	(receptacleatlocation receptacle40_couch location_Xpos17_Yneg7_place68_room19_floorA)
	(receptacleatlocation receptacle41_couch location_Xneg51_Yneg145_place69_room21_floorB)
	(receptacleatlocation receptacle42_couch location_Xneg68_Yneg132_place70_room21_floorB)
	(receptacleatlocation receptacle4_bench location_Xpos8_Yneg77_place42_room16_floorB)
	(receptacleatlocation receptacle65_bed location_Xneg28_Yneg5_place71_room4_floorA)
	(receptacleatlocation receptacle66_bed location_Xneg28_Yneg14_place72_room5_floorB)
	(receptacleatlocation receptacle67_bed location_Xpos16_Yneg129_place73_room7_floorB)
	(receptacleatlocation receptacle68_bed location_Xpos17_Yneg13_place74_room6_floorB)
	(receptacleatlocation receptacle69_dining_table location_Xpos21_Yneg59_place75_room13_floorA)
	(receptacleatlocation receptacle70_dining_table location_Xneg44_Yneg84_place76_room24_floorA)
	(receptacleatlocation receptacle71_dining_table location_Xneg99_Yneg90_place77_room15_floorB)
	(receptacleatlocation receptacle72_dining_table location_Xneg2_Yneg84_place78_room10_floorB)
	(receptacleatlocation receptacle73_toilet location_Xneg37_Yneg59_place79_room2_floorB)
	(receptacleatlocation receptacle74_toilet location_Xneg33_Yneg58_place80_room1_floorA)
	(receptacleatlocation receptacle75_toilet location_Xpos24_Yneg85_place81_room3_floorB)
	(receptacleatlocation receptacle81_oven location_Xpos5_Yneg74_place82_room17_floorA)
	(receptacleatlocation receptacle82_oven location_Xneg82_Yneg121_place83_room18_floorB)
	(receptacleatlocation receptacle83_sink location_Xneg36_Yneg44_place84_room2_floorB)
	(receptacleatlocation receptacle84_sink location_Xneg26_Yneg59_place85_room1_floorA)
	(receptacleatlocation receptacle85_sink location_Xpos18_Yneg75_place86_room17_floorA)
	(receptacleatlocation receptacle86_refrigerator location_Xneg82_Yneg133_place87_room18_floorB)
	(receptacleatlocation receptacle87_refrigerator location_Xneg1_Yneg59_place88_room17_floorA)
	(receptacleatlocation receptacle88_refrigerator location_Xneg9_Yneg133_place89_room7_floorB)
	(receptacleatlocation receptacle89_refrigerator location_Xneg67_Yneg107_place90_room24_floorA)
	(receptacleopeningtype receptacle81_oven)
	(receptacleopeningtype receptacle82_oven)
	(receptacleopeningtype receptacle86_refrigerator)
	(receptacleopeningtype receptacle87_refrigerator)
	(receptacleopeningtype receptacle88_refrigerator)
	(receptacleopeningtype receptacle89_refrigerator)
  )
  (:goal (and
	(inreceptacle item78_tv_largeitem receptacle33_chair)
	(inreceptacle item52_potted_plant_largeitem receptacle23_chair)
	(inreceptacle item51_potted_plant_largeitem receptacle26_chair)
	(inreceptacle item59_potted_plant_largeitem receptacle20_chair)
	(inreceptacle item63_potted_plant_largeitem receptacle25_chair)
	(inreceptacle item77_tv_largeitem receptacle89_refrigerator)
	(inreceptacle item100_book_smallitem receptacle30_chair)
	(inreceptacle item9_cup_smallitem receptacle88_refrigerator)
	(inreceptacle item44_potted_plant_largeitem receptacle20_chair)
	(inreceptacle item101_book_smallitem receptacle22_chair)))
)
