
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_knife_smallitem - item
	item11_knife_smallitem - item
	item12_bowl_smallitem - item
	item13_bowl_smallitem - item
	item14_cake_mediumitem - item
	item1_kite_largeitem - item
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item2_bottle_smallitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item40_potted_plant_largeitem - item
	item48_tv_largeitem - item
	item49_tv_largeitem - item
	item4_bottle_smallitem - item
	item50_tv_largeitem - item
	item51_remote_smallitem - item
	item52_remote_smallitem - item
	item5_bottle_smallitem - item
	item67_book_smallitem - item
	item68_clock_mediumitem - item
	item69_clock_mediumitem - item
	item6_wine_glass_smallitem - item
	item70_clock_mediumitem - item
	item71_vase_mediumitem - item
	item72_vase_mediumitem - item
	item7_cup_smallitem - item
	item8_cup_smallitem - item
	item9_cup_smallitem - item
	location_Xneg10_Yneg21_place34_room10_floorA - location
	location_Xneg10_Yneg22_place39_room2_floorB - location
	location_Xneg10_Yneg24_place34_room10_floorA - location
	location_Xneg10_Ypos67_place28_room7_floorA - location
	location_Xneg10_Ypos69_place27_room7_floorA - location
	location_Xneg12_Ypos63_place25_room7_floorA - location
	location_Xneg13_Ypos61_place26_room7_floorA - location
	location_Xneg14_Ypos44_place52_room8_floorA - location
	location_Xneg14_Ypos48_place52_room8_floorA - location
	location_Xneg15_Yneg28_place34_room10_floorA - location
	location_Xneg15_Ypos33_place43_room8_floorA - location
	location_Xneg16_Ypos33_place42_room8_floorA - location
	location_Xneg17_Ypos37_place42_room8_floorA - location
	location_Xneg17_Ypos39_place52_room8_floorA - location
	location_Xneg18_Ypos30_place35_room4_floorB - location
	location_Xneg18_Ypos33_place14_room12_floorA - location
	location_Xneg18_Ypos39_place12_room12_floorA - location
	location_Xneg18_Ypos45_place18_room12_floorA - location
	location_Xneg24_Ypos52_place54_room7_floorA - location
	location_Xneg26_Ypos52_place54_room7_floorA - location
	location_Xneg27_Yneg17_place49_room3_floorB - location
	location_Xneg28_Yneg22_place49_room3_floorB - location
	location_Xneg28_Yneg24_place49_room3_floorB - location
	location_Xneg28_Yneg28_place40_room3_floorB - location
	location_Xneg29_Ypos54_place54_room7_floorA - location
	location_Xneg2_Ypos70_place24_room7_floorA - location
	location_Xneg30_Yneg20_place49_room3_floorB - location
	location_Xneg31_Yneg28_place40_room3_floorB - location
	location_Xneg31_Ypos53_place54_room7_floorA - location
	location_Xneg34_Ypos52_place53_room7_floorA - location
	location_Xneg38_Yneg35_place55_room14_floorA - location
	location_Xneg41_Yneg35_place45_room14_floorA - location
	location_Xneg41_Ypos43_place13_room12_floorA - location
	location_Xneg42_Yneg16_place41_room1_floorA - location
	location_Xneg43_Yneg8_place51_room1_floorA - location
	location_Xneg48_Ypos22_place36_room5_floorB - location
	location_Xneg4_Ypos19_place35_room4_floorB - location
	location_Xneg50_Yneg38_place32_room13_floorB - location
	location_Xneg56_Ypos76_place20_room9_floorA - location
	location_Xneg61_Yneg9_place17_room13_floorB - location
	location_Xneg61_Ypos18_place37_room5_floorB - location
	location_Xneg63_Yneg34_place32_room13_floorB - location
	location_Xneg63_Ypos76_place21_room9_floorA - location
	location_Xneg67_Ypos76_place19_room9_floorA - location
	location_Xneg6_Ypos65_place38_room7_floorA - location
	location_Xneg6_Ypos66_place38_room7_floorA - location
	location_Xneg71_Ypos1_place15_room5_floorB - location
	location_Xneg73_Ypos26_place22_room5_floorB - location
	location_Xneg79_Yneg38_place33_room13_floorB - location
	location_Xneg80_Ypos55_place29_room9_floorA - location
	location_Xneg81_Ypos69_place30_room9_floorA - location
	location_Xneg84_Ypos66_place31_room9_floorA - location
	location_Xneg85_Ypos67_place31_room9_floorA - location
	location_Xneg87_Ypos69_place31_room9_floorA - location
	location_Xneg8_Yneg10_place16_room4_floorB - location
	location_Xneg9_Yneg25_place34_room10_floorA - location
	location_Xneg9_Yneg35_place39_room2_floorB - location
	location_Xpos0_Ypos64_place23_room7_floorA - location
	location_Xpos10_Ypos30_place50_room8_floorA - location
	location_Xpos11_Yneg17_place47_room2_floorB - location
	location_Xpos11_Yneg21_place44_room10_floorA - location
	location_Xpos11_Ypos27_place50_room8_floorA - location
	location_Xpos11_Ypos48_place50_room8_floorA - location
	location_Xpos12_Ypos32_place50_room8_floorA - location
	location_Xpos5_Yneg32_place48_room2_floorB - location
	location_Xpos5_Yneg33_place44_room10_floorA - location
	location_Xpos6_Yneg33_place44_room10_floorA - location
	location_Xpos9_Yneg14_place47_room2_floorB - location
	location_Xpos9_Yneg22_place46_room2_floorB - location
	location_Xpos9_Ypos29_place50_room8_floorA - location
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_couch - receptacle
	receptacle26_couch - receptacle
	receptacle27_couch - receptacle
	receptacle41_bed - receptacle
	receptacle42_bed - receptacle
	receptacle43_bed - receptacle
	receptacle44_dining_table - receptacle
	receptacle45_toilet - receptacle
	receptacle46_toilet - receptacle
	receptacle47_toilet - receptacle
	receptacle53_microwave - receptacle
	receptacle54_oven - receptacle
	receptacle55_oven - receptacle
	receptacle56_oven - receptacle
	receptacle57_sink - receptacle
	receptacle58_sink - receptacle
	receptacle59_sink - receptacle
	receptacle60_sink - receptacle
	receptacle61_sink - receptacle
	receptacle62_sink - receptacle
	receptacle63_refrigerator - receptacle
	receptacle64_refrigerator - receptacle
	receptacle65_refrigerator - receptacle
	receptacle66_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg6_Ypos66_place38_room7_floorA)
	(inanyreceptacle item10_knife_smallitem)
	(inanyreceptacle item11_knife_smallitem)
	(inanyreceptacle item12_bowl_smallitem)
	(inanyreceptacle item13_bowl_smallitem)
	(inanyreceptacle item2_bottle_smallitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item36_potted_plant_largeitem)
	(inanyreceptacle item37_potted_plant_largeitem)
	(inanyreceptacle item38_potted_plant_largeitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item40_potted_plant_largeitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inanyreceptacle item50_tv_largeitem)
	(inanyreceptacle item51_remote_smallitem)
	(inanyreceptacle item52_remote_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item67_book_smallitem)
	(inanyreceptacle item68_clock_mediumitem)
	(inanyreceptacle item69_clock_mediumitem)
	(inanyreceptacle item6_wine_glass_smallitem)
	(inanyreceptacle item70_clock_mediumitem)
	(inanyreceptacle item71_vase_mediumitem)
	(inanyreceptacle item72_vase_mediumitem)
	(inanyreceptacle item7_cup_smallitem)
	(inanyreceptacle item8_cup_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inreceptacle item10_knife_smallitem receptacle61_sink)
	(inreceptacle item11_knife_smallitem receptacle53_microwave)
	(inreceptacle item12_bowl_smallitem receptacle58_sink)
	(inreceptacle item13_bowl_smallitem receptacle46_toilet)
	(inreceptacle item2_bottle_smallitem receptacle45_toilet)
	(inreceptacle item34_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item35_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item36_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item37_potted_plant_largeitem receptacle44_dining_table)
	(inreceptacle item38_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item39_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item3_bottle_smallitem receptacle60_sink)
	(inreceptacle item40_potted_plant_largeitem receptacle63_refrigerator)
	(inreceptacle item4_bottle_smallitem receptacle63_refrigerator)
	(inreceptacle item50_tv_largeitem receptacle55_oven)
	(inreceptacle item51_remote_smallitem receptacle27_couch)
	(inreceptacle item52_remote_smallitem receptacle27_couch)
	(inreceptacle item5_bottle_smallitem receptacle53_microwave)
	(inreceptacle item67_book_smallitem receptacle27_couch)
	(inreceptacle item68_clock_mediumitem receptacle41_bed)
	(inreceptacle item69_clock_mediumitem receptacle25_couch)
	(inreceptacle item6_wine_glass_smallitem receptacle65_refrigerator)
	(inreceptacle item70_clock_mediumitem receptacle55_oven)
	(inreceptacle item71_vase_mediumitem receptacle60_sink)
	(inreceptacle item72_vase_mediumitem receptacle61_sink)
	(inreceptacle item7_cup_smallitem receptacle60_sink)
	(inreceptacle item8_cup_smallitem receptacle65_refrigerator)
	(inreceptacle item9_cup_smallitem receptacle65_refrigerator)
	(itematlocation item10_knife_smallitem location_Xpos11_Ypos48_place50_room8_floorA)
	(itematlocation item11_knife_smallitem location_Xneg17_Ypos37_place42_room8_floorA)
	(itematlocation item12_bowl_smallitem location_Xpos11_Yneg17_place47_room2_floorB)
	(itematlocation item13_bowl_smallitem location_Xneg28_Yneg28_place40_room3_floorB)
	(itematlocation item14_cake_mediumitem location_Xneg71_Ypos1_place15_room5_floorB)
	(itematlocation item1_kite_largeitem location_Xneg41_Ypos43_place13_room12_floorA)
	(itematlocation item28_potted_plant_largeitem location_Xneg18_Ypos45_place18_room12_floorA)
	(itematlocation item29_potted_plant_largeitem location_Xneg67_Ypos76_place19_room9_floorA)
	(itematlocation item2_bottle_smallitem location_Xneg10_Yneg22_place39_room2_floorB)
	(itematlocation item30_potted_plant_largeitem location_Xneg56_Ypos76_place20_room9_floorA)
	(itematlocation item31_potted_plant_largeitem location_Xneg63_Ypos76_place21_room9_floorA)
	(itematlocation item32_potted_plant_largeitem location_Xneg18_Ypos39_place12_room12_floorA)
	(itematlocation item33_potted_plant_largeitem location_Xneg18_Ypos33_place14_room12_floorA)
	(itematlocation item34_potted_plant_largeitem location_Xpos10_Ypos30_place50_room8_floorA)
	(itematlocation item35_potted_plant_largeitem location_Xpos12_Ypos32_place50_room8_floorA)
	(itematlocation item36_potted_plant_largeitem location_Xpos11_Ypos27_place50_room8_floorA)
	(itematlocation item37_potted_plant_largeitem location_Xneg6_Ypos65_place38_room7_floorA)
	(itematlocation item38_potted_plant_largeitem location_Xneg87_Ypos69_place31_room9_floorA)
	(itematlocation item39_potted_plant_largeitem location_Xneg84_Ypos66_place31_room9_floorA)
	(itematlocation item3_bottle_smallitem location_Xneg27_Yneg17_place49_room3_floorB)
	(itematlocation item40_potted_plant_largeitem location_Xneg14_Ypos48_place52_room8_floorA)
	(itematlocation item48_tv_largeitem location_Xneg8_Yneg10_place16_room4_floorB)
	(itematlocation item49_tv_largeitem location_Xneg61_Yneg9_place17_room13_floorB)
	(itematlocation item4_bottle_smallitem location_Xneg17_Ypos39_place52_room8_floorA)
	(itematlocation item50_tv_largeitem location_Xpos6_Yneg33_place44_room10_floorA)
	(itematlocation item51_remote_smallitem location_Xneg10_Yneg24_place34_room10_floorA)
	(itematlocation item52_remote_smallitem location_Xneg9_Yneg25_place34_room10_floorA)
	(itematlocation item5_bottle_smallitem location_Xneg17_Ypos37_place42_room8_floorA)
	(itematlocation item67_book_smallitem location_Xneg10_Yneg21_place34_room10_floorA)
	(itematlocation item68_clock_mediumitem location_Xneg18_Ypos30_place35_room4_floorB)
	(itematlocation item69_clock_mediumitem location_Xneg50_Yneg38_place32_room13_floorB)
	(itematlocation item6_wine_glass_smallitem location_Xneg24_Ypos52_place54_room7_floorA)
	(itematlocation item70_clock_mediumitem location_Xpos11_Yneg21_place44_room10_floorA)
	(itematlocation item71_vase_mediumitem location_Xneg28_Yneg24_place49_room3_floorB)
	(itematlocation item72_vase_mediumitem location_Xpos12_Ypos32_place50_room8_floorA)
	(itematlocation item7_cup_smallitem location_Xneg28_Yneg22_place49_room3_floorB)
	(itematlocation item8_cup_smallitem location_Xneg26_Ypos52_place54_room7_floorA)
	(itematlocation item9_cup_smallitem location_Xneg31_Ypos53_place54_room7_floorA)
	(receptacleatlocation receptacle15_chair location_Xneg73_Ypos26_place22_room5_floorB)
	(receptacleatlocation receptacle16_chair location_Xpos0_Ypos64_place23_room7_floorA)
	(receptacleatlocation receptacle17_chair location_Xneg2_Ypos70_place24_room7_floorA)
	(receptacleatlocation receptacle18_chair location_Xneg12_Ypos63_place25_room7_floorA)
	(receptacleatlocation receptacle19_chair location_Xneg13_Ypos61_place26_room7_floorA)
	(receptacleatlocation receptacle20_chair location_Xneg10_Ypos69_place27_room7_floorA)
	(receptacleatlocation receptacle21_chair location_Xneg10_Ypos67_place28_room7_floorA)
	(receptacleatlocation receptacle22_chair location_Xneg80_Ypos55_place29_room9_floorA)
	(receptacleatlocation receptacle23_chair location_Xneg81_Ypos69_place30_room9_floorA)
	(receptacleatlocation receptacle24_chair location_Xneg85_Ypos67_place31_room9_floorA)
	(receptacleatlocation receptacle25_couch location_Xneg63_Yneg34_place32_room13_floorB)
	(receptacleatlocation receptacle26_couch location_Xneg79_Yneg38_place33_room13_floorB)
	(receptacleatlocation receptacle27_couch location_Xneg15_Yneg28_place34_room10_floorA)
	(receptacleatlocation receptacle41_bed location_Xneg4_Ypos19_place35_room4_floorB)
	(receptacleatlocation receptacle42_bed location_Xneg48_Ypos22_place36_room5_floorB)
	(receptacleatlocation receptacle43_bed location_Xneg61_Ypos18_place37_room5_floorB)
	(receptacleatlocation receptacle44_dining_table location_Xneg6_Ypos66_place38_room7_floorA)
	(receptacleatlocation receptacle45_toilet location_Xneg9_Yneg35_place39_room2_floorB)
	(receptacleatlocation receptacle46_toilet location_Xneg31_Yneg28_place40_room3_floorB)
	(receptacleatlocation receptacle47_toilet location_Xneg42_Yneg16_place41_room1_floorA)
	(receptacleatlocation receptacle53_microwave location_Xneg16_Ypos33_place42_room8_floorA)
	(receptacleatlocation receptacle54_oven location_Xneg15_Ypos33_place43_room8_floorA)
	(receptacleatlocation receptacle55_oven location_Xpos5_Yneg33_place44_room10_floorA)
	(receptacleatlocation receptacle56_oven location_Xneg41_Yneg35_place45_room14_floorA)
	(receptacleatlocation receptacle57_sink location_Xpos9_Yneg22_place46_room2_floorB)
	(receptacleatlocation receptacle58_sink location_Xpos9_Yneg14_place47_room2_floorB)
	(receptacleatlocation receptacle59_sink location_Xpos5_Yneg32_place48_room2_floorB)
	(receptacleatlocation receptacle60_sink location_Xneg30_Yneg20_place49_room3_floorB)
	(receptacleatlocation receptacle61_sink location_Xpos9_Ypos29_place50_room8_floorA)
	(receptacleatlocation receptacle62_sink location_Xneg43_Yneg8_place51_room1_floorA)
	(receptacleatlocation receptacle63_refrigerator location_Xneg14_Ypos44_place52_room8_floorA)
	(receptacleatlocation receptacle64_refrigerator location_Xneg34_Ypos52_place53_room7_floorA)
	(receptacleatlocation receptacle65_refrigerator location_Xneg29_Ypos54_place54_room7_floorA)
	(receptacleatlocation receptacle66_refrigerator location_Xneg38_Yneg35_place55_room14_floorA)
	(receptacleopeningtype receptacle53_microwave)
	(receptacleopeningtype receptacle54_oven)
	(receptacleopeningtype receptacle55_oven)
	(receptacleopeningtype receptacle56_oven)
	(receptacleopeningtype receptacle63_refrigerator)
	(receptacleopeningtype receptacle64_refrigerator)
	(receptacleopeningtype receptacle65_refrigerator)
	(receptacleopeningtype receptacle66_refrigerator)
  )
  (:goal (and
	(inreceptacle item36_potted_plant_largeitem receptacle59_sink)
	(inreceptacle item3_bottle_smallitem receptacle26_couch)
	(inreceptacle item9_cup_smallitem receptacle55_oven)
	(inreceptacle item49_tv_largeitem receptacle62_sink)
	(inreceptacle item6_wine_glass_smallitem receptacle62_sink)
	(inreceptacle item35_potted_plant_largeitem receptacle43_bed)
	(inreceptacle item70_clock_mediumitem receptacle15_chair)
	(inreceptacle item14_cake_mediumitem receptacle19_chair)
	(inreceptacle item11_knife_smallitem receptacle43_bed)
	(inreceptacle item2_bottle_smallitem receptacle20_chair)))
)
