
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_suitcase_largeitem - item
	item11_sports_ball_largeitem - item
	item12_bottle_smallitem - item
	item13_bottle_smallitem - item
	item14_bottle_smallitem - item
	item15_cup_smallitem - item
	item16_cup_smallitem - item
	item17_knife_smallitem - item
	item18_cake_mediumitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_umbrella_largeitem - item
	item40_potted_plant_largeitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item4_umbrella_largeitem - item
	item59_tv_largeitem - item
	item5_umbrella_largeitem - item
	item60_tv_largeitem - item
	item61_laptop_mediumitem - item
	item6_umbrella_largeitem - item
	item74_book_smallitem - item
	item75_book_smallitem - item
	item76_book_smallitem - item
	item77_book_smallitem - item
	item78_book_smallitem - item
	item79_book_smallitem - item
	item7_umbrella_largeitem - item
	item80_book_smallitem - item
	item81_clock_mediumitem - item
	item82_clock_mediumitem - item
	item83_clock_mediumitem - item
	item84_vase_mediumitem - item
	item85_vase_mediumitem - item
	item86_vase_mediumitem - item
	item87_vase_mediumitem - item
	item8_handbag_largeitem - item
	item9_tie_smallitem - item
	location_Xneg13_Ypos28_place33_room10_floorB - location
	location_Xneg15_Yneg15_place51_room6_floorB - location
	location_Xneg15_Ypos121_place67_room1_floorA - location
	location_Xneg15_Ypos131_place66_room1_floorA - location
	location_Xneg17_Ypos125_place67_room1_floorA - location
	location_Xneg18_Ypos0_place50_room5_floorA - location
	location_Xneg20_Ypos18_place53_room6_floorB - location
	location_Xneg23_Ypos122_place21_room8_floorA - location
	location_Xneg23_Ypos133_place26_room8_floorA - location
	location_Xneg24_Yneg6_place51_room6_floorB - location
	location_Xneg24_Ypos17_place53_room6_floorB - location
	location_Xneg36_Ypos22_place28_room10_floorB - location
	location_Xneg38_Yneg14_place63_room12_floorA - location
	location_Xneg38_Yneg5_place60_room12_floorA - location
	location_Xneg38_Ypos51_place23_room9_floorA - location
	location_Xneg38_Ypos51_place24_room9_floorA - location
	location_Xneg39_Ypos114_place15_room8_floorA - location
	location_Xneg39_Ypos115_place16_room8_floorA - location
	location_Xneg3_Ypos85_place69_room2_floorA - location
	location_Xneg40_Yneg5_place62_room12_floorA - location
	location_Xneg40_Ypos4_place70_room12_floorA - location
	location_Xneg42_Ypos116_place17_room8_floorA - location
	location_Xneg43_Ypos96_place25_room13_floorA - location
	location_Xneg54_Ypos4_place70_room12_floorA - location
	location_Xneg54_Ypos5_place70_room12_floorA - location
	location_Xneg54_Ypos6_place70_room12_floorA - location
	location_Xneg59_Ypos30_place39_room11_floorA - location
	location_Xneg62_Yneg15_place61_room12_floorA - location
	location_Xneg64_Ypos30_place54_room11_floorA - location
	location_Xneg66_Yneg14_place61_room12_floorA - location
	location_Xneg66_Ypos25_place40_room11_floorA - location
	location_Xneg67_Yneg39_place32_room15_floorA - location
	location_Xneg67_Ypos30_place54_room11_floorA - location
	location_Xneg67_Ypos34_place35_room11_floorA - location
	location_Xneg68_Ypos91_place27_room13_floorA - location
	location_Xneg68_Ypos91_place34_room13_floorA - location
	location_Xneg69_Ypos29_place54_room11_floorA - location
	location_Xneg69_Ypos4_place64_room12_floorA - location
	location_Xneg69_Ypos59_place46_room13_floorA - location
	location_Xneg69_Ypos80_place48_room17_floorB - location
	location_Xneg69_Ypos95_place48_room17_floorB - location
	location_Xneg70_Yneg40_place31_room15_floorA - location
	location_Xneg70_Ypos30_place54_room11_floorA - location
	location_Xneg70_Ypos72_place46_room13_floorA - location
	location_Xneg71_Yneg14_place42_room7_floorB - location
	location_Xneg71_Ypos131_place49_room4_floorA - location
	location_Xneg72_Ypos35_place38_room11_floorA - location
	location_Xneg72_Ypos67_place47_room17_floorB - location
	location_Xneg73_Ypos24_place37_room11_floorA - location
	location_Xneg73_Ypos30_place54_room11_floorA - location
	location_Xneg74_Yneg39_place31_room15_floorA - location
	location_Xneg76_Yneg13_place42_room7_floorB - location
	location_Xneg76_Ypos82_place34_room13_floorA - location
	location_Xneg77_Yneg15_place61_room12_floorA - location
	location_Xneg77_Ypos44_place68_room17_floorB - location
	location_Xneg78_Ypos23_place71_room3_floorB - location
	location_Xneg79_Yneg40_place31_room15_floorA - location
	location_Xneg79_Ypos30_place36_room11_floorA - location
	location_Xneg80_Ypos95_place45_room13_floorA - location
	location_Xneg81_Ypos10_place64_room12_floorA - location
	location_Xneg82_Yneg13_place56_room7_floorB - location
	location_Xneg82_Ypos79_place34_room13_floorA - location
	location_Xneg83_Yneg10_place43_room7_floorB - location
	location_Xneg83_Ypos60_place46_room13_floorA - location
	location_Xneg83_Ypos67_place47_room17_floorB - location
	location_Xneg84_Ypos16_place52_room7_floorB - location
	location_Xneg84_Ypos81_place45_room13_floorA - location
	location_Xneg85_Ypos138_place55_room4_floorA - location
	location_Xneg85_Ypos95_place45_room13_floorA - location
	location_Xneg86_Ypos138_place55_room4_floorA - location
	location_Xneg87_Ypos140_place55_room4_floorA - location
	location_Xneg88_Yneg13_place44_room7_floorB - location
	location_Xneg88_Ypos27_place71_room3_floorB - location
	location_Xneg89_Ypos142_place55_room4_floorA - location
	location_Xneg91_Ypos42_place59_room3_floorB - location
	location_Xneg91_Ypos93_place20_room17_floorB - location
	location_Xneg92_Ypos102_place18_room4_floorA - location
	location_Xneg92_Ypos99_place19_room4_floorA - location
	location_Xneg93_Ypos94_place45_room13_floorA - location
	location_Xneg94_Ypos96_place29_room13_floorA - location
	location_Xneg96_Ypos104_place22_room4_floorA - location
	location_Xpos0_Ypos86_place69_room2_floorA - location
	location_Xpos3_Yneg12_place41_room5_floorA - location
	location_Xpos4_Ypos84_place58_room2_floorA - location
	location_Xpos5_Ypos31_place30_room5_floorA - location
	location_Xpos5_Ypos93_place57_room1_floorA - location
	location_Xpos8_Ypos115_place65_room1_floorA - location
	receptacle19_chair - receptacle
	receptacle1_bench - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_bench - receptacle
	receptacle30_chair - receptacle
	receptacle31_couch - receptacle
	receptacle32_couch - receptacle
	receptacle33_couch - receptacle
	receptacle34_couch - receptacle
	receptacle48_bed - receptacle
	receptacle49_bed - receptacle
	receptacle50_bed - receptacle
	receptacle51_bed - receptacle
	receptacle52_dining_table - receptacle
	receptacle53_dining_table - receptacle
	receptacle54_dining_table - receptacle
	receptacle55_dining_table - receptacle
	receptacle56_toilet - receptacle
	receptacle57_toilet - receptacle
	receptacle58_toilet - receptacle
	receptacle62_microwave - receptacle
	receptacle63_oven - receptacle
	receptacle64_oven - receptacle
	receptacle65_toaster - receptacle
	receptacle66_sink - receptacle
	receptacle67_sink - receptacle
	receptacle68_sink - receptacle
	receptacle69_sink - receptacle
	receptacle70_sink - receptacle
	receptacle71_sink - receptacle
	receptacle72_refrigerator - receptacle
	receptacle73_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg83_Ypos60_place46_room13_floorA)
	(inanyreceptacle item10_suitcase_largeitem)
	(inanyreceptacle item11_sports_ball_largeitem)
	(inanyreceptacle item12_bottle_smallitem)
	(inanyreceptacle item13_bottle_smallitem)
	(inanyreceptacle item14_bottle_smallitem)
	(inanyreceptacle item16_cup_smallitem)
	(inanyreceptacle item17_knife_smallitem)
	(inanyreceptacle item18_cake_mediumitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item36_potted_plant_largeitem)
	(inanyreceptacle item40_potted_plant_largeitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item47_potted_plant_largeitem)
	(inanyreceptacle item59_tv_largeitem)
	(inanyreceptacle item60_tv_largeitem)
	(inanyreceptacle item6_umbrella_largeitem)
	(inanyreceptacle item74_book_smallitem)
	(inanyreceptacle item75_book_smallitem)
	(inanyreceptacle item76_book_smallitem)
	(inanyreceptacle item77_book_smallitem)
	(inanyreceptacle item78_book_smallitem)
	(inanyreceptacle item7_umbrella_largeitem)
	(inanyreceptacle item80_book_smallitem)
	(inanyreceptacle item83_clock_mediumitem)
	(inanyreceptacle item84_vase_mediumitem)
	(inanyreceptacle item86_vase_mediumitem)
	(inanyreceptacle item87_vase_mediumitem)
	(inreceptacle item10_suitcase_largeitem receptacle33_couch)
	(inreceptacle item11_sports_ball_largeitem receptacle52_dining_table)
	(inreceptacle item12_bottle_smallitem receptacle63_oven)
	(inreceptacle item13_bottle_smallitem receptacle71_sink)
	(inreceptacle item14_bottle_smallitem receptacle73_refrigerator)
	(inreceptacle item16_cup_smallitem receptacle69_sink)
	(inreceptacle item17_knife_smallitem receptacle63_oven)
	(inreceptacle item18_cake_mediumitem receptacle31_couch)
	(inreceptacle item35_potted_plant_largeitem receptacle54_dining_table)
	(inreceptacle item36_potted_plant_largeitem receptacle54_dining_table)
	(inreceptacle item40_potted_plant_largeitem receptacle31_couch)
	(inreceptacle item41_potted_plant_largeitem receptacle32_couch)
	(inreceptacle item44_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item45_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item46_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item47_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item59_tv_largeitem receptacle20_chair)
	(inreceptacle item60_tv_largeitem receptacle34_couch)
	(inreceptacle item6_umbrella_largeitem receptacle1_bench)
	(inreceptacle item74_book_smallitem receptacle32_couch)
	(inreceptacle item75_book_smallitem receptacle72_refrigerator)
	(inreceptacle item76_book_smallitem receptacle72_refrigerator)
	(inreceptacle item77_book_smallitem receptacle72_refrigerator)
	(inreceptacle item78_book_smallitem receptacle28_chair)
	(inreceptacle item7_umbrella_largeitem receptacle1_bench)
	(inreceptacle item80_book_smallitem receptacle31_couch)
	(inreceptacle item83_clock_mediumitem receptacle50_bed)
	(inreceptacle item84_vase_mediumitem receptacle66_sink)
	(inreceptacle item86_vase_mediumitem receptacle54_dining_table)
	(inreceptacle item87_vase_mediumitem receptacle20_chair)
	(itematlocation item10_suitcase_largeitem location_Xneg83_Ypos67_place47_room17_floorB)
	(itematlocation item11_sports_ball_largeitem location_Xneg20_Ypos18_place53_room6_floorB)
	(itematlocation item12_bottle_smallitem location_Xneg77_Yneg15_place61_room12_floorA)
	(itematlocation item13_bottle_smallitem location_Xpos0_Ypos86_place69_room2_floorA)
	(itematlocation item14_bottle_smallitem location_Xneg78_Ypos23_place71_room3_floorB)
	(itematlocation item15_cup_smallitem location_Xneg43_Ypos96_place25_room13_floorA)
	(itematlocation item16_cup_smallitem location_Xneg17_Ypos125_place67_room1_floorA)
	(itematlocation item17_knife_smallitem location_Xneg62_Yneg15_place61_room12_floorA)
	(itematlocation item18_cake_mediumitem location_Xneg80_Ypos95_place45_room13_floorA)
	(itematlocation item35_potted_plant_largeitem location_Xneg87_Ypos140_place55_room4_floorA)
	(itematlocation item36_potted_plant_largeitem location_Xneg85_Ypos138_place55_room4_floorA)
	(itematlocation item37_potted_plant_largeitem location_Xneg92_Ypos102_place18_room4_floorA)
	(itematlocation item38_potted_plant_largeitem location_Xneg92_Ypos99_place19_room4_floorA)
	(itematlocation item39_potted_plant_largeitem location_Xneg96_Ypos104_place22_room4_floorA)
	(itematlocation item3_umbrella_largeitem location_Xneg39_Ypos114_place15_room8_floorA)
	(itematlocation item40_potted_plant_largeitem location_Xneg85_Ypos95_place45_room13_floorA)
	(itematlocation item41_potted_plant_largeitem location_Xneg70_Ypos72_place46_room13_floorA)
	(itematlocation item42_potted_plant_largeitem location_Xneg38_Ypos51_place23_room9_floorA)
	(itematlocation item43_potted_plant_largeitem location_Xneg38_Ypos51_place24_room9_floorA)
	(itematlocation item44_potted_plant_largeitem location_Xneg70_Ypos30_place54_room11_floorA)
	(itematlocation item45_potted_plant_largeitem location_Xneg64_Ypos30_place54_room11_floorA)
	(itematlocation item46_potted_plant_largeitem location_Xneg67_Ypos30_place54_room11_floorA)
	(itematlocation item47_potted_plant_largeitem location_Xneg73_Ypos30_place54_room11_floorA)
	(itematlocation item4_umbrella_largeitem location_Xneg39_Ypos115_place16_room8_floorA)
	(itematlocation item59_tv_largeitem location_Xneg68_Ypos91_place34_room13_floorA)
	(itematlocation item5_umbrella_largeitem location_Xneg42_Ypos116_place17_room8_floorA)
	(itematlocation item60_tv_largeitem location_Xneg69_Ypos95_place48_room17_floorB)
	(itematlocation item61_laptop_mediumitem location_Xpos5_Ypos31_place30_room5_floorA)
	(itematlocation item6_umbrella_largeitem location_Xneg70_Yneg40_place31_room15_floorA)
	(itematlocation item74_book_smallitem location_Xneg83_Ypos60_place46_room13_floorA)
	(itematlocation item75_book_smallitem location_Xneg54_Ypos5_place70_room12_floorA)
	(itematlocation item76_book_smallitem location_Xneg54_Ypos4_place70_room12_floorA)
	(itematlocation item77_book_smallitem location_Xneg54_Ypos6_place70_room12_floorA)
	(itematlocation item78_book_smallitem location_Xneg71_Yneg14_place42_room7_floorB)
	(itematlocation item79_book_smallitem location_Xneg23_Ypos133_place26_room8_floorA)
	(itematlocation item7_umbrella_largeitem location_Xneg79_Yneg40_place31_room15_floorA)
	(itematlocation item80_book_smallitem location_Xneg93_Ypos94_place45_room13_floorA)
	(itematlocation item81_clock_mediumitem location_Xneg68_Ypos91_place27_room13_floorA)
	(itematlocation item82_clock_mediumitem location_Xneg36_Ypos22_place28_room10_floorB)
	(itematlocation item83_clock_mediumitem location_Xneg15_Yneg15_place51_room6_floorB)
	(itematlocation item84_vase_mediumitem location_Xneg81_Ypos10_place64_room12_floorA)
	(itematlocation item85_vase_mediumitem location_Xneg94_Ypos96_place29_room13_floorA)
	(itematlocation item86_vase_mediumitem location_Xneg89_Ypos142_place55_room4_floorA)
	(itematlocation item87_vase_mediumitem location_Xneg76_Ypos82_place34_room13_floorA)
	(itematlocation item8_handbag_largeitem location_Xneg91_Ypos93_place20_room17_floorB)
	(itematlocation item9_tie_smallitem location_Xneg23_Ypos122_place21_room8_floorA)
	(receptacleatlocation receptacle19_chair location_Xneg13_Ypos28_place33_room10_floorB)
	(receptacleatlocation receptacle1_bench location_Xneg74_Yneg39_place31_room15_floorA)
	(receptacleatlocation receptacle20_chair location_Xneg82_Ypos79_place34_room13_floorA)
	(receptacleatlocation receptacle21_chair location_Xneg67_Ypos34_place35_room11_floorA)
	(receptacleatlocation receptacle22_chair location_Xneg79_Ypos30_place36_room11_floorA)
	(receptacleatlocation receptacle23_chair location_Xneg73_Ypos24_place37_room11_floorA)
	(receptacleatlocation receptacle24_chair location_Xneg72_Ypos35_place38_room11_floorA)
	(receptacleatlocation receptacle25_chair location_Xneg59_Ypos30_place39_room11_floorA)
	(receptacleatlocation receptacle26_chair location_Xneg66_Ypos25_place40_room11_floorA)
	(receptacleatlocation receptacle27_chair location_Xpos3_Yneg12_place41_room5_floorA)
	(receptacleatlocation receptacle28_chair location_Xneg76_Yneg13_place42_room7_floorB)
	(receptacleatlocation receptacle29_chair location_Xneg83_Yneg10_place43_room7_floorB)
	(receptacleatlocation receptacle2_bench location_Xneg67_Yneg39_place32_room15_floorA)
	(receptacleatlocation receptacle30_chair location_Xneg88_Yneg13_place44_room7_floorB)
	(receptacleatlocation receptacle31_couch location_Xneg84_Ypos81_place45_room13_floorA)
	(receptacleatlocation receptacle32_couch location_Xneg69_Ypos59_place46_room13_floorA)
	(receptacleatlocation receptacle33_couch location_Xneg72_Ypos67_place47_room17_floorB)
	(receptacleatlocation receptacle34_couch location_Xneg69_Ypos80_place48_room17_floorB)
	(receptacleatlocation receptacle48_bed location_Xneg71_Ypos131_place49_room4_floorA)
	(receptacleatlocation receptacle49_bed location_Xneg18_Ypos0_place50_room5_floorA)
	(receptacleatlocation receptacle50_bed location_Xneg24_Yneg6_place51_room6_floorB)
	(receptacleatlocation receptacle51_bed location_Xneg84_Ypos16_place52_room7_floorB)
	(receptacleatlocation receptacle52_dining_table location_Xneg24_Ypos17_place53_room6_floorB)
	(receptacleatlocation receptacle53_dining_table location_Xneg69_Ypos29_place54_room11_floorA)
	(receptacleatlocation receptacle54_dining_table location_Xneg86_Ypos138_place55_room4_floorA)
	(receptacleatlocation receptacle55_dining_table location_Xneg82_Yneg13_place56_room7_floorB)
	(receptacleatlocation receptacle56_toilet location_Xpos5_Ypos93_place57_room1_floorA)
	(receptacleatlocation receptacle57_toilet location_Xpos4_Ypos84_place58_room2_floorA)
	(receptacleatlocation receptacle58_toilet location_Xneg91_Ypos42_place59_room3_floorB)
	(receptacleatlocation receptacle62_microwave location_Xneg38_Yneg5_place60_room12_floorA)
	(receptacleatlocation receptacle63_oven location_Xneg66_Yneg14_place61_room12_floorA)
	(receptacleatlocation receptacle64_oven location_Xneg40_Yneg5_place62_room12_floorA)
	(receptacleatlocation receptacle65_toaster location_Xneg38_Yneg14_place63_room12_floorA)
	(receptacleatlocation receptacle66_sink location_Xneg69_Ypos4_place64_room12_floorA)
	(receptacleatlocation receptacle67_sink location_Xpos8_Ypos115_place65_room1_floorA)
	(receptacleatlocation receptacle68_sink location_Xneg15_Ypos131_place66_room1_floorA)
	(receptacleatlocation receptacle69_sink location_Xneg15_Ypos121_place67_room1_floorA)
	(receptacleatlocation receptacle70_sink location_Xneg77_Ypos44_place68_room17_floorB)
	(receptacleatlocation receptacle71_sink location_Xneg3_Ypos85_place69_room2_floorA)
	(receptacleatlocation receptacle72_refrigerator location_Xneg40_Ypos4_place70_room12_floorA)
	(receptacleatlocation receptacle73_refrigerator location_Xneg88_Ypos27_place71_room3_floorB)
	(receptacleopeningtype receptacle62_microwave)
	(receptacleopeningtype receptacle63_oven)
	(receptacleopeningtype receptacle64_oven)
	(receptacleopeningtype receptacle72_refrigerator)
	(receptacleopeningtype receptacle73_refrigerator)
  )
  (:goal (and
	(inreceptacle item44_potted_plant_largeitem receptacle67_sink)
	(inreceptacle item82_clock_mediumitem receptacle72_refrigerator)
	(inreceptacle item85_vase_mediumitem receptacle1_bench)
	(inreceptacle item46_potted_plant_largeitem receptacle51_bed)
	(inreceptacle item75_book_smallitem receptacle50_bed)
	(inreceptacle item61_laptop_mediumitem receptacle50_bed)
	(inreceptacle item39_potted_plant_largeitem receptacle19_chair)
	(inreceptacle item86_vase_mediumitem receptacle66_sink)
	(inreceptacle item80_book_smallitem receptacle26_chair)
	(inreceptacle item15_cup_smallitem receptacle33_couch)))
)
