
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_cake_mediumitem - item
	item11_cake_mediumitem - item
	item1_kite_largeitem - item
	item25_potted_plant_largeitem - item
	item26_potted_plant_largeitem - item
	item27_potted_plant_largeitem - item
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item2_surfboard_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_surfboard_largeitem - item
	item4_bottle_smallitem - item
	item50_tv_largeitem - item
	item51_tv_largeitem - item
	item5_cup_smallitem - item
	item66_book_smallitem - item
	item67_book_smallitem - item
	item68_clock_mediumitem - item
	item69_clock_mediumitem - item
	item6_cup_smallitem - item
	item70_vase_mediumitem - item
	item71_vase_mediumitem - item
	item72_vase_mediumitem - item
	item73_vase_mediumitem - item
	item74_vase_mediumitem - item
	item75_vase_mediumitem - item
	item76_vase_mediumitem - item
	item77_vase_mediumitem - item
	item78_teddy_bear_mediumitem - item
	item7_spoon_smallitem - item
	item8_cake_mediumitem - item
	item9_cake_mediumitem - item
	location_Xneg10_Yneg97_place30_room16_floorB - location
	location_Xneg13_Yneg40_place24_room5_floorB - location
	location_Xneg15_Yneg74_place36_room16_floorB - location
	location_Xneg17_Yneg29_place16_room12_floorA - location
	location_Xneg18_Yneg2_place21_room11_floorA - location
	location_Xneg25_Yneg99_place30_room16_floorB - location
	location_Xneg2_Yneg79_place35_room16_floorB - location
	location_Xneg2_Yneg83_place35_room16_floorB - location
	location_Xneg33_Yneg6_place39_room6_floorB - location
	location_Xneg34_Ypos1_place39_room6_floorB - location
	location_Xneg35_Yneg8_place39_room6_floorB - location
	location_Xneg37_Yneg10_place17_room7_floorA - location
	location_Xneg37_Yneg1_place53_room2_floorB - location
	location_Xneg38_Yneg1_place53_room2_floorB - location
	location_Xneg39_Yneg7_place54_room2_floorB - location
	location_Xneg3_Yneg96_place27_room16_floorB - location
	location_Xneg40_Yneg86_place25_room10_floorB - location
	location_Xneg40_Ypos4_place53_room2_floorB - location
	location_Xneg42_Yneg25_place51_room3_floorB - location
	location_Xneg42_Yneg25_place52_room1_floorA - location
	location_Xneg42_Yneg35_place58_room15_floorB - location
	location_Xneg42_Yneg90_place34_room10_floorB - location
	location_Xneg43_Yneg26_place51_room3_floorB - location
	location_Xneg43_Yneg32_place59_room15_floorB - location
	location_Xneg43_Yneg67_place49_room15_floorB - location
	location_Xneg44_Yneg26_place51_room3_floorB - location
	location_Xneg44_Yneg86_place31_room10_floorB - location
	location_Xneg45_Yneg27_place51_room3_floorB - location
	location_Xneg46_Yneg34_place60_room19_floorA - location
	location_Xneg47_Yneg86_place32_room10_floorB - location
	location_Xneg47_Yneg91_place26_room10_floorB - location
	location_Xneg48_Yneg24_place46_room1_floorA - location
	location_Xneg48_Yneg35_place58_room15_floorB - location
	location_Xneg48_Yneg50_place56_room19_floorA - location
	location_Xneg48_Yneg82_place28_room10_floorB - location
	location_Xneg48_Yneg86_place43_room10_floorB - location
	location_Xneg48_Yneg92_place44_room10_floorB - location
	location_Xneg48_Ypos15_place47_room2_floorB - location
	location_Xneg48_Ypos16_place47_room2_floorB - location
	location_Xneg49_Yneg34_place58_room15_floorB - location
	location_Xneg49_Ypos15_place47_room2_floorB - location
	location_Xneg49_Ypos16_place47_room2_floorB - location
	location_Xneg49_Ypos17_place47_room2_floorB - location
	location_Xneg50_Yneg23_place45_room3_floorB - location
	location_Xneg50_Yneg63_place49_room15_floorB - location
	location_Xneg50_Yneg91_place29_room10_floorB - location
	location_Xneg51_Yneg32_place48_room15_floorB - location
	location_Xneg53_Ypos15_place47_room2_floorB - location
	location_Xneg55_Yneg33_place61_room19_floorA - location
	location_Xneg55_Yneg86_place33_room10_floorB - location
	location_Xneg56_Yneg16_place55_room1_floorA - location
	location_Xneg56_Yneg55_place56_room19_floorA - location
	location_Xneg57_Yneg22_place50_room3_floorB - location
	location_Xneg57_Yneg97_place29_room10_floorB - location
	location_Xneg57_Ypos14_place47_room2_floorB - location
	location_Xneg58_Yneg41_place61_room19_floorA - location
	location_Xneg58_Yneg56_place57_room15_floorB - location
	location_Xneg58_Yneg96_place29_room10_floorB - location
	location_Xneg5_Yneg52_place42_room12_floorA - location
	location_Xneg60_Yneg61_place57_room15_floorB - location
	location_Xneg60_Yneg93_place33_room10_floorB - location
	location_Xneg61_Yneg94_place33_room10_floorB - location
	location_Xneg61_Yneg95_place33_room10_floorB - location
	location_Xneg61_Yneg99_place29_room10_floorB - location
	location_Xpos0_Yneg20_place23_room4_floorB - location
	location_Xpos0_Yneg49_place38_room5_floorB - location
	location_Xpos10_Yneg64_place18_room14_floorA - location
	location_Xpos11_Yneg26_place38_room5_floorB - location
	location_Xpos12_Yneg60_place19_room14_floorA - location
	location_Xpos14_Yneg57_place22_room17_floorB - location
	location_Xpos4_Ypos5_place40_room4_floorB - location
	location_Xpos5_Yneg23_place38_room5_floorB - location
	location_Xpos5_Ypos15_place41_room4_floorB - location
	location_Xpos7_Yneg19_place15_room11_floorA - location
	location_Xpos7_Yneg20_place20_room4_floorB - location
	location_Xpos7_Yneg40_place38_room5_floorB - location
	location_Xpos9_Yneg81_place37_room16_floorB - location
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_couch - receptacle
	receptacle23_couch - receptacle
	receptacle24_couch - receptacle
	receptacle40_bed - receptacle
	receptacle41_bed - receptacle
	receptacle42_bed - receptacle
	receptacle43_bed - receptacle
	receptacle44_bed - receptacle
	receptacle45_dining_table - receptacle
	receptacle46_dining_table - receptacle
	receptacle47_toilet - receptacle
	receptacle48_toilet - receptacle
	receptacle49_toilet - receptacle
	receptacle52_microwave - receptacle
	receptacle53_oven - receptacle
	receptacle54_sink - receptacle
	receptacle55_sink - receptacle
	receptacle56_sink - receptacle
	receptacle57_sink - receptacle
	receptacle58_sink - receptacle
	receptacle59_sink - receptacle
	receptacle60_sink - receptacle
	receptacle61_sink - receptacle
	receptacle62_refrigerator - receptacle
	receptacle63_refrigerator - receptacle
	receptacle64_refrigerator - receptacle
	receptacle65_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg50_Yneg23_place45_room3_floorB)
	(inanyreceptacle item10_cake_mediumitem)
	(inanyreceptacle item11_cake_mediumitem)
	(inanyreceptacle item25_potted_plant_largeitem)
	(inanyreceptacle item26_potted_plant_largeitem)
	(inanyreceptacle item27_potted_plant_largeitem)
	(inanyreceptacle item28_potted_plant_largeitem)
	(inanyreceptacle item29_potted_plant_largeitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item36_potted_plant_largeitem)
	(inanyreceptacle item37_potted_plant_largeitem)
	(inanyreceptacle item38_potted_plant_largeitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inanyreceptacle item50_tv_largeitem)
	(inanyreceptacle item51_tv_largeitem)
	(inanyreceptacle item5_cup_smallitem)
	(inanyreceptacle item66_book_smallitem)
	(inanyreceptacle item67_book_smallitem)
	(inanyreceptacle item69_clock_mediumitem)
	(inanyreceptacle item6_cup_smallitem)
	(inanyreceptacle item70_vase_mediumitem)
	(inanyreceptacle item71_vase_mediumitem)
	(inanyreceptacle item73_vase_mediumitem)
	(inanyreceptacle item74_vase_mediumitem)
	(inanyreceptacle item75_vase_mediumitem)
	(inanyreceptacle item76_vase_mediumitem)
	(inanyreceptacle item78_teddy_bear_mediumitem)
	(inanyreceptacle item8_cake_mediumitem)
	(inanyreceptacle item9_cake_mediumitem)
	(inreceptacle item10_cake_mediumitem receptacle41_bed)
	(inreceptacle item11_cake_mediumitem receptacle41_bed)
	(inreceptacle item25_potted_plant_largeitem receptacle16_chair)
	(inreceptacle item26_potted_plant_largeitem receptacle16_chair)
	(inreceptacle item27_potted_plant_largeitem receptacle53_oven)
	(inreceptacle item28_potted_plant_largeitem receptacle16_chair)
	(inreceptacle item29_potted_plant_largeitem receptacle20_chair)
	(inreceptacle item30_potted_plant_largeitem receptacle20_chair)
	(inreceptacle item31_potted_plant_largeitem receptacle20_chair)
	(inreceptacle item32_potted_plant_largeitem receptacle55_sink)
	(inreceptacle item36_potted_plant_largeitem receptacle49_toilet)
	(inreceptacle item37_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item38_potted_plant_largeitem receptacle49_toilet)
	(inreceptacle item39_potted_plant_largeitem receptacle57_sink)
	(inreceptacle item4_bottle_smallitem receptacle49_toilet)
	(inreceptacle item50_tv_largeitem receptacle17_chair)
	(inreceptacle item51_tv_largeitem receptacle49_toilet)
	(inreceptacle item5_cup_smallitem receptacle62_refrigerator)
	(inreceptacle item66_book_smallitem receptacle40_bed)
	(inreceptacle item67_book_smallitem receptacle22_couch)
	(inreceptacle item69_clock_mediumitem receptacle60_sink)
	(inreceptacle item6_cup_smallitem receptacle62_refrigerator)
	(inreceptacle item70_vase_mediumitem receptacle55_sink)
	(inreceptacle item71_vase_mediumitem receptacle55_sink)
	(inreceptacle item73_vase_mediumitem receptacle49_toilet)
	(inreceptacle item74_vase_mediumitem receptacle49_toilet)
	(inreceptacle item75_vase_mediumitem receptacle57_sink)
	(inreceptacle item76_vase_mediumitem receptacle65_refrigerator)
	(inreceptacle item78_teddy_bear_mediumitem receptacle40_bed)
	(inreceptacle item8_cake_mediumitem receptacle40_bed)
	(inreceptacle item9_cake_mediumitem receptacle41_bed)
	(itematlocation item10_cake_mediumitem location_Xneg35_Yneg8_place39_room6_floorB)
	(itematlocation item11_cake_mediumitem location_Xneg35_Yneg8_place39_room6_floorB)
	(itematlocation item1_kite_largeitem location_Xpos7_Yneg19_place15_room11_floorA)
	(itematlocation item25_potted_plant_largeitem location_Xneg58_Yneg96_place29_room10_floorB)
	(itematlocation item26_potted_plant_largeitem location_Xneg61_Yneg99_place29_room10_floorB)
	(itematlocation item27_potted_plant_largeitem location_Xneg43_Yneg67_place49_room15_floorB)
	(itematlocation item28_potted_plant_largeitem location_Xneg57_Yneg97_place29_room10_floorB)
	(itematlocation item29_potted_plant_largeitem location_Xneg60_Yneg93_place33_room10_floorB)
	(itematlocation item2_surfboard_largeitem location_Xneg17_Yneg29_place16_room12_floorA)
	(itematlocation item30_potted_plant_largeitem location_Xneg61_Yneg94_place33_room10_floorB)
	(itematlocation item31_potted_plant_largeitem location_Xneg61_Yneg95_place33_room10_floorB)
	(itematlocation item32_potted_plant_largeitem location_Xneg44_Yneg26_place51_room3_floorB)
	(itematlocation item33_potted_plant_largeitem location_Xpos10_Yneg64_place18_room14_floorA)
	(itematlocation item34_potted_plant_largeitem location_Xpos12_Yneg60_place19_room14_floorA)
	(itematlocation item35_potted_plant_largeitem location_Xpos7_Yneg20_place20_room4_floorB)
	(itematlocation item36_potted_plant_largeitem location_Xneg48_Ypos15_place47_room2_floorB)
	(itematlocation item37_potted_plant_largeitem location_Xneg60_Yneg61_place57_room15_floorB)
	(itematlocation item38_potted_plant_largeitem location_Xneg49_Ypos15_place47_room2_floorB)
	(itematlocation item39_potted_plant_largeitem location_Xneg37_Yneg1_place53_room2_floorB)
	(itematlocation item3_surfboard_largeitem location_Xneg37_Yneg10_place17_room7_floorA)
	(itematlocation item4_bottle_smallitem location_Xneg49_Ypos16_place47_room2_floorB)
	(itematlocation item50_tv_largeitem location_Xneg25_Yneg99_place30_room16_floorB)
	(itematlocation item51_tv_largeitem location_Xneg53_Ypos15_place47_room2_floorB)
	(itematlocation item5_cup_smallitem location_Xneg48_Yneg35_place58_room15_floorB)
	(itematlocation item66_book_smallitem location_Xpos0_Yneg49_place38_room5_floorB)
	(itematlocation item67_book_smallitem location_Xneg2_Yneg79_place35_room16_floorB)
	(itematlocation item68_clock_mediumitem location_Xpos14_Yneg57_place22_room17_floorB)
	(itematlocation item69_clock_mediumitem location_Xneg48_Yneg50_place56_room19_floorA)
	(itematlocation item6_cup_smallitem location_Xneg49_Yneg34_place58_room15_floorB)
	(itematlocation item70_vase_mediumitem location_Xneg43_Yneg26_place51_room3_floorB)
	(itematlocation item71_vase_mediumitem location_Xneg45_Yneg27_place51_room3_floorB)
	(itematlocation item72_vase_mediumitem location_Xpos0_Yneg20_place23_room4_floorB)
	(itematlocation item73_vase_mediumitem location_Xneg49_Ypos17_place47_room2_floorB)
	(itematlocation item74_vase_mediumitem location_Xneg48_Ypos16_place47_room2_floorB)
	(itematlocation item75_vase_mediumitem location_Xneg38_Yneg1_place53_room2_floorB)
	(itematlocation item76_vase_mediumitem location_Xneg58_Yneg41_place61_room19_floorA)
	(itematlocation item77_vase_mediumitem location_Xneg13_Yneg40_place24_room5_floorB)
	(itematlocation item78_teddy_bear_mediumitem location_Xpos11_Yneg26_place38_room5_floorB)
	(itematlocation item7_spoon_smallitem location_Xneg18_Yneg2_place21_room11_floorA)
	(itematlocation item8_cake_mediumitem location_Xpos5_Yneg23_place38_room5_floorB)
	(itematlocation item9_cake_mediumitem location_Xneg33_Yneg6_place39_room6_floorB)
	(receptacleatlocation receptacle12_chair location_Xneg40_Yneg86_place25_room10_floorB)
	(receptacleatlocation receptacle13_chair location_Xneg47_Yneg91_place26_room10_floorB)
	(receptacleatlocation receptacle14_chair location_Xneg3_Yneg96_place27_room16_floorB)
	(receptacleatlocation receptacle15_chair location_Xneg48_Yneg82_place28_room10_floorB)
	(receptacleatlocation receptacle16_chair location_Xneg50_Yneg91_place29_room10_floorB)
	(receptacleatlocation receptacle17_chair location_Xneg10_Yneg97_place30_room16_floorB)
	(receptacleatlocation receptacle18_chair location_Xneg44_Yneg86_place31_room10_floorB)
	(receptacleatlocation receptacle19_chair location_Xneg47_Yneg86_place32_room10_floorB)
	(receptacleatlocation receptacle20_chair location_Xneg55_Yneg86_place33_room10_floorB)
	(receptacleatlocation receptacle21_chair location_Xneg42_Yneg90_place34_room10_floorB)
	(receptacleatlocation receptacle22_couch location_Xneg2_Yneg83_place35_room16_floorB)
	(receptacleatlocation receptacle23_couch location_Xneg15_Yneg74_place36_room16_floorB)
	(receptacleatlocation receptacle24_couch location_Xpos9_Yneg81_place37_room16_floorB)
	(receptacleatlocation receptacle40_bed location_Xpos7_Yneg40_place38_room5_floorB)
	(receptacleatlocation receptacle41_bed location_Xneg34_Ypos1_place39_room6_floorB)
	(receptacleatlocation receptacle42_bed location_Xpos4_Ypos5_place40_room4_floorB)
	(receptacleatlocation receptacle43_bed location_Xpos5_Ypos15_place41_room4_floorB)
	(receptacleatlocation receptacle44_bed location_Xneg5_Yneg52_place42_room12_floorA)
	(receptacleatlocation receptacle45_dining_table location_Xneg48_Yneg86_place43_room10_floorB)
	(receptacleatlocation receptacle46_dining_table location_Xneg48_Yneg92_place44_room10_floorB)
	(receptacleatlocation receptacle47_toilet location_Xneg50_Yneg23_place45_room3_floorB)
	(receptacleatlocation receptacle48_toilet location_Xneg48_Yneg24_place46_room1_floorA)
	(receptacleatlocation receptacle49_toilet location_Xneg57_Ypos14_place47_room2_floorB)
	(receptacleatlocation receptacle52_microwave location_Xneg51_Yneg32_place48_room15_floorB)
	(receptacleatlocation receptacle53_oven location_Xneg50_Yneg63_place49_room15_floorB)
	(receptacleatlocation receptacle54_sink location_Xneg57_Yneg22_place50_room3_floorB)
	(receptacleatlocation receptacle55_sink location_Xneg42_Yneg25_place51_room3_floorB)
	(receptacleatlocation receptacle56_sink location_Xneg42_Yneg25_place52_room1_floorA)
	(receptacleatlocation receptacle57_sink location_Xneg40_Ypos4_place53_room2_floorB)
	(receptacleatlocation receptacle58_sink location_Xneg39_Yneg7_place54_room2_floorB)
	(receptacleatlocation receptacle59_sink location_Xneg56_Yneg16_place55_room1_floorA)
	(receptacleatlocation receptacle60_sink location_Xneg56_Yneg55_place56_room19_floorA)
	(receptacleatlocation receptacle61_sink location_Xneg58_Yneg56_place57_room15_floorB)
	(receptacleatlocation receptacle62_refrigerator location_Xneg42_Yneg35_place58_room15_floorB)
	(receptacleatlocation receptacle63_refrigerator location_Xneg43_Yneg32_place59_room15_floorB)
	(receptacleatlocation receptacle64_refrigerator location_Xneg46_Yneg34_place60_room19_floorA)
	(receptacleatlocation receptacle65_refrigerator location_Xneg55_Yneg33_place61_room19_floorA)
	(receptacleopeningtype receptacle52_microwave)
	(receptacleopeningtype receptacle53_oven)
	(receptacleopeningtype receptacle62_refrigerator)
	(receptacleopeningtype receptacle63_refrigerator)
	(receptacleopeningtype receptacle64_refrigerator)
	(receptacleopeningtype receptacle65_refrigerator)
  )
  (:goal (and
	(inreceptacle item28_potted_plant_largeitem receptacle52_microwave)
	(inreceptacle item31_potted_plant_largeitem receptacle59_sink)
	(inreceptacle item73_vase_mediumitem receptacle16_chair)
	(inreceptacle item25_potted_plant_largeitem receptacle56_sink)
	(inreceptacle item77_vase_mediumitem receptacle24_couch)
	(inreceptacle item3_surfboard_largeitem receptacle23_couch)
	(inreceptacle item38_potted_plant_largeitem receptacle45_dining_table)
	(inreceptacle item11_cake_mediumitem receptacle53_oven)
	(inreceptacle item10_cake_mediumitem receptacle59_sink)
	(inreceptacle item50_tv_largeitem receptacle63_refrigerator)))
)
