
(define (problem taskograph_rearrangement) (:domain taskography_v3)
  (:objects
        agent - agent
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	item10_book_smallitem - item
	item11_book_smallitem - item
	item12_book_smallitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item19_teddy_bear_mediumitem - item
	item20_orange_smallitem - item
	item21_orange_smallitem - item
	item22_orange_smallitem - item
	item39_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item4_bottle_smallitem - item
	item50_potted_plant_largeitem - item
	item5_bottle_smallitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item9_book_smallitem - item
	location_Xneg11_Ypos38_place22_room3_floorB - location
	location_Xneg13_Ypos21_place29_room10_floorA - location
	location_Xneg14_Yneg12_place31_room9_floorA - location
	location_Xneg14_Yneg19_place32_room9_floorA - location
	location_Xneg14_Ypos21_place28_room10_floorA - location
	location_Xneg14_Ypos42_place5_room3_floorB - location
	location_Xneg16_Yneg10_place38_room9_floorA - location
	location_Xneg16_Yneg11_place38_room9_floorA - location
	location_Xneg16_Yneg13_place31_room9_floorA - location
	location_Xneg16_Ypos66_place36_room4_floorB - location
	location_Xneg17_Yneg12_place31_room9_floorA - location
	location_Xneg18_Ypos49_place35_room10_floorA - location
	location_Xneg19_Yneg13_place30_room9_floorA - location
	location_Xneg1_Ypos36_place35_room10_floorA - location
	location_Xneg1_Ypos56_place36_room4_floorB - location
	location_Xneg22_Yneg23_place15_room5_floorB - location
	location_Xneg22_Ypos67_place1_room4_floorB - location
	location_Xneg23_Yneg12_place10_room5_floorB - location
	location_Xneg23_Yneg4_place13_room5_floorB - location
	location_Xneg23_Ypos44_place7_room10_floorA - location
	location_Xneg24_Yneg10_place11_room5_floorB - location
	location_Xneg24_Yneg10_place12_room5_floorB - location
	location_Xneg24_Ypos38_place20_room3_floorB - location
	location_Xneg29_Ypos64_place25_room10_floorA - location
	location_Xneg2_Yneg13_place33_room8_floorB - location
	location_Xneg2_Ypos20_place27_room10_floorA - location
	location_Xneg2_Ypos77_place36_room4_floorB - location
	location_Xneg32_Ypos67_place26_room10_floorA - location
	location_Xneg35_Yneg7_place3_room5_floorB - location
	location_Xneg39_Yneg6_place19_room1_floorA - location
	location_Xneg3_Yneg1_place0_room9_floorA - location
	location_Xneg3_Yneg1_place4_room8_floorB - location
	location_Xneg3_Ypos57_place36_room4_floorB - location
	location_Xneg41_Yneg4_place19_room1_floorA - location
	location_Xneg42_Yneg12_place2_room1_floorA - location
	location_Xneg42_Yneg4_place19_room1_floorA - location
	location_Xneg44_Yneg1_place37_room5_floorB - location
	location_Xneg44_Ypos56_place25_room10_floorA - location
	location_Xneg46_Yneg6_place23_room1_floorA - location
	location_Xneg5_Ypos20_place27_room10_floorA - location
	location_Xneg6_Ypos31_place21_room2_floorB - location
	location_Xneg6_Ypos46_place35_room10_floorA - location
	location_Xpos0_Yneg15_place34_room8_floorB - location
	location_Xpos0_Ypos16_place8_room9_floorA - location
	location_Xpos0_Ypos58_place36_room4_floorB - location
	location_Xpos11_Yneg15_place33_room8_floorB - location
	location_Xpos11_Yneg2_place17_room9_floorA - location
	location_Xpos12_Yneg3_place16_room9_floorA - location
	location_Xpos13_Ypos16_place17_room9_floorA - location
	location_Xpos14_Yneg14_place33_room8_floorB - location
	location_Xpos14_Yneg16_place34_room8_floorB - location
	location_Xpos14_Yneg17_place14_room8_floorB - location
	location_Xpos1_Yneg19_place33_room8_floorB - location
	location_Xpos1_Ypos17_place9_room9_floorA - location
	location_Xpos2_Ypos27_place6_room2_floorB - location
	location_Xpos2_Ypos31_place24_room2_floorB - location
	location_Xpos3_Ypos16_place17_room9_floorA - location
	location_Xpos7_Yneg15_place18_room9_floorA - location
	place0_door_room9_kitchen - place
	place10_item9_book - place
	place11_item10_book - place
	place12_item11_book - place
	place13_item43_potted_plant - place
	place14_item47_potted_plant - place
	place15_item19_teddy_bear - place
	place16_receptacle1_microwave - place
	place17_receptacle2_oven - place
	place18_receptacle8_refrigerator - place
	place19_receptacle13_sink - place
	place1_door_room4_bedroom - place
	place20_receptacle14_sink - place
	place21_receptacle15_sink - place
	place22_receptacle23_toilet - place
	place23_receptacle24_toilet - place
	place24_receptacle25_toilet - place
	place25_receptacle26_chair - place
	place26_receptacle27_chair - place
	place27_receptacle28_chair - place
	place28_receptacle29_chair - place
	place29_receptacle30_chair - place
	place2_door_room1_bathroom - place
	place30_receptacle31_chair - place
	place31_receptacle32_chair - place
	place32_receptacle33_chair - place
	place33_receptacle36_chair - place
	place34_receptacle37_chair - place
	place35_receptacle38_couch - place
	place36_receptacle51_bed - place
	place37_receptacle52_bed - place
	place38_receptacle53_dining_table - place
	place3_door_room5_childs_room - place
	place4_door_room8_home_office - place
	place5_door_room3_bathroom - place
	place6_door_room2_bathroom - place
	place7_door_room10_living_room - place
	place8_item4_bottle - place
	place9_item5_bottle - place
	receptacle13_sink - receptacle
	receptacle14_sink - receptacle
	receptacle15_sink - receptacle
	receptacle1_microwave - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_toilet - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_couch - receptacle
	receptacle51_bed - receptacle
	receptacle52_bed - receptacle
	receptacle53_dining_table - receptacle
	receptacle8_refrigerator - receptacle
	room10_living_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_childs_room - room
	room8_home_office - room
	room9_kitchen - room
  )
  (:init 
	(atlocation agent location_Xneg23_Ypos44_place7_room10_floorA)
	(inanyreceptacle item12_book_smallitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item17_vase_mediumitem)
	(inanyreceptacle item18_vase_mediumitem)
	(inanyreceptacle item20_orange_smallitem)
	(inanyreceptacle item21_orange_smallitem)
	(inanyreceptacle item22_orange_smallitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item49_potted_plant_largeitem)
	(inanyreceptacle item50_potted_plant_largeitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inplace agent place7_door_room10_living_room)
	(inreceptacle item12_book_smallitem receptacle36_chair)
	(inreceptacle item16_vase_mediumitem receptacle51_bed)
	(inreceptacle item17_vase_mediumitem receptacle51_bed)
	(inreceptacle item18_vase_mediumitem receptacle51_bed)
	(inreceptacle item20_orange_smallitem receptacle53_dining_table)
	(inreceptacle item21_orange_smallitem receptacle32_chair)
	(inreceptacle item22_orange_smallitem receptacle32_chair)
	(inreceptacle item39_potted_plant_largeitem receptacle26_chair)
	(inreceptacle item3_bottle_smallitem receptacle2_oven)
	(inreceptacle item41_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item42_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item44_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item45_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle37_chair)
	(inreceptacle item48_potted_plant_largeitem receptacle13_sink)
	(inreceptacle item49_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item50_potted_plant_largeitem receptacle2_oven)
	(inreceptacle item6_bottle_smallitem receptacle51_bed)
	(inreceptacle item7_bottle_smallitem receptacle13_sink)
	(inroom agent room10_living_room)
	(itematlocation item10_book_smallitem location_Xneg24_Yneg10_place11_room5_floorB)
	(itematlocation item11_book_smallitem location_Xneg24_Yneg10_place12_room5_floorB)
	(itematlocation item12_book_smallitem location_Xpos1_Yneg19_place33_room8_floorB)
	(itematlocation item16_vase_mediumitem location_Xneg3_Ypos57_place36_room4_floorB)
	(itematlocation item17_vase_mediumitem location_Xpos0_Ypos58_place36_room4_floorB)
	(itematlocation item18_vase_mediumitem location_Xneg1_Ypos56_place36_room4_floorB)
	(itematlocation item19_teddy_bear_mediumitem location_Xneg22_Yneg23_place15_room5_floorB)
	(itematlocation item20_orange_smallitem location_Xneg16_Yneg11_place38_room9_floorA)
	(itematlocation item21_orange_smallitem location_Xneg17_Yneg12_place31_room9_floorA)
	(itematlocation item22_orange_smallitem location_Xneg16_Yneg13_place31_room9_floorA)
	(itematlocation item39_potted_plant_largeitem location_Xneg44_Ypos56_place25_room10_floorA)
	(itematlocation item3_bottle_smallitem location_Xpos3_Ypos16_place17_room9_floorA)
	(itematlocation item41_potted_plant_largeitem location_Xneg18_Ypos49_place35_room10_floorA)
	(itematlocation item42_potted_plant_largeitem location_Xneg2_Ypos20_place27_room10_floorA)
	(itematlocation item43_potted_plant_largeitem location_Xneg23_Yneg4_place13_room5_floorB)
	(itematlocation item44_potted_plant_largeitem location_Xpos11_Yneg15_place33_room8_floorB)
	(itematlocation item45_potted_plant_largeitem location_Xpos14_Yneg14_place33_room8_floorB)
	(itematlocation item46_potted_plant_largeitem location_Xpos14_Yneg16_place34_room8_floorB)
	(itematlocation item47_potted_plant_largeitem location_Xpos14_Yneg17_place14_room8_floorB)
	(itematlocation item48_potted_plant_largeitem location_Xneg41_Yneg4_place19_room1_floorA)
	(itematlocation item49_potted_plant_largeitem location_Xneg1_Ypos36_place35_room10_floorA)
	(itematlocation item4_bottle_smallitem location_Xpos0_Ypos16_place8_room9_floorA)
	(itematlocation item50_potted_plant_largeitem location_Xpos13_Ypos16_place17_room9_floorA)
	(itematlocation item5_bottle_smallitem location_Xpos1_Ypos17_place9_room9_floorA)
	(itematlocation item6_bottle_smallitem location_Xneg2_Ypos77_place36_room4_floorB)
	(itematlocation item7_bottle_smallitem location_Xneg42_Yneg4_place19_room1_floorA)
	(itematlocation item9_book_smallitem location_Xneg23_Yneg12_place10_room5_floorB)
	(largeitem item39_potted_plant_largeitem)
	(largeitem item41_potted_plant_largeitem)
	(largeitem item42_potted_plant_largeitem)
	(largeitem item43_potted_plant_largeitem)
	(largeitem item44_potted_plant_largeitem)
	(largeitem item45_potted_plant_largeitem)
	(largeitem item46_potted_plant_largeitem)
	(largeitem item47_potted_plant_largeitem)
	(largeitem item48_potted_plant_largeitem)
	(largeitem item49_potted_plant_largeitem)
	(largeitem item50_potted_plant_largeitem)
	(locationinplace location_Xneg11_Ypos38_place22_room3_floorB place22_receptacle23_toilet)
	(locationinplace location_Xneg13_Ypos21_place29_room10_floorA place29_receptacle30_chair)
	(locationinplace location_Xneg14_Yneg12_place31_room9_floorA place31_receptacle32_chair)
	(locationinplace location_Xneg14_Yneg19_place32_room9_floorA place32_receptacle33_chair)
	(locationinplace location_Xneg14_Ypos21_place28_room10_floorA place28_receptacle29_chair)
	(locationinplace location_Xneg14_Ypos42_place5_room3_floorB place5_door_room3_bathroom)
	(locationinplace location_Xneg16_Yneg10_place38_room9_floorA place38_receptacle53_dining_table)
	(locationinplace location_Xneg16_Yneg11_place38_room9_floorA place38_receptacle53_dining_table)
	(locationinplace location_Xneg16_Yneg13_place31_room9_floorA place31_receptacle32_chair)
	(locationinplace location_Xneg16_Ypos66_place36_room4_floorB place36_receptacle51_bed)
	(locationinplace location_Xneg17_Yneg12_place31_room9_floorA place31_receptacle32_chair)
	(locationinplace location_Xneg18_Ypos49_place35_room10_floorA place35_receptacle38_couch)
	(locationinplace location_Xneg19_Yneg13_place30_room9_floorA place30_receptacle31_chair)
	(locationinplace location_Xneg1_Ypos36_place35_room10_floorA place35_receptacle38_couch)
	(locationinplace location_Xneg1_Ypos56_place36_room4_floorB place36_receptacle51_bed)
	(locationinplace location_Xneg22_Yneg23_place15_room5_floorB place15_item19_teddy_bear)
	(locationinplace location_Xneg22_Ypos67_place1_room4_floorB place1_door_room4_bedroom)
	(locationinplace location_Xneg23_Yneg12_place10_room5_floorB place10_item9_book)
	(locationinplace location_Xneg23_Yneg4_place13_room5_floorB place13_item43_potted_plant)
	(locationinplace location_Xneg23_Ypos44_place7_room10_floorA place7_door_room10_living_room)
	(locationinplace location_Xneg24_Yneg10_place11_room5_floorB place11_item10_book)
	(locationinplace location_Xneg24_Yneg10_place12_room5_floorB place12_item11_book)
	(locationinplace location_Xneg24_Ypos38_place20_room3_floorB place20_receptacle14_sink)
	(locationinplace location_Xneg29_Ypos64_place25_room10_floorA place25_receptacle26_chair)
	(locationinplace location_Xneg2_Yneg13_place33_room8_floorB place33_receptacle36_chair)
	(locationinplace location_Xneg2_Ypos20_place27_room10_floorA place27_receptacle28_chair)
	(locationinplace location_Xneg2_Ypos77_place36_room4_floorB place36_receptacle51_bed)
	(locationinplace location_Xneg32_Ypos67_place26_room10_floorA place26_receptacle27_chair)
	(locationinplace location_Xneg35_Yneg7_place3_room5_floorB place3_door_room5_childs_room)
	(locationinplace location_Xneg39_Yneg6_place19_room1_floorA place19_receptacle13_sink)
	(locationinplace location_Xneg3_Yneg1_place0_room9_floorA place0_door_room9_kitchen)
	(locationinplace location_Xneg3_Yneg1_place4_room8_floorB place4_door_room8_home_office)
	(locationinplace location_Xneg3_Ypos57_place36_room4_floorB place36_receptacle51_bed)
	(locationinplace location_Xneg41_Yneg4_place19_room1_floorA place19_receptacle13_sink)
	(locationinplace location_Xneg42_Yneg12_place2_room1_floorA place2_door_room1_bathroom)
	(locationinplace location_Xneg42_Yneg4_place19_room1_floorA place19_receptacle13_sink)
	(locationinplace location_Xneg44_Yneg1_place37_room5_floorB place37_receptacle52_bed)
	(locationinplace location_Xneg44_Ypos56_place25_room10_floorA place25_receptacle26_chair)
	(locationinplace location_Xneg46_Yneg6_place23_room1_floorA place23_receptacle24_toilet)
	(locationinplace location_Xneg5_Ypos20_place27_room10_floorA place27_receptacle28_chair)
	(locationinplace location_Xneg6_Ypos31_place21_room2_floorB place21_receptacle15_sink)
	(locationinplace location_Xneg6_Ypos46_place35_room10_floorA place35_receptacle38_couch)
	(locationinplace location_Xpos0_Yneg15_place34_room8_floorB place34_receptacle37_chair)
	(locationinplace location_Xpos0_Ypos16_place8_room9_floorA place8_item4_bottle)
	(locationinplace location_Xpos0_Ypos58_place36_room4_floorB place36_receptacle51_bed)
	(locationinplace location_Xpos11_Yneg15_place33_room8_floorB place33_receptacle36_chair)
	(locationinplace location_Xpos11_Yneg2_place17_room9_floorA place17_receptacle2_oven)
	(locationinplace location_Xpos12_Yneg3_place16_room9_floorA place16_receptacle1_microwave)
	(locationinplace location_Xpos13_Ypos16_place17_room9_floorA place17_receptacle2_oven)
	(locationinplace location_Xpos14_Yneg14_place33_room8_floorB place33_receptacle36_chair)
	(locationinplace location_Xpos14_Yneg16_place34_room8_floorB place34_receptacle37_chair)
	(locationinplace location_Xpos14_Yneg17_place14_room8_floorB place14_item47_potted_plant)
	(locationinplace location_Xpos1_Yneg19_place33_room8_floorB place33_receptacle36_chair)
	(locationinplace location_Xpos1_Ypos17_place9_room9_floorA place9_item5_bottle)
	(locationinplace location_Xpos2_Ypos27_place6_room2_floorB place6_door_room2_bathroom)
	(locationinplace location_Xpos2_Ypos31_place24_room2_floorB place24_receptacle25_toilet)
	(locationinplace location_Xpos3_Ypos16_place17_room9_floorA place17_receptacle2_oven)
	(locationinplace location_Xpos7_Yneg15_place18_room9_floorA place18_receptacle8_refrigerator)
	(mediumitem item16_vase_mediumitem)
	(mediumitem item17_vase_mediumitem)
	(mediumitem item18_vase_mediumitem)
	(mediumitem item19_teddy_bear_mediumitem)
	(placeinroom place0_door_room9_kitchen room9_kitchen)
	(placeinroom place10_item9_book room5_childs_room)
	(placeinroom place11_item10_book room5_childs_room)
	(placeinroom place12_item11_book room5_childs_room)
	(placeinroom place13_item43_potted_plant room5_childs_room)
	(placeinroom place14_item47_potted_plant room8_home_office)
	(placeinroom place15_item19_teddy_bear room5_childs_room)
	(placeinroom place16_receptacle1_microwave room9_kitchen)
	(placeinroom place17_receptacle2_oven room9_kitchen)
	(placeinroom place18_receptacle8_refrigerator room9_kitchen)
	(placeinroom place19_receptacle13_sink room1_bathroom)
	(placeinroom place1_door_room4_bedroom room4_bedroom)
	(placeinroom place20_receptacle14_sink room3_bathroom)
	(placeinroom place21_receptacle15_sink room2_bathroom)
	(placeinroom place22_receptacle23_toilet room3_bathroom)
	(placeinroom place23_receptacle24_toilet room1_bathroom)
	(placeinroom place24_receptacle25_toilet room2_bathroom)
	(placeinroom place25_receptacle26_chair room10_living_room)
	(placeinroom place26_receptacle27_chair room10_living_room)
	(placeinroom place27_receptacle28_chair room10_living_room)
	(placeinroom place28_receptacle29_chair room10_living_room)
	(placeinroom place29_receptacle30_chair room10_living_room)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place30_receptacle31_chair room9_kitchen)
	(placeinroom place31_receptacle32_chair room9_kitchen)
	(placeinroom place32_receptacle33_chair room9_kitchen)
	(placeinroom place33_receptacle36_chair room8_home_office)
	(placeinroom place34_receptacle37_chair room8_home_office)
	(placeinroom place35_receptacle38_couch room10_living_room)
	(placeinroom place36_receptacle51_bed room4_bedroom)
	(placeinroom place37_receptacle52_bed room5_childs_room)
	(placeinroom place38_receptacle53_dining_table room9_kitchen)
	(placeinroom place3_door_room5_childs_room room5_childs_room)
	(placeinroom place4_door_room8_home_office room8_home_office)
	(placeinroom place5_door_room3_bathroom room3_bathroom)
	(placeinroom place6_door_room2_bathroom room2_bathroom)
	(placeinroom place7_door_room10_living_room room10_living_room)
	(placeinroom place8_item4_bottle room9_kitchen)
	(placeinroom place9_item5_bottle room9_kitchen)
	(placelocation location_Xneg11_Ypos38_place22_room3_floorB place22_receptacle23_toilet)
	(placelocation location_Xneg13_Ypos21_place29_room10_floorA place29_receptacle30_chair)
	(placelocation location_Xneg14_Yneg12_place31_room9_floorA place31_receptacle32_chair)
	(placelocation location_Xneg14_Yneg19_place32_room9_floorA place32_receptacle33_chair)
	(placelocation location_Xneg14_Ypos21_place28_room10_floorA place28_receptacle29_chair)
	(placelocation location_Xneg14_Ypos42_place5_room3_floorB place5_door_room3_bathroom)
	(placelocation location_Xneg16_Yneg10_place38_room9_floorA place38_receptacle53_dining_table)
	(placelocation location_Xneg16_Ypos66_place36_room4_floorB place36_receptacle51_bed)
	(placelocation location_Xneg19_Yneg13_place30_room9_floorA place30_receptacle31_chair)
	(placelocation location_Xneg22_Yneg23_place15_room5_floorB place15_item19_teddy_bear)
	(placelocation location_Xneg22_Ypos67_place1_room4_floorB place1_door_room4_bedroom)
	(placelocation location_Xneg23_Yneg12_place10_room5_floorB place10_item9_book)
	(placelocation location_Xneg23_Yneg4_place13_room5_floorB place13_item43_potted_plant)
	(placelocation location_Xneg23_Ypos44_place7_room10_floorA place7_door_room10_living_room)
	(placelocation location_Xneg24_Yneg10_place11_room5_floorB place11_item10_book)
	(placelocation location_Xneg24_Yneg10_place12_room5_floorB place12_item11_book)
	(placelocation location_Xneg24_Ypos38_place20_room3_floorB place20_receptacle14_sink)
	(placelocation location_Xneg29_Ypos64_place25_room10_floorA place25_receptacle26_chair)
	(placelocation location_Xneg2_Yneg13_place33_room8_floorB place33_receptacle36_chair)
	(placelocation location_Xneg32_Ypos67_place26_room10_floorA place26_receptacle27_chair)
	(placelocation location_Xneg35_Yneg7_place3_room5_floorB place3_door_room5_childs_room)
	(placelocation location_Xneg39_Yneg6_place19_room1_floorA place19_receptacle13_sink)
	(placelocation location_Xneg3_Yneg1_place0_room9_floorA place0_door_room9_kitchen)
	(placelocation location_Xneg3_Yneg1_place4_room8_floorB place4_door_room8_home_office)
	(placelocation location_Xneg42_Yneg12_place2_room1_floorA place2_door_room1_bathroom)
	(placelocation location_Xneg44_Yneg1_place37_room5_floorB place37_receptacle52_bed)
	(placelocation location_Xneg46_Yneg6_place23_room1_floorA place23_receptacle24_toilet)
	(placelocation location_Xneg5_Ypos20_place27_room10_floorA place27_receptacle28_chair)
	(placelocation location_Xneg6_Ypos31_place21_room2_floorB place21_receptacle15_sink)
	(placelocation location_Xneg6_Ypos46_place35_room10_floorA place35_receptacle38_couch)
	(placelocation location_Xpos0_Yneg15_place34_room8_floorB place34_receptacle37_chair)
	(placelocation location_Xpos0_Ypos16_place8_room9_floorA place8_item4_bottle)
	(placelocation location_Xpos11_Yneg2_place17_room9_floorA place17_receptacle2_oven)
	(placelocation location_Xpos12_Yneg3_place16_room9_floorA place16_receptacle1_microwave)
	(placelocation location_Xpos14_Yneg17_place14_room8_floorB place14_item47_potted_plant)
	(placelocation location_Xpos1_Ypos17_place9_room9_floorA place9_item5_bottle)
	(placelocation location_Xpos2_Ypos27_place6_room2_floorB place6_door_room2_bathroom)
	(placelocation location_Xpos2_Ypos31_place24_room2_floorB place24_receptacle25_toilet)
	(placelocation location_Xpos7_Yneg15_place18_room9_floorA place18_receptacle8_refrigerator)
	(receptacleatlocation receptacle13_sink location_Xneg39_Yneg6_place19_room1_floorA)
	(receptacleatlocation receptacle14_sink location_Xneg24_Ypos38_place20_room3_floorB)
	(receptacleatlocation receptacle15_sink location_Xneg6_Ypos31_place21_room2_floorB)
	(receptacleatlocation receptacle1_microwave location_Xpos12_Yneg3_place16_room9_floorA)
	(receptacleatlocation receptacle23_toilet location_Xneg11_Ypos38_place22_room3_floorB)
	(receptacleatlocation receptacle24_toilet location_Xneg46_Yneg6_place23_room1_floorA)
	(receptacleatlocation receptacle25_toilet location_Xpos2_Ypos31_place24_room2_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg29_Ypos64_place25_room10_floorA)
	(receptacleatlocation receptacle27_chair location_Xneg32_Ypos67_place26_room10_floorA)
	(receptacleatlocation receptacle28_chair location_Xneg5_Ypos20_place27_room10_floorA)
	(receptacleatlocation receptacle29_chair location_Xneg14_Ypos21_place28_room10_floorA)
	(receptacleatlocation receptacle2_oven location_Xpos11_Yneg2_place17_room9_floorA)
	(receptacleatlocation receptacle30_chair location_Xneg13_Ypos21_place29_room10_floorA)
	(receptacleatlocation receptacle31_chair location_Xneg19_Yneg13_place30_room9_floorA)
	(receptacleatlocation receptacle32_chair location_Xneg14_Yneg12_place31_room9_floorA)
	(receptacleatlocation receptacle33_chair location_Xneg14_Yneg19_place32_room9_floorA)
	(receptacleatlocation receptacle36_chair location_Xneg2_Yneg13_place33_room8_floorB)
	(receptacleatlocation receptacle37_chair location_Xpos0_Yneg15_place34_room8_floorB)
	(receptacleatlocation receptacle38_couch location_Xneg6_Ypos46_place35_room10_floorA)
	(receptacleatlocation receptacle51_bed location_Xneg16_Ypos66_place36_room4_floorB)
	(receptacleatlocation receptacle52_bed location_Xneg44_Yneg1_place37_room5_floorB)
	(receptacleatlocation receptacle53_dining_table location_Xneg16_Yneg10_place38_room9_floorA)
	(receptacleatlocation receptacle8_refrigerator location_Xpos7_Yneg15_place18_room9_floorA)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle8_refrigerator)
	(roomplace place0_door_room9_kitchen room9_kitchen)
	(roomplace place1_door_room4_bedroom room4_bedroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room5_childs_room room5_childs_room)
	(roomplace place4_door_room8_home_office room8_home_office)
	(roomplace place5_door_room3_bathroom room3_bathroom)
	(roomplace place6_door_room2_bathroom room2_bathroom)
	(roomplace place7_door_room10_living_room room10_living_room)
	(smallitem item10_book_smallitem)
	(smallitem item11_book_smallitem)
	(smallitem item12_book_smallitem)
	(smallitem item20_orange_smallitem)
	(smallitem item21_orange_smallitem)
	(smallitem item22_orange_smallitem)
	(smallitem item3_bottle_smallitem)
	(smallitem item4_bottle_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item6_bottle_smallitem)
	(smallitem item7_bottle_smallitem)
	(smallitem item9_book_smallitem)
  )
  (:goal (and
	(inreceptacle item49_potted_plant_largeitem receptacle33_chair)
	(inreceptacle item10_book_smallitem receptacle14_sink)
	(inreceptacle item18_vase_mediumitem receptacle8_refrigerator)
	(inreceptacle item20_orange_smallitem receptacle29_chair)
	(inreceptacle item12_book_smallitem receptacle32_chair)
	(inreceptacle item17_vase_mediumitem receptacle27_chair)
	(inreceptacle item6_bottle_smallitem receptacle38_couch)
	(inreceptacle item7_bottle_smallitem receptacle26_chair)
	(inreceptacle item21_orange_smallitem receptacle14_sink)
	(inreceptacle item48_potted_plant_largeitem receptacle26_chair)))
)
