
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_cup_smallitem - item
	item11_vase_mediumitem - item
	item39_potted_plant_largeitem - item
	item40_potted_plant_largeitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item7_book_smallitem - item
	item8_book_smallitem - item
	item9_cup_smallitem - item
	location_Xneg11_Yneg16_place40_room3_floorB - location
	location_Xneg15_Yneg16_place43_room3_floorB - location
	location_Xneg17_Yneg15_place44_room3_floorB - location
	location_Xneg8_Ypos4_place19_room3_floorB - location
	location_Xpos10_Ypos43_place17_room2_floorB - location
	location_Xpos10_Ypos53_place20_room2_floorB - location
	location_Xpos12_Ypos38_place17_room2_floorB - location
	location_Xpos12_Ypos46_place17_room2_floorB - location
	location_Xpos12_Ypos53_place22_room2_floorB - location
	location_Xpos14_Yneg17_place12_room3_floorB - location
	location_Xpos15_Yneg20_place11_room3_floorB - location
	location_Xpos16_Ypos45_place23_room1_floorA - location
	location_Xpos17_Ypos34_place18_room10_floorB - location
	location_Xpos18_Ypos36_place16_room1_floorA - location
	location_Xpos19_Ypos45_place21_room1_floorA - location
	location_Xpos21_Ypos47_place18_room10_floorB - location
	location_Xpos25_Ypos64_place15_room10_floorB - location
	location_Xpos30_Ypos32_place13_room10_floorB - location
	location_Xpos34_Ypos62_place15_room10_floorB - location
	location_Xpos37_Ypos36_place13_room10_floorB - location
	location_Xpos43_Yneg13_place8_room12_floorB - location
	location_Xpos44_Ypos1_place39_room11_floorA - location
	location_Xpos47_Ypos62_place14_room10_floorB - location
	location_Xpos4_Ypos3_place45_room3_floorB - location
	location_Xpos57_Yneg15_place9_room12_floorB - location
	location_Xpos60_Ypos0_place41_room11_floorA - location
	location_Xpos61_Ypos0_place42_room12_floorB - location
	location_Xpos61_Ypos15_place42_room12_floorB - location
	location_Xpos61_Ypos49_place25_room10_floorB - location
	location_Xpos62_Ypos11_place41_room11_floorA - location
	location_Xpos62_Ypos47_place32_room9_floorA - location
	location_Xpos62_Ypos58_place26_room10_floorB - location
	location_Xpos63_Ypos53_place34_room9_floorA - location
	location_Xpos64_Ypos52_place35_room9_floorA - location
	location_Xpos65_Ypos46_place36_room9_floorA - location
	location_Xpos66_Ypos49_place33_room9_floorA - location
	location_Xpos72_Ypos48_place31_room5_floorB - location
	location_Xpos75_Ypos14_place42_room12_floorB - location
	location_Xpos75_Ypos49_place46_room5_floorB - location
	location_Xpos76_Yneg11_place37_room12_floorB - location
	location_Xpos76_Yneg1_place24_room11_floorA - location
	location_Xpos76_Ypos56_place29_room5_floorB - location
	location_Xpos76_Ypos59_place30_room5_floorB - location
	location_Xpos79_Ypos53_place27_room5_floorB - location
	location_Xpos80_Ypos39_place36_room9_floorA - location
	location_Xpos80_Ypos40_place36_room9_floorA - location
	location_Xpos80_Ypos46_place28_room5_floorB - location
	location_Xpos83_Ypos2_place38_room12_floorB - location
	location_Xpos9_Yneg18_place10_room3_floorB - location
	receptacle12_bench - receptacle
	receptacle13_toilet - receptacle
	receptacle14_toilet - receptacle
	receptacle15_toilet - receptacle
	receptacle16_toilet - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_oven - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle35_couch - receptacle
	receptacle36_couch - receptacle
	receptacle37_couch - receptacle
	receptacle38_couch - receptacle
	receptacle3_sink - receptacle
	receptacle49_bed - receptacle
	receptacle4_sink - receptacle
	receptacle50_dining_table - receptacle
	receptacle5_sink - receptacle
	receptacle6_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xpos83_Ypos2_place38_room12_floorB)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item43_potted_plant_largeitem)
	(inanyreceptacle item47_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item7_book_smallitem)
	(inanyreceptacle item8_book_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inreceptacle item10_cup_smallitem receptacle5_sink)
	(inreceptacle item39_potted_plant_largeitem receptacle36_couch)
	(inreceptacle item41_potted_plant_largeitem receptacle36_couch)
	(inreceptacle item42_potted_plant_largeitem receptacle3_sink)
	(inreceptacle item43_potted_plant_largeitem receptacle6_refrigerator)
	(inreceptacle item47_potted_plant_largeitem receptacle29_chair)
	(inreceptacle item48_potted_plant_largeitem receptacle5_sink)
	(inreceptacle item7_book_smallitem receptacle35_couch)
	(inreceptacle item8_book_smallitem receptacle29_chair)
	(inreceptacle item9_cup_smallitem receptacle1_oven)
	(itematlocation item10_cup_smallitem location_Xpos12_Ypos46_place17_room2_floorB)
	(itematlocation item11_vase_mediumitem location_Xpos57_Yneg15_place9_room12_floorB)
	(itematlocation item39_potted_plant_largeitem location_Xpos61_Ypos0_place42_room12_floorB)
	(itematlocation item40_potted_plant_largeitem location_Xpos43_Yneg13_place8_room12_floorB)
	(itematlocation item41_potted_plant_largeitem location_Xpos75_Ypos14_place42_room12_floorB)
	(itematlocation item42_potted_plant_largeitem location_Xpos25_Ypos64_place15_room10_floorB)
	(itematlocation item43_potted_plant_largeitem location_Xpos17_Ypos34_place18_room10_floorB)
	(itematlocation item44_potted_plant_largeitem location_Xpos9_Yneg18_place10_room3_floorB)
	(itematlocation item45_potted_plant_largeitem location_Xpos15_Yneg20_place11_room3_floorB)
	(itematlocation item46_potted_plant_largeitem location_Xpos14_Yneg17_place12_room3_floorB)
	(itematlocation item47_potted_plant_largeitem location_Xpos80_Ypos39_place36_room9_floorA)
	(itematlocation item48_potted_plant_largeitem location_Xpos12_Ypos38_place17_room2_floorB)
	(itematlocation item7_book_smallitem location_Xpos60_Ypos0_place41_room11_floorA)
	(itematlocation item8_book_smallitem location_Xpos80_Ypos40_place36_room9_floorA)
	(itematlocation item9_cup_smallitem location_Xpos30_Ypos32_place13_room10_floorB)
	(receptacleatlocation receptacle12_bench location_Xneg8_Ypos4_place19_room3_floorB)
	(receptacleatlocation receptacle13_toilet location_Xpos10_Ypos53_place20_room2_floorB)
	(receptacleatlocation receptacle14_toilet location_Xpos19_Ypos45_place21_room1_floorA)
	(receptacleatlocation receptacle15_toilet location_Xpos12_Ypos53_place22_room2_floorB)
	(receptacleatlocation receptacle16_toilet location_Xpos16_Ypos45_place23_room1_floorA)
	(receptacleatlocation receptacle17_chair location_Xpos76_Yneg1_place24_room11_floorA)
	(receptacleatlocation receptacle18_chair location_Xpos61_Ypos49_place25_room10_floorB)
	(receptacleatlocation receptacle19_chair location_Xpos62_Ypos58_place26_room10_floorB)
	(receptacleatlocation receptacle1_oven location_Xpos37_Ypos36_place13_room10_floorB)
	(receptacleatlocation receptacle20_chair location_Xpos79_Ypos53_place27_room5_floorB)
	(receptacleatlocation receptacle21_chair location_Xpos80_Ypos46_place28_room5_floorB)
	(receptacleatlocation receptacle22_chair location_Xpos76_Ypos56_place29_room5_floorB)
	(receptacleatlocation receptacle23_chair location_Xpos76_Ypos59_place30_room5_floorB)
	(receptacleatlocation receptacle24_chair location_Xpos72_Ypos48_place31_room5_floorB)
	(receptacleatlocation receptacle25_chair location_Xpos62_Ypos47_place32_room9_floorA)
	(receptacleatlocation receptacle26_chair location_Xpos66_Ypos49_place33_room9_floorA)
	(receptacleatlocation receptacle27_chair location_Xpos63_Ypos53_place34_room9_floorA)
	(receptacleatlocation receptacle28_chair location_Xpos64_Ypos52_place35_room9_floorA)
	(receptacleatlocation receptacle29_chair location_Xpos65_Ypos46_place36_room9_floorA)
	(receptacleatlocation receptacle2_oven location_Xpos47_Ypos62_place14_room10_floorB)
	(receptacleatlocation receptacle30_chair location_Xpos76_Yneg11_place37_room12_floorB)
	(receptacleatlocation receptacle31_chair location_Xpos83_Ypos2_place38_room12_floorB)
	(receptacleatlocation receptacle32_chair location_Xpos44_Ypos1_place39_room11_floorA)
	(receptacleatlocation receptacle33_chair location_Xneg11_Yneg16_place40_room3_floorB)
	(receptacleatlocation receptacle35_couch location_Xpos62_Ypos11_place41_room11_floorA)
	(receptacleatlocation receptacle36_couch location_Xpos61_Ypos15_place42_room12_floorB)
	(receptacleatlocation receptacle37_couch location_Xneg15_Yneg16_place43_room3_floorB)
	(receptacleatlocation receptacle38_couch location_Xneg17_Yneg15_place44_room3_floorB)
	(receptacleatlocation receptacle3_sink location_Xpos34_Ypos62_place15_room10_floorB)
	(receptacleatlocation receptacle49_bed location_Xpos4_Ypos3_place45_room3_floorB)
	(receptacleatlocation receptacle4_sink location_Xpos18_Ypos36_place16_room1_floorA)
	(receptacleatlocation receptacle50_dining_table location_Xpos75_Ypos49_place46_room5_floorB)
	(receptacleatlocation receptacle5_sink location_Xpos10_Ypos43_place17_room2_floorB)
	(receptacleatlocation receptacle6_refrigerator location_Xpos21_Ypos47_place18_room10_floorB)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle6_refrigerator)
  )
  (:goal (and
	(inreceptacle item44_potted_plant_largeitem receptacle5_sink)
	(inreceptacle item8_book_smallitem receptacle13_toilet)
	(inreceptacle item43_potted_plant_largeitem receptacle12_bench)
	(inreceptacle item9_cup_smallitem receptacle38_couch)
	(inreceptacle item7_book_smallitem receptacle33_chair)
	(inreceptacle item42_potted_plant_largeitem receptacle13_toilet)
	(inreceptacle item45_potted_plant_largeitem receptacle35_couch)
	(inreceptacle item47_potted_plant_largeitem receptacle49_bed)
	(inreceptacle item48_potted_plant_largeitem receptacle16_toilet)
	(inreceptacle item39_potted_plant_largeitem receptacle12_bench)))
)
