
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	location_Xneg11_Ypos38_place22_room3_floorB - location
	location_Xneg13_Ypos21_place29_room10_floorA - location
	location_Xneg14_Yneg12_place31_room9_floorA - location
	location_Xneg14_Yneg19_place32_room9_floorA - location
	location_Xneg14_Ypos21_place28_room10_floorA - location
	location_Xneg16_Yneg10_place38_room9_floorA - location
	location_Xneg16_Yneg11_place38_room9_floorA - location
	location_Xneg16_Yneg13_place31_room9_floorA - location
	location_Xneg16_Ypos66_place36_room4_floorB - location
	location_Xneg17_Yneg12_place31_room9_floorA - location
	location_Xneg18_Ypos49_place35_room10_floorA - location
	location_Xneg19_Yneg13_place30_room9_floorA - location
	location_Xneg1_Ypos36_place35_room10_floorA - location
	location_Xneg1_Ypos56_place36_room4_floorB - location
	location_Xneg22_Yneg23_place15_room5_floorB - location
	location_Xneg23_Yneg12_place10_room5_floorB - location
	location_Xneg23_Yneg4_place13_room5_floorB - location
	location_Xneg24_Yneg10_place11_room5_floorB - location
	location_Xneg24_Yneg10_place12_room5_floorB - location
	location_Xneg24_Ypos38_place20_room3_floorB - location
	location_Xneg29_Ypos64_place25_room10_floorA - location
	location_Xneg2_Yneg13_place33_room8_floorB - location
	location_Xneg2_Ypos20_place27_room10_floorA - location
	location_Xneg2_Ypos77_place36_room4_floorB - location
	location_Xneg32_Ypos67_place26_room10_floorA - location
	location_Xneg39_Yneg6_place19_room1_floorA - location
	location_Xneg3_Ypos57_place36_room4_floorB - location
	location_Xneg41_Yneg4_place19_room1_floorA - location
	location_Xneg42_Yneg4_place19_room1_floorA - location
	location_Xneg44_Yneg1_place37_room5_floorB - location
	location_Xneg44_Ypos56_place25_room10_floorA - location
	location_Xneg46_Yneg6_place23_room1_floorA - location
	location_Xneg5_Ypos20_place27_room10_floorA - location
	location_Xneg6_Ypos31_place21_room2_floorB - location
	location_Xneg6_Ypos46_place35_room10_floorA - location
	location_Xpos0_Yneg15_place34_room8_floorB - location
	location_Xpos0_Ypos16_place8_room9_floorA - location
	location_Xpos0_Ypos58_place36_room4_floorB - location
	location_Xpos11_Yneg15_place33_room8_floorB - location
	location_Xpos11_Yneg2_place17_room9_floorA - location
	location_Xpos12_Yneg3_place16_room9_floorA - location
	location_Xpos13_Ypos16_place17_room9_floorA - location
	location_Xpos14_Yneg14_place33_room8_floorB - location
	location_Xpos14_Yneg16_place34_room8_floorB - location
	location_Xpos14_Yneg17_place14_room8_floorB - location
	location_Xpos1_Yneg19_place33_room8_floorB - location
	location_Xpos1_Ypos17_place9_room9_floorA - location
	location_Xpos2_Ypos31_place24_room2_floorB - location
	location_Xpos3_Ypos16_place17_room9_floorA - location
	location_Xpos7_Yneg15_place18_room9_floorA - location
	object10_book - object
	object11_book - object
	object12_book - object
	object16_vase - object
	object17_vase - object
	object18_vase - object
	object19_teddy_bear - object
	object20_orange - object
	object21_orange - object
	object22_orange - object
	object39_potted_plant - object
	object3_bottle - object
	object41_potted_plant - object
	object42_potted_plant - object
	object43_potted_plant - object
	object44_potted_plant - object
	object45_potted_plant - object
	object46_potted_plant - object
	object47_potted_plant - object
	object48_potted_plant - object
	object49_potted_plant - object
	object4_bottle - object
	object50_potted_plant - object
	object5_bottle - object
	object6_bottle - object
	object7_bottle - object
	object9_book - object
	receptacle13_sink - receptacle
	receptacle14_sink - receptacle
	receptacle15_sink - receptacle
	receptacle1_microwave - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_toilet - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_couch - receptacle
	receptacle51_bed - receptacle
	receptacle52_bed - receptacle
	receptacle53_dining_table - receptacle
	receptacle8_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg24_Yneg10_place11_room5_floorB)
	(inreceptacle object12_book receptacle36_chair)
	(inreceptacle object16_vase receptacle51_bed)
	(inreceptacle object17_vase receptacle51_bed)
	(inreceptacle object18_vase receptacle51_bed)
	(inreceptacle object20_orange receptacle53_dining_table)
	(inreceptacle object21_orange receptacle32_chair)
	(inreceptacle object22_orange receptacle32_chair)
	(inreceptacle object39_potted_plant receptacle26_chair)
	(inreceptacle object3_bottle receptacle2_oven)
	(inreceptacle object41_potted_plant receptacle38_couch)
	(inreceptacle object42_potted_plant receptacle28_chair)
	(inreceptacle object44_potted_plant receptacle36_chair)
	(inreceptacle object45_potted_plant receptacle36_chair)
	(inreceptacle object46_potted_plant receptacle37_chair)
	(inreceptacle object48_potted_plant receptacle13_sink)
	(inreceptacle object49_potted_plant receptacle38_couch)
	(inreceptacle object50_potted_plant receptacle2_oven)
	(inreceptacle object6_bottle receptacle51_bed)
	(inreceptacle object7_bottle receptacle13_sink)
	(objectatlocation object10_book location_Xneg24_Yneg10_place11_room5_floorB)
	(objectatlocation object11_book location_Xneg24_Yneg10_place12_room5_floorB)
	(objectatlocation object12_book location_Xpos1_Yneg19_place33_room8_floorB)
	(objectatlocation object16_vase location_Xneg3_Ypos57_place36_room4_floorB)
	(objectatlocation object17_vase location_Xpos0_Ypos58_place36_room4_floorB)
	(objectatlocation object18_vase location_Xneg1_Ypos56_place36_room4_floorB)
	(objectatlocation object19_teddy_bear location_Xneg22_Yneg23_place15_room5_floorB)
	(objectatlocation object20_orange location_Xneg16_Yneg11_place38_room9_floorA)
	(objectatlocation object21_orange location_Xneg17_Yneg12_place31_room9_floorA)
	(objectatlocation object22_orange location_Xneg16_Yneg13_place31_room9_floorA)
	(objectatlocation object39_potted_plant location_Xneg44_Ypos56_place25_room10_floorA)
	(objectatlocation object3_bottle location_Xpos3_Ypos16_place17_room9_floorA)
	(objectatlocation object41_potted_plant location_Xneg18_Ypos49_place35_room10_floorA)
	(objectatlocation object42_potted_plant location_Xneg2_Ypos20_place27_room10_floorA)
	(objectatlocation object43_potted_plant location_Xneg23_Yneg4_place13_room5_floorB)
	(objectatlocation object44_potted_plant location_Xpos11_Yneg15_place33_room8_floorB)
	(objectatlocation object45_potted_plant location_Xpos14_Yneg14_place33_room8_floorB)
	(objectatlocation object46_potted_plant location_Xpos14_Yneg16_place34_room8_floorB)
	(objectatlocation object47_potted_plant location_Xpos14_Yneg17_place14_room8_floorB)
	(objectatlocation object48_potted_plant location_Xneg41_Yneg4_place19_room1_floorA)
	(objectatlocation object49_potted_plant location_Xneg1_Ypos36_place35_room10_floorA)
	(objectatlocation object4_bottle location_Xpos0_Ypos16_place8_room9_floorA)
	(objectatlocation object50_potted_plant location_Xpos13_Ypos16_place17_room9_floorA)
	(objectatlocation object5_bottle location_Xpos1_Ypos17_place9_room9_floorA)
	(objectatlocation object6_bottle location_Xneg2_Ypos77_place36_room4_floorB)
	(objectatlocation object7_bottle location_Xneg42_Yneg4_place19_room1_floorA)
	(objectatlocation object9_book location_Xneg23_Yneg12_place10_room5_floorB)
	(receptacleatlocation receptacle13_sink location_Xneg39_Yneg6_place19_room1_floorA)
	(receptacleatlocation receptacle14_sink location_Xneg24_Ypos38_place20_room3_floorB)
	(receptacleatlocation receptacle15_sink location_Xneg6_Ypos31_place21_room2_floorB)
	(receptacleatlocation receptacle1_microwave location_Xpos12_Yneg3_place16_room9_floorA)
	(receptacleatlocation receptacle23_toilet location_Xneg11_Ypos38_place22_room3_floorB)
	(receptacleatlocation receptacle24_toilet location_Xneg46_Yneg6_place23_room1_floorA)
	(receptacleatlocation receptacle25_toilet location_Xpos2_Ypos31_place24_room2_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg29_Ypos64_place25_room10_floorA)
	(receptacleatlocation receptacle27_chair location_Xneg32_Ypos67_place26_room10_floorA)
	(receptacleatlocation receptacle28_chair location_Xneg5_Ypos20_place27_room10_floorA)
	(receptacleatlocation receptacle29_chair location_Xneg14_Ypos21_place28_room10_floorA)
	(receptacleatlocation receptacle2_oven location_Xpos11_Yneg2_place17_room9_floorA)
	(receptacleatlocation receptacle30_chair location_Xneg13_Ypos21_place29_room10_floorA)
	(receptacleatlocation receptacle31_chair location_Xneg19_Yneg13_place30_room9_floorA)
	(receptacleatlocation receptacle32_chair location_Xneg14_Yneg12_place31_room9_floorA)
	(receptacleatlocation receptacle33_chair location_Xneg14_Yneg19_place32_room9_floorA)
	(receptacleatlocation receptacle36_chair location_Xneg2_Yneg13_place33_room8_floorB)
	(receptacleatlocation receptacle37_chair location_Xpos0_Yneg15_place34_room8_floorB)
	(receptacleatlocation receptacle38_couch location_Xneg6_Ypos46_place35_room10_floorA)
	(receptacleatlocation receptacle51_bed location_Xneg16_Ypos66_place36_room4_floorB)
	(receptacleatlocation receptacle52_bed location_Xneg44_Yneg1_place37_room5_floorB)
	(receptacleatlocation receptacle53_dining_table location_Xneg16_Yneg10_place38_room9_floorA)
	(receptacleatlocation receptacle8_refrigerator location_Xpos7_Yneg15_place18_room9_floorA)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle8_refrigerator)
  )
  (:goal (and
	(inreceptacle object6_bottle receptacle52_bed)
	(inreceptacle object43_potted_plant receptacle27_chair)
	(inreceptacle object22_orange receptacle51_bed)
	(inreceptacle object7_bottle receptacle52_bed)
	(inreceptacle object42_potted_plant receptacle23_toilet)
	(inreceptacle object19_teddy_bear receptacle36_chair)
	(inreceptacle object44_potted_plant receptacle38_couch)
	(inreceptacle object20_orange receptacle24_toilet)
	(inreceptacle object39_potted_plant receptacle1_microwave)
	(inreceptacle object48_potted_plant receptacle27_chair)))
)
