
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_book_smallitem - item
	item11_book_smallitem - item
	item12_book_smallitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item19_teddy_bear_mediumitem - item
	item20_orange_smallitem - item
	item21_orange_smallitem - item
	item22_orange_smallitem - item
	item39_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item4_bottle_smallitem - item
	item50_potted_plant_largeitem - item
	item5_bottle_smallitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item9_book_smallitem - item
	location_Xneg11_Ypos38_place22_room3_floorB - location
	location_Xneg13_Ypos21_place29_room10_floorA - location
	location_Xneg14_Yneg12_place31_room9_floorA - location
	location_Xneg14_Yneg19_place32_room9_floorA - location
	location_Xneg14_Ypos21_place28_room10_floorA - location
	location_Xneg16_Yneg10_place38_room9_floorA - location
	location_Xneg16_Yneg11_place38_room9_floorA - location
	location_Xneg16_Yneg13_place31_room9_floorA - location
	location_Xneg16_Ypos66_place36_room4_floorB - location
	location_Xneg17_Yneg12_place31_room9_floorA - location
	location_Xneg18_Ypos49_place35_room10_floorA - location
	location_Xneg19_Yneg13_place30_room9_floorA - location
	location_Xneg1_Ypos36_place35_room10_floorA - location
	location_Xneg1_Ypos56_place36_room4_floorB - location
	location_Xneg22_Yneg23_place15_room5_floorB - location
	location_Xneg23_Yneg12_place10_room5_floorB - location
	location_Xneg23_Yneg4_place13_room5_floorB - location
	location_Xneg24_Yneg10_place11_room5_floorB - location
	location_Xneg24_Yneg10_place12_room5_floorB - location
	location_Xneg24_Ypos38_place20_room3_floorB - location
	location_Xneg29_Ypos64_place25_room10_floorA - location
	location_Xneg2_Yneg13_place33_room8_floorB - location
	location_Xneg2_Ypos20_place27_room10_floorA - location
	location_Xneg2_Ypos77_place36_room4_floorB - location
	location_Xneg32_Ypos67_place26_room10_floorA - location
	location_Xneg39_Yneg6_place19_room1_floorA - location
	location_Xneg3_Ypos57_place36_room4_floorB - location
	location_Xneg41_Yneg4_place19_room1_floorA - location
	location_Xneg42_Yneg4_place19_room1_floorA - location
	location_Xneg44_Yneg1_place37_room5_floorB - location
	location_Xneg44_Ypos56_place25_room10_floorA - location
	location_Xneg46_Yneg6_place23_room1_floorA - location
	location_Xneg5_Ypos20_place27_room10_floorA - location
	location_Xneg6_Ypos31_place21_room2_floorB - location
	location_Xneg6_Ypos46_place35_room10_floorA - location
	location_Xpos0_Yneg15_place34_room8_floorB - location
	location_Xpos0_Ypos16_place8_room9_floorA - location
	location_Xpos0_Ypos58_place36_room4_floorB - location
	location_Xpos11_Yneg15_place33_room8_floorB - location
	location_Xpos11_Yneg2_place17_room9_floorA - location
	location_Xpos12_Yneg3_place16_room9_floorA - location
	location_Xpos13_Ypos16_place17_room9_floorA - location
	location_Xpos14_Yneg14_place33_room8_floorB - location
	location_Xpos14_Yneg16_place34_room8_floorB - location
	location_Xpos14_Yneg17_place14_room8_floorB - location
	location_Xpos1_Yneg19_place33_room8_floorB - location
	location_Xpos1_Ypos17_place9_room9_floorA - location
	location_Xpos2_Ypos31_place24_room2_floorB - location
	location_Xpos3_Ypos16_place17_room9_floorA - location
	location_Xpos7_Yneg15_place18_room9_floorA - location
	receptacle13_sink - receptacle
	receptacle14_sink - receptacle
	receptacle15_sink - receptacle
	receptacle1_microwave - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_toilet - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_couch - receptacle
	receptacle51_bed - receptacle
	receptacle52_bed - receptacle
	receptacle53_dining_table - receptacle
	receptacle8_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xneg32_Ypos67_place26_room10_floorA)
	(inanyreceptacle item12_book_smallitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item17_vase_mediumitem)
	(inanyreceptacle item18_vase_mediumitem)
	(inanyreceptacle item20_orange_smallitem)
	(inanyreceptacle item21_orange_smallitem)
	(inanyreceptacle item22_orange_smallitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item49_potted_plant_largeitem)
	(inanyreceptacle item50_potted_plant_largeitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inreceptacle item12_book_smallitem receptacle36_chair)
	(inreceptacle item16_vase_mediumitem receptacle51_bed)
	(inreceptacle item17_vase_mediumitem receptacle51_bed)
	(inreceptacle item18_vase_mediumitem receptacle51_bed)
	(inreceptacle item20_orange_smallitem receptacle53_dining_table)
	(inreceptacle item21_orange_smallitem receptacle32_chair)
	(inreceptacle item22_orange_smallitem receptacle32_chair)
	(inreceptacle item39_potted_plant_largeitem receptacle26_chair)
	(inreceptacle item3_bottle_smallitem receptacle2_oven)
	(inreceptacle item41_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item42_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item44_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item45_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle37_chair)
	(inreceptacle item48_potted_plant_largeitem receptacle13_sink)
	(inreceptacle item49_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item50_potted_plant_largeitem receptacle2_oven)
	(inreceptacle item6_bottle_smallitem receptacle51_bed)
	(inreceptacle item7_bottle_smallitem receptacle13_sink)
	(itematlocation item10_book_smallitem location_Xneg24_Yneg10_place11_room5_floorB)
	(itematlocation item11_book_smallitem location_Xneg24_Yneg10_place12_room5_floorB)
	(itematlocation item12_book_smallitem location_Xpos1_Yneg19_place33_room8_floorB)
	(itematlocation item16_vase_mediumitem location_Xneg3_Ypos57_place36_room4_floorB)
	(itematlocation item17_vase_mediumitem location_Xpos0_Ypos58_place36_room4_floorB)
	(itematlocation item18_vase_mediumitem location_Xneg1_Ypos56_place36_room4_floorB)
	(itematlocation item19_teddy_bear_mediumitem location_Xneg22_Yneg23_place15_room5_floorB)
	(itematlocation item20_orange_smallitem location_Xneg16_Yneg11_place38_room9_floorA)
	(itematlocation item21_orange_smallitem location_Xneg17_Yneg12_place31_room9_floorA)
	(itematlocation item22_orange_smallitem location_Xneg16_Yneg13_place31_room9_floorA)
	(itematlocation item39_potted_plant_largeitem location_Xneg44_Ypos56_place25_room10_floorA)
	(itematlocation item3_bottle_smallitem location_Xpos3_Ypos16_place17_room9_floorA)
	(itematlocation item41_potted_plant_largeitem location_Xneg18_Ypos49_place35_room10_floorA)
	(itematlocation item42_potted_plant_largeitem location_Xneg2_Ypos20_place27_room10_floorA)
	(itematlocation item43_potted_plant_largeitem location_Xneg23_Yneg4_place13_room5_floorB)
	(itematlocation item44_potted_plant_largeitem location_Xpos11_Yneg15_place33_room8_floorB)
	(itematlocation item45_potted_plant_largeitem location_Xpos14_Yneg14_place33_room8_floorB)
	(itematlocation item46_potted_plant_largeitem location_Xpos14_Yneg16_place34_room8_floorB)
	(itematlocation item47_potted_plant_largeitem location_Xpos14_Yneg17_place14_room8_floorB)
	(itematlocation item48_potted_plant_largeitem location_Xneg41_Yneg4_place19_room1_floorA)
	(itematlocation item49_potted_plant_largeitem location_Xneg1_Ypos36_place35_room10_floorA)
	(itematlocation item4_bottle_smallitem location_Xpos0_Ypos16_place8_room9_floorA)
	(itematlocation item50_potted_plant_largeitem location_Xpos13_Ypos16_place17_room9_floorA)
	(itematlocation item5_bottle_smallitem location_Xpos1_Ypos17_place9_room9_floorA)
	(itematlocation item6_bottle_smallitem location_Xneg2_Ypos77_place36_room4_floorB)
	(itematlocation item7_bottle_smallitem location_Xneg42_Yneg4_place19_room1_floorA)
	(itematlocation item9_book_smallitem location_Xneg23_Yneg12_place10_room5_floorB)
	(receptacleatlocation receptacle13_sink location_Xneg39_Yneg6_place19_room1_floorA)
	(receptacleatlocation receptacle14_sink location_Xneg24_Ypos38_place20_room3_floorB)
	(receptacleatlocation receptacle15_sink location_Xneg6_Ypos31_place21_room2_floorB)
	(receptacleatlocation receptacle1_microwave location_Xpos12_Yneg3_place16_room9_floorA)
	(receptacleatlocation receptacle23_toilet location_Xneg11_Ypos38_place22_room3_floorB)
	(receptacleatlocation receptacle24_toilet location_Xneg46_Yneg6_place23_room1_floorA)
	(receptacleatlocation receptacle25_toilet location_Xpos2_Ypos31_place24_room2_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg29_Ypos64_place25_room10_floorA)
	(receptacleatlocation receptacle27_chair location_Xneg32_Ypos67_place26_room10_floorA)
	(receptacleatlocation receptacle28_chair location_Xneg5_Ypos20_place27_room10_floorA)
	(receptacleatlocation receptacle29_chair location_Xneg14_Ypos21_place28_room10_floorA)
	(receptacleatlocation receptacle2_oven location_Xpos11_Yneg2_place17_room9_floorA)
	(receptacleatlocation receptacle30_chair location_Xneg13_Ypos21_place29_room10_floorA)
	(receptacleatlocation receptacle31_chair location_Xneg19_Yneg13_place30_room9_floorA)
	(receptacleatlocation receptacle32_chair location_Xneg14_Yneg12_place31_room9_floorA)
	(receptacleatlocation receptacle33_chair location_Xneg14_Yneg19_place32_room9_floorA)
	(receptacleatlocation receptacle36_chair location_Xneg2_Yneg13_place33_room8_floorB)
	(receptacleatlocation receptacle37_chair location_Xpos0_Yneg15_place34_room8_floorB)
	(receptacleatlocation receptacle38_couch location_Xneg6_Ypos46_place35_room10_floorA)
	(receptacleatlocation receptacle51_bed location_Xneg16_Ypos66_place36_room4_floorB)
	(receptacleatlocation receptacle52_bed location_Xneg44_Yneg1_place37_room5_floorB)
	(receptacleatlocation receptacle53_dining_table location_Xneg16_Yneg10_place38_room9_floorA)
	(receptacleatlocation receptacle8_refrigerator location_Xpos7_Yneg15_place18_room9_floorA)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle8_refrigerator)
  )
  (:goal (and
	(inreceptacle item48_potted_plant_largeitem receptacle23_toilet)
	(inreceptacle item19_teddy_bear_mediumitem receptacle33_chair)
	(inreceptacle item7_bottle_smallitem receptacle29_chair)
	(inreceptacle item41_potted_plant_largeitem receptacle32_chair)
	(inreceptacle item44_potted_plant_largeitem receptacle24_toilet)
	(inreceptacle item21_orange_smallitem receptacle37_chair)
	(inreceptacle item43_potted_plant_largeitem receptacle8_refrigerator)
	(inreceptacle item18_vase_mediumitem receptacle36_chair)
	(inreceptacle item4_bottle_smallitem receptacle13_sink)
	(inreceptacle item39_potted_plant_largeitem receptacle14_sink)))
)
