
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item10_book_smallitem - item
	item11_book_smallitem - item
	item12_book_smallitem - item
	item13_vase_mediumitem - item
	item14_vase_mediumitem - item
	item15_vase_mediumitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item19_vase_mediumitem - item
	item1_sports_ball_largeitem - item
	item20_vase_mediumitem - item
	item21_vase_mediumitem - item
	item22_vase_mediumitem - item
	item23_vase_mediumitem - item
	item24_vase_mediumitem - item
	item25_vase_mediumitem - item
	item26_vase_mediumitem - item
	item27_vase_mediumitem - item
	item28_vase_mediumitem - item
	item29_vase_mediumitem - item
	item30_vase_mediumitem - item
	item31_bottle_smallitem - item
	item34_bowl_smallitem - item
	item52_potted_plant_largeitem - item
	item53_potted_plant_largeitem - item
	item54_potted_plant_largeitem - item
	item55_potted_plant_largeitem - item
	item56_potted_plant_largeitem - item
	item57_potted_plant_largeitem - item
	item58_potted_plant_largeitem - item
	item59_potted_plant_largeitem - item
	item60_potted_plant_largeitem - item
	location_Xneg11_Yneg81_place20_room21_floorB - location
	location_Xneg11_Ypos0_place52_room17_floorB - location
	location_Xneg12_Yneg5_place55_room17_floorB - location
	location_Xneg13_Yneg8_place55_room17_floorB - location
	location_Xneg14_Yneg96_place38_room26_floorA - location
	location_Xneg14_Ypos20_place51_room19_floorB - location
	location_Xneg18_Yneg5_place52_room17_floorB - location
	location_Xneg18_Yneg93_place34_room1_floorA - location
	location_Xneg19_Yneg46_place30_room20_floorB - location
	location_Xneg19_Yneg48_place28_room20_floorB - location
	location_Xneg20_Yneg46_place29_room20_floorB - location
	location_Xneg20_Yneg47_place16_room20_floorB - location
	location_Xneg20_Yneg51_place24_room20_floorB - location
	location_Xneg20_Yneg53_place22_room20_floorB - location
	location_Xneg20_Yneg54_place17_room20_floorB - location
	location_Xneg20_Yneg55_place23_room20_floorB - location
	location_Xneg20_Yneg95_place34_room1_floorA - location
	location_Xneg21_Yneg105_place43_room1_floorA - location
	location_Xneg21_Yneg47_place21_room20_floorB - location
	location_Xneg23_Ypos30_place42_room5_floorA - location
	location_Xneg24_Ypos35_place46_room6_floorC - location
	location_Xneg24_Ypos7_place61_room5_floorA - location
	location_Xneg25_Ypos28_place50_room19_floorB - location
	location_Xneg28_Ypos26_place46_room6_floorC - location
	location_Xneg2_Yneg113_place48_room15_floorB - location
	location_Xneg30_Ypos20_place50_room19_floorB - location
	location_Xneg41_Yneg47_place59_room20_floorB - location
	location_Xneg4_Yneg23_place33_room17_floorB - location
	location_Xneg53_Yneg45_place58_room18_floorA - location
	location_Xneg56_Yneg51_place59_room20_floorB - location
	location_Xneg57_Yneg72_place53_room20_floorB - location
	location_Xneg69_Yneg29_place54_room20_floorB - location
	location_Xneg6_Yneg43_place37_room4_floorC - location
	location_Xneg73_Yneg80_place19_room20_floorB - location
	location_Xneg7_Yneg50_place37_room4_floorC - location
	location_Xneg81_Yneg79_place31_room20_floorB - location
	location_Xneg83_Yneg81_place18_room20_floorB - location
	location_Xneg86_Yneg68_place27_room18_floorA - location
	location_Xneg89_Yneg100_place39_room27_floorA - location
	location_Xneg89_Yneg68_place25_room18_floorA - location
	location_Xneg92_Yneg73_place26_room18_floorA - location
	location_Xpos11_Ypos17_place35_room17_floorB - location
	location_Xpos13_Ypos18_place35_room17_floorB - location
	location_Xpos14_Yneg53_place15_room13_floorA - location
	location_Xpos17_Yneg46_place57_room11_floorB - location
	location_Xpos20_Yneg102_place47_room15_floorB - location
	location_Xpos23_Yneg70_place36_room2_floorB - location
	location_Xpos24_Yneg34_place32_room4_floorC - location
	location_Xpos25_Yneg74_place36_room2_floorB - location
	location_Xpos2_Yneg8_place60_room6_floorC - location
	location_Xpos5_Yneg44_place56_room11_floorB - location
	location_Xpos6_Ypos14_place49_room5_floorA - location
	location_Xpos7_Yneg45_place62_room11_floorB - location
	location_Xpos7_Yneg46_place62_room11_floorB - location
	location_Xpos8_Yneg11_place40_room17_floorB - location
	location_Xpos8_Yneg53_place41_room11_floorB - location
	location_Xpos8_Ypos12_place35_room17_floorB - location
	location_Xpos9_Yneg78_place45_room4_floorC - location
	location_Xpos9_Yneg79_place44_room2_floorB - location
	location_Xpos9_Ypos15_place35_room17_floorB - location
	receptacle2_oven - receptacle
	receptacle32_bench - receptacle
	receptacle33_bench - receptacle
	receptacle35_toilet - receptacle
	receptacle36_toilet - receptacle
	receptacle37_toilet - receptacle
	receptacle38_chair - receptacle
	receptacle39_chair - receptacle
	receptacle3_sink - receptacle
	receptacle40_chair - receptacle
	receptacle41_chair - receptacle
	receptacle42_chair - receptacle
	receptacle43_chair - receptacle
	receptacle44_chair - receptacle
	receptacle45_chair - receptacle
	receptacle46_chair - receptacle
	receptacle47_chair - receptacle
	receptacle48_chair - receptacle
	receptacle49_chair - receptacle
	receptacle4_sink - receptacle
	receptacle50_couch - receptacle
	receptacle51_couch - receptacle
	receptacle5_sink - receptacle
	receptacle61_bed - receptacle
	receptacle62_bed - receptacle
	receptacle63_dining_table - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_refrigerator - receptacle
  )
  (:init 
	(atlocation agent location_Xpos8_Yneg11_place40_room17_floorB)
	(inanyreceptacle item11_book_smallitem)
	(inanyreceptacle item20_vase_mediumitem)
	(inanyreceptacle item21_vase_mediumitem)
	(inanyreceptacle item22_vase_mediumitem)
	(inanyreceptacle item23_vase_mediumitem)
	(inanyreceptacle item24_vase_mediumitem)
	(inanyreceptacle item28_vase_mediumitem)
	(inanyreceptacle item30_vase_mediumitem)
	(inanyreceptacle item31_bottle_smallitem)
	(inanyreceptacle item34_bowl_smallitem)
	(inanyreceptacle item55_potted_plant_largeitem)
	(inanyreceptacle item56_potted_plant_largeitem)
	(inanyreceptacle item58_potted_plant_largeitem)
	(inanyreceptacle item59_potted_plant_largeitem)
	(inanyreceptacle item60_potted_plant_largeitem)
	(inreceptacle item11_book_smallitem receptacle42_chair)
	(inreceptacle item20_vase_mediumitem receptacle38_chair)
	(inreceptacle item21_vase_mediumitem receptacle44_chair)
	(inreceptacle item22_vase_mediumitem receptacle4_sink)
	(inreceptacle item23_vase_mediumitem receptacle4_sink)
	(inreceptacle item24_vase_mediumitem receptacle4_sink)
	(inreceptacle item28_vase_mediumitem receptacle63_dining_table)
	(inreceptacle item30_vase_mediumitem receptacle44_chair)
	(inreceptacle item31_bottle_smallitem receptacle3_sink)
	(inreceptacle item34_bowl_smallitem receptacle47_chair)
	(inreceptacle item55_potted_plant_largeitem receptacle5_sink)
	(inreceptacle item56_potted_plant_largeitem receptacle6_sink)
	(inreceptacle item58_potted_plant_largeitem receptacle51_couch)
	(inreceptacle item59_potted_plant_largeitem receptacle63_dining_table)
	(inreceptacle item60_potted_plant_largeitem receptacle63_dining_table)
	(itematlocation item10_book_smallitem location_Xneg20_Yneg47_place16_room20_floorB)
	(itematlocation item11_book_smallitem location_Xneg25_Ypos28_place50_room19_floorB)
	(itematlocation item12_book_smallitem location_Xneg20_Yneg54_place17_room20_floorB)
	(itematlocation item13_vase_mediumitem location_Xneg83_Yneg81_place18_room20_floorB)
	(itematlocation item14_vase_mediumitem location_Xneg73_Yneg80_place19_room20_floorB)
	(itematlocation item15_vase_mediumitem location_Xneg11_Yneg81_place20_room21_floorB)
	(itematlocation item16_vase_mediumitem location_Xneg21_Yneg47_place21_room20_floorB)
	(itematlocation item17_vase_mediumitem location_Xneg20_Yneg53_place22_room20_floorB)
	(itematlocation item18_vase_mediumitem location_Xneg20_Yneg55_place23_room20_floorB)
	(itematlocation item19_vase_mediumitem location_Xneg20_Yneg51_place24_room20_floorB)
	(itematlocation item1_sports_ball_largeitem location_Xpos14_Yneg53_place15_room13_floorA)
	(itematlocation item20_vase_mediumitem location_Xneg24_Ypos35_place46_room6_floorC)
	(itematlocation item21_vase_mediumitem location_Xneg11_Ypos0_place52_room17_floorB)
	(itematlocation item22_vase_mediumitem location_Xpos9_Ypos15_place35_room17_floorB)
	(itematlocation item23_vase_mediumitem location_Xpos13_Ypos18_place35_room17_floorB)
	(itematlocation item24_vase_mediumitem location_Xpos11_Ypos17_place35_room17_floorB)
	(itematlocation item25_vase_mediumitem location_Xneg19_Yneg48_place28_room20_floorB)
	(itematlocation item26_vase_mediumitem location_Xneg20_Yneg46_place29_room20_floorB)
	(itematlocation item27_vase_mediumitem location_Xneg19_Yneg46_place30_room20_floorB)
	(itematlocation item28_vase_mediumitem location_Xpos7_Yneg45_place62_room11_floorB)
	(itematlocation item29_vase_mediumitem location_Xneg81_Yneg79_place31_room20_floorB)
	(itematlocation item30_vase_mediumitem location_Xneg11_Ypos0_place52_room17_floorB)
	(itematlocation item31_bottle_smallitem location_Xneg18_Yneg93_place34_room1_floorA)
	(itematlocation item34_bowl_smallitem location_Xneg12_Yneg5_place55_room17_floorB)
	(itematlocation item52_potted_plant_largeitem location_Xneg89_Yneg68_place25_room18_floorA)
	(itematlocation item53_potted_plant_largeitem location_Xneg92_Yneg73_place26_room18_floorA)
	(itematlocation item54_potted_plant_largeitem location_Xneg86_Yneg68_place27_room18_floorA)
	(itematlocation item55_potted_plant_largeitem location_Xpos25_Yneg74_place36_room2_floorB)
	(itematlocation item56_potted_plant_largeitem location_Xneg6_Yneg43_place37_room4_floorC)
	(itematlocation item57_potted_plant_largeitem location_Xpos24_Yneg34_place32_room4_floorC)
	(itematlocation item58_potted_plant_largeitem location_Xneg56_Yneg51_place59_room20_floorB)
	(itematlocation item59_potted_plant_largeitem location_Xpos7_Yneg45_place62_room11_floorB)
	(itematlocation item60_potted_plant_largeitem location_Xpos7_Yneg46_place62_room11_floorB)
	(receptacleatlocation receptacle2_oven location_Xneg4_Yneg23_place33_room17_floorB)
	(receptacleatlocation receptacle32_bench location_Xpos8_Yneg53_place41_room11_floorB)
	(receptacleatlocation receptacle33_bench location_Xneg23_Ypos30_place42_room5_floorA)
	(receptacleatlocation receptacle35_toilet location_Xneg21_Yneg105_place43_room1_floorA)
	(receptacleatlocation receptacle36_toilet location_Xpos9_Yneg79_place44_room2_floorB)
	(receptacleatlocation receptacle37_toilet location_Xpos9_Yneg78_place45_room4_floorC)
	(receptacleatlocation receptacle38_chair location_Xneg28_Ypos26_place46_room6_floorC)
	(receptacleatlocation receptacle39_chair location_Xpos20_Yneg102_place47_room15_floorB)
	(receptacleatlocation receptacle3_sink location_Xneg20_Yneg95_place34_room1_floorA)
	(receptacleatlocation receptacle40_chair location_Xneg2_Yneg113_place48_room15_floorB)
	(receptacleatlocation receptacle41_chair location_Xpos6_Ypos14_place49_room5_floorA)
	(receptacleatlocation receptacle42_chair location_Xneg30_Ypos20_place50_room19_floorB)
	(receptacleatlocation receptacle43_chair location_Xneg14_Ypos20_place51_room19_floorB)
	(receptacleatlocation receptacle44_chair location_Xneg18_Yneg5_place52_room17_floorB)
	(receptacleatlocation receptacle45_chair location_Xneg57_Yneg72_place53_room20_floorB)
	(receptacleatlocation receptacle46_chair location_Xneg69_Yneg29_place54_room20_floorB)
	(receptacleatlocation receptacle47_chair location_Xneg13_Yneg8_place55_room17_floorB)
	(receptacleatlocation receptacle48_chair location_Xpos5_Yneg44_place56_room11_floorB)
	(receptacleatlocation receptacle49_chair location_Xpos17_Yneg46_place57_room11_floorB)
	(receptacleatlocation receptacle4_sink location_Xpos8_Ypos12_place35_room17_floorB)
	(receptacleatlocation receptacle50_couch location_Xneg53_Yneg45_place58_room18_floorA)
	(receptacleatlocation receptacle51_couch location_Xneg41_Yneg47_place59_room20_floorB)
	(receptacleatlocation receptacle5_sink location_Xpos23_Yneg70_place36_room2_floorB)
	(receptacleatlocation receptacle61_bed location_Xpos2_Yneg8_place60_room6_floorC)
	(receptacleatlocation receptacle62_bed location_Xneg24_Ypos7_place61_room5_floorA)
	(receptacleatlocation receptacle63_dining_table location_Xpos7_Yneg46_place62_room11_floorB)
	(receptacleatlocation receptacle6_sink location_Xneg7_Yneg50_place37_room4_floorC)
	(receptacleatlocation receptacle7_sink location_Xneg14_Yneg96_place38_room26_floorA)
	(receptacleatlocation receptacle8_sink location_Xneg89_Yneg100_place39_room27_floorA)
	(receptacleatlocation receptacle9_refrigerator location_Xpos8_Yneg11_place40_room17_floorB)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle9_refrigerator)
  )
  (:goal (and
	(inreceptacle item57_potted_plant_largeitem receptacle48_chair)
	(inreceptacle item18_vase_mediumitem receptacle4_sink)
	(inreceptacle item22_vase_mediumitem receptacle32_bench)
	(inreceptacle item17_vase_mediumitem receptacle39_chair)
	(inreceptacle item56_potted_plant_largeitem receptacle35_toilet)
	(inreceptacle item34_bowl_smallitem receptacle37_toilet)
	(inreceptacle item26_vase_mediumitem receptacle41_chair)
	(inreceptacle item15_vase_mediumitem receptacle3_sink)
	(inreceptacle item52_potted_plant_largeitem receptacle36_toilet)
	(inreceptacle item14_vase_mediumitem receptacle61_bed)))
)
