
(define (problem taskograph_rearrangement) (:domain taskography_v1)
  (:objects
        agent - agent
	item11_handbag_largeitem - item
	item12_clock_mediumitem - item
	item13_clock_mediumitem - item
	item14_vase_mediumitem - item
	item15_bottle_smallitem - item
	item16_bottle_smallitem - item
	item17_bottle_smallitem - item
	item18_bottle_smallitem - item
	item19_book_smallitem - item
	item1_keyboard_largeitem - item
	item20_suitcase_largeitem - item
	item21_suitcase_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item40_potted_plant_largeitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item47_tv_largeitem - item
	item48_tv_largeitem - item
	item49_tv_largeitem - item
	location_Xneg11_Yneg15_place47_room11_floorB - location
	location_Xneg12_Yneg14_place47_room11_floorB - location
	location_Xneg12_Yneg15_place47_room11_floorB - location
	location_Xneg16_Yneg16_place47_room11_floorB - location
	location_Xneg16_Ypos81_place17_room19_floorA - location
	location_Xneg17_Ypos82_place16_room19_floorA - location
	location_Xneg20_Ypos25_place28_room15_floorA - location
	location_Xneg21_Yneg11_place47_room11_floorB - location
	location_Xneg22_Ypos18_place21_room8_floorC - location
	location_Xneg23_Yneg6_place30_room8_floorC - location
	location_Xneg23_Ypos9_place31_room8_floorC - location
	location_Xneg26_Ypos54_place29_room13_floorC1 - location
	location_Xneg30_Ypos84_place23_room17_floorA - location
	location_Xneg39_Yneg13_place26_room21_floorC - location
	location_Xneg39_Yneg14_place27_room21_floorC - location
	location_Xneg44_Yneg9_place40_room16_floorB - location
	location_Xneg51_Ypos9_place45_room16_floorB - location
	location_Xneg53_Ypos5_place48_room6_floorC - location
	location_Xneg54_Ypos37_place35_room3_floorC - location
	location_Xneg54_Ypos44_place50_room17_floorA - location
	location_Xneg59_Ypos81_place25_room17_floorA - location
	location_Xneg5_Ypos67_place43_room1_floorB - location
	location_Xneg60_Ypos16_place44_room16_floorB - location
	location_Xneg60_Ypos40_place34_room3_floorC - location
	location_Xneg66_Ypos37_place34_room3_floorC - location
	location_Xneg67_Yneg12_place33_room16_floorB - location
	location_Xneg68_Yneg14_place32_room16_floorB - location
	location_Xneg6_Ypos70_place43_room1_floorB - location
	location_Xneg74_Ypos36_place41_room3_floorC - location
	location_Xneg74_Ypos60_place51_room17_floorA - location
	location_Xneg75_Ypos19_place53_room6_floorC - location
	location_Xneg7_Ypos70_place43_room1_floorB - location
	location_Xneg83_Ypos1_place36_room16_floorB - location
	location_Xneg8_Yneg13_place22_room14_floorB - location
	location_Xpos13_Yneg14_place37_room2_floorC - location
	location_Xpos14_Yneg15_place18_room14_floorB - location
	location_Xpos14_Yneg15_place37_room2_floorC - location
	location_Xpos15_Ypos72_place52_room5_floorC - location
	location_Xpos20_Yneg15_place19_room14_floorB - location
	location_Xpos25_Ypos2_place49_room15_floorA - location
	location_Xpos26_Yneg14_place38_room2_floorC - location
	location_Xpos28_Ypos3_place49_room15_floorA - location
	location_Xpos2_Yneg12_place42_room2_floorC - location
	location_Xpos30_Ypos59_place46_room9_floorA - location
	location_Xpos30_Ypos74_place54_room4_floorB - location
	location_Xpos33_Yneg4_place49_room15_floorA - location
	location_Xpos40_Ypos9_place24_room2_floorC - location
	location_Xpos4_Ypos68_place39_room1_floorB - location
	location_Xpos9_Yneg14_place20_room14_floorB - location
	receptacle10_refrigerator - receptacle
	receptacle22_toilet - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_microwave - receptacle
	receptacle30_chair - receptacle
	receptacle31_couch - receptacle
	receptacle32_couch - receptacle
	receptacle3_oven - receptacle
	receptacle44_bed - receptacle
	receptacle45_bed - receptacle
	receptacle46_bed - receptacle
	receptacle4_sink - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_sink - receptacle
  )
  (:init 
	(atlocation agent location_Xneg66_Ypos37_place34_room3_floorC)
	(inanyreceptacle item15_bottle_smallitem)
	(inanyreceptacle item18_bottle_smallitem)
	(inanyreceptacle item1_keyboard_largeitem)
	(inanyreceptacle item38_potted_plant_largeitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item40_potted_plant_largeitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item43_potted_plant_largeitem)
	(inanyreceptacle item49_tv_largeitem)
	(inreceptacle item15_bottle_smallitem receptacle4_sink)
	(inreceptacle item18_bottle_smallitem receptacle7_sink)
	(inreceptacle item1_keyboard_largeitem receptacle30_chair)
	(inreceptacle item38_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item39_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item40_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item41_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item42_potted_plant_largeitem receptacle24_toilet)
	(inreceptacle item43_potted_plant_largeitem receptacle24_toilet)
	(inreceptacle item49_tv_largeitem receptacle30_chair)
	(itematlocation item11_handbag_largeitem location_Xneg22_Ypos18_place21_room8_floorC)
	(itematlocation item12_clock_mediumitem location_Xneg8_Yneg13_place22_room14_floorB)
	(itematlocation item13_clock_mediumitem location_Xneg30_Ypos84_place23_room17_floorA)
	(itematlocation item14_vase_mediumitem location_Xpos40_Ypos9_place24_room2_floorC)
	(itematlocation item15_bottle_smallitem location_Xneg60_Ypos40_place34_room3_floorC)
	(itematlocation item16_bottle_smallitem location_Xneg39_Yneg13_place26_room21_floorC)
	(itematlocation item17_bottle_smallitem location_Xneg39_Yneg14_place27_room21_floorC)
	(itematlocation item18_bottle_smallitem location_Xpos14_Yneg15_place37_room2_floorC)
	(itematlocation item19_book_smallitem location_Xneg26_Ypos54_place29_room13_floorC1)
	(itematlocation item1_keyboard_largeitem location_Xpos25_Ypos2_place49_room15_floorA)
	(itematlocation item20_suitcase_largeitem location_Xneg23_Yneg6_place30_room8_floorC)
	(itematlocation item21_suitcase_largeitem location_Xneg23_Ypos9_place31_room8_floorC)
	(itematlocation item33_potted_plant_largeitem location_Xneg17_Ypos82_place16_room19_floorA)
	(itematlocation item34_potted_plant_largeitem location_Xneg16_Ypos81_place17_room19_floorA)
	(itematlocation item35_potted_plant_largeitem location_Xpos14_Yneg15_place18_room14_floorB)
	(itematlocation item36_potted_plant_largeitem location_Xpos20_Yneg15_place19_room14_floorB)
	(itematlocation item37_potted_plant_largeitem location_Xpos9_Yneg14_place20_room14_floorB)
	(itematlocation item38_potted_plant_largeitem location_Xneg12_Yneg14_place47_room11_floorB)
	(itematlocation item39_potted_plant_largeitem location_Xneg12_Yneg15_place47_room11_floorB)
	(itematlocation item40_potted_plant_largeitem location_Xneg11_Yneg15_place47_room11_floorB)
	(itematlocation item41_potted_plant_largeitem location_Xneg16_Yneg16_place47_room11_floorB)
	(itematlocation item42_potted_plant_largeitem location_Xneg7_Ypos70_place43_room1_floorB)
	(itematlocation item43_potted_plant_largeitem location_Xneg6_Ypos70_place43_room1_floorB)
	(itematlocation item47_tv_largeitem location_Xneg59_Ypos81_place25_room17_floorA)
	(itematlocation item48_tv_largeitem location_Xneg20_Ypos25_place28_room15_floorA)
	(itematlocation item49_tv_largeitem location_Xpos28_Ypos3_place49_room15_floorA)
	(receptacleatlocation receptacle10_refrigerator location_Xneg44_Yneg9_place40_room16_floorB)
	(receptacleatlocation receptacle22_toilet location_Xneg74_Ypos36_place41_room3_floorC)
	(receptacleatlocation receptacle23_toilet location_Xpos2_Yneg12_place42_room2_floorC)
	(receptacleatlocation receptacle24_toilet location_Xneg5_Ypos67_place43_room1_floorB)
	(receptacleatlocation receptacle25_chair location_Xneg60_Ypos16_place44_room16_floorB)
	(receptacleatlocation receptacle26_chair location_Xneg51_Ypos9_place45_room16_floorB)
	(receptacleatlocation receptacle27_chair location_Xpos30_Ypos59_place46_room9_floorA)
	(receptacleatlocation receptacle28_chair location_Xneg21_Yneg11_place47_room11_floorB)
	(receptacleatlocation receptacle29_chair location_Xneg53_Ypos5_place48_room6_floorC)
	(receptacleatlocation receptacle2_microwave location_Xneg68_Yneg14_place32_room16_floorB)
	(receptacleatlocation receptacle30_chair location_Xpos33_Yneg4_place49_room15_floorA)
	(receptacleatlocation receptacle31_couch location_Xneg54_Ypos44_place50_room17_floorA)
	(receptacleatlocation receptacle32_couch location_Xneg74_Ypos60_place51_room17_floorA)
	(receptacleatlocation receptacle3_oven location_Xneg67_Yneg12_place33_room16_floorB)
	(receptacleatlocation receptacle44_bed location_Xpos15_Ypos72_place52_room5_floorC)
	(receptacleatlocation receptacle45_bed location_Xneg75_Ypos19_place53_room6_floorC)
	(receptacleatlocation receptacle46_bed location_Xpos30_Ypos74_place54_room4_floorB)
	(receptacleatlocation receptacle4_sink location_Xneg66_Ypos37_place34_room3_floorC)
	(receptacleatlocation receptacle5_sink location_Xneg54_Ypos37_place35_room3_floorC)
	(receptacleatlocation receptacle6_sink location_Xneg83_Ypos1_place36_room16_floorB)
	(receptacleatlocation receptacle7_sink location_Xpos13_Yneg14_place37_room2_floorC)
	(receptacleatlocation receptacle8_sink location_Xpos26_Yneg14_place38_room2_floorC)
	(receptacleatlocation receptacle9_sink location_Xpos4_Ypos68_place39_room1_floorB)
	(receptacleopeningtype receptacle10_refrigerator)
	(receptacleopeningtype receptacle2_microwave)
	(receptacleopeningtype receptacle3_oven)
  )
  (:goal (and
	(inreceptacle item11_handbag_largeitem receptacle3_oven)
	(inreceptacle item1_keyboard_largeitem receptacle5_sink)
	(inreceptacle item17_bottle_smallitem receptacle26_chair)
	(inreceptacle item20_suitcase_largeitem receptacle9_sink)
	(inreceptacle item13_clock_mediumitem receptacle10_refrigerator)
	(inreceptacle item41_potted_plant_largeitem receptacle10_refrigerator)
	(inreceptacle item12_clock_mediumitem receptacle31_couch)
	(inreceptacle item19_book_smallitem receptacle32_couch)
	(inreceptacle item18_bottle_smallitem receptacle45_bed)
	(inreceptacle item35_potted_plant_largeitem receptacle5_sink)))
)
